TYPO3-Solr/ext-solr

Documentation/FAQ/Index.rst
This question was frequently ask in Slack.
Adds FAQ to docs
=> Add FAQ for different host / port configuration in v10

Classes/System/Service/ConfigurationService.php
Filter Queries are escaped by " if they are not numeric. Therefore wildcards are not possible. This commit extends the check, if the fieldValue should be escaped by double quotes.
Add a filter in the FlexForm "url"
/private -> only page with Slug /private is found
/private* -> no page is found
\/private* -> page /private and subpages are found
=> Allow Wildcards in Filter Queries

Classes/System/Util/SiteUtility.php, Tests/Unit/System/Util/SiteUtilityTest.php
It's possible to use environment variables in the site configuration, but values like true or false are currently misinterpreted as evaluated as strings. This issue e.g. prevents the deactivation of Solr connections using environment variables.
This pr fixes this issue by evaluating the site configuration values.
By setting `solr_enabled_read` via environment variables, this issue can be reproduced. Without this patch set value will always be interpreted as `true` and it's not possible to deactivate a Solr connection.
Relevant configuration line in site configuration can e.g. look like:
```
solr_enabled_read: "%env(SOLR_ENABLED_READ_DE)%"
```
Fixes: #2538
=> [BUGFIX] Fix misinterpreted environment variables

Classes/Controller/SuggestController.php
With this, the SuggestAction Controller can handle Requests with no `tx_solr[callback]` given and willthen return pure JSON with no callback-prefix.
Call the Controller with no callback-parameter. It is still not crashing and returns a pure JSON.
=> [FEATURE] Enable SuggestAction to Provide pure JSON

Classes/ConnectionManager.php
* Is adding the language uid as array key again in order to have the correct core to language
relation in the IndexInspector
Check in the backend if the correct core is used when the documents are shown with the index inspector.
Fixes: #2553
=> IndexInspector is showing wrong language to document relation

Resources/Public/JavaScript/search_controller.js
When a user clicks on a facet filter option the result is loaded using AJAX (if you choose to use the AJAXIFY static typoscript template). If you then request another page (e.g. from the search results) and return back to the search results using the browser back button your set filter options are gone.
This PR adds JS code to replace the current browsers URL on the search results page after the AJAX call is returned.
Therefore the status of the chosen filter options is reflected in the URL and you can use the back button to return to search page with the previously chosen options already set.
- Create a page with the solr search plugin
- Configure facet options to filter the search result
- Use the solr static typoscript template "AJAXIFY search results"
- Click a filter option and see …
=> [TASK] Replace current URL with new filter URL

Classes/FrontendEnvironment/Tsfe.php
* Checks in addition if contentId is set as expected in order to force a re-initialization of the language context if required
Fixes: #2559
=> Records are not properly overlayed when language context exists

.travis.yml, Tests/Integration/UtilTest.php
* Add's php 7.4 to the travis setup
* Makes build passing against TYPO3 10 required
* Build should be executed with PHP 7.4 as well
* Builds against TYPO3 10 should be green and required to be green
Fixes: #2561
=> Add PHP 7.4 to travis.yml and require TYPO3 10 build to pass

Resources/Public/JavaScript/suggest_controller.js
Before this change the autocomplete div `.autocomplete-suggestions` was always added to the body (see `jquery.autocomplete.min.js`). But when you want to overwrite styling relative to the form this was impossible. So by adding a check for `.tx-solr-autocomplete` you can now add a div with class `.tx-solr-autocomplete` inside the form to have your autocomplete on that position.
Add `<div class="tx-solr-autocomplete"></div>` somewhere inside the `<s:searchForm id="tx-solr-search-form-pi-results">` element and see the autocomplete divs are now added on that position. By removing the div, the autocomplete is appended to the body.
Fixes: #2569
=> [FEATURE] Add check for .tx-solr-autocomplete to add autocomplete div

Classes/Domain/Search/ResultSet/SearchResultSetService.php
The trailing semicolon in line 90 was breaking the functionality of
phpdocumentor, which was updated by TYPO3 core recently. Removing it
makes the frontend work again.
Solves: #2573
=> [BUGFIX] Remove breaking semicolon from SearchResultSetService

Classes/ContentObject/Classification.php, Classes/ContentObject/Content.php, Classes/ContentObject/Multivalue.php, Classes/ContentObject/Relation.php, Classes/Domain/Search/Query/ParameterBuilder/Faceting.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetParser.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/NumericRange/NumericRangeFacetParser.php, Classes/System/Util/ArrayAccessor.php, Tests/Integration/ContentObject/RelationTest.php, Tests/Integration/Controller/SearchControllerTest.php, Tests/Integration/TSFEBootstrapResult.php, Tests/Integration/UtilTest.php, Tests/Unit/ContentObject/ClassificationTest.php, Tests/Unit/ContentObject/MultivalueTest.php, Tests/Unit/Domain/Search/Query/QueryBuilderTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetParserTest.php, ext_localconf.php
* `The hook $TYPO3_CONF_VARS[SC_OPTIONS][tslib/class.tslib_content.php][cObjTypeAndClass] for adding custom cObjects will be removed in TYPO3 v11.0. Use a custom cObject which you can register directly instead.`
* `ApacheSolrForTypo3\Solr\Tests\Integration\UtilTest::getConfigurationFromPageIdInitializesTsfe`
* `ApacheSolrForTypo3\Solr\Tests\Integration\UtilTest::getConfigurationFromPageIdInitializesTsfeOnCacheCall`
Fixes: #2584
Resolves troubles in CI
=> [TASK] resolve deprecations since TYPO3 10.4 with aware of functionality within TYPO3 9.5

Tests/Integration/Domain/Search/ResultSet/Fixtures/simple_site.xml, Tests/Integration/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
* Changes the ResultSetReconsitutionProcessorTest to use the initialization logic for Sites
to be able to use the cObject from TSFE in ResultSetReconsitutionProcessor
Tests of ResultSetReconsitutionProcessor are executed and green for TYPO3 9 & 10
=> [TASK] Fix integration tests for ResultSetReconstitutionProcessor

Classes/FrontendEnvironment/Tsfe.php, Tests/Integration/UtilTest.php
* Fixes the integration tests for the Util class by adjusting the assertions
* Check if the test is now exected for TYPO3 9 and 10 and is green on travis
=> [TASK] Fix Util integration tests for TYPO3 10 LTS

Tests/Integration/Domain/Index/IndexServiceTest.php
* Removes the conditional skip for TYPO3 10 since this seems to be fixed in the core
Test is executed with TYPO3 9 & 10 and green
=> [TASK] Fix absRefPrefix test

Classes/Util.php, composer.json, ext_emconf.php
In favor of the deprecated constant TYPO3_branch the class Typo3Version should be used.
This is available since 9.5.16
=> Replace usage of TYPO3_branch

Configuration/FlexForms/Form.xml, Configuration/FlexForms/Results.xml
The langDisable setting has been removed with TYPO3 7 and can be
removed.
=> [TASK] Remove langdisable=1 in FlexForms

Configuration/SiteConfiguration/Overrides/sites.php
If using dot env, the eval int option leads to an error in the site config.
Resolves: #2533
=> [BUGFIX] Remove eval int from port in site configuration

Classes/IndexQueue/Indexer.php, Tests/Integration/IndexQueue/IndexerTest.php, Tests/Integration/IntegrationTest.php
* Fixes the indexing if the default language was disabled in the site config
* Add's an integration test for that case
Check the indexing of a site when the default language was disabled in the site configuration.
Fixes: #2451
=> [BUGFIX] Fix indexing when default language is disabled in site config

ext_emconf.php
set to max supported TYPO3 Version 10.4.99 in ext_emconf.php
=> [BUGFIX] set max TYPO3 Version to 10.4.99 in ext_emconf.php

Docker/SolrServer/Dockerfile
* Changes the user and group to the real groups of the container since this fails on docker hub and is same on each environment. 
* Check if the docker container is build on docker hub and synonyms and stopwords can be written
Fixes: #2612
=> [TASK] Use fixed groups instead of env variables

Build/Test/IntegrationFrontendTests.xml, Build/Test/IntegrationTests.xml, Build/Test/cibuild.sh, Build/Test/publish_coverage.sh, Classes/ViewHelpers/Uri/AbstractUriViewHelper.php, Classes/ViewHelpers/Uri/Facet/AddFacetItemViewHelper.php, Classes/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelper.php, Classes/ViewHelpers/Uri/Facet/RemoveFacetItemViewHelper.php, Classes/ViewHelpers/Uri/Facet/RemoveFacetViewHelper.php, Classes/ViewHelpers/Uri/Facet/SetFacetItemViewHelper.php, Classes/ViewHelpers/Uri/Paginate/GroupItemPageViewHelper.php, Classes/ViewHelpers/Uri/Paginate/ResultPageViewHelper.php, Classes/ViewHelpers/Uri/Search/CurrentSearchViewHelper.php, Classes/ViewHelpers/Uri/Search/StartNewSearchViewHelper.php, Classes/ViewHelpers/Uri/Sorting/RemoveSortingViewHelper.php, Classes/ViewHelpers/Uri/Sorting/SetSortingViewHelper.php, Tests/Integration/Controller/AbstractFrontendControllerTest.php, Tests/Integration/Controller/SearchControllerTest.php, Tests/Integration/Controller/SuggestControllerTest.php, Tests/Integration/TSFETestBootstrapper.php, Tests/Integration/UtilTest.php, Tests/Unit/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelperTest.php
Some tests within SearchControllerTests were skipped for TYPO3 v10,
which are re-enabled now.
The main reason why this happened was/is the changed behaviour
of DependencyInjection in TYPO3 v10. This way, a Singleton (in this case
EnvironmentService of Extbase) cannot be replaced during a Functional
Call anymore - which should not be done in any case.
Some frontend-related tests failed for this reason, because it was not possible
to mock the behaviour of TYPO3_MODE=FE in Tests.
Enabling these tests showed that the tests failed as the ViewHelpers did not
receive the current request by the ControllerContext, which is now
optionally injected into all ViewHelpers that generated links.
To run these Integration Tests, a new PHPunit configuration
called "IntegrationFrontendTests.xml" is added …
=> [BUGFIX] Re-enable Integration Tests for TYPO3 v10

.travis.yml, Build/Test/IntegrationFrontendTests.xml, Build/Test/IntegrationTests.xml, Build/Test/cibuild.sh, Build/Test/publish_coverage.sh, Classes/ViewHelpers/Uri/AbstractUriViewHelper.php, Classes/ViewHelpers/Uri/Facet/AddFacetItemViewHelper.php, Classes/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelper.php, Classes/ViewHelpers/Uri/Facet/RemoveFacetItemViewHelper.php, Classes/ViewHelpers/Uri/Facet/RemoveFacetViewHelper.php, Classes/ViewHelpers/Uri/Facet/SetFacetItemViewHelper.php, Classes/ViewHelpers/Uri/Paginate/GroupItemPageViewHelper.php, Classes/ViewHelpers/Uri/Paginate/ResultPageViewHelper.php, Classes/ViewHelpers/Uri/Search/CurrentSearchViewHelper.php, Classes/ViewHelpers/Uri/Search/StartNewSearchViewHelper.php, Classes/ViewHelpers/Uri/Sorting/RemoveSortingViewHelper.php, Classes/ViewHelpers/Uri/Sorting/SetSortingViewHelper.php, Tests/Integration/Controller/AbstractFrontendControllerTest.php, Tests/Integration/Controller/SearchControllerTest.php, Tests/Integration/Controller/SuggestControllerTest.php, Tests/Integration/TSFETestBootstrapper.php, Tests/Integration/UtilTest.php, Tests/Unit/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelperTest.php
Some tests within SearchControllerTests were skipped for TYPO3 v10,
which are re-enabled now.
The main reason why this happened was/is the changed behaviour
of DependencyInjection in TYPO3 v10. This way, a Singleton (in this case
EnvironmentService of Extbase) cannot be replaced during a Functional
Call anymore - which should not be done in any case.
Some frontend-related tests failed for this reason, because it was not possible
to mock the behaviour of TYPO3_MODE=FE in Tests.
Enabling these tests showed that the tests failed as the ViewHelpers did not
receive the current request by the ControllerContext, which is now
optionally injected into all ViewHelpers that generated links.
To run these Integration Tests, a new PHPunit configuration
called "IntegrationFrontendTests.xml" is added …
=> [BUGFIX:BACKPORT] Re-enable Integration Tests for TYPO3 v10

.travis.yml, Classes/IndexQueue/Indexer.php, Classes/IndexQueue/Initializer/Page.php, Classes/System/Page/Rootline.php, Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_configuration_in_rootline.xml, Tests/Integration/IndexQueue/Fixtures/can_index_with_multiple_sites.xml, Tests/Integration/IndexQueue/IndexerTest.php
SolR currently traverses all pages in the root line to the
most outer page with is_siteroot in a setup with nested sites.
The Indexer thus always indexed from the most outer page
in previous revisions, however the root page should always
be based on the first site within a single tree
The PR modifies the root line object to always fetch the right
site, in addition, the indexer now fetches the right page ID and
root ID when resolving the site from the queue items.
=> [BUGFIX] Fix multiple rootpages in nested sites

.travis.yml, Classes/FrontendEnvironment/Tsfe.php, Tests/Integration/UtilTest.php
Since EXT:solr is using an internal TYPO3 Core method in TSFE (getPageAndRootlineWithDomain) the change adapts the internal method call to use the adaption for TYPO3 v10.4.4 and adds compatibility with that branch.
Check if indexing is working and all tests are green
Thx to: @bmack & @dkd-kaehm 
Fixes: #2640
=> [BUGFIX] Ensure to hand in PSR-7 Request to TSFE->getPageAndRootlineWithDomain

Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_configuration_in_rootline.xml
Removes the wrong is_siteroot flag of a sys_folder in the fixtures
=> [BUGFIX:Backport] Remove unneeded is_siteroot flag in nested storage folder

Classes/IndexQueue/Initializer/Page.php
Ensures that Page::resolveMountPageTree allways returns an array
=> [BUGFIX:Backport] Always return array on non-mounted sites

Classes/IndexQueue/Indexer.php, Classes/System/Page/Rootline.php, Tests/Integration/IndexQueue/Fixtures/can_index_with_multiple_sites.xml, Tests/Integration/IndexQueue/IndexerTest.php
SolR currently traverses all pages in the root line to the
most outer page with is_siteroot in a setup with nested sites.
The Indexer thus always indexed from the most outer page
in previous revisions, however the root page should always
be based on the first site within a single tree
=> [BUGFIX:Backport] Fix multiple rootpages in nested sites

ext_localconf.php
Currently Solr logs into a hardcoded logfile "typo3temp/var/logs/solr.log", which is in a different directory than the other logfiles. Since v9, TYPO3 by default logs into "typo3temp/var/log" (note the missing S). This is unexpected, and could lead to user not finding the log file at all. See also: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Feature-85236-InfixOptionToDefaultLogFileNamesForFileWriter.html
Activate logging in TypoScript an do something to create log output (e.g. logging.indexing = 1). There will be a new log file created in typo3temp/var/log named "typo3_solr_f5841fa7f9.log".
Fixes: #2626
=> [FEATURE] Change FileWriter configuration to use logFileInfix

Classes/Domain/Search/Uri/SearchUriBuilder.php, Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
Fixes a regression from #2633. Since then the uriBuilder is reused
and needs a reset for every new uri.
Resolves: #2656
=> [BUGFIX] Reset uriBuilder before building a new uri

Resources/Public/StyleSheets/Frontend/loader.css
The loading animation used for the Ajaxify TS template, when loading facetted search results is now placed accurately in the center. This error showed especially on mobile devices, where you could see that the animation was not placed in the center correctly.
It places the loading animation accurately in the center.
- Make a facetted search
- Use the Ajaxify static Typoscript template
- Choose a filter option and see the loading animation being placed in the center
=> [BUGFIX] Place loading animation in accurate center position

Classes/Domain/Index/PageIndexer/Helper/UriBuilder/AbstractUriStrategy.php, Classes/System/Url/UrlHelper.php
This adds the missing port option to the override configuration:
```
plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.port = 80
```
Obvious ;-)
Fixes: #2327
=> [BUGFIX] Add option to override 'port' in frontend indexing URL

Classes/Domain/Index/PageIndexer/Helper/UriBuilder/AbstractUriStrategy.php, Classes/System/Url/UrlHelper.php
This adds the missing port option to the override configuration:
```
plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.port = 80
```
Obvious ;-)
Fixes: #2327
=> [BUGFIX:PORT:release-11.0.x] Add option to override 'port' in frontend indexing URL

Classes/Domain/Index/PageIndexer/Helper/UriBuilder/AbstractUriStrategy.php, Classes/System/Url/UrlHelper.php
This adds the missing port option to the override configuration:
```
plugin.tx_solr.index.queue.pages.indexer.frontendDataHelper.port = 80
```
Resolves: #2327
=> [BUGFIX:PORT:master] Add option to override 'port' in frontend indexing URL

Configuration/FlexForms/Form.xml
In the search plugin selection "form only" the renderType attribute is missing
in the flexform configuration which prevents rendering the custom template
select in the backend. This fixes it by adding the renderType attribute.
Fixes: #2661
=> [BUGFIX] Fix missing renderType attribute in flexform for search plugin

CONTRIBUTING.md, Documentation/Settings.cfg
see commits:
* Remove outdated information in CONTRIBUTING.md
* Changes to get an "Edit on GitHub" button on top right of rendered docs
* Add information about contributing to docs in CONTRIBUTING.md
You can render documentation locally using Docker:
* [Render documentation with Docker](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/RenderingDocs/Index.html)
For this change, I don't think it is necessary (as only Settings.cfg was changed).
Fixes: #2689
=> [DOCS] Improvements for contributing to the documentation

Configuration/FlexForms/Form.xml
In the search plugin selection "form only" the renderType attribute is missing
in the flexform configuration which prevents rendering the custom template
select in the backend. This fixes it by adding the renderType attribute.
Fixes: #2661
=> [BUGFIX:BACKPORT:11] Fix missing renderType attribute in flexform for search plugin

Configuration/FlexForms/Form.xml
In the search plugin selection "form only" the renderType attribute is missing
in the flexform configuration which prevents rendering the custom template
select in the backend. This fixes it by adding the renderType attribute.
Fixes: #2661
=> [BUGFIX:BACKPORT:10] Fix missing renderType attribute in flexform for search plugin

Classes/System/Solr/Node.php
=> [BUGFIX:PORT:master] Build core base path right, when path is slash only

Classes/System/Solr/Node.php
=> [BUGFIX] Build core base path right, when path is slash only

Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
**Describe the bug**
using EXT:solrfluidgrouping always inserts num_found=0 in statisticRecord
**To Reproduce**
1. EXT:solrfluidgrouping
2. Enable statistics = 1 in TS
3. Go to your search page
4. Search for phrase with results
4. See error in in tx_solr_statistics table num_found is 0
num_found should reflect number of Results
**Used versions (please complete the following information):**
- TYPO3 Version: [e.g. 10.4]
- EXT:solr Version: [e.g. 11.0.1]
**Fix**
use `$resultSet->getAllResultCount()` instead of `$response->response->numFound` for tx_solr_statistics num_found DB column
Fixes: #2667
=> [BUGFIX:BACKPORT:10] use num_found in static db table #2667

Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
**Describe the bug**
using EXT:solrfluidgrouping always inserts num_found=0 in statisticRecord
**To Reproduce**
1. EXT:solrfluidgrouping
2. Enable statistics = 1 in TS
3. Go to your search page
4. Search for phrase with results
4. See error in in tx_solr_statistics table num_found is 0
num_found should reflect number of Results
**Used versions (please complete the following information):**
- TYPO3 Version: [e.g. 10.4]
- EXT:solr Version: [e.g. 11.0.1]
**Fix**
use `$resultSet->getAllResultCount()` instead of `$response->response->numFound` for tx_solr_statistics num_found DB column
Fixes: #2667
=> [BUGFIX:BACKPORT:11] use num_found in static db table #2667

Classes/IndexQueue/PageIndexerRequest.php
The variable is currently assigned to the page parent uid, but for page records the index queue item record uid represents the page uid already.
Fixes: #2663
=> [BUGFIX] Fix assignment for page uid variable

Classes/IndexQueue/PageIndexerRequest.php
The variable is currently assigned to the page parent uid, but for page records the index queue item record uid represents the page uid already.
Fixes: #2663
=> [BUGFIX:BACKPORT:10] Fix assignment for page uid variable

Classes/IndexQueue/PageIndexerRequest.php
The variable is currently assigned to the page parent uid, but for page records the index queue item record uid represents the page uid already.
Fixes: #2663
=> [BUGFIX:BACKPORT:11] Fix assignment for page uid variable

CONTRIBUTING.md
Replace information about vagrant with ddev inside of the contribution description
Verify the link inside of the instruction for ddev.
Check if the correct TYPO3 LTS and Solr server version is mentioned.
Fixes: #2672
=> [#2672] Replace information about vagrant with ddev

Classes/Domain/Search/SearchRequest.php, Tests/Unit/Domain/SearchRequestBuilderTest.php
Reset page argument if set to 0.
As 0 is the default, there is no need to have two different states to represent this.
By resetting, the array will not return the info and links to page 0 will not include the page argument.
This prevents two separate urls to the same source.
Reset page internally when being set to zero.
Create a search result with pagination. Open another page then the first.
Check the generated url for the first page, it should no longer contain the page argument.
Before this change it would contain the argument with value 0.
Fixes: #2719
=> Prevent duplicate urls for page 0

.github/no-response.yml
* will close the issues automatically if no response from creator is taken in 28 days
after adding more-information-needed label
=> [TASK] integrate githubs  probot / no-response

Documentation/FAQ/Index.rst, Documentation/GettingStarted/ConfigureExtension.rst
Makes it clear that `config.index_enable = 1` is still required to index anything.
Setup a clean install and try to index any content without `config.index_enable = 1`
Fixes: #2523
=> [DOCS] Note that config.index_enable is still needed - release 10

Documentation/FAQ/Index.rst, Documentation/GettingStarted/ConfigureExtension.rst
Makes it clear that `config.index_enable = 1` is still required to index anything.
Setup a clean install and try to index any content without `config.index_enable = 1`
Fixes: #2523
=> [DOCS] Note that config.index_enable is still needed - master

Documentation/FAQ/Index.rst, Documentation/GettingStarted/ConfigureExtension.rst
Makes it clear that `config.index_enable = 1` is still required to index anything.
Setup a clean install and try to index any content without `config.index_enable = 1`
Fixes: #2523
=> [DOCS] Note that config.index_enable is still needed - release 11

Classes/Domain/Search/SearchRequest.php, Tests/Unit/Domain/SearchRequestBuilderTest.php
Reset page argument if set to 0.
As 0 is the default, there is no need to have two different states to represent this.
By resetting, the array will not return the info and links to page 0 will not include the page argument.
This prevents two separate urls to the same source.
Reset page internally when being set to zero.
Create a search result with pagination. Open another page then the first.
Check the generated url for the first page, it should no longer contain the page argument.
Before this change it would contain the argument with value 0.
Fixes: #2719
=> [BUGFIX] Prevent duplicate urls for page 0 (#2718)

Classes/IndexQueue/FrontendHelper/AbstractFrontendHelper.php, Classes/IndexQueue/FrontendHelper/Dispatcher.php, Classes/IndexQueue/FrontendHelper/Manager.php, Classes/IndexQueue/FrontendHelper/PageIndexer.php, Classes/IndexQueue/PageIndexerRequestHandler.php, Classes/Middleware/FrontendUserAuthenticator.php, Classes/Middleware/PageIndexerFinisher.php, Classes/Middleware/PageIndexerInitialization.php, Configuration/RequestMiddlewares.php, Tests/Integration/Controller/SearchControllerTest.php, Tests/Integration/Controller/SuggestControllerTest.php
* implements FrontendUserAuthenticator middleware for indexing requests,
which fakes FE users with FE groups needed to access restricted pages and content elements
Fixes: #2634
=> [BUGFIX:BACKPORT:11] Restricted pages are not being indexed in Typo3 10

Classes/ViewHelpers/SearchFormViewHelper.php
ViewHelper SearchFormViewHelper contains a hard coded plugin namespace 'tx_solr'.
This Pull-Request is replaced the hard coded plugin namespace the configuration value
TBD
Fixes: #2691
=> [BUGFIX] Hard codes plugin namespace #2691

Documentation/Settings.cfg
This change fixes links for the "Edit on GitHub" button and in CONTRIBUTING.md due to an error in the previously merged PR #2690 
I am very sorry about this blunder. This time I double checked by rendering locally. 
btw. the "Edit on GitHub" is now already visible in the rendered documentation for "master".
=> [DOCS] Fix links

Classes/IndexQueue/RecordMonitor.php
This PR fixes a #2511 
To test you would need to index a table with translations enabled but without enable fields.
Fixes: #2511
=> Closes #2511: database exception in RecordMonitor

.editorconfig
Add editor configuration file based on TYPO3 standard in order to standardize the code format.
This configuration based on the TYPO3 editor configuration:
- https://github.com/TYPO3/TYPO3.CMS/blob/master/.editorconfig
No tests required.
Fixes: #2747
=> [TASK] Editor configuration

Classes/ViewHelpers/Backend/Security/IfHasAccessToModuleViewHelper.php
Calls of method BackendUserAuthentication::modAccess with two arguments deprecated since TYPO3 9.5, only one parameter is available in TYPO3 10.4
Resolves: #2746
This pull request removes the second parameter in call of method BackendUserAuthentication::modAccess.
This parameter is deprecated since TYPO3 9.5 and dropped in version 10.4.
https://github.com/TYPO3/TYPO3.CMS/blob/bf49d5eab37c660fce310905e18f8880ac378cae/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php#L447
1. Be on at least TYPO3 9.5
2. Enable reporting of deprecation errors (trigger_error + E_USER_DEPRECATED)
3. Visit the Solr "Info" backend module
4. An error is triggered
_Expected behavior_
No error should be triggered; the return value from modAccess() can be cast to …
=> [BUGFIX] Removes secondary parameter #2746

Classes/ViewHelpers/Backend/Security/IfHasAccessToModuleViewHelper.php
Calls of method BackendUserAuthentication::modAccess with two arguments deprecated since TYPO3 9.5, only one parameter is available in TYPO3 10.4
This pull request removes the second parameter in call of method BackendUserAuthentication::modAccess.
This parameter is deprecated since TYPO3 9.5 and dropped in version 10.4.
https://github.com/TYPO3/TYPO3.CMS/blob/bf49d5eab37c660fce310905e18f8880ac378cae/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php#L447
1. Be on at least TYPO3 9.5
2. Enable reporting of deprecation errors (trigger_error + E_USER_DEPRECATED)
3. Visit the Solr "Info" backend module
4. An error is triggered
_Expected behavior_
No error should be triggered; the return value from modAccess() can be cast to boolean which …
=> [BUGFIX:BACKPORT:11] Removes secondary parameter #2746

Classes/ViewHelpers/Backend/Security/IfHasAccessToModuleViewHelper.php
Calls of method BackendUserAuthentication::modAccess with two arguments deprecated since TYPO3 9.5, only one parameter is available in TYPO3 10.4
This pull request removes the second parameter in call of method BackendUserAuthentication::modAccess.
This parameter is deprecated since TYPO3 9.5 and dropped in version 10.4.
https://github.com/TYPO3/TYPO3.CMS/blob/bf49d5eab37c660fce310905e18f8880ac378cae/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php#L447
1. Be on at least TYPO3 9.5
2. Enable reporting of deprecation errors (trigger_error + E_USER_DEPRECATED)
3. Visit the Solr "Info" backend module
4. An error is triggered
_Expected behavior_
No error should be triggered; the return value from modAccess() can be cast to boolean which …
=> [BUGFIX:BACKPORT:10] Removes secondary parameter #2746

Configuration/TypoScript/Examples/Suggest/setup.txt
Adapts the typoscript to TYPO3 v9 notation and set the right type.
Also the right type is set now, when callback parameter isn't used.
Fixes: #2783
=> [BUGFIX] Correct Content-Type header for suggest response

Documentation/Configuration/Reference/TxSolrSearch.rst
Just a correction of a wrong typoscript path in TxSolrSearch.rst which stole some minutes of my day.
=> [DOCS] Fix TS lastSearches path

Classes/Query/Modifier/Faceting.php
To be able to combine facets from _GET and from flexforms, the key of the facets must be set to a proper name. Otherwise the index would be overriden.
Fixes: #2301
=> [BUGFIX:BACKPORT] Add facet name to facet filters (#2343)

Classes/Domain/Search/Score/ScoreCalculationService.php
Quote the value of variable $field for regular expressions.
The quote avoid exceptions in case the value contains one single slash.
To reproduce use the project https://github.com/TYPO3-Solr/solr-ddev-site
1. Open the backend
2. Select page `EXT:Solr test cases`
3. Add a text element with content `/Users/user1/Pictures/picture1.png`
4. Save page and index
5. Open frontend and search for `Users/`
Page `EXT:Solr test cases` should be listed within the search results
Fixes: #2824
=> [BUGFIX:BACKPORT:10] Quote field within score calculation

Classes/Domain/Search/Score/ScoreCalculationService.php
Quote the value of variable $field for regular expressions.
The quote avoid exceptions in case the value contains one single slash.
To reproduce use the project https://github.com/TYPO3-Solr/solr-ddev-site
1. Open the backend
2. Select page `EXT:Solr test cases`
3. Add a text element with content `/Users/user1/Pictures/picture1.png`
4. Save page and index
5. Open frontend and search for `Users/`
Page `EXT:Solr test cases` should be listed within the search results
Fixes: #2824
=> [BUGFIX:BACKPORT:11] Quote field within score calculation

Classes/Domain/Search/Score/ScoreCalculationService.php
Quote the value of variable $field for regular expressions.
The quote avoid exceptions in case the value contains one single slash.
To reproduce use the project https://github.com/TYPO3-Solr/solr-ddev-site
1. Open the backend
2. Select page `EXT:Solr test cases`
3. Add a text element with content `/Users/user1/Pictures/picture1.png`
4. Save page and index
5. Open frontend and search for `Users/`
Page `EXT:Solr test cases` should be listed within the search results
Fixes: #2824
=> [BUGFIX] Quote field within score calculation

Classes/ConnectionManager.php
* Is adding the language uid as array key again 
in order to have the correct core to language 
relation in the IndexInspector
Fixes: #2553
Fixes: #2731
Authored-by: Timo Hund
=> [BUGFIX:BACKPORT:10]  IndexInspector wrong language to document relation

Classes/Domain/Site/Site.php, Classes/Domain/Site/SiteInterface.php, Classes/Domain/Site/SiteRepository.php, Tests/Integration/Domain/Site/Fixtures/get_available_sites_do_not_return_sites_not_enabled.xml, Tests/Integration/Domain/Site/SiteRepositoryTest.php, Tests/Integration/IntegrationTest.php, Tests/Unit/Domain/Site/SiteRepositoryTest.php
SiteRepository should not return sites with disabled solr
when calling "getAvailableSites"
Resolves: #2795
Fixes: #2795
=> [BUGFIX] disabled Solr Sites #2795

Classes/Domain/Site/Site.php, Classes/Domain/Site/SiteInterface.php, Classes/Domain/Site/SiteRepository.php, Tests/Integration/Domain/Site/Fixtures/get_available_sites_do_not_return_sites_not_enabled.xml, Tests/Integration/Domain/Site/SiteRepositoryTest.php, Tests/Integration/IntegrationTest.php, Tests/Unit/Domain/Site/SiteRepositoryTest.php
SiteRepository should not return sites with disabled solr
when calling "getAvailableSites"
Resolves: #2795
=> [BUGFIX:BACKPORT:10] disabled Solr Sites #2795

Classes/Domain/Site/Site.php, Classes/Domain/Site/SiteInterface.php, Classes/Domain/Site/SiteRepository.php, Tests/Integration/Domain/Site/Fixtures/get_available_sites_do_not_return_sites_not_enabled.xml, Tests/Integration/Domain/Site/SiteRepositoryTest.php, Tests/Integration/IntegrationTest.php, Tests/Unit/Domain/Site/SiteRepositoryTest.php
SiteRepository should not return sites with disabled solr
when calling "getAvailableSites"
Resolves: #2795
=> [BUGFIX:BACKPORT:11] disabled Solr Sites #2795

Classes/Typo3PageContentExtractor.php, Tests/Unit/Typo3PageContentExtractorTest.php
=> [BUGFIX] Enable unicode when fetching pages

Classes/Domain/Search/Statistics/StatisticsRepository.php
Using backticks to specify columns in addSelectLiteral will result in an Doctrine\DBAL\Exception\SyntaxErrorException.
Remove the backticks in addSelectLiteral used in \ApacheSolrForTypo3\Solr\Domain\Search\Statistics\StatisticsRepository::getQueriesOverTime
Using TYPO3 V10 with a postgresql DB and apache-solr-for-typo3/solr V11.0.2.
Selecting the Solr Info Module in TYPO3 Backend will throw an Doctrine\DBAL\Exception\SyntaxErrorException.
Plain Installation. Nothing indexed yet.
Fixes: #2700
=> [BUGFIX] removing backticks in addSelectLiteral

Classes/Domain/Index/Queue/Statistic/QueueStatisticsRepository.php
After loading the indexing configuration and selecting The Index Queue Modul an Doctrine\DBAL\Exception\SyntaxErrorException occurs.
Create an indexing configuration and load it in TYPO3 Backend Module.
Click on Index Queue.
Fixes: #2702
=> [BUGFIX] using named parameter for empty string comparison

Configuration/TypoScript/Examples/Suggest/setup.typoscript
If `$GLOBALS['TYPO3_CONF_VARS']['FE']['debug']` is enabled (e.g. on Staging or local environments), the TypoScriptFrontendController will add some information to the response 
```html
```
to avoid this, the setting `config.debug=0` can be used which turns this off, no matter which global debug config is set
Resolves: #2834
=> [TASK] Disable cache time information for ajax request

Configuration/TypoScript/Examples/Suggest/setup.typoscript
If `$GLOBALS['TYPO3_CONF_VARS']['FE']['debug']` is enabled (e.g. on Staging or local environments), the TypoScriptFrontendController will add some information to the response 
```html
```
to avoid this, the setting `config.debug=0` can be used which turns this of, no matter which global debug config is set
Fixes: #2834
=> [TASK:BACKPORT:10] Disable cache time information for ajax request

Configuration/TypoScript/Examples/Suggest/setup.typoscript
If `$GLOBALS['TYPO3_CONF_VARS']['FE']['debug']` is enabled (e.g. on Staging or local environments), the TypoScriptFrontendController will add some information to the response 
```html
```
to avoid this, the setting `config.debug=0` can be used which turns this of, no matter which global debug config is set
Fixes: #2834
=> [TASK:BACKPORT:11] Disable cache time information for ajax request

Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
This will allow the usage of stdWrap for sorting labels.
Example: 
```
plugin.tx_solr.search {
sorting {
options {
relevance {
field = relevance
label = Relevance
label.data = LLL:EXT:your_sitepackage/Resources/Private/Language/locallang.xlf:search.results.sorting.relevance
}
}
}
}
```
Resolves #2339
=> Allow stdWrap on sorting label

Classes/Domain/Variants/VariantsProcessor.php, Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
This PR fixes the handling of case sensitive variant ids
The VariantsProcessor expects the content of the variant field to be
in lowercase and explicitly applies an mb_strtolower. Since Solr returns
the contents in the expanded field unchanged and the contents might be
case sensitive, the variants may not be recognized correctly and cannot
be accessed.
This issue is fixed by removing the unnecessary mb_strtolower.
Configure a custom variant field with case sensitive contents and check if the 
variants are detected correctly and are accessible.
Fixes: #2865
=> [BUGFIX] Fix handling of case sensitive variant ids

Classes/Domain/Variants/VariantsProcessor.php, Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
This PR backports the fix of the handling of case sensitive variant ids for
EXT:solr 11.x
The VariantsProcessor expects the content of the variant field to be
in lowercase and explicitly applies an mb_strtolower. Since Solr returns
the contents in the expanded field unchanged and the contents might be
case sensitive, the variants may not be recognized correctly and cannot
be accessed.
This issue is fixed by removing the unnecessary mb_strtolower.
Configure a custom variant field with case sensitive contents and check if the 
variants are detected correctly and are accessible.
Fixes: #2865
=> [BUGFIX:BACKPORT:11] Fix handling of case sensitive variant ids

Classes/Domain/Variants/VariantsProcessor.php, Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
This PR backports the fix of the handling of case sensitive variant ids for
EXT:solr 10.x
The VariantsProcessor expects the content of the variant field to be
in lowercase and explicitly applies an mb_strtolower. Since Solr returns
the contents in the expanded field unchanged and the contents might be
case sensitive, the variants may not be recognized correctly and cannot
be accessed.
This issue is fixed by removing the unnecessary mb_strtolower.
Configure a custom variant field with case sensitive contents and check if the 
variants are detected correctly and are accessible.
Fixes: #2865
=> [BUGFIX:BACKPORT:10] Fix handling of case sensitive variant ids

Classes/Domain/Search/ResultSet/Result/SearchResult.php, Classes/Domain/Variants/VariantsProcessor.php, Documentation/Configuration/Reference/TxSolrSearch.rst, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
To allow to access the number of existing variants, the SearchResult
is extended. Without this modification the number of existing variants
can is unknown, as the number of returned variants may be limited by
variants.limit.
Configure variants and check the set `variantsNumFound` in SearchResult
Resolves: #2870
=> [FEATURE] Store number of existing variants

Classes/Domain/Search/ResultSet/Result/SearchResult.php, Classes/Domain/Variants/VariantsProcessor.php, Documentation/Configuration/Reference/TxSolrSearch.rst, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
To allow to access the number of existing variants, the SearchResult
is extended. Without this modification the number of existing variants
can is unknown, as the number of returned variants may be limited by
variants.limit.
This is a backport of #2871 for EXT:solr 11.x
Configure variants and check the set `variantsNumFound` in SearchResult
Resolves: #2870
=> [FEATURE:BACKPORT:11] Store number of existing variants

Classes/Domain/Search/ResultSet/Result/SearchResult.php, Classes/Domain/Variants/VariantsProcessor.php, Documentation/Configuration/Reference/TxSolrSearch.rst, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
To allow to access the number of existing variants, the SearchResult
is extended. Without this modification the number of existing variants
can is unknown, as the number of returned variants may be limited by
variants.limit.
This is a backport of #2871 for EXT:solr 10.x
Configure variants and check the set `variantsNumFound` in SearchResult
Resolves: #2870
=> [FEATURE:BACKPORT:10] Store number of existing variants

Classes/Domain/Variants/VariantsProcessor.php, Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
If variants are enabled and a returned Solr document has no variants, the variant field value is not set. Currently variantFieldValue is only set if variantId is set in expanded, but if there is only one variant in the Solr index there will be no data in the expanded array.
This comit fixes this issue by ensuring that the variant field value is set even if there is no data in the expanded array.
1. Activate variants
2. Set the variant field to simulate
2.1. one document with at least one variant
2.2. one document without further variants
3. Check the variant field value of the document without variants, it's now set
Fixes: #2878
=> [BUGFIX] Fix missing variant field value

Classes/Domain/Variants/VariantsProcessor.php, Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
If variants are enabled and a returned Solr document has no variants, the variant field value is not set. Currently variantFieldValue is only set if variantId is set in expanded, but if there is only one variant in the Solr index there will be no data in the expanded array.
This comit fixes this issue by ensuring that the variant field value is set even if there is no data in the expanded array.
Backport for EXT:solr 11.x
1. Activate variants
2. Set the variant field to simulate
2.1. one document with at least one variant
2.2. one document without further variants
3. Check the variant field value of the document without variants, it's now set
Fixes: #2878
=> [BUGFIX:BACKPORT:11] Fix missing variant field value

Classes/Domain/Variants/VariantsProcessor.php, Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
If variants are enabled and a returned Solr document has no variants, the variant field value is not set. Currently variantFieldValue is only set if variantId is set in expanded, but if there is only one variant in the Solr index there will be no data in the expanded array.
This comit fixes this issue by ensuring that the variant field value is set even if there is no data in the expanded array.
Backport for EXT:solr 10.x
1. Activate variants
2. Set the variant field to simulate
2.1. one document with at least one variant
2.2. one document without further variants
3. Check the variant field value of the document without variants, it's now set
Fixes: #2878
=> [BUGFIX:BACKPORT:10] Fix missing variant field value

Classes/IndexQueue/Indexer.php
Restore the  line, which was removed by porting a commit from release-10.0.x to newer  in `Indexer::isRootPageIdPartOfRootLine()`
Related: #2520
Fixes: #2842
=> [BUGFIX:PORT:master] Function call with non existing variable

Classes/ViewHelpers/TranslateViewHelper.php
fix arguments for vsprintf in TranslateViewHelper when it's cached
Please see #2830 for details.
=> #2830 fixes Cached TranslateViewHelper

Classes/ViewHelpers/TranslateViewHelper.php
fix arguments for vsprintf in TranslateViewHelper when it's cached
Fixes: #2830
=> [BUGFIX:BP:10] Exception on Cached state of TranslateViewHelper

Classes/ViewHelpers/TranslateViewHelper.php
fix arguments for vsprintf in TranslateViewHelper when it's cached
Fixes: #2830
=> [BUGFIX:BP:11] Exception on Cached state of TranslateViewHelper

Classes/IndexQueue/RecordMonitor.php, Tests/Unit/IndexQueue/RecordMonitorTest.php
It is assumed here that if the $status is 'new', then the $recordUid must be a 'NEW...' string, which is normally the case.
However the $id is passed by reference and might be changed by other extensions. gridelements for example changes the $id.
https://gitlab.com/coderscare/gridelements/-/issues/156
So the check must be made more robust here.
=> [BUGFIX] Check if $recordUid is non-numeric before substitution

Classes/IndexQueue/RecordMonitor.php, Tests/Unit/IndexQueue/RecordMonitorTest.php
It is assumed here that if the $status is 'new', then the $recordUid must be a 'NEW...' string, which is normally the case.
However the $id is passed by reference and might be changed by other extensions. gridelements for example changes the $id.
https://gitlab.com/coderscare/gridelements/-/issues/156
So the check must be made more robust here.
Fixes: #2836
=> [BUGFIX:BP:10] Check if $recordUid is non-numeric before substitution

Classes/IndexQueue/RecordMonitor.php, Tests/Unit/IndexQueue/RecordMonitorTest.php
It is assumed here that if the $status is 'new', then the $recordUid must be a 'NEW...' string, which is normally the case.
However the $id is passed by reference and might be changed by other extensions. gridelements for example changes the $id.
https://gitlab.com/coderscare/gridelements/-/issues/156
So the check must be made more robust here.
Fixes: #2836
=> [BUGFIX:BP:11] Check if $recordUid is non-numeric before substitution

Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php, Classes/System/Configuration/TypoScriptConfiguration.php, Classes/ViewHelpers/Widget/Controller/FrequentlySearchedController.php
Drop creating cache fallback within class FrequentlySearchedController.
The fallback based on old TYPO3 vor code and is not functional since at least TYPO3 7.
Fixes: #2782
=> [TASK] Remove TYPO3 long time ago deprecated cache class

Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php, Classes/System/Configuration/TypoScriptConfiguration.php, Classes/ViewHelpers/Widget/Controller/FrequentlySearchedController.php
Drop creating cache fallback within class FrequentlySearchedController.
The fallback based on old TYPO3 vor code and is not functional since at least TYPO3 7.
Fixes: #2782
=> [TASK:BP:11] Remove TYPO3 long time ago deprecated cache class

Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php, Classes/System/Configuration/TypoScriptConfiguration.php, Classes/ViewHelpers/Widget/Controller/FrequentlySearchedController.php
Drop creating cache fallback within class FrequentlySearchedController.
The fallback based on old TYPO3 vor code and is not functional since at least TYPO3 7.
Fixes: #2782
=> [TASK:BP:10] Remove TYPO3 long time ago deprecated cache class

Classes/IndexQueue/Initializer/AbstractInitializer.php
Since TYPO3 10.4 the workspace now is not identify by pid value -1,
instead field 't3ver_wsid' is in use to filter workspace records.
This bugfix changes the filter to this new field and takes care about TYPO3 9.5 compatibility.
This test uses project https://github.com/TYPO3-Solr/solr-ddev-site
1. Install extension workspaces: `ddev composer require typo3/cms-workspaces:^10.4`
2. Activate extension: `ddev exec vendor/bin/typo3cms extension:activate workspaces`
3. Create a new workspace `Solr test` within the backend
- Note: When save an error occured, but the workspace is created
4. Switch to workspace `Solr test`
5. Add a new site `Workspace-site`
6. Activate the page
- Note: When save an error occured, but the page is activated
7. Go to the Solr Index Queue and initialise the Queue
You …
=> [BUGFIX] Change filter for workspace

Classes/IndexQueue/Initializer/AbstractInitializer.php
Since TYPO3 10.4 the workspace now is not identify by pid value -1,
instead field 't3ver_wsid' is in use to filter workspace records.
This bugfix changes the filter to this new field and takes care about TYPO3 9.5 compatibility.
1. Install extension workspaces: `ddev composer require typo3/cms-workspaces:^10.4`
2. Activate extension: `ddev exec vendor/bin/typo3cms extension:activate workspaces`
3. Create a new workspace `Solr test` within the backend
- Note: When save an error occured, but the workspace is created
4. Switch to workspace `Solr test`
5. Add a new site `Workspace-site`
6. Activate the page
- Note: When save an error occured, but the page is activated
7. Go to the Solr Index Queue and initialise the Queue
You should not find the page within the index queue.
Fixes: #2847
=> [BUGFIX:BP:11] Change filter for workspace

Classes/IndexQueue/Indexer.php
Generate a new context for language overlay items.
Change the language aspect to the given language id
This example based on the project https://github.com/TYPO3-Solr/solr-ddev-site
1. Enable news extension `ddev enable-news`
2. Add a new page `Translation` below `EXT:Solr test cases`
3. Add a text element with title `Example` and content `This is an example text.`
4. Translate the page to dansk. Title: `Oversættelse`
5. Translate the text element into dansk (connected mode)
- Title: `Eksempel`
- Content: `Dette er en eksempeltekst.` 
6. Translate the page to german. Title: `Übersetzung`
7. Add a new text element (free mode)
- Title: `Übersetzung im free mode`
- Content: `Diese Übersetzung soll im Freemode vorliegen.` 
8. Translate News with uid 3 `News № 1` to dansk
- Title: `Besked № 1` …
=> [BUGFIX] Language aspect for indexer

Classes/IndexQueue/Indexer.php
Generate a new context for language overlay items.
Change the language aspect to the given language id
This example based on the project https://github.com/TYPO3-Solr/solr-ddev-site
1. Enable news extension `ddev enable-news`
2. Add a new page `Translation` below `EXT:Solr test cases`
3. Add a text element with title `Example` and content `This is an example text.`
4. Translate the page to dansk. Title: `Oversættelse`
5. Translate the text element into dansk (connected mode)
- Title: `Eksempel`
- Content: `Dette er en eksempeltekst.` 
6. Translate the page to german. Title: `Übersetzung`
7. Add a new text element (free mode)
- Title: `Übersetzung im free mode`
- Content: `Diese Übersetzung soll im Freemode vorliegen.` 
8. Translate News with uid 3 `News № 1` to dansk
- Title: `Besked № 1` …
=> [BUGFIX:BP:11] Language aspect for indexer

Classes/Controller/SuggestController.php, Classes/Domain/Search/Query/SuggestQuery.php, Tests/Integration/Controller/Fixtures/can_suggest_with_uri_special_chars.xml, Tests/Integration/Controller/SuggestControllerTest.php
Since solarium escapes the special uri characters with RFC1738,
there are no needs to do the same within the EXT:Solr.
see:
https://github.com/solariumphp/solarium/blob/97a9df0c2d9ba35db3c747b30c0809702296f18b/src/Component/RequestBuilder/RequestParamsTrait.php#L153
This is the first step of removing the escaping/encoding from EXT:Solr API.
Other components of EXT:solr will be fixed as well in different pull requests.
Fixes: #2917
=> [BUGFIX:BP:10] remove escaping on suggestion prefix

Classes/Controller/SuggestController.php, Classes/Domain/Search/Query/SuggestQuery.php, Tests/Integration/Controller/Fixtures/can_suggest_with_uri_special_chars.xml, Tests/Integration/Controller/SuggestControllerTest.php
Since solarium escapes the special uri characters with RFC1738,
there are no needs to do the same within the EXT:Solr.
see:
https://github.com/solariumphp/solarium/blob/97a9df0c2d9ba35db3c747b30c0809702296f18b/src/Component/RequestBuilder/RequestParamsTrait.php#L153
This is the first step of removing the escaping/encoding from EXT:Solr API.
Other components of EXT:solr will be fixed as well in different pull requests.
Fixes: #2917
=> [BUGFIX:BP:11] remove escaping on suggestion prefix

Classes/Controller/SuggestController.php, Classes/Domain/Search/Query/SuggestQuery.php, Tests/Integration/Controller/Fixtures/can_suggest_with_uri_special_chars.xml, Tests/Integration/Controller/SuggestControllerTest.php
Since solarium escapes the special uri characters with RFC1738,
there are no needs to do the same within the EXT:Solr.
see:
https://github.com/solariumphp/solarium/blob/97a9df0c2d9ba35db3c747b30c0809702296f18b/src/Component/RequestBuilder/RequestParamsTrait.php#L153
This is the first step of removing the escaping/encoding from EXT:Solr API.
Other components of EXT:solr will be fixed as well in different pull requests.
=> [BUGFIX] remove escaping on suggestion prefix

Classes/FrontendEnvironment/Tsfe.php
The indexing fails when the `TypoScriptFrontendController` is constructed w/o a frontend user in `TypoScriptFrontendController::initUserGroups()` on line 930 when the visibility `includeHiddenContent` assigned to `$this->fe_user->showHiddenRecords`;
Fixes: #2761
Ported from: #2762
=> [BUGFIX] Pass FrontendUserAuthentication to TypoScriptFrontendController

Classes/FrontendEnvironment/Tsfe.php
The indexing fails when the `TypoScriptFrontendController` is constructed w/o a frontend user in `TypoScriptFrontendController::initUserGroups()` on line 930 when the visibility `includeHiddenContent` assigned to `$this->fe_user->showHiddenRecords;` This PR passes the `$fe_user` to the `TypoScriptFrontendController::_construct()`.
Fixes: #2761
=> [BUGFIX] Pass `FrontendUserAuthentication` to `TypoScriptFrontendController`

Build/Test/bootstrap.sh
Since changes of TYPO3 10.4.16 upgrade to doctrine/dbal v2.13.1 the builds are failing on TYPO3 10.4.16.
This temporary change is applied to be able to run tests within TYPO3 10.4.
=> [TASK] Fix test builds 2021.05.11

Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php, Resources/Private/Partials/Result/Sorting.html, Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
* Makes it possible to mark relevance sorting option as active.
Fixes: #2541
=> [BUGFIX:BP:10] Make relevance sorting option markable as active

Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php, Resources/Private/Partials/Result/Sorting.html, Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
* Makes it possible to mark relevance sorting option as active.
Fixes: #2541
=> [BUGFIX:BP:11] Make relevance sorting option markable as active

Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php, Resources/Private/Partials/Result/Sorting.html, Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
* It makes it possible to mark relevance sorting option as active.
1. Search for some word and check the relevance option state. It must be active.
2. Change the sorting to some other option and make sure the relevance is not marked as active, but only the selected option.
3. Select relevance again and make sure only relevance is marked as active.
Fixes: #2541
=> [BUGFIX] Make relevance sorting option markable as active

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
This prevents the Exception `Call to a member function getWriteService() on null` when solr is disabled (solr_enabled_read: false)
It prevents an exception when solr is disabled (solr_enabled_read: false)
Set `solr_enabled_read: false` and save a translated page
Fixes: #2940
=> [BUGFIX] Delete documents for valid connections only

Classes/System/Solr/ResponseAdapter.php, Classes/System/Solr/Service/SolrWriteService.php
Format of Solr Cell response changed, access to file title and file meta
data differs since Tika 1.24. This commit fixes the issue by adapting
the data access in the SolrWriteService.
Followup from: #2892
=> [TASK] Make Apache Solr v8.6+ compatible

Classes/Domain/Site/Site.php, Tests/Integration/Domain/Site/Fixtures/get_pages_returns_subpages_when_root_pages_should_not_be_indexed.xml, Tests/Integration/Domain/Site/SiteTest.php
Site->getPages() should use page indexConfigurationName if no configuration is found for rootPage
Resolves: #2742
use "pages" indexConfigurationName even if no Configuration found for rootPage
s. Integration Test
Fixes: #2742
=> [BUGFIX] use pages configuration as default #issue-2742

Classes/System/Solr/Service/SolrAdminService.php, Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
The fix is ported from https://github.com/solariumphp/solarium/pull/742
Note: 
The issue on base words containing "/" character in base word 
still persists in Apache Solr.
See: https://issues.apache.org/jira/browse/SOLR-6853
Fixes: #2336
=> [BUGFIX:BP:10] Delete synonyms with URL special chars

Classes/System/Solr/Service/SolrAdminService.php, Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
The fix is ported from https://github.com/solariumphp/solarium/pull/742
Note: 
The issue on base words containing "/" character in base word 
still persists in Apache Solr.
See: https://issues.apache.org/jira/browse/SOLR-6853
Fixes: #2336
=> [BUGFIX:BP:11.0] Delete synonyms with URL special chars

Classes/Report/SolrConfigStatus.php
Update the configset version for TYPO3 backend reporting. Has been missed to be updated in https://github.com/TYPO3-Solr/ext-solr/commit/d74d290f704cf9b98d21476ff74be89537a1d827
=> [TASK] Update solr config status for 11.1 configset

Documentation/Releases/solr-release-11-1.rst, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/danish/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/dutch/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/english/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/finnish/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/french/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/german/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/hungarian/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/irish/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/italian/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/norwegian/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/polish/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/portuguese/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/serbian/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/spanish/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/swedish/schema.xml, Resources/Private/Solr/configsets/ext_solr_11_1_0/conf/turkish/schema.xml
Adds the folding and normalization filters to improve the search
behaviour e.g. accents can be skipped.
For must languages the ASCII Folding Filter is used, but for e.g. for
Scandinavian languages language specific folding and normalization
filters are used.
Adapted schemata are:
- danish (Scandinavian Normalization, Scandinavian Folding)
- dutch
- english
- finish
- french
- german
- hungarian
- irish
- italian
- norwegian (Scandinavian Normalization, Scandinavian Folding)
- polish
- portuguese
- serbian (if no Serbian Normalization Filter)
- swedish (Scandinavian Normalization, Scandinavian Folding)
- spanish
- turkish
Test stemming and search behaviour of the affected cores, e.g. by using the analysis module.
Resolves: #2270
=> [TASK] Add folding and normalization Filters

Resources/Private/Partials/Result/Document.html, Resources/Private/Partials/Result/Facets.html, Resources/Private/Partials/Result/FacetsActive.html, Resources/Private/Partials/Result/PerPage.html, Resources/Private/Partials/Result/RelevanceBar.html, Resources/Private/Partials/Result/Sorting.html, Resources/Private/Partials/Search/Form.html, Resources/Private/Partials/Search/FrequentlySearched.html, Resources/Private/Partials/Search/LastSearches.html, Resources/Private/Templates/Search/Detail.html, Resources/Private/Templates/Search/Form.html, Resources/Private/Templates/Search/FrequentlySearched.html, Resources/Private/Templates/Search/Results.html, Resources/Private/Templates/Search/SolrNotAvailable.html, Resources/Private/Templates/ViewHelpers/Widget/GroupItemPaginate/Index.html, Resources/Private/Templates/ViewHelpers/Widget/ResultPaginate/Index.html
This PR fixes #2970. There is only one commit (165566674c57471fa0f30426f1c336f4422af98b). All others are from Github's fork/master sync.
By code review.
Fixes: #2970
=> Fix #2970: use correct html tags in templates

Classes/FrontendEnvironment/Tsfe.php
When initializing the TSFE a TYPO3_REQUEST is also initialized.
A request must always have a applicationType attribute.
If no applicationType is given `ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])`
can't bee used and throws an exception.
Call `ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])` on the 
`$GLOBALS['TYPO3_REQUEST']` that is initialized in
`Classes/FrontendEnvironment/Tsfe.php`
Fixes: #2932
=> [BUGFIX] Add missing applicationType to faked request

Classes/FrontendEnvironment/Tsfe.php
When initializing the TSFE a TYPO3_REQUEST is also initialized.
A request must always have a applicationType attribute.
If no applicationType is given `ApplicationType::fromRequest($GLOBALS['TYPO3_REQUEST'])`
can't bee used and throws an exception.
Fixes: #2932
Ported from: #2933
=> [BUGFIX:BP:11] Add missing applicationType to faked request

Classes/Domain/Search/Uri/SearchUriBuilder.php, Classes/System/Configuration/ExtensionConfiguration.php, Classes/System/UserFunctions/FlexFormUserFunctions.php, Configuration/FlexForms/Form.xml, Configuration/FlexForms/Results.xml, Documentation/Releases/solr-release-11-1.rst, Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php, ext_conf_template.txt, ext_localconf.php
cHash handling was adapted/disabled to fix generated links in TYPO3 9,
as this adaptions lead to invalid links, e.g. facet links, in TYPO3 10
and Site configuration support is available since EXT:solr 10 there is
no need for this adaptions.
This commit removes the implemented removal of the cHash parameter,
now the UriBuilder is used to build the link template.
Index some contents and check the generated links in the frontend:
- facet
- sorting
- pagination
Resolves: #2725
=> [TASK] Adapt cHash handling for TYPO3 10

Tests/Integration/IntegrationTest.php
currently the errorHandling for site configuration is written
```
errorHandling:
-
-
errorFluidTemplate: typo3/sysext/core/Tests/Functional/Fixtures/Frontend/FluidError.html
...
```
which will never be grabed because of array depth 2 
but shoult be array depth 1
```
errorHandling:
-
errorFluidTemplate: typo3/sysext/core/Tests/Functional/Fixtures/Frontend/FluidError.html
...
```
s. your written site-configuration in
`cat .Build/Web/typo3temp/var/tests/functional-<*>/typo3conf/sites/integration_tree_one/config.yaml`
=> [BUGFIX] writing errorHandling of site configuration

Classes/System/Util/SiteUtility.php
This pr makes the implemented language cache in SiteUtility.php (see https://github.com/TYPO3-Solr/ext-solr/commit/c3ed93df060b3ab9e8cb052bde13dd0663f27bba) work with multi site setups.
The languages should to be stored per root page, otherwise it leads to problems when having multiple rootpages that share sys_language ids for the languages.
Fixes: #2986
=> [TASK] Make language cache work with multi site setups

Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeTest.php
While getRangeString() might be protected, it can be called from the public function getUriValue() in the parent class.
Called with partially defined date ranges (start OR end missing) may lead to exceptions, because the format() is applied on null.
* Call solr with a filter parameter of e,g, tx_solr[filter][0]=cal:202105110000-
* Customize rendering of the result, e.g. using getUriValue() to generate a follow-up link.
* without pr: DateRange::getRangeString() is called, and excepts on the format() of $this->endRequested.
* with pr: DateRange::getRangeString() is called, and returns the same filter value for re-use.
Fixes: #2942
=> [BUGFIX] getRangeString(): check type before format() - call

Configuration/TypoScript/Examples/Suggest/setup.typoscript
Based on the issue in https://github.com/TYPO3-Solr/ext-solr/issues/2988
Updating typoscript condition to use the Symfony Expression Language.
Have the extension installed, use Solr, have no "_Expression could not be parsed. - {"expression":"globalString = GP:tx_solr|callback = "}_" in your typo3 error logs.
Fixes: #2988
=> Update TypoScript condition to Expression Language

Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeTest.php
function can be called publicly (via parent's getUriValue()), thus an incomplete range may lead to an unexpected exception
Fixes: #2942
Backported from: #2943
=> [BUGFIX:BP:10] getRangeString(): check type before format() - call

Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeTest.php
function can be called publicly (via parent's getUriValue()), thus an incomplete range may lead to an unexpected exception
Fixes: #2942
Backported from: #2943
=> [BUGFIX:BP:11] getRangeString(): check type before format() - call

Classes/Report/SiteHandlingStatus.php, Classes/System/Url/UrlHelper.php, Tests/Unit/System/Url/UrlHelperTest.php
If some url part is not set the getters have to return
an emtpy string.
Fixes: #2756
=> [BUGFIX] Fix type error in UrlHelper

Documentation/Appendix/VersionMatrix.rst
As we're planning to simplify the extension and dependency
handling we're harmonize the extension version with TYPO3.
So the next version of EXT:solr is 11.1.0, which is
compatible with TYPO3 10 LTS and all EXT:solr* addons in v 10.0.
=> [TASK] Update Version-Matrix for EXT:solr v11.1 stack

Classes/Domain/Index/Queue/QueueItemRepository.php
When updating a tracked, localisable item in the Solr queue the TCA setting for the "tstamp" / last updated on field ist not evaluated.
This leads to an exception with records that use a non-default name for this database field.
This PR changes this behaviour to use the TCA settings for the `$itemType`.
Add (or change) a custom record that is configured for Solr to use a non-default name for this field. E.g:
```php
$GLOBALS['TCA'][$table]['ctrl']['tstamp'] = 'updated_on';
```
Then you can test this exception and the fix before and after applying this small change.
Fixes: TYPO3-Solr#3037
=> [BUGFIX] Respect TCA setting of 'tstamp' field

Classes/Domain/Index/Queue/QueueItemRepository.php
When updating a tracked, localisable item in the Solr queue the TCA setting for the "tstamp" / last updated on field ist not evaluated.
This leads to an exception with records that use a non-default name for this database field.
Add (or change) a custom record that is configured for Solr to use a non-default name for this field
Resolves: #3037
=> [BUGFIX:BP:11-0] Respect TCA setting of 'tstamp' field

Classes/Domain/Index/Queue/QueueItemRepository.php
When updating a tracked, localisable item in the Solr queue the TCA setting for the "tstamp" / last updated on field ist not evaluated.
This leads to an exception with records that use a non-default name for this database field.
Add (or change) a custom record that is configured for Solr to use a non-default name for this field
Resolves: #3037
=> [BUGFIX:BP:11-1] Respect TCA setting of 'tstamp' field

Configuration/SiteConfiguration/Overrides/sites.php
It sets solr_path_read in site configuration to be not required
Leave solr_path_read empty and try to save the site configuration within its Sites module
Fixes: #3041
=> [BUGFIX] Set solr_path_read to be not required in site configuration #3041

Classes/Controller/SuggestController.php, Classes/Domain/Search/Suggest/SuggestService.php, Tests/Unit/Domain/Search/Suggest/SuggestServiceTest.php
This change prevents fatal error on suggest if invalid syntax on Apache Solr "qf" parameters.
Related: #2318
=> [BUGFIX] Prevent fatal on suggest action with invalid filters params

ext_localconf.php
Use the proper way to get the current context instead of deprecated call
=> [TASK] Use Environment::getContext() instead of GeneralUtility

Classes/Routing/RoutingService.php
Skips empty filters so no error gets thrown when using search & facets
When using routeEnhancers and filters as inputs, there is a possibility that an filter is empty  which results in an url like
`?tx_solr[q]=&tx_solr[filter][0]=`. This would throw an error
This pr adds an check if the filter is completely empty and skips it
Use an routeEnhancer and add an facet to the search form. Leave the fields empty and send
Fixes: #3099
=> [Bugfix:BP:11-5] routeenhancer with empty filters

Classes/Routing/RoutingService.php
Skips empty filters so no error gets thrown when using search & facets
When using routeEnhancers and filters as inputs, there is a possibility that an filter is empty  which results in an url like
`?tx_solr[q]=&tx_solr[filter][0]=`. This would throw an error
This pr adds an check if the filter is completely empty and skips it
Use an routeEnhancer and add an facet to the search form. Leave the fields empty and send
Fixes: #3099
=> [Bugfix:BP:11-1] routeenhancer with empty filters

Classes/Routing/RoutingService.php
Skips empty filters so no error gets thrown when using search & facets
When using routeEnhancers and filters as inputs, there is a possibility that an filter is empty  which results in an url like
`?tx_solr[q]=&tx_solr[filter][0]=`. This would throw an error
This pr adds an check if the filter is completely empty and skips it
Use an routeEnhancer and add an facet to the search form. Leave the fields empty and send
Fixes: #3099
=> [Bugfix] routeenhancer with empty filters

Resources/Private/Language/cs.locallang.xlf
This PR adds Czech locallang.xlf file.
The translations were provided by our customer and contributed to Ext:solr.
Setup a TYPO3 installation with Czech language and Solr cores. Index some pages or records and use the search.
Labels from Ext:solr should now be displayed in Czech instead of English.
Fixes: #3132 (Please create an related issue first and mark it as fixed here with your pr)
=> [TASK] Add Czech translation

Classes/Middleware/FrontendUserAuthenticator.php
The initialization of the user was not fully completed on indexer crawl page requests, thus storing data in the user session was not possible.
Initialize the fake user which is used when indexer crawles pages.
Try to index a page which puts data into the user session store (e.g. form honeypot) - which previously resulted in an "Call to a member function set() on null" error.
Relates: #2976
Fixes: #3088
=> [FIX] Can't index pages which require a user session

Classes/Domain/Search/Uri/SearchUriBuilder.php
The following line forces the creation of `tx_solr.filter` in arguments, since the arguments array is handled as reference and do not observe `pluginNamespace` configuration:
```php
$this->sortFilterParametersIfNecessary($previousSearchRequest, $arguments['tx_solr']['filter']);
```
This PR fixes the folowing issues:
1. `tx_solr.filter` are only sorted if present in arguments array
2. `tx_solr.filter` are not forced to be created anymore
3. namespace configuration is observed 
Fixes: #3126 for v11.5 (TYPO3 11).
See #3127 for main
=> [Bugfix] Prevent unwanted filter parameters from being generated (v11.5)

Classes/Domain/Search/Uri/SearchUriBuilder.php
The following line forces the creation of `tx_solr.filter` in arguments, since the arguments array is handled as reference and do not observe `pluginNamespace` configuration:
```php
$this->sortFilterParametersIfNecessary($previousSearchRequest, $arguments['tx_solr']['filter']);
```
This PR fixes the folowing issues:
1. `tx_solr.filter` are only sorted if present in arguments array
2. `tx_solr.filter` are not forced to be created anymore
3. namespace configuration is observed 
Fixes: #3126 for main.
Fixes: #3126 for main.
See #3128 for v11.1 (TYPO3 10).
=> [Bugfix] Prevent unwanted filter parameters from being generated (main)

Classes/Domain/Search/Uri/SearchUriBuilder.php
The following line forces the creation of `tx_solr.filter` in arguments, since the arguments array is handled as reference and do not observe `pluginNamespace` configuration:
```php
$this->sortFilterParametersIfNecessary($previousSearchRequest, $arguments['tx_solr']['filter']);
```
This PR fixes the folowing issues:
1. `tx_solr.filter` are only sorted if present in arguments array
2. `tx_solr.filter` are not forced to be created anymore
3. namespace configuration is observed 
Fixes: #3126 for v11.1 (TYPO3 10).
See #3127 for main
=> [Bugfix] Prevent unwanted filter parameters from being generated (v11.1)

Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
This PR improves variants handling by sorting user groups for the page in reverse order, which makes main variant to be from the user group instead of from the anonymous group.
* Add content for a user group on the page
* Add `variants = 1` to the configuration ([ref](https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Configuration/Reference/TxSolrSearch.html#variants))
* Index the page
* Search for the keyword in the protected content
* The page will be found but the content will not be highlighted because the variant will be from the anonymous user
* Apply the patch
* Clear the index
* Reindex
* Try searching again and see highlighted variant
Fixes: #3143
=> [FEATURE] Fix #3143: improve variant handling by sorting user groups

Classes/Task/ReIndexTaskAdditionalFieldProvider.php
This PR fixes exception in scheduler with TYPO3 v11 and PHP 8.
Try to add a new task on YUPO3 v11 + PHP 8 + EXT:solr at `release-11.5.x`.
Fixes: #3145
=> [BUGFIX] Fix #3145: exception in scheduler with php 8

Classes/ViewHelpers/TranslateViewHelper.php
This PR fixes `TypeError` in `TranslateViewHelper` under php 8.
Since this viewhelper contains compilation instructions, it also needs `null` hints in php 8 to allow passing `null` values.
See #3141 for instructions.
Fixes: #3141
=> [BUGFIX] Fix #3141: TypeError in TranslateViewHelper

Classes/Domain/Index/IndexService.php
Since we catch \Throwable instead of \Exception, we should change the typehint of the error log generating method, too. This will prevent errors while catching \Error instances.
This pr will change the method signature of ApacheSolrForTypo3\Solr\Domain\Index\IndexService::generateIndexingErrorLog 
Fixes: #3161
=> Allow to generate indexing error log from throwable

Build/Test/IntegrationFrontendTests.xml, Classes/Backend/IndexingConfigurationSelectorField.php, Classes/ContentObject/Relation.php, Classes/Controller/AbstractBaseController.php, Classes/Controller/Backend/Search/InfoModuleController.php, Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/Domain/Index/Queue/QueueItemRepository.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/AbstractRangeFacetParser.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetQueryBuilder.php, Classes/Domain/Search/ResultSet/Result/SearchResult.php, Classes/FieldProcessor/PageUidToHierarchy.php, Classes/IndexQueue/AbstractIndexer.php, Classes/IndexQueue/FrontendHelper/PageIndexer.php, Classes/IndexQueue/Indexer.php, Classes/IndexQueue/Queue.php, Classes/Middleware/SolrRoutingMiddleware.php, Classes/Query/Modifier/Faceting.php, Classes/Typo3PageIndexer.php, Classes/ViewHelpers/Debug/DocumentScoreAnalyzerViewHelper.php, Classes/ViewHelpers/Debug/QueryViewHelper.php
In TYPO11 with PHP 8 there are some Errors like *PHP Warning: Undefined array key*.
This PR adds some additional checks and prevents this errors.
The additional options in IndexingConfigurationSelectorField are required to prevent warnings in TYPO3 core Backend FormElements and FieldWizards.
=> [BUGFIX] Prevent some "undefined array key" warnings with php 8

Classes/ViewHelpers/TranslateViewHelper.php
If using PHP 8.1, the following exception is thrown
```
PHP Runtime Deprecation Notice: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in
```
Cast the value to a string to avoid the exception
=> [BUGFIX] Fix notice in TranslateViewHelper

Classes/Domain/Site/SiteRepository.php
Path of write connection is read from read scope, so different paths
couldn't be used, this is fixed by inserting the right scope.
Configure and test write connection
Fixes: #2916
=> [BUGFIX:BP:11.2] Fix write connection

Classes/FrontendEnvironment/Tsfe.php
This change makes sure to keep a BE_USER as TSFE->determineId() might unset
the global object. 
Fixes: #3167
=> [BUGFIX] Ensure BE_USER is kept when initializing TSFE

.gitattributes
The github configuration should be removed for production environment.
1. Checkout project
```
git clone git@github.com:TYPO3-Solr/ext-solr.git
```
2. Create archive
```
cd ext-solr
git archive --output=./ext-solr.tar --format=tar HEAD
```
3. Check content of archive
```
tar -tvf ext-solr.tar | grep '.github'
```
The result should not contain ".github".
Fixes: #3212
=> [TASK] Ignore github configuration for export

Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php, Classes/IndexQueue/PageIndexer.php
I got the folowing error in **TYPO3 11** with **PHP 8** after editing a be_user:
```
PHP Warning: Undefined array key "TSFE" in ./typo3conf/ext/solr/Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php line 169
```
This PR fixes an issue in backend for records located on page id 0 like be_users.
If there is no TSFE and the page id is 0, there is no need to check the rootline to get the root page id.
Trace:
```php
[
0 => './typo3/index.php:{closure}#21',
1 => './typo3/index.php:TYPO3\\CMS\\Core\\Http\\AbstractApplication->run#20',
2 => './typo3/sysext/core/Classes/Http/AbstractApplication.php:TYPO3\\CMS\\Backend\\Http\\Application->handle#100',
3 => './typo3/sysext/backend/Classes/Http/Application.php:TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle#72',
4 => …
```
=> [BUGFIX] Skip rootline check in be for records stored at pid 0

Classes/Task/ReIndexTaskAdditionalFieldProvider.php
Fixes exception when setting up the scheduler task for force reindexing page.
=> FIX: Argument 1 passed to AbstractSolrTask::setRootPageId() must be of the type int, string given

Documentation/Configuration/Reference/TxSolrIndex.rst, Documentation/FAQ/Index.rst
Added explanations of the virtual field in [queue.[indexConfig].fields](https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Configuration/Reference/TxSolrIndex.html#id12) and [FAQ](https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/FAQ/Index.html)
Slack Conversation: https://app.slack.com/client/T024TUMLZ/C02FF05Q4/thread/C02FF05Q4-1646727764.460269
=> [DOCS] Provide info about the virtual field __solr_contents in Docs

Classes/Controller/Backend/Search/InfoModuleController.php
As strftime is deprecated, its warning must be supressed as there is no dropin replacement. See https://review.typo3.org/c/Packages/TYPO3.CMS/+/72055 which solved it in the same way
=> [TASK] Supress warnings of strftime

composer.json
This extension seems not to be necessary for ext:solr.
Maybe it was required by mistake.
Fixes: #3226
It removes the requirement of ext:bootstrap_package.
No PHP warning with version 8.0. See issue #3226 .
Fixes: #3226
=> [TASK] Remove unnecessary bootstrap_package

Documentation/Index.rst, Documentation/Releases/solr-release-11-5.rst, Documentation/Settings.cfg, ext_emconf.php
First release candidate of 11.5.0 for TYPO3 11 LTS
#standwithukraine #nowar
* TYPO3 11 LTS compatibility
* Improved data update handling
* #3166 
* #3160
* #3169 
* #3220 
This release candidate is not available in TYPO3 TER, if you want to try this
release, please download and install this release manually from:
* https://github.com/TYPO3-Solr/ext-solr/releases/tag/11.5.0-rc-1
---
* Provide patches through pull requests or review and comment on
existing pull requests
* Go to www.typo3-solr.com or call dkd to sponsor the ongoing
development of Apache Solr for TYPO3
Support us by becoming an EB partner: …
=> Release 11.5.0-rc-1

Classes/Controller/Backend/Search/IndexQueueModuleController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf
Not all kind of errors while initializing the index queue are currently handled and so an error page or debug trace might be
shown. This commit adds an additional check and implements a more pleasant error message.
Force an error during queue initializing, e.g. activate solrfal logging and deny access to the log file.
Related: TYPO3-Solr/ext-solrfal#148
=> [TASK] Improve error handling in index queue module

README.md, composer.json
Reduce README.md to an abstract and links to important pages
that cover the user's next steps, especially the full
documentation and TER page for installation, but also add-ons
and the paid services.
The details of the contribution are already in CONTRIBUTION.md
and in the full documentation - and obvious if you look at the
git history.
The contact details should be moved to the full documentation.
Keep outgoing links to a minimum to not distract the user.
Related: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182
=> [DOCS] Align README.md with other extensions

Classes/Domain/Search/ResultSet/Facets/AbstractFacet.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/AbstractOptionsFacet.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacet.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParser.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacet.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacet.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetParser.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/AbstractRangeFacetParser.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacet.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/NumericRange/NumericRangeFacet.php, Classes/Domain/Search/ResultSet/SearchResultSetService.php, Classes/FrontendEnvironment/TypoScript.php, Classes/Task/OptimizeIndexTaskAdditionalFieldProvider.php, Classes/Task/ReIndexTaskAdditionalFieldProvider.php, Classes/ViewHelpers/SearchFormViewHelper.php, Classes/ViewHelpers/Uri/Result/AddSearchWordListViewHelper.php, Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/FacetCollectionTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionCollectionTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/OptionCollectionTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/RequirementsServiceTest.php, Tests/Unit/Domain/Search/ResultSet/SearchResultSetServiceTest.php, Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php, Tests/Unit/ViewHelpers/Facet/Area/GroupViewHelperTest.php, Tests/Unit/ViewHelpers/Uri/Facet/AbstractFacetItemViewHelperTest.php
This pull requests contains several bugfixes and improvements for TYPO3 11
- variable and argument types are enforced to prevent type errors
- ObjectManager in SearchResultSetService is now instantiated via class constructor to simplify the replacement of the ObjectManager in other solr add-ons
- AbstractFacet instantiates the ObjectManager via class constructor to ensure ObjectManager is correctly initialized (#3235)
- configure and uses all facet types
- debug Solr result set in the frontend
- run tests
Fixes: #3235
=> [BUGFIX] Minor TYPO3 11 bugfixes and improvements

Classes/Pagination/ResultsPagination.php
With these two additional getters it is possible to access the variables
in fluid templates.
Fixes: #3254
=> [BUG] Make pageRangeFirst and pageRangeLast accessible in fluid

Classes/IndexQueue/RecordMonitor.php
Before accessing the dataHandler array ensure the requested key is available and skip, if this is not the case. 
Fixes: #3269
=> [BUGFIX] Ensure array value is set when accessing

Classes/Domain/Search/ResultSet/SearchResultSet.php, Classes/Domain/Search/Uri/SearchUriBuilder.php
This change fixes two issues for class properties initialized by inject or setter methods.
The properties and getters must be nullable, 
if inject method or setter methods initialise properties.
This patch applies on:
* \ApacheSolrForTypo3\Solr\Domain\Search\Uri\SearchUriBuilder::$routingService
* \ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\SearchResultSet::$response
Fixes: #3288
ToDos:
=> [BUGFIX] Class properties must not be accessed before initialization

Classes/IndexQueue/RecordMonitor.php, Tests/Unit/IndexQueue/RecordMonitorTest.php, ext_localconf.php
This pull request respects the indexing configuration for new and updated subpages. On each save of a subpage or a record on a subpage the rootline is checked for at least one page that is configured to exclude all subentries from search. If this is the case the subpage is not added to the indexing queue.
Fixes: #3276
=> [BUGFIX] Respect indexing configuration for new and updated subpages

Classes/GarbageCollector.php
Replaces explode with GeneralUtility::intExplode
Fixes: #3249
=> [BUGFIX] User groups always compared as integers

Classes/Domain/Search/Query/SuggestQuery.php, Tests/Unit/Domain/Search/Query/SuggestQueryTest.php
Sending a suggest query containing only spaces causes PHP 8+ to throw a
TypeError exception because the result of the regular expression will
not have a third entry in its matches array.
Use null-coalescing operator to ensure a string is given to the trim
function in the SuggestQuery constructor.
Enter only spaces into the search field (which has the autocomplete/suggest function properly configured)  of a TYPO3 installation that uses PHP 8.0 or newer.
Additionally a test was added: \ApacheSolrForTypo3\Solr\Tests\Unit\Domain\Search\Query\SuggestQueryTest->testSuggestQueryDoesNotErrorOnEmptyKeywords
Fixes: #3302
=> Fix empty suggest query triggering a PHP error

Classes/Domain/Search/Query/SuggestQuery.php, Tests/Unit/Domain/Search/Query/SuggestQueryTest.php
Sending a suggest query containing only spaces causes PHP 8+ to throw a
TypeError exception because the result of the regular expression will
not have a third entry in its matches array.
Use null-coalescing operator to ensure a string is given to the trim
function in the SuggestQuery constructor.
Enter only spaces into the search field (which has the autocomplete/suggest function properly configured)  of a TYPO3 installation that uses PHP 8.0 or newer.
Additionally a test was added: \ApacheSolrForTypo3\Solr\Tests\Unit\Domain\Search\Query\SuggestQueryTest->testSuggestQueryDoesNotErrorOnEmptyKeywords
Fixes: #3302
=> [BUGFIX:BP:11.5] Empty suggest query triggers a PHP error

.php-cs-fixer.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilder.php, Tests/Integration/IntegrationTest.php, Tests/Unit/UnitTest.php
Ensures correct return types in OptionsFacetQueryBuilder for settings
facetLimit and minimum count.
Configure facetLimit and/or minimumCount, e.g.:
- facets.facetxy.facetLimit
- facets.facetxy.minimumCount
Fixes: #3304
=> [BUGFIX] Fix type errors in OptionsFacetQueryBuilder

Documentation/Configuration/Reference/TxSolrLogging.rst
Add missing doc for plugin.tx_solr.logging.indexing.pageIndexed
=> [DOCS] add missing doc for plugin.tx_solr.logging.indexing.pageIndexed

.php-cs-fixer.php, Tests/Integration/IntegrationTest.php, Tests/Unit/UnitTest.php
typo3/coding-standards 0.5.4 includes rule modernize_strpos, which is not possible with PHP 7.4 as str_contains requires
PHP 8.
This pull request removes rule modernize_strpos and contains some minor adaptions.
=> [TASK:BP:11.5] Adjust typo3/coding-standards settings

Documentation/Configuration/Reference/TxSolrLogging.rst
Add missing doc for plugin.tx_solr.logging.indexing.pageIndexed
Related: #3102
=> [DOCS:BP:11.2] add missing doc for plugin.tx_solr.logging.indexing.pageIndexed

Build/Test/bootstrap.sh, composer.json, ext_emconf.php
With EXT:solr 11.5 we're increasingly using local objects, but most ContentObjects in the TYPO3 core required a global version of the TypoScriptFrontendController which leads to problems during indexing. TYPO3 11.5.14 contains some adaptions to support the usage of local TypoScriptFrontendController objects, these adaptions are fixing this issue, so we require at least TYPO3 11.5.14.
Resolves: #3239
Resolves: #3244
=> [TASK] Require TYPO3 11.5.14

Build/Test/bootstrap.sh, composer.json, ext_emconf.php
With EXT:solr 11.5 we're increasingly using local objects, but most ContentObjects in the TYPO3 core required a global version of the TypoScriptFrontendController which leads to problems during indexing. TYPO3 11.5.14 contains some adaptions to support the usage of local TypoScriptFrontendController objects, these adaptions are fixing this issue, so we require at least TYPO3 11.5.14.
Resolves: #3239
Resolves: #3244
=> [TASK:BP:11.5] Require TYPO3 11.5.14

Configuration/SiteConfiguration/Overrides/sites.php
- increase size for host field
- change arrangement of columns to 2x2 instead of a single row
- clear cache
- check arrangement in sites modules config solr tab
Fixes: #3295
=> [TASK:BP:11.5] Adapt column arrangement within sites config

Configuration/SiteConfiguration/Overrides/sites.php
- increase size for host field
- change arrangement of columns to 2x2 instead of a single row
- clear cache
- check arrangement in sites modules config solr tab
Fixes: #3295
=> [TASK:BP:11.2] Adapt column arrangement within sites config

Classes/FieldProcessor/Service.php, Documentation/Frontend/Facets.rst, Tests/Unit/FieldProcessor/ServiceTest.php, Tests/Unit/FieldProcessor/TestFieldProcessor.php
Relates: #1811
Be able to register custom field processors.
Execute the test `\ApacheSolrForTypo3\Solr\Tests\Unit\FieldProcessor\ServiceTest::customFieldProcessorTurnsFooIntoBar`
Fixes: #1811
=> [FEATURE:BP:11.5] Add custom field processors

Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
The keywords field of the statistics database is only 128 characters
long. If a search keyword with more than 128 chars is used, the 
database insert fails if statistics are enabled.
1. enable statistics
2. use a search term with more than 128 characters
Fixes: #3321
=> [BUGFIX] Ensure keywords string does not exceed database field length

Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
The keywords field of the statistics database is only 128 characters
long. If a search keyword with more than 128 chars is used, the 
database insert fails if statistics are enabled.
Fixes: #3321
Ports: #3322
=> Ensure keywords string does not exceed database field length

Classes/Controller/SearchController.php
fixes #3323
While paginating searchResults, this pr makes sure that the currentPage never gets below 1 and prevents an exception and a 503 error on the client side. 
This can happen i.e. through the GET parameter ?[page]=0 or ?[page]=-20
Open a searchResult page and set the page to 0 or lower than 0. Now instead of an exception and 503 error on the client side, the current page should be set to 1:
https://xyz.de/suche?tx_solr[page]=0
Fixes: #3323
=> [BUG] make sure that $currentPageNumber in resultsAction is always >= 1

Classes/IndexQueue/PageIndexerRequest.php
This PR adds logging for failed site requests. This helps to detect what exactly happened. Messages will appear in the log file for Testing and Development contexts by default. Preview password will be masked in logs.
Test by placing password protection in front of the site and starting indexing without user name and password. You will get a vague error in the queue module but a good description of the problem in the log file.
We had a more complicated case, which cost us several lost hours due to missing logging of errors: the site was password protected and we supplied the password. But it still failed to index. When we added logging, we found that the site was accessed using proxy, which we had on this host and proxy did not care to pass on http authentication. It took a lot of time to …
=> [FEATURE] add logging for failed http requests

Classes/FrontendEnvironment/Tsfe.php
…in Tsfe->getPidToUseForTsfeInitialization. Fixes #3306
Before calling Tsfe->getPidToUseForTsfeInitialization recursively from itself, checks if the function parameters are different from the current call. If they are not, calling recursively will end in an infinite loop, crashing the application by running into PHPs memory limit.
- In TYPO3, create a sysfolder named "General Storage"
- Add a typoscript root template to that sysfolder
- Create a subfolder containing some indexable records, for example "news"
- Add an indexable record (news item)
- Setup SOLR to index the record (include the default news indexing configuration typoscript)
- Build index query for news
- Run indexer
Without the fix, php memory limit will be reached ("Allowed memory size of xyz bytes exhausted").
The fix …
=> [BUGFIX] fix infinite loop in Tsfe::getPidToUseForTsfeInitialization()

Documentation/Releases/solr-release-11-5.rst, Documentation/Settings.cfg, ext_emconf.php
#standwithukraine #nowar
We are happy to release EXT:solr 11.5.0 for TYPO3 11 LTS.
The focus of this release has been on TYPO3 11 LTS compatibility.
NOTE: At least TYPO3 v11.5.14 is required.
Huge improvements:
* TYPO3 11 LTS compatibility
* Improve and Fix TSFE Initialization
* Get "free content mode" working
* Improved data update handling
* Bootstrap 5.1
* Custom field processors
* N-Gram Filter for strings
* etc. and many more 
https://github.com/TYPO3-Solr/ext-solr/releases/tag/11.5.0
---
* Provide patches through pull requests or review and comment on
existing pull …
=> Release 11.5.0

.scrutinizer.yml, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php
Fixes Uncaught TYPO3 Exception when a page with uid 0 is  handed to the solr handlePageUpdate function.
Ports: #3338
=> [BUGFIX:BP:11.2] Do not handle page updates on new page with uid 0

Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php
Fixes Uncaught TYPO3 Exception when a page with uid 0 is  handed to the solr handlePageUpdate function.
Ports: #3338
=> [BUGFIX:BP:11.5] Do not handle page updates on new page with uid 0

Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php
Fixes `Uncaught TYPO3 Exception` when a page with uid `0` is handed to the solr `handlePageUpdate` function.
There are edge cases when creating a new page in the TYPO3 backend might fail – non-related to ext-solr – and usually an error gets logged or displayed.
Edge cases like development, db connection issues, migth also be on missing user permissions… 
If a new page creation in TYPO3 BE fails and ext-solr is active, this results in ext-solr failing.
And instead of showing or logging the original error message from the underlying problem, an error message from ext-solr is thrown:
```php
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 2 passed to ApacheSolrForTypo3\Solr\Domain\Index\Queue\UpdateHandler\AbstractUpdateHandler::getAllCurrentStateFieldsMatch() must be of the …
```
=> [BUGFIX] Do not handle page update for failed new page creation

Classes/Middleware/SolrRoutingMiddleware.php, Tests/Unit/Middleware/SolrRoutingMiddlewareTest.php
Shortcircuit work in SolrRoutingMiddleware like in PageIndexerFinisher: When a request does not have the X-Tx-Solr-Iq header, then it's not interesting for the Solr extension.
Background: Superflous logging 'Could not resolve page by path...' to Solr logfile.
Relates: #3202
Ports: #3339
=> [BUGFIX:BP:11.2] Shortcircuit work in SolrRoutingMiddleware

Classes/Middleware/SolrRoutingMiddleware.php, Tests/Unit/Middleware/SolrRoutingMiddlewareTest.php
Shortcircuit work in SolrRoutingMiddleware like in PageIndexerFinisher: When a request does not have the X-Tx-Solr-Iq header, then it's not interesting for the Solr extension.
Background: Superflous logging 'Could not resolve page by path...' to Solr logfile.
Relates: #3202
Ports: #3339
=> [BUGFIX:BP:11.5] Shortcircuit work in SolrRoutingMiddleware

Classes/Middleware/SolrRoutingMiddleware.php, Tests/Unit/Middleware/SolrRoutingMiddlewareTest.php
Shortcircuit work in SolrRoutingMiddleware like in PageIndexerFinisher: When a request does not have the X-Tx-Solr-Iq header, then it's not interesting for the Solr extension.
Background: Superflous logging 'Could not resolve page by path...' to Solr logfile.
- Index a page, see that its indexed correctly
- You don't see superflous logging for non-existing url paths
Fixes: #3202
=> [BUGFIX] Shortcircuit work in SolrRoutingMiddleware

Classes/IndexQueue/Indexer.php, Classes/PageDocumentPostProcessor.php, Classes/Typo3PageIndexer.php, Documentation/Development/Indexing.rst, Tests/Integration/Controller/AbstractFrontendControllerTest.php, Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php, Tests/Integration/IndexQueue/FrontendHelper/TestPageIndexerDocumentsModifier.php, Tests/Integration/IntegrationTest.php, Tests/Integration/SearchTest.php
It calls the hook preAddModifyDocuments also for pages and deprecates the hook indexPagePostProcessPageDocument
* Register Hook `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['IndexQueueIndexer']['preAddModifyDocuments']['TestPageIndexerDocumentsModifier'] = TestPageIndexerDocumentsModifier::class;`
* Index a page
* See `postProcessorField_stringS: postprocessed` in the indexed document
Fixes: #2285 
Ports: #3076
=> !!![TASK] Use preAddModifyDocuments hook for pages

Classes/IndexQueue/Indexer.php, Classes/PageDocumentPostProcessor.php, Classes/Typo3PageIndexer.php, Documentation/Development/Indexing.rst, Tests/Integration/Controller/AbstractFrontendControllerTest.php, Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php, Tests/Integration/IndexQueue/FrontendHelper/TestPageIndexerDocumentsModifier.php, Tests/Integration/IntegrationTest.php, Tests/Integration/SearchTest.php
It calls the hook preAddModifyDocuments also for pages and deprecates the hook indexPagePostProcessPageDocument
* Register Hook `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['IndexQueueIndexer']['preAddModifyDocuments']['TestPageIndexerDocumentsModifier'] = TestPageIndexerDocumentsModifier::class;`
* Index a page
* See `postProcessorField_stringS: postprocessed` in the indexed document
Fixes: #2285
=> !!![TASK] Use preAddModifyDocuments  hook for pages

Classes/FrontendEnvironment/TypoScript.php
Reading nested TypoScript will no longer log a warning when the value can not be accessed. In this case, the second value in the array returned in `TypoScript::ext_getSetup` will be an empty string. However, the second value is not used by Ext:solr anymore.
This also fixes an issue with PHP 8 where such warning would cause the indexing to fail, when the method is used inside of an indexer.
Set in TypoScript setup:
```typoscript
plugin.tx_myextension {
settings {
foo = bar
}
}
```
Place this snipped inside a Solr indexer or Solr indexer hook:
```php
use ApacheSolrForTypo3\Solr\FrontendEnvironment;
// @var $indexItem \ApacheSolrForTypo3\Solr\IndexQueue\Item
$settings =  GeneralUtility::makeInstance(FrontendEnvironment::class)
->getConfigurationFromPageId($indexItem->getRootPageUid(), …
```
=> [BUGFIX] Fix array key access in ext_getSetup

Classes/FrontendEnvironment/TypoScript.php
Reading nested TypoScript will no longer log a warning when the value can not be accessed. In this case, the second value in the array returned in `TypoScript::ext_getSetup` will be an empty string. However, the second value is not used by Ext:solr anymore.
This also fixes an issue with PHP 8 where such warning would cause the indexing to fail, when the method is used inside of an indexer.
Fixes: #3359
Ports: #3360
=> [BUGFIX] Fix array key access in ext_getSetup (Backport 11.5)

Classes/Backend/IndexingConfigurationSelectorField.php, Classes/Domain/Index/Queue/QueueInitializationService.php, Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php, Classes/System/Configuration/TypoScriptConfiguration.php, Classes/Task/ReIndexTask.php, Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript, Documentation/Configuration/Reference/TxSolrIndex.rst, Tests/Unit/Domain/Index/Queue/QueueInitializerServiceTest.php, Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
Queue types shouldn't be restricted to internal data, which is already prepared in some classes. As index queue setting 'table' suggests that a local table is expected, this is replaced with a new setting 'type'.
`queue.[indexConfig].table` is now deprecated and will be removed in v13, 'type' should be used instead.
Configure an indexing configuration and configure the local table via `type` instead of `table`
Fixes: #3364
=> [TASK] Introduce index queue type setting

Classes/Backend/IndexingConfigurationSelectorField.php
Index queue module uses the registered record icon for each indexing configuration, if no valid icon is found or no local table is used, the default fallback icon is used and indicates an error. This commit implements an icon check and a default icon that doesn't imply an error.
Configure an indexing configuration that uses a indexing source that doesn't configure an icon. With this changeset a default icon (`mimetypes-other-other`) is used.
Resolves: #3368
=> [TASK] Indexing configuration icon fallback

Classes/Backend/IndexingConfigurationSelectorField.php
Backport 11.5
Index queue module uses the registered record icon for each indexing configuration, if no valid icon is found or no local table is used, the default fallback icon is used and indicates an error. This commit implements an icon check and a default icon that doesn't imply an error.
Configure an indexing configuration that uses a indexing source that doesn't configure an icon. With this changeset a default icon (`mimetypes-other-other`) is used.
Resolves: #3368
=> [TASK:BP:11.5] Indexing configuration icon fallback

Classes/IndexQueue/AbstractIndexer.php, Tests/Unit/IndexQueue/AbstractIndexerTest.php
In case the data used for a Solr field is not present in the data (e.g. if it is conditionally set via a custom indexer), the field will no longer be created.
Previously the data was accessed anyways, resulting in a PHP warning which would abort the indexing in PHP 8.
Fixes: #3366
=> [BUGFIX] Do not index missing fields

Classes/Backend/IndexingConfigurationSelectorField.php, Classes/Domain/Index/Queue/QueueInitializationService.php, Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php, Classes/System/Configuration/TypoScriptConfiguration.php, Classes/Task/ReIndexTask.php, Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript, Documentation/Configuration/Reference/TxSolrIndex.rst, Tests/Unit/Domain/Index/Queue/QueueInitializerServiceTest.php, Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
Backport 11.5
Queue types shouldn't be restricted to internal data, which is already prepared in some classes. As index queue setting 'table' suggests that a local table is expected, this is replaced with a new setting 'type'.
`queue.[indexConfig].table` is now deprecated and will be removed in v13, 'type' should be used instead.
Configure an indexing configuration and configure the local table via `type` instead of `table`
Fixes: #3364
=> [TASK:BP:11.5] Introduce index queue type setting

Classes/Domain/Site/SiteRepository.php
It disables indexing a language that has no core configured.
Further there are no connection errors in the backend module nor pages with indexing errors due to that language
Add a site language with an empty core
Fixes #3362
=> [TASK] Do not index language with unconfigured core

Classes/Domain/Site/SiteRepository.php
It disables indexing a language that has no core configured.
Further there are no connection errors in the backend module nor pages with indexing errors due to that language
Relates: #3362
Ports: #3363
=> [TASK:BP:11.5] Do not index language with unconfigured core

.github/workflows/ci-matrix.json, .github/workflows/ci.yml
The GitHub Actions must run if pull-request against task/3376-TYPO3_12_compatibility is created.
Note:
The task/3376-TYPO3_12_compatibility must be used for pull-request against main branch. The task/3376-TYPO3_12_compatibility must be used for non-stable pre-releases for TYPO3 12
Fixes: #3382
Relates:  #3376
=> [TASK] Prepare GitHub-Actions for task/3376-TYPO3_12_compatibility branch

Classes/Domain/Site/SiteRepository.php, Classes/IndexQueue/Indexer.php
Prepend wrong FE language on empty cache,
use a clone of context on indexing to encapsulate the index from cli process
Clear all caches and call the frontend of a site with nondefault language
Fixes: #3375
=> [TASK] #3375: prepend wrong fe language on empty cache,

Classes/Controller/SearchController.php
What this pr does
Add a signal before search in resultsAction to be able to modify the arguments.
How to test
Check that the signal is correctly emitted by connecting to it from another extension.
Fixes: #3387
=> [FEATURE] Add signal before search in resultsAction

Classes/System/Util/SiteUtility.php
`SiteUtility::getConnectionProperty()` method must handle mixed types.
Fixes: #3394
Ports: #3396
=> [BUGFIX] Type-hinting for SiteUtility::getConnectionProperty()

Classes/Exception.php
To simplify the exception handling a generic Apache Solr for TYPO3 exception is introduced, this will be the base exception thrown by Solr extensions.
This is a preparation for a future exception handling that should allow more specific exception handling.
=> [TASK] Introduce generic EXT:solr exception

Classes/Exception.php
To simplify the exception handling a generic Apache Solr for TYPO3 exception is introduced, this will be the base exception thrown by Solr extensions.
This is a preparation for a future exception handling that should allow more specific exception handling.
=> [TASK:BP:11.5] Introduce generic EXT:solr exception

Classes/ConnectionManager.php, Classes/Controller/AbstractBaseController.php, Classes/Domain/Site/SiteHashService.php, Classes/Domain/Site/SiteRepository.php, Classes/System/Util/SiteUtility.php, Configuration/Services.yaml, Tests/Unit/Domain/Search/ApacheSolrDocument/RepositoryTest.php, Tests/Unit/Domain/Search/Query/QueryBuilderTest.php, Tests/Unit/Domain/Search/Query/SuggestQueryTest.php, Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php, Tests/Unit/Domain/Site/SiteHashServiceTest.php, Tests/Unit/Query/Modifier/ElevationTest.php, Tests/Unit/Query/Modifier/FacetingTest.php, Tests/Unit/Search/RelevanceComponentTest.php, Tests/Unit/Search/SortingComponentTest.php
Solr plugins are initializing Solr connections for all available
languages, this causes wrong language initializations in the
PageRenderer, as all created TypoScriptFrontendController instances
will overwrite the language setting.
By allowing to fetch the Solr configuration by TYPO3 site and a
specific language this issue is solved and the initialization
overhead is reduced.
- Place a Solr plugin
- Place another Plugin relying on the SiteLanguage
Fixes: #3423
=> [BUGFIX:BP:11.5] Fix frontend Solr connection initialization

Classes/ConnectionManager.php, Classes/Controller/AbstractBaseController.php, Classes/Domain/Site/SiteHashService.php, Classes/Domain/Site/SiteRepository.php, Classes/System/Util/SiteUtility.php, Configuration/Services.yaml, Tests/Unit/Domain/Search/ApacheSolrDocument/RepositoryTest.php, Tests/Unit/Domain/Search/Query/QueryBuilderTest.php, Tests/Unit/Domain/Search/Query/SuggestQueryTest.php, Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php, Tests/Unit/Domain/Site/SiteHashServiceTest.php, Tests/Unit/Query/Modifier/ElevationTest.php, Tests/Unit/Query/Modifier/FacetingTest.php, Tests/Unit/Search/RelevanceComponentTest.php, Tests/Unit/Search/SortingComponentTest.php
Solr plugins are initializing Solr connections for all available
languages, this causes wrong language initializations in the
PageRenderer, as all created TypoScriptFrontendController instances
will overwrite the language setting.
By allowing to fetch the Solr configuration by TYPO3 site and a
specific language this issue is solved and the initialization
overhead is reduced.
- Place a Solr plugin
- Place another Plugin relying on the SiteLanguage
Fixes: #3423
=> [BUGFIX] Fix frontend Solr connection initialization

.github/workflows/ci.yml, Build/Test/cibuild.sh, composer.json
composer constraint >=0.5.0 doesn't fit current needs for different PHP versions. 
To avoid different rules for PHP 7.4 vs 8.0+, the constraint is set to use typo3/coding-standards 0.6.x only.
Todo: 
Extract coding standards test from cibuild and run it one time only directly via actions job.  Alternativelly, run it for specific version only.
**Note: This port will be overidden via task/3376-TYPO3_12_compatibility properly.**
Ports: #3429
=> [ACTIONS:2022.12.22:P:main] Use fixed typo3/coding-standards 0.6.x < 0.7.0 for TYPO3 11.5

.github/workflows/ci.yml, Build/Test/cibuild.sh, composer.json
composer constraint >=0.5.0 doesn't fit current needs for different PHP versions. To avoid different rules for PHP 7.4 vs 8.0+, the constraint is set to use typo3/coding-standards 0.6.x only.
Todo: 
Extract coding standards test from cibuild and run it one time only directly via actions job.  
Alternatively, run it for specific version only.
=> [ACTIONS:2022.12.22] Use fixed typo3/coding-standards 0.6.x < 0.7.0 for TYPO3 11.5

Classes/IndexQueue/FrontendHelper/PageIndexer.php
Not initialized variable leads to exception using PHP 8+ in
https://github.com/TYPO3-Solr/ext-solr/blob/bfe1599a7533ed8aff0060ab932067ecd32dacad/Classes/IndexQueue/FrontendHelper/PageIndexer.php#L256
Fixes: #3403
Ports: #3404
=> [BUGFIX:P:11.5] Proper check for config.index_enable

Classes/FieldProcessor/TimestampToUtcIsoDate.php
Due to refactoring in `FormatService`, the parameter for `timestampToUtcIso` has been defined as `int` or `null`. The function is however used in `TimestampToUtcIsoDate` with the direct value of the field, which is a string. This change ensures, that an integer value is passed.
Fixes: #3406
=> [BUGFIX] Typecast $timestamp to int in TimestampToUtcIsoDate

Classes/FieldProcessor/TimestampToUtcIsoDate.php
Due to refactoring in `FormatService`, the parameter for `timestampToUtcIso` has been defined as `int` or `null`. The function is however used in `TimestampToUtcIsoDate` with the direct value of the field, which is a string. This change ensures, that an integer value is passed.
Fixes: #3406
Ports: #3405
=> [BUGFIX:P:11.5] Typecast $timestamp to int in TimestampToUtcIsoDate

Classes/Query/Modifier/Faceting.php
An empty filter in query string of URL `tx_solr[filter][]=` leads to PHP 8+ Warninng:
```
PHP Warning: Undefined array key 1 in /var/www/html/web/typo3conf/ext/solr/Classes/Query/Modifier/Faceting.php line 241
```
See: https://github.com/TYPO3-Solr/ext-solr/blob/bfe1599a7533ed8aff0060ab932067ecd32dacad/Classes/Query/Modifier/Faceting.php#L241
Closes: #3398
=> [BUGFIX] prevent undefined array key warning if filter is empty

Classes/Query/Modifier/Faceting.php
An empty filter in query string of URL `tx_solr[filter][]=` leads to PHP 8+ Warninng:
```
PHP Warning: Undefined array key 1 in /var/www/html/web/typo3conf/ext/solr/Classes/Query/Modifier/Faceting.php line 241
```
See: https://github.com/TYPO3-Solr/ext-solr/blob/bfe1599a7533ed8aff0060ab932067ecd32dacad/Classes/Query/Modifier/Faceting.php#L241
Ports: #3398
=> [BUGFIX:P:11.5] prevent undefined array key warning if filter is empty

Classes/IndexQueue/RecordMonitor.php
To avoid php warning for undefined array key, check if key is set in $page array.
Fixes #3380
Ports: #3381
=> [BUGFIX:P:12.0] Fix php warning undefined array key no_search_sub_entries

Classes/IndexQueue/RecordMonitor.php
To avoid php warning for undefined array key, check if key is set in $page array.
Fixing the follwing bug:
After enabling/disabling a page in page tree with the context menu the following php warning appears:
PHP Warning: Undefined array key "no_search_sub_entries" in /var/www/html/web/typo3conf/ext/solr/Classes/IndexQueue/RecordMonitor.php line 203
1. Open context menu of a page in page tree
2. Click on 'Disable' or 'Enable' (depends on state of the page ;-))
3. The php warning appears
Fixes #3380
=> [BUGFIX] Fix php warning undefined array key no_search_sub_entries

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-11-5.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 11.5, containing:
- [BUGFIX] Do not include removed strptime() (#3335)
- [BUGFIX:BP:11.5] Do not handle page updates on new page with uid 0 (#3344)
- [BUGFIX:BP:11.5] Shortcircuit work in SolrRoutingMiddleware (#3341)
- !!![TASK] Use preAddModifyDocuments  hook for pages (#3076)
- [BUGFIX] Fix array key access in ext_getSetup (Backport 11.5) (#3361)
- [TASK:BP:11.5] Indexing configuration icon fallback (#3371)
- [BUGFIX:BP:11.5] Do not index missing fields (#3372)
- [TASK:BP:11.5] Introduce index queue type setting (#3370)
- [TASK:BP:11.5] Do not index language with unconfigured core (#3373)
- [BUGFIX] Make API eID script compatible with TYPO3 v11.5 (#3350)
- [BUGFIX] Type-hinting for SiteUtility::getConnectionProperty() (#3396)
- [TASK:BP:11.5] …
=> [RELEASE] 11.5.1 - Maintenance Release

Configuration/Services.yaml
Adjust dependency injection for reports
Run the integration tests.
The error message `The definition for "ApacheSolrForTypo3\Solr\Report\SiteHandlingStatus::class" has no class.` does not appear anymore.
Fixes: #3376
=> [TASK:T12] Adjust dependency injection

Classes/Domain/Index/Queue/UpdateHandler/AbstractUpdateHandler.php, Classes/System/Records/Pages/PagesRepository.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/AbstractUpdateHandlerTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/DataUpdateHandlerTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/GarbageHandlerTest.php
The use of the `QueryGenerator::getTreeList()` was replaced with
`\ApacheSolrForTypo3\Solr\System\Records\Pages\PagesRepository::getTreeList()`
Resolves: #3453
Relates: #3376
=> [TASK:T12] Replace query generator

Classes/ContentObject/Relation.php, Tests/Integration/ContentObject/Fixtures/TCA/tx_fakeextension_domain_model_bar.php, Tests/Integration/ContentObject/Fixtures/TCA/tx_fakeextension_domain_model_foo.php, Tests/Integration/ContentObject/Fixtures/fake_extension.sql, Tests/Integration/ContentObject/Fixtures/solr_relation_can_resolve_m_to_n_relations.xml, Tests/Integration/ContentObject/Fixtures/solr_relation_can_resolve_one_to_n_relations.xml, Tests/Integration/ContentObject/Fixtures/solr_relation_can_resolve_one_to_one_relations.xml, Tests/Integration/ContentObject/RelationTest.php
This changeset fixes issues with the resolution of values in SOLR_RELATION, fixed is the resolution of:
- foreignLabelFields (2nd level+)
- multiple values in m:n relations
- nested m:n relations
- nested multi values
Additionally the missing stdWrap functionality on values from mm relations is added.
Integration tests are added to ensure the right behaviour of SOLR_RELATION.
Test scenarios are added in `RelationTest`
For manual testing:
-  Create a table A with an 1:m relation to table B
-  In table B create an n:m relation to table C
-  Configure indexing for table A with a multi value field that should contain all relations to table C
- Index the records
- Relations must be resolved correctly
Resolves: #3152
Resolves: #3408
=> [BUGFIX] Fix value resolution in SOLR_RELATION

Build/Test/cibuild.sh, Classes/ContentObject/Relation.php, Classes/FrontendEnvironment/Tsfe.php, Configuration/Services.yaml, Tests/Unit/ContentObject/AbstractContentObjectTest.php, Tests/Unit/ContentObject/ClassificationTest.php, Tests/Unit/ContentObject/MultivalueTest.php, composer.json, ext_localconf.php
Move to new way of TYPO3 12+ to register custom content objects.
See: [Breaking: #96659 - Registration of cObjects via TYPO3_CONF_VARS](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96659-RegistrationOfCObjectsViaTYPO3_CONF_VARS.html)
* Unit\ContentObject\ClassificationTest::*
* Unit\ContentObject\MultivalueTest::*
* Integration\ContentObject\RelationTest::*
To avoid rewrites of xml fixtures for TYPO3 12 compatibility task, the "typo3/testing-framework" is fixed to v 7.x.
Fixes: https://github.com/TYPO3-Solr/ext-solr/issues/3476
=> [TASK:T12] Registration of cObjects for TYPO3 12 LTS 

composer.json
The composer script "tests:env" olways used the dev stability, even if stable TYPO3 used in matrix.
This fix uses grep instead of not working sh string substitution comparator.
Ports: #3463
=> [BUGFIX:BP:11.2] Don't use minimum-stability dev on TYPO3 stable in build/CI

.github/workflows/ci.yml, composer.json
The composer script "tests:env" olways used the dev stability, even if stable TYPO3 used in matrix.
This fix uses grep instead of not working sh string substitution comparator.
Ports: #3463
=> [BUGFIX:BP:11.5] Don't use minimum-stability dev on TYPO3 stable in build/CI

composer.json
The composer script "tests:env" olways used the dev stability, even if stable TYPO3 used in matrix.
This fix uses grep instead of not working sh string substitution comparator.
---
The ports will be provided as well for:
* release-11.5.x
* release-11.2.x
* release-11.0.x(ELTS)
=> [BUGFIX] Don't use minimum-stability dev on TYPO3 stable in build/CI

Classes/ContentObject/Relation.php, Tests/Integration/ContentObject/Fixtures/TCA/tx_fakeextension_domain_model_bar.php, Tests/Integration/ContentObject/Fixtures/TCA/tx_fakeextension_domain_model_foo.php, Tests/Integration/ContentObject/Fixtures/fake_extension.sql, Tests/Integration/ContentObject/Fixtures/solr_relation_can_resolve_m_to_n_relations.xml, Tests/Integration/ContentObject/Fixtures/solr_relation_can_resolve_one_to_n_relations.xml, Tests/Integration/ContentObject/Fixtures/solr_relation_can_resolve_one_to_one_relations.xml, Tests/Integration/ContentObject/RelationTest.php
This changeset fixes issues with the resolution of values in SOLR_RELATION, fixed is the resolution of:
- foreignLabelFields (2nd level+)
- multiple values in m:n relations
- nested m:n relations
- nested multi values
Additionally the missing stdWrap functionality on values from mm relations is added.
Integration tests are added to ensure the right behaviour of SOLR_RELATION.
Test scenarios are added in `RelationTest`
For manual testing:
-  Create a table A with an 1:m relation to table B
-  In table B create an n:m relation to table C
-  Configure indexing for table A with a multi value field that should contain all relations to table C
- Index the records
- Relations must be resolved correctly
Resolves: #3152
Resolves: #3408
=> [BUGFIX:BP:11.5] Fix value resolution in SOLR_RELATION

Classes/System/UserFunctions/FlexFormUserFunctions.php
Do not get TypoScript from simulated frontend environment but from the ConfigurationManager. 
Check the description in the issue and you will see the error but with this patch it works
Fixes: #3420
---
=> [BUGFIX] Use ConfigurationManager to get typscript in FlexForm

Classes/System/UserFunctions/FlexFormUserFunctions.php
Do not get TypoScript from simulated frontend environment  but from the ConfigurationManager.
Fixes: #3420
Ports: #3486
=>  [BUGFIX:P:11.5] Use ConfigurationManager to get typscript in plugin FlexForm

Classes/Controller/SearchController.php, Classes/Controller/SuggestController.php
To prevent fatal errors (null pointer exception) we are forwarding to action solrNotAvailable  if the property SearchService is not set.
Fixes: #3426
---
=> [BUGFIX] Exception on search plugin if no Solr connection is configured

.github/workflows/ci.yml
PCOV is faster as xDebug for coverage.
We are using coverage currently for Scrutinizer.
Later other static analyse tools will benefit as well.
Fixes: #3526
=> [TASK] Use PCOV for coverage instead of xDebug

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/Domain/Index/Queue/RecordMonitor/Exception/RootPageRecordNotFoundException.php, Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/IndexQueue/Queue.php, Tests/Integration/Fixtures/can_handle_missing_page_on_deletion.xml, Tests/Integration/GarbageCollectorTest.php, Tests/Integration/IndexQueue/QueueTest.php, Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
If a records page or the site root is not available exceptions will occur during garbage collection. This commit improves
the handling of missing pages to fix this issue.
Try to delete a record without a proper page tree connection via DataHandler, e.g. use a deleted site root or a deleted record
storage.
Fixes: #3500
=> [BUGFIX] Fix handling of non existing pages on deletions

Configuration/SiteConfiguration/Overrides/sites.php
Instead of using 
```php
'eval' => 'required',
```
use 
```php
'required' => true,
```
=> [BUGFIX] Use correct eval for site TCA

Classes/Domain/Index/IndexService.php, Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/IndexQueue/Indexer.php, Classes/System/Solr/Service/AbstractSolrService.php, Classes/System/Solr/Service/SolrReadService.php, Tests/Unit/Domain/Index/Queue/GarbageRemover/AbstractStrategyTest.php, Tests/Unit/Domain/Index/Queue/GarbageRemover/PageStrategyTest.php, Tests/Unit/Domain/Index/Queue/GarbageRemover/RecordStrategyTest.php
Solr requests may fail due to server errors or faulty queries, thrown exceptions or just an invalid status code indicate such errors.
This commit ensures that exceptions are handled and a valid response with a meaningful status code is returned. Handling is centralized in SolrService so that other components just have to deal with the status code.
Additionally the GarbageCollection is considering this status and is logging missing index update.
- Configure an indexing configuration e.g. for news
- Simulate invalid Solr responses
- Try to hide an indexed record in TYPO3 backend
Record update shouldn't fail, but a log entry should be in place.
Resolves: #2903
=> [TASK] Handle Solr connection exception

Classes/Domain/Index/IndexService.php, Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/IndexQueue/Indexer.php, Classes/System/Solr/Service/AbstractSolrService.php, Classes/System/Solr/Service/SolrReadService.php, Tests/Unit/Domain/Index/Queue/GarbageRemover/AbstractStrategyTest.php, Tests/Unit/Domain/Index/Queue/GarbageRemover/PageStrategyTest.php, Tests/Unit/Domain/Index/Queue/GarbageRemover/RecordStrategyTest.php
Solr requests may fail due to server errors or faulty queries, thrown exceptions or just an invalid status code indicate such errors.
This commit ensures that exceptions are handled and a valid response with a meaningful status code is returned. Handling is centralized in SolrService so that other components just have to deal with the status code.
Additionally the GarbageCollection is considering this status and is logging missing index update.
- Configure an indexing configuration e.g. for news
- Simulate invalid Solr responses
- Try to hide an indexed record in TYPO3 backend
Record update shouldn't fail, but a log entry should be in place.
Resolves: #2903
=> [TASK:BP:11.5] Handle Solr connection exception

Classes/IndexQueue/Indexer.php, Tests/Unit/IndexQueue/IndexerTest.php
If a Solr response is not valid (=200) the index queue item should be marked as failed to prevent the indexer of being blocked. This commit fixes this issue by throwing an `IndexingException` which causes the `IndexService` to mark the item as failed.
- Add an indexing configuration
- Initialize the queue
- Simulate an indexing error on Solr side, e.g. by stopping the Solr container
- Try to index 
Queue items should now be marked as failed and the indexing should not fail silently.
Resolves: #3108
=> [BUGFIX] Fix Solr response handling during indexing

Classes/System/UserFunctions/FlexFormUserFunctions.php
Backport of https://github.com/TYPO3-Solr/ext-solr/pull/3549
---
When you configure additional pluginnamespaces via extension configuration, the dropdown in the plugin flexform shows _Default_ followed by empty entries.
Extension Configuration to reproduce this:
```php
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['solr']['pluginNamespaces'] => 'search,sitesearch,newssearch,eventsearch'
```
The `view.pluginNamespace` DropDown shows up with the folowing Field:
```html
<select class="form-select form-control-adapt">
<option value="tx_solr" selected="selected">Default</option>
<option value="search"></option>
<option value="sitesearch"></option>
<option value="newssearch"></option>
<option value="eventsearch"></option>
</select>
```
It is hard to select an plugin namespace with empty labels.
The …
=> [BUGFIX:BP:11.5] Use plugin namespace as label for flexforms

Classes/System/UserFunctions/FlexFormUserFunctions.php
Backport of https://github.com/TYPO3-Solr/ext-solr/pull/3549
---
When you configure additional pluginnamespaces via extension configuration, the dropdown in the plugin flexform shows _Default_ followed by empty entries.
Extension Configuration to reproduce this:
```php
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['solr']['pluginNamespaces'] => 'search,sitesearch,newssearch,eventsearch'
```
The `view.pluginNamespace` DropDown shows up with the folowing Field:
```html
<select class="form-select form-control-adapt">
<option value="tx_solr" selected="selected">Default</option>
<option value="search"></option>
<option value="sitesearch"></option>
<option value="newssearch"></option>
<option value="eventsearch"></option>
</select>
```
It is hard to select an plugin namespace with empty labels.
The …
=> [BUGFIX:BP:11.2] Use plugin namespace as label for flexforms

Classes/Domain/Index/Queue/QueueItemRepository.php, Classes/IndexQueue/Queue.php, Classes/System/Configuration/TypoScriptConfiguration.php, composer.json
Backport of #3509
----
Fixes https://github.com/TYPO3-Solr/ext-solr/issues/3492 by reading and saving the `indexingPriority` attribute when using the QueueItemRepository
1. Set an `indexingPriority` to an existing queue (e.g. `plugin.tx_solr.index.queue.news.indexingPriority = 50`)
2. Create a new item of the corresponding type (e.g. `news`) and save the record
3. Open the `tx_solr_indexqueue_item` table. The queued item will get an indexingPriority of `50`
Fixes: #3492
=> [BUGFIX:BP:11.0] Respect indexingPriority in QueueItemRepository

Classes/Domain/Index/Queue/QueueItemRepository.php, Classes/IndexQueue/Queue.php, Classes/System/Configuration/TypoScriptConfiguration.php
Backport of #3509
----
Fixes https://github.com/TYPO3-Solr/ext-solr/issues/3492 by reading and saving the `indexingPriority` attribute when using the QueueItemRepository
1. Set an `indexingPriority` to an existing queue (e.g. `plugin.tx_solr.index.queue.news.indexingPriority = 50`)
2. Create a new item of the corresponding type (e.g. `news`) and save the record
3. Open the `tx_solr_indexqueue_item` table. The queued item will get an indexingPriority of `50`
Fixes: #3492
=> [BUGFIX:BP:11.2] Respect indexingPriority in QueueItemRepository

Classes/Domain/Index/Queue/QueueItemRepository.php, Classes/IndexQueue/Queue.php, Classes/System/Configuration/TypoScriptConfiguration.php
Fixes https://github.com/TYPO3-Solr/ext-solr/issues/3492 by reading and saving the `indexingPriority` attribute when using the QueueItemRepository
1. Set an `indexingPriority` to an existing queue (e.g. `plugin.tx_solr.index.queue.news.indexingPriority = 50`)
2. Create a new item of the corresponding type (e.g. `news`) and save the record
3. Open the `tx_solr_indexqueue_item` table. The queued item will get an indexingPriority of `50`
Fixes: #3492
---
=> [BUGFIX] Respect indexingPriority in QueueItemRepository

Classes/Backend/IndexingConfigurationSelectorField.php
Show icon, value and label again in Index Queue module.
Open Index Queue module. You only see the checkboxes of the indexes, but no label, icon or value. This patch solves this issue
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.3/Deprecation-99739-IndexedArrayKeysForTCAItems.html
=> [BUGFIX] Add named array keys to items for Index Queue

Classes/Domain/Search/ResultSet/Facets/AbstractFacetPackage.php, Classes/Domain/Search/Uri/SearchUriBuilder.php, Classes/Query/Modifier/Elevation.php, Classes/Query/Modifier/Faceting.php, Classes/Query/Modifier/Statistics.php, Classes/ViewHelpers/TranslateViewHelper.php, Configuration/Services.yaml
Query Modifiers are called with GeneralUtility::makeInstance. That's why we have to mark them as public in Services.yaml.
Further it removes superflous annotations and adds checks against null in SearchUriBuilder, AbstractFacetPackage and TranslateViewHelper.
=> [BUGFIX] Mark query modifiers as public in Services.yaml

Classes/Controller/AbstractBaseController.php, Classes/ViewHelpers/AbstractSolrFrontendViewHelper.php, Classes/ViewHelpers/Uri/AbstractUriViewHelper.php
As extbase ControllerContext has been removed with TYPO3 12, we have replaced ControllerContext in various
ViewHelper classes.
Relates: #3376
=> [BUGFIX] Replace ControllerContext

Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupUrlDecoder.php, Classes/Query/Modifier/Faceting.php
ensure a string is always returned, even if the query does not exist
Define a queryGroup "A", filter by that new group, manipulate the url by hand, submit form. Page should not show error.
=> [BUGFIX] add empty string as fallback

Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupUrlDecoder.php, Classes/Query/Modifier/Faceting.php
Backport of #3444 
---
ensure a string is always returned, even if the query does not exist
Define a queryGroup "A", filter by that new group, manipulate the url by hand, submit form. Page should not show error.
=> [BUGFIX:BP:11.5] add empty string as fallback

Configuration/TypoScript/OpenSearch/setup.typoscript
"TSFE:sys_language_uid" not working anymore
Replace outdated/removed TypoScript.
Opensearch URLs are generated with empty L-queryparam in at least TYPO3 v11 (probably even in v10).
`&L=`
Fixes: #3521
=> [FIX] use siteLanguage TypoScript object to get language id

Configuration/TypoScript/OpenSearch/setup.typoscript
Backport of #3522
--- 
"TSFE:sys_language_uid" not working anymore
Replace outdated/removed TypoScript.
Opensearch URLs are generated with empty L-queryparam in at least TYPO3 v11 (probably even in v10).
`&L=`
Fixes: #3521
=> [BUGFIX:BP:11.5] use siteLanguage TypoScript object to get language id

Resources/Private/Partials/Search/FrequentlySearched.html, Resources/Private/Partials/Search/LastSearches.html
Wraps output of frequent searches and last searches in format.htmlentities, to prevent XSS. In rare scenarios there might be issues with unsanitized output of frequent searches and/or last searches, this issues are now solved.
The StatisticsWriterProcessor is already sanitizing the stored terms, but as it's possible to use any custom table it should be ensured the data is sanitized.
If last searches is activated and configured for global mode, there might be issues too. Though it's required that the prepared query delivers result documents, as EXT:solr will only store the terms if results are found, the output should be sanitized too.
As special configurations and index contents are required to reproduce the issues, the easiest way is to place simulated data …
=> [BUGFIX] Sanitize frequent and last searches output

Resources/Private/Partials/Search/FrequentlySearched.html, Resources/Private/Partials/Search/LastSearches.html
Backport of https://github.com/TYPO3-Solr/ext-solr/pull/3590
---
Wraps output of frequent searches and last searches in format.htmlentities, to prevent XSS. In rare scenarios there might be issues with unsanitized output of frequent searches and/or last searches, this issues are now solved.
The StatisticsWriterProcessor is already sanitizing the stored terms, but as it's possible to use any custom table it should be ensured the data is sanitized.
If last searches is activated and configured for global mode, there might be issues too. Though it's required that the prepared query delivers result documents, as EXT:solr will only store the terms if results are found, the output should be sanitized too.
As special configurations and index contents are required to …
=> [BUGFIX:BP:11.2] Sanitize frequent and last searches output

Classes/Controller/Backend/Search/AbstractModuleController.php
Backport of https://github.com/TYPO3-Solr/ext-solr/pull/3068
---
Changed from always picking the 0 array value to pick always the first.
Ports: #3068
=> [BUGFIX:BP:11.5] 

Classes/FrontendEnvironment/Tsfe.php
TYPO3 by default enables a preview mode if a backend user is logged in,
the VisibilityAspect is configured to show hidden elements.
Due to this setting hidden relations/translations might be indexed
when running the Solr indexer via the TYPO3 backend.
To avoid this, the VisibilityAspect is adapted for indexing.
1. Create two sys_categories "Category 1" and "Category 2". Create a German translation for both of them ("Kategorie 1" and "Kategorie 2") and disable the translation of "Category 2"
2. Create a Ext:news record and assign both categories to it. Then create a German translation. Make sure both categories are selected there as well.
3. Add News indexer in TypoScript setup:
```typoscript
@import 'EXT:solr/Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript'
```
3. Index …
=> [BUGFIX] Enforce visibility context in Tsfe

Classes/IndexQueue/Queue.php
Fixes: #3597
---
Ports: 
- ~[ ] release-11.2.x(ELTS?)~ not using the Site object
- ~[ ] release-11.0.x(ELTS?)~  not using the Site object
=> [BUGFIX] Avoid getSolrConfiguration() on null

Resources/Private/Solr/configsets/ext_solr_11_2_0/conf/solrconfig.xml
Backport of #3602 
---------
The SQL handler is not used by EXT:solr and is only available if SolrCloud is used. But as there is a vulnerability we are explicitly deactivating this handler, as adviced in CVE-2022-39135.
SQL handler is not used by  EXT:solr, so just check if core can be loaded after applying the changes. 
Resolves: #3414
=> [TASK:BP:11.2] Disable sql handler

Resources/Private/Solr/configsets/ext_solr_11_5_0/conf/solrconfig.xml
The SQL handler is not used by EXT:solr and is only available if SolrCloud is used. But as there is a vulnerability we are explicitly deactivating this handler, as adviced in CVE-2022-39135.
SQL handler is not used by  EXT:solr, so just check if core can be loaded after applying the changes. 
Resolves: #3414
=> [TASK] Disable sql handler

Classes/IndexQueue/FrontendHelper/PageIndexer.php
Set variable `$this->responseData['pageIndexed'] = false` try/catch to make it available for further processing
See detailed information in related issue
Fixes: #3605
=> [BUGFIX] Avoid PHP 8 warning when page indexing fails

Classes/Util.php
This fix an error in case a record was not found in the garbage collector process.
Fixes: #3531
=> [BUGFIX] Ensure record exists before asserting if draft

Classes/IndexQueue/FrontendHelper/PageIndexer.php
Backport of #3608
----
Fix usage of null coalescing operator
See detailed information in related issue
Fixes: #3607
=> [BUGFIX:BP:11.5] Fix usage of null coalescing operator

Classes/ViewHelpers/Document/HighlightResultViewHelper.php
fix regression in HighlightResultViewHelper if there is no content to highlight, by checking if getHighlightedContent is a string before passing it to escapeEverythingExceptAllowedTags, otherwise an empty string is returned for the renderStatic method, as before the regression. 
see issue
Fixes: #3448
=> return empty string for renderStatic if there is no content to highlight

Classes/Controller/Backend/Search/InfoModuleController.php, Configuration/TypoScript/Examples/EverythingOn/setup.typoscript, Documentation/Configuration/Reference/TxSolrStatistics.rst, Resources/Private/Language/cs.locallang.xlf, Resources/Private/Language/es.locallang.xlf, Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/ja.locallang.xlf, Resources/Private/Language/ko.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Language/pt.locallang.xlf, Resources/Private/Templates/Backend/Search/InfoModule/Index.html
The statistics are hard-coded so far. It is now defined in Typoscript. If no values are defined, the previous values are set as the default value in the code to prevent a breaking change.
Simply add TypoScript and look at the statistics in the backend info module.
The documentation is adapted if everything fits in terms of content and the variable naming is also good enough.
Fixes: #3534
=> [FEATURE] Make statistics more dynamic

Classes/System/UserFunctions/FlexFormUserFunctions.php
Especially on TYPO3 10 the user function to load the flex form configuration produced an error.
Fixes: #3622
Ports: #3626
=> [BUGFIX:P:11.2] make CE search form in backend editable again

Classes/System/UserFunctions/FlexFormUserFunctions.php
Especially on TYPO3 10 the userfunction to load the flex form configuration produced an error.
This implements `TYPO3\CMS\Extbase\Object->get()` - deprecated by TYPO3 12:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4/Deprecation-90803-DeprecationOfObjectManagergetInExtbaseContext.html
`FlexFormUserFunctions` does not implement the extbase controller and thereby does not have dependency injection.
With missing dependency injection the instantiation of the `Interface::class` by `GeneralUtility::makeInstance(ConfigurationManagerInterface::class)` fails with:
`Cannot instantiate interface TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface`
The solution to instantiate an object of `ConfigurationManager::class` is not feasible here - there are different …
=> [BUGFIX] make CE search form in backend editable again

ext_tables.sql
There are SQL CREATE TABLE definitions for tx_solr_cache and tx_solr_cache_tags.
These tables have been added back then when TYPO3 did not always create cache tables.
However, since TYPO3 v9, these tables have been renamed and are automatically created, so the SQL definition can be removed.
The SQL tables are not referenced anywhere in the current source code.
Re-install the extension, drop the tables and see if everything still works.
Fixes: #3636
=> [TASK] Remove unused tx_solr_cache DB tables

Classes/ViewHelpers/PageBrowserRangeViewHelper.php
Resolve PHP warning in getResponseBody() method.
Just search for "examples" in solr-ddev-site package
=> Prevent PHP warning on getResponseBody in PageBrowserRangeViewHelper

Configuration/TypoScript/Examples/Ajaxify/setup.txt, Configuration/TypoScript/Examples/BoostQueries/setup.txt, Configuration/TypoScript/Examples/EverythingOn/setup.txt, Configuration/TypoScript/Examples/Facets/DateRange/setup.txt, Configuration/TypoScript/Examples/Facets/Hierarchy/setup.txt, Configuration/TypoScript/Examples/Facets/NumericRange/setup.txt, Configuration/TypoScript/Examples/Facets/Options/setup.txt, Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.txt, Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.txt, Configuration/TypoScript/Examples/Facets/OptionsSinglemode/setup.txt, Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.txt, Configuration/TypoScript/Examples/Facets/QueryGroup/setup.txt, Configuration/TypoScript/Examples/FilterPages/setup.txt, Configuration/TypoScript/Examples/IndexQueueNews/setup.txt, Configuration/TypoScript/Examples/IndexQueueNewsContentElements/setup.txt, Configuration/TypoScript/Examples/IndexQueueTtNews/setup.txt, Configuration/TypoScript/Examples/Suggest/setup.txt, Configuration/TypoScript/OpenSearch/constants.txt, Configuration/TypoScript/OpenSearch/setup.txt, Configuration/TypoScript/Solr/constants.txt, Configuration/TypoScript/Solr/setup.txt, Configuration/TypoScript/StyleSheets/setup.txt
With TYPO3 12 there is no support for loading the old txt files of TypoScript anymore.
=> Remove old txt files for TypoScript

.github/workflows/ci.yml
This change removes the cache key from the GitHub workflow as this is "OK" from a time-consuming performance.
Fixes: #3663
=> [TASK] Housekeeping: Remove cache key from ci.yaml

Classes/ContentObject/Relation.php, Classes/Controller/SearchController.php, Classes/Controller/SuggestController.php, Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php, Classes/Domain/Search/Query/QueryBuilder.php, Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php, Classes/Domain/Search/Suggest/SuggestService.php, Classes/IndexQueue/FrontendHelper/PageIndexer.php, Classes/Search.php, Classes/Util.php, Classes/ViewHelpers/SearchFormViewHelper.php, Tests/Unit/Domain/Search/Query/QueryBuilderTest.php
The Util class methods "getLanguageUid()" and "getFrontendUserGroupsList()" have been removed as they can be retrieved differently.
Fixes: #3669
=> [TASK] Reduce usages of Util class

Classes/Controller/SearchController.php, Classes/Domain/Index/IndexService.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php, Classes/Domain/Search/Uri/SearchUriBuilder.php, Classes/Event/Indexing/AfterItemHasBeenIndexedEvent.php, Classes/Event/Indexing/AfterItemsHaveBeenIndexedEvent.php, Classes/Event/Indexing/BeforeItemIsIndexedEvent.php, Classes/Event/Indexing/BeforeItemsAreIndexedEvent.php, Classes/Event/Parser/AfterFacetIsParsedEvent.php, Classes/Event/Routing/AfterUriIsProcessedEvent.php, Classes/Event/Routing/BeforeCachedVariablesAreProcessedEvent.php, Classes/Event/Routing/BeforeVariableInCachedUrlAreReplacedEvent.php, Classes/Event/Search/AfterFrequentlySearchHasBeenExecutedEvent.php, Classes/Event/Search/BeforeSearchFormIsShownEvent.php, Classes/Event/Search/BeforeSearchResultIsShownEvent.php, Classes/EventListener/EnhancedRouting/CachedPathVariableModifier.php, Classes/EventListener/EnhancedRouting/CachedUrlModifier.php, Classes/EventListener/EnhancedRouting/PostEnhancedUriProcessor.php, Documentation/Releases/solr-release-12-0.rst
New namings:
* `ApacheSolrForTypo3\Solr\Event\Indexing\AfterIndexItemEvent` is now called `ApacheSolrForTypo3\Solr\Event\Indexing\AfterItemHasBeenIndexedEvent`
* `ApacheSolrForTypo3\Solr\Event\Indexing\AfterIndexItemsEvent` is now called `ApacheSolrForTypo3\Solr\Event\Indexing\AfterItemsHaveBeenIndexedEvent`
* `ApacheSolrForTypo3\Solr\Event\Indexing\BeforeIndexItemEvent` is now called `ApacheSolrForTypo3\Solr\Event\Indexing\BeforeItemIsIndexedEvent`
* `ApacheSolrForTypo3\Solr\Event\Indexing\BeforeIndexItemsEvent` is now called `ApacheSolrForTypo3\Solr\Event\Indexing\BeforeItemsAreIndexedEvent`
* `ApacheSolrForTypo3\Solr\Event\Parser\AfterFacetParsedEvent` is now called `ApacheSolrForTypo3\Solr\Event\Parser\AfterFacedIsParsedEvent`
* …
=> [TASK] Rename previously created PSR-14 events

Configuration/TypoScript/Solr/setup.typoscript, Documentation/Configuration/Reference/TxSolrIndex.rst, Documentation/Releases/solr-release-12-0.rst
Currently there is no important reason to index the shortcut pages, because the target pages are indexed as expected and the shortcuts are 307-redirected to their targets. So contents can be found in search results as expected.
Fixes: #3685
=>  !!![TASK] Don't index shortcut pages anymore

Docker/SolrServer/Dockerfile, Docker/SolrServer/docker-entrypoint-initdb.d/as-sudo-tweaks.sh, Docker/SolrServer/docker-entrypoint-initdb.d/as-sudo/fix-file-permissions.sh
This change makes it possible to change solr unix GID:UID on docker image build time. It is required for dev. environments and custom setups of EXT:solr docker containers.
=> [TASK] Make it possible to change solr unix GID:UID on docker image build

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-11-2.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 10.4 and the last non ELTS release, as TYPO3 10 LTS reaches the ELTS phase on April 30, 2023.
EXT:solr release-11.2.x will not be maintained in this public repository any more. The maintenance and builds will be moved to a private repository and ELTS versions, EXT:solr 11.2.3+ for TYPO3 10 ELTS versions, can be obtained through the dkd EB program (https://shop.dkd.de/Produkte/Apache-Solr-fuer-TYPO3).
This release contains:
* [BUGFIX:P:11.2] make CE search form in backend editable again by @dkd-kaehm in https://github.com/TYPO3-Solr/ext-solr/pull/3640
* [DOC] Fix wrong type for boostQuery in the docs and example by @rr-it  and @dkd-kaehm in https://github.com/TYPO3-Solr/ext-solr/commit/a997a2f464462bc998aa755215f765e5efc6f172
Please read the release …
=> [RELEASE] 11.2.3 - Maintenance Release (last non ELTS)

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-11-5.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 11.5, containing:
* [BUGFIX] make CE search form in backend editable again by @rr-it in https://github.com/TYPO3-Solr/ext-solr/pull/3626
* [DOC] Fix wrong type for boostQuery in the docs and example by @dkd-kaehm in https://github.com/TYPO3-Solr/ext-solr/commit/3e7ff72b7bc8ddd9cb7f5b7e998a328773483dfb
*  [TASK] Fix unit tests for 2023.06.07 by @dkd-kaehm in https://github.com/TYPO3-Solr/ext-solr/pull/3695
https://github.com/TYPO3-Solr/ext-solr/releases/tag/11.5.3
---
* Provide patches through pull requests or review and comment on …
=>  [RELEASE] 11.5.3 - Maintenance Release

Classes/Event/Search/BeforeSearchResultIsShownEvent.php
It would be cool if properties of the event could be changed. Otherwise the event doesn't help much - IMO
I need it e.g. for the pagination to be changed
=> [BUGFIX] Make BeforeSearchResultIsShownEvent more usable

Classes/IndexQueue/Indexer.php, Classes/Util.php
Site and document id determination is improved by using root page ids if already available, so we can dispense with the unnecessary use of the RootPageResolver
Resolves: #3709
=> [TASK] Improve site and document id determination

Classes/Backend/IndexingConfigurationSelectorField.php
Undefined array key "label" in vendor/typo3/cms-backend/Classes/Form/Element/AbstractFormElement.php line 146
Fixes: #issue (Please create an related issue first and mark it as fixed here with your pr)
=> BUGFIX: Add missing label key to prevent php warning

Classes/ViewHelpers/SearchFormViewHelper.php
Problem:
Calling the `s:searchForm` ViewHelper with the `pageType` or `suggestPageType` argument with a value from a typoscript setting will lead to a TypeError
```html
<s:searchForm pageType="{settings.pageType}" suggestPageType="{settings.suggestPageType}">
```
`TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder::setTargetPageType(): Argument #1 ($targetPageType) must be of type int, string given, called in /var/www/html/private/typo3conf/ext/solr/Classes/ViewHelpers/SearchFormViewHelper.php`
Solution:
Cast both arguments to int
=> [BUGFIX] Fix TypeError in SearchFormViewHelper

Classes/FrontendEnvironment/Tsfe.php
This PR allows to pages with publish time in future to be added to the index queue for automatic indexing when they go public.
Notes:
1. The side effect: scheduler task will not be 100% complete with such pages present in the queue.
2. This improves the PR [#3719](https://github.com/TYPO3-Solr/ext-solr/pull/3719)
1. Add a page with time in future
3. You can now see that it appeared in the index queue table
4. Run the indexer, the page will not be indexed
5. Wait until publish time & next scheduler run
6. See the page appearing in the solr index
7. Change public time to future again
8. See the page disappearing from the index and being scheduled for indexing
Fixes: #3547, #3702
Related: #3702
=> Enable time-limited pages to be indexed automatically

Classes/EventListener/EnhancedRouting/CachedPathVariableModifier.php, Classes/EventListener/EnhancedRouting/PostEnhancedUriProcessor.php, Classes/Middleware/SolrRoutingMiddleware.php, Classes/Routing/Enhancer/SolrFacetMaskAndCombineEnhancer.php, Tests/Unit/Middleware/SolrRoutingMiddlewareTest.php
Backport of #3742 
---
SolrRoutingMiddleware was limited to indexing processs, but as the SolrFacetMaskAndCombineEnhancer requires this middleware to add the required parameters from the route path, this limitation causes that the route enhancer is ineffective.
This commit fixes this issue by reenabling the middleware for frontend requests and also ensures that route paths can be resolved correctly if PageTypeSuffix enhancer is active.
Configure route enhancer:
- SolrFacetMaskAndCombineEnhancer
- PageTypeSuffix 
With this commit
- EXT:solr can handle and react to facet parameters in route path
- no warning `Could not resolve page by path "menu.json" and language "de"` if requesting a specific page type on root page
- no TypeError occurs if no options are passed to the …
=> [BUGFIX:BP:11.5] Fix EXT:solr route enhancer

Classes/Util.php
Also consider "modified placeholder records" as draft records to avoid them being indexed and also to avoid exceptions in the backend (PHP 8) in the garbage collector.
Resolves: #3641
Relates: #3531
=> [BUG] Fix detection of "draft records" in workspaces

Classes/Domain/Search/Uri/SearchUriBuilder.php, Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
When there are route enhancers defined for a page containing the Solr search plugin, e.g. to realize pretty URLs for the search term, filters or pagination, there are issues with the URI caching that utilizes placeholders. Placeholders usually do not get replaced, leading to the issue described in #2984.
This PR implements a solution for route enhancers that define `requirements` in their parameters. The requirements are checked against the placeholders, leading to an exception. This exception is caught and it will then proceed the URI building with the original arguments instead of the placeholder arguments.
Fixes: #2984
See https://github.com/TYPO3-Solr/ext-solr/issues/2984
1. Set up the following route enhancer (set the page containing the Solr list plugin in `limitToPages`):
```yaml …
```
=> [BUGFIX] Retry Uri Building after exception

Classes/Domain/Search/Uri/SearchUriBuilder.php, Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
Backport of #3562
------------
When there are route enhancers defined for a page containing the Solr search plugin, e.g. to realize pretty URLs for the search term, filters or pagination, there are issues with the URI caching that utilizes placeholders. Placeholders usually do not get replaced, leading to the issue described in #2984.
This PR implements a solution for route enhancers that define `requirements` in their parameters. The requirements are checked against the placeholders, leading to an exception. This exception is caught and it will then proceed the URI building with the original arguments instead of the placeholder arguments.
Fixes: #2984
See https://github.com/TYPO3-Solr/ext-solr/issues/2984
1. Set up the following route enhancer (set the page containing the Solr list …
=> [BUGFIX:BP:11.5] Retry Uri Building after exception

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
This PR fixes a bug where an index document does not a have a site object assigned. In this case, the index document can be safely removed.
Since this bug occurred in a TYPO3 v11.5 environment, the PR should be backported to the 11.5.x branch.
Resolves: #3769
Releases: main, 11.5
=> [BUGFIX] Delete index documents without available site

Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/Domain/Index/Queue/UpdateHandler/EventListener/ImmediateProcessingEventListener.php, Classes/Domain/Index/Queue/UpdateHandler/Events/AbstractRecordMovedEvent.php, Classes/Domain/Index/Queue/UpdateHandler/Events/PageMovedEvent.php, Classes/Domain/Index/Queue/UpdateHandler/Events/RecordMovedEvent.php, Classes/Domain/Index/Queue/UpdateHandler/GarbageHandler.php, Classes/GarbageCollector.php, Classes/IndexQueue/RecordMonitor.php, Tests/Integration/Fixtures/can_collect_garbage_if_page_tree_is_moved.csv, Tests/Integration/GarbageCollectorTest.php, Tests/Integration/IndexQueue/Fixtures/can_handle_mounted_page_tree_movement.csv, Tests/Integration/IndexQueue/Fixtures/can_handle_page_tree_movement.csv, Tests/Integration/IndexQueue/RecordMonitorTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/GarbageHandlerTest.php
If a page is moved, subpages have to be considered, e.g. as rootline and slug might have changed. Also the MountPagesUpdater has to be triggerd to ensure mounted pages will be updated too.
This commit adds the missing recursive updates, an extension to the RecordMovedEvent and PageMovedEvent is done allowing that recursive updates on move operations will only be done if the parent page of the page has changed.
Move a page with subpages and check index and queue, moved pages have to be removed from index and queued for reindexing.
Resolves: #206
=> [TASK] Ensure recursive page update on page movement

Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/Domain/Index/Queue/UpdateHandler/EventListener/ImmediateProcessingEventListener.php, Classes/Domain/Index/Queue/UpdateHandler/Events/AbstractRecordMovedEvent.php, Classes/Domain/Index/Queue/UpdateHandler/Events/PageMovedEvent.php, Classes/Domain/Index/Queue/UpdateHandler/Events/RecordMovedEvent.php, Classes/Domain/Index/Queue/UpdateHandler/GarbageHandler.php, Classes/GarbageCollector.php, Classes/IndexQueue/RecordMonitor.php, Tests/Integration/Fixtures/can_collect_garbage_if_page_tree_is_moved.xml, Tests/Integration/GarbageCollectorTest.php, Tests/Integration/IndexQueue/Fixtures/can_handle_mounted_page_tree_movement.xml, Tests/Integration/IndexQueue/Fixtures/can_handle_page_tree_movement.xml, Tests/Integration/IndexQueue/RecordMonitorTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/GarbageHandlerTest.php
Backport of https://github.com/TYPO3-Solr/ext-solr/pull/3787
---
If a page is moved, subpages have to be considered, e.g. as rootline and slug might have changed. Also the MountPagesUpdater has to be triggerd to ensure mounted pages will be updated too.
This commit adds the missing recursive updates, an extension to the RecordMovedEvent and PageMovedEvent is done allowing that recursive updates on move operations will only be done if the parent page of the page has changed.
Move a page with subpages and check index and queue, moved pages have to be removed from index and queued for reindexing.
Resolves: #206
=> [TASK:BP:11.5] Ensure recursive page update on page movement

Tests/Integration/Controller/SearchControllerTest.php, composer.json, ext_emconf.php
Due to an internal bug in typo3fluid/fluid the pagination might fail, this bug is fixed in typo3fluid/fluid 2.9.2.
We now require typo3fluid/fluid >= 2.9.2 to ensure the right version is used and the pagination works as expected.
The failing test is reenabled.
Resolves: #3691
=>  [TASK] Require TYPO3 12.4.3 to get typo3fluid/fluid >= 2.9.2 

Classes/Event/Indexing/AfterPageDocumentIsCreatedForIndexingEvent.php, Classes/Event/Indexing/BeforeDocumentIsProcessedForIndexingEvent.php, Classes/Event/Indexing/BeforeDocumentsAreIndexedEvent.php, Classes/Event/Indexing/BeforePageDocumentIsProcessedForIndexingEvent.php, Classes/IndexQueue/FrontendHelper/PageIndexer.php, Classes/IndexQueue/Indexer.php, Tests/Unit/IndexQueue/IndexerTest.php
Almost all in EXT:solr 12-ALPHA introduced events propagate the Site and SiteLanguage objects, which are fetched from simulated TSFE object. That does not allow to use the required TSFE in subsequent processing directly, without instantiate TSFE objects manually. EXT:solr* stack requires exact the same TSFE object, which is used by indexed Records/Pages, to process correctly.
This change makes it possible to reuse simulated TSFE object in listeners to be able to delegate right Core-Context objects for TYPO3 CORE components.  The Site and SiteLanguage getters are still available.
Fixes: #3800
=> [TASK] Always delegate simulated TSFE via PSR-14 events instead of Site/SiteLanguage

Classes/Domain/Search/Query/ParameterBuilder/Highlighting.php, Resources/Private/Solr/configsets/ext_solr_12_0_0/conf/solrconfig.xml, Tests/Integration/SearchTest.php
Since Apache Solr 9 the Unified Highlighter is used by default,  causing the fragment size setting to be ignored in our setup.
By configuring the Original Highlighter as default, this issue is fixed till we update our highlighting setup to use the recommended highlighter.
1. Index contents
2. Activate the results highlighting 
`plugin.tx_solr.search.results.resultsHighlighting = 1`
3. Test the results in the frontend with different `fragmentSize` settings, e.g. `20` (fastVector) and `15` (original) 
With this bugfix the fragment size will be considered and ensured that the `fastVector` or `original` hightlighter is used.
Resolves: #3798
=> [BUGFIX] Fix result highlighting fragment size

Classes/Controller/Backend/Search/InfoModuleController.php, Classes/Domain/Site/SiteRepository.php, Tests/Unit/Domain/Site/SiteRepositoryTest.php, ext_tables.sql
TYPO3 registry was mainly used for connection storage, which is obsolete since the introduction of the Site handling. Luke limit read by the InfoModuleController was never set in the registry, so for now the fallback value of 20000 is used.
This is a breaking change as the SiteRepository expected the registry to be passed, which is no longer necessary.
Resolves: #3792
=> !!![CLEANUP] Remove obsolete TYPO3 registry usages

Classes/IndexQueue/Queue.php
Fixes the error:
Uncaught TYPO3 Exception: Return value of ApacheSolrForTypo3\Solr\IndexQueue\Queue::getPageItemChangedTime() must be of the type int, null returned
Fixes: #3806
Ports: #3812
=> [BUGFIX:BP:11.5] Return value getPageItemChangedTime() must be of the type int

Classes/Event/Routing/AfterUriIsProcessedEvent.php, Classes/Event/Routing/BeforeCachedVariablesAreProcessedEvent.php, Classes/Event/Routing/BeforeVariableInCachedUrlAreReplacedEvent.php, Classes/Routing/Enhancer/SolrFacetMaskAndCombineEnhancer.php, Classes/System/Configuration/ExtensionConfiguration.php, Configuration/RequestMiddlewares.php, Configuration/Services.yaml, Documentation/Development/Events.rst, Documentation/Releases/solr-release-12-0.rst, Resources/Private/Language/locallang_be.xlf, ext_conf_template.txt
- [BUGFIX] Fix facet route enhancer
- !!![TASK] Configuration option enableRouteEnhancer
1) Configure EXT:solr route enhancer, e.g.:
```
routeEnhancers:
solrContentType:
type: SolrFacetMaskAndCombineEnhancer
limitToPages:
- 6
extensionKey: tx_solr
routePath: '/contentType/{type}'
_arguments:
type: filter-type
requirements:
type: '.*'
```
2) Check facet links with enabled and disabled option "enableRouteEnhancer"
Fixes: #3810
---
**Caution**: PR contains an additional bugfix for the route enhancer in general, do not squash!
=> !!![TASK] Configuration option enableRouteEnhancer

Classes/Controller/Backend/Search/InfoModuleController.php
In info module cores and connections are listed only once.
Resolves: #3616
Ports: #3617
=> [BUGFIX:BP:11.5] Do not list cores twice in Index Inspector

Classes/Controller/Backend/Search/InfoModuleController.php
In info module cores and connections are listed only once.
Use one core for multiple languages => see info module
Fixes: #3616
---
Maintaners comments:
Port into:
=> [BUGFIX] Do not list cores twice in Index Inspector

Classes/IndexQueue/AbstractIndexer.php, Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
Resolves #3758
Use less strict return types on some methods to allow all possible field types.
Use fields like dateS, boolS and intS during indexing.
Fixes: #3758
=> [BUGFIX] Less strict return types on resolving values

Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php, Classes/Domain/Search/SearchRequest.php, Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
Enables to resolve a solr response when multiple sortings are passed as argument.
1. Configure multiple sorting options (see attached img)
2. Pass multiple sorting options to the searchrequest (see attached img)
Fixes: #3627
=> [BUGFIX] Fixes multiple sortings

Classes/ContentObject/Relation.php
Prevent indexing error on missing 'foreignLabelField' of SOLR_RELATION
Related: #3734
=> [BUGFIX] Prevent indexing error on missing 'foreignLabelField'

Classes/Domain/Search/ResultSet/Result/SearchResult.php
Force the score to be a float.
TBH: I didn't yet that test that myself but a colleague had the issue and just patched it locally
=> [BUGFIX] Force score to float

Classes/FieldProcessor/Service.php
=> [BUGFIX:BP:11.5] Fix possible notice

Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript, Documentation/FAQ/Index.rst
* adds explanation how to generate URLs to restricted pages
* enables `typolink.linkAccessRestrictedPages` for EXT:news index example
Fixes: #3615
Ports: #3620
=> [DOC:BP:11.5] Add FAQ how to generate URLs to restricted pages

Documentation/FAQ/Index.rst
…t well. What can be the reason?
Fixes: #issue (Please create an related issue first and mark it as fixed here with your pr)
Todo:
=> [DOC] Solr claims to be not configured in backend context, although I did it well. What can be the reason?

Classes/System/Service/ConfigurationService.php, Documentation/Releases/solr-release-12-0.rst, Tests/Unit/System/Service/ConfigurationServiceTest.php
With this PR it is now possible to use complex query in FlexForm filter value.
I add a regex to prevent a too big breaking change. The old behaviour is still working, so if a string value contains space(s) and no special characters of the solr query parser, the string is always wrapped with double quotes. But if the string contains special characters no wrapping happen (special characters are `+ - && || ! ( ) { } [ ] ^ " ~ * ? : \`.
There is some cases where this PR can break, for example if the filter value is something like `toto AND tata` or `music (rock)` or `my "flow" is`. Here the wrapping and the escaping of the inner double quote have to be manually updated like this `"toto AND tata"`, `"music (rock)"` and `"my \"flow\" is"`.
Fixes: #2151
=> !!![FEATURE] Allow using complex filter values in FlexForm

Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParserTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetTest.php
Cast solr value to string to handle float values correctly.
When the result values are 0.01, 0.02, 0.03 the last count wins with the array key 0
see https://3v4l.org/2LOHk#v8.1.20
Tested on dev-master with TYPO3 12.4.3
Port:
=> [BUGFIX] Handle float values in options facet parser

Classes/IndexQueue/Indexer.php
Given the following scenario:
- non-localized root page for multi-language site
- below this root page is a localized folder
- inside that localized folder are localized record to index
Since TypoScriptFrontendController is not initialized for sys_folder page records, it'll walk up to the parent page and try to initialize TypoScriptFrontendController for it. However, this isn't possible in the given scenario because the page isn't localized into all languages. Tsfe::getTsfeByPageIdAndLanguageId() returns null in this case, which triggers a NullPointerException when getLanguageOverlay() is called on it. When the NPE is thrown none of the localizations of the item will be indexed, even though some could have been successfully indexed.
This change checks aborts the operation when the …
=> [BUGFIX] handle localizations with un-available tsfe more gracefully

Classes/EventListener/PageIndexer/FrontendGroupsModifier.php, Tests/Integration/FrontendEnvironment/Fixtures/can_initialize_tsfe_for_page_with_different_fe_groups_settings.csv, Tests/Integration/FrontendEnvironment/TsfeTest.php, Tests/Integration/IndexQueue/Fixtures/can_index_access_protected_page_show_at_any_login.csv, Tests/Integration/IndexQueue/PageIndexerTest.php
The TSFE can not be initialized in record-monitoring(BE editiing) context for pages,  whichs fe_group is set to -2(show if fe_user is logged in).
This leads to following behavior:
* After editing the [sub]pages in BE, the page is removed from index and never indexed again.
* By reinitialization of pages index queue the page is indexed as expected with expected groups.
Relates: #3347, #3351
Ported from: #3819
---
**This bug is not present on TYPO3 12.4.7 + EXT:solr bbdda0cf2dfc946d09b5207c58ece034696cf63e, so the test only will be merged. The fix for EXT:solr 11.5+ will be done within #3819**
The indexing of pages with fe_group=-2 / "show at any login" was broken in 12.0.0(RC1), which is fixed in this pr.
=> [TEST] TSFE can be initialized for pages with fe_group="-2"

Classes/Domain/Search/ResultSet/Result/Parser/GroupedResultParser.php, Tests/Unit/Domain/Search/ResultSet/Result/Parser/Fixtures/fake_solr_response_group_on_fields.json, Tests/Unit/Domain/Search/ResultSet/Result/Parser/GroupedResultsParserTest.php
The groupValue is expected by EXT:solr to be a string, but it must be  possible to reuse available fields for grouping.
This change adds cast to string on fetched groupValue.
Fixes: #3821
=> [BUGFIX] Grouping fails on non-string filed types

Tests/Integration/Controller/SearchControllerTest.php
Reenables test case "canDoAnInitialEmptySearchWithoutResults" of SearchControllerTest, as issue was already fixed in #3112.
Resolves: #3150
Releated: #3112
Ports: #3230
=> [TASK:P:main] Reenable skipped test of SearchControllerTest

.gitattributes, Classes/System/Solr/Service/SolrWriteService.php, Configuration/SiteConfiguration/Overrides/sites.php, composer.json
This change makes it possible to find out the causes by unexpected behaviour of service. For example it will be used by EXT:tika 12.0.1+ in Reports module to find out the cause of trouble with Tika-Cell connection.
Relates: https://github.com/TYPO3-Solr/ext-tika/issues/211
=> [TASK] Add response object to return array of SolrWriteService::extractByQuery()

Build/generate_documentation.sh
After second run of "composer t3:docs:build:prod" the unneccessary  symlink `Documentation -> Resources/Public/Documentation` inside of `Resources/Public/Documentation` was created because of `-f` option on `ln` command. The symlink `Documentation.HTML` is now removed each time, and the `-f` option is remod from `ln -s`  comman
=> [BUGFIX][DOC] avoid creation of symlink inside the prod docs

Classes/IndexQueue/FrontendHelper/PageIndexer.php
Logging the response eases debugging.
Integrators and developers can check the response in order to retrieve the actual reported issue, a crucial info in order to fix indexing issues.
Add an error log entry with solr response body in case indexing a page did not succeed.
Create a broken page indexing and check the log for the new entry.
Fixes: #3846, #2590
=> [TASK] Log solr response in case of Page indexing issue

Classes/ViewHelpers/Uri/AbstractUriViewHelper.php, Tests/Unit/ViewHelpers/Uri/Facet/AddFacetItemViewHelperTest.php, Tests/Unit/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelperTest.php
Checking RenderingContext is not enough as it might provide either a ServerRequest or Extbase Request.
We use the RequestBuilder to ensure there is a proper Extbase Request.
A none Extbase Request might exist in case of usage within StandaloneView or other contexts without providing an Extbase Request.
Fixes: #3851
Ensure that an Extbase request is provided.
I don't have an easy step by step way … Maybe test that this won't break anything instead?
=> [BUGFIX] Provide proper Uri Builder Request in VH

Classes/ContentObject/Relation.php
If you enableRecursiveValueResolution and the foreignLabelField is not set because the record has no relation, the item can not be indexed.
See Ticket.
Fixes: #3856
=> [BUGFIX] prevent empty array key if foreignLabelField is null

Classes/EventListener/Extbase/PersistenceEventListener.php, Classes/IndexQueue/RecordMonitor.php, Classes/Trait/SkipMonitoringTrait.php, Configuration/Services.yaml, Tests/Integration/Extbase/Fixtures/delete_items.csv, Tests/Integration/Extbase/Fixtures/hidden_items.csv, Tests/Integration/Extbase/Fixtures/update_items.csv, Tests/Integration/Extbase/PersistenceEventListenerTest.php, Tests/Integration/Fixtures/Extensions/fake_extension/Classes/Domain/Model/Foo.php, Tests/Integration/Fixtures/Extensions/fake_extension/Classes/Domain/Repository/FooRepository.php, Tests/Integration/Fixtures/Extensions/fake_extension/Configuration/Services.yaml, composer.json
Extbase records are now monitored.
* New entities are added to index queue
* Updated entities are updated in the index queue
* Entities turned inaccessable are removed from index queue
* Soft/Hard deleted entities are removed in the index queue
`.Build/bin/phpunit --config=Build/Test/IntegrationTests.xml Tests/Integration/Extbase/PersistenceEventListenerTest.php`
Fixes: #126
---
=> [FEATURE] Monitor extbase records

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Appendix/VersionMatrix.rst, Documentation/Releases/solr-release-11-5.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 11.5 and the last release that supports Apache Solr 8.11. Next EXT:solr release for TYPO3 11.5 will be 11.6.0, it will contain support for Apache Solr 9 and some breaking improvements.
11.5.4 contains the following changes:
- [TASK] Fix CI 2023.09.11 on release-11.5.x by @dkd-kaehm in https://github.com/TYPO3-Solr/ext-solr/pull/3777
- [BUGFIX:BP:11.5] Fix EXT:solr route enhancer by @dkd-friedrich in https://github.com/TYPO3-Solr/ext-solr/pull/3743
- [BUG] Fix detection of "draft records" in workspaces by @baschny in https://github.com/TYPO3-Solr/ext-solr/pull/3642
- [BUGFIX] Do not index translations on default language in languages free mode by @dkd-kaehm in https://github.com/TYPO3-Solr/ext-solr/pull/3786
- [BUGFIX:BP:11.5] Retry Uri Building …
=> [RELEASE] 11.5.4 - Maintenance Release

Documentation/Releases/solr-release-11-5.rst
The changelog is a single file, each major version.  This change allows us to avoid porting of changelog files across release-zz.y branches. Most probably we'll introduce single file - each commit changelog approach to avoid  all the problems related to our current approach.
Relates: #3854
Ports: #3863
---
The commit of this pull-request should be ported back to older branches.
=> [DOC:11.6] Fix changelogs and add hints about outdated state on branches

Documentation/Configuration/Reference/TxSolrSearch.rst
For `grouping.groups.[groupName].*` there was the groups-key missing in "TS Path" of documentation.
Fixes: #3871
=> [TASK] Add missing groups-key to TS Path

Documentation/Configuration/Reference/TxSolrSearch.rst
The `sortBy` in group configuration is supported but was *not* documented.  Especially when using `query.sortBy` and grouping, you'll need it.
Fixes: #3869
=> Add `grouping.groups.[groupName].sortBy`

Classes/EventListener/Extbase/PersistenceEventListener.php, Classes/IndexQueue/RecordMonitor.php, Classes/Traits/SkipMonitoringTrait.php
The \\Trait\\  namespace is allowed on PHP 8.0+ only.
To avoid confusions between EXT:solr 11.6 and 12.0 the namespace is adjusted to 11.6.x state.
Relates: #3843, #3844
=> [TASK] Rename namespace \\Trait\\ to \\Traits\\, due of consistency with 11.6.x

Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php, Documentation/Releases/solr-release-11-5.rst, Tests/Unit/Domain/Search/Statistics/StatisticsWriterProcessorTest.php, ext_tables.sql
**Note:** This change requires the database schema update.
With the Security update at November, 14th 2023 the cookie generation changed in the TYPO3 core.
This leads to an exception, when executing the search and statistics are enabled.
Reason is, that the generated cookies are longer than the old ones and do not fit in the tx_solr_statistics.cookie any more. The available length is 32 chars, TYPO3 core allows up to 190.
This change increases the length of `tx_solr_statistics.cookie` field to 255 characters. Beside of that, the deprecated method to fetch the fe_user cookie value is adjusted to new TYPO3 API.
Fixes: #3877
=> !!![BUGFIX:11.5] Exception with tx_solr_statistics after latest TYPO3 security update

Classes/IndexQueue/Indexer.php
Indexer does not work for extbase-records with sys_language_uid=-1 This change adds additional check for '-1'  `Indexer::isLanguageInAFreeContentMode()`  to avoid the fetching the language -1 from TYPO3 site object. 
Fixes: #3879
=> [BUGFIX] Indexer does not work for extbase-records with sys_language_uid=-1

Classes/IndexQueue/Indexer.php
Indexer does not work for extbase-records with sys_language_uid=-1 This change adds additional check for '-1'  `Indexer::isLanguageInAFreeContentMode()`  to avoid the fetching the language -1 from TYPO3 site object. 
Fixes: #3879
Ports: #3885
=> [BUGFIX:11.5] Indexer does not work for extbase-records with sys_language_uid=-1

Classes/Middleware/SolrRoutingMiddleware.php
Fixes infinite loop and therefore server crashing if route doesn't exist or URl is in the scheme like domain/id=123456
use old school requests like /index.php?id=123 or any URI which will not be found in the slug Provider class (any none existing URI with speaking URL)
Fixes: #3873
=> [BUGFIX:11.5]  Infinite loop in SolrRoutingMiddleware 

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-12-0.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 12.4.
**Note:** This release requires the database schema update, due of database schema change from pull-request https://github.com/TYPO3-Solr/ext-solr/pull/3881
https://github.com/TYPO3-Solr/ext-solr/releases/tag/12.0.1
---
* Provide patches through pull requests or review and comment on existing pull requests
* Go to www.typo3-solr.com or call dkd to sponsor the ongoing development of Apache Solr for TYPO3
Support us by becoming an EB partner:
https://shop.dkd.de/Produkte/Apache-Solr-fuer-TYPO3/
or call:
+49 (0)69 - 2475218 0 …
=> [RELEASE] 12.0.1 - Maintenance Release

Classes/IndexQueue/AbstractIndexer.php
`AbstractIndexer::addDocumentFieldsFromTyposcript()` disallows any PHPs empty value. This change adds explicit checks for disallowed values:
* null
* empty string
* empty array
Fixes: #3900
=> [BUGFIX] false as field value is not allowed

Tests/Unit/Domain/Search/Suggest/SuggestServiceTest.php
Relates: #3902, #3903
The PR from above was merged accidentally without green CI pipeline.
This change fixes the issue.
=> [BUGFIX] Unit tests missing mock of EventDispatcher for AfterSuggestQueryHasBeenPreparedEvent

Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
The path should use EXT: syntax.
That way TYPO3 can properly handle the file and add version numbers and check for existence.
Open the queue backend module and check that the css file has a proper timestamp as parameter when setting `$GLOBALS['TYPO3_CONF_VARS']['BE']['versionNumberInFilename']` to `0`
Fixes: #3897
=> [BUGFIX] Broken IndexQueueModule.css asset path in backend

Classes/Domain/Search/ResultSet/Facets/AbstractFacetItem.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParser.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php, Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetParser.php, Classes/Domain/Search/ResultSet/Facets/RangeBased/AbstractRangeFacetParser.php, Configuration/Services.yaml, Documentation/Development/Events.rst
The `AfterFacetIsParsedEvent` was newer dispatched, because the `::injectEventDispatcher()`  was never called due of missing dependency injection settings. This change sets almost all classes within `ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\` namespace  to autowire and public DI. 
The non-wireable classes are excluded from autowire and public DI and should behave the same as before this change.
**In addition the `AfterFacetIsParsedEvent` is added to all available facet types.**
Fixes: #3920
---
We want the integration tests to check if the events are fired properly.
=> [BUGFIX] `AfterFacetIsParsedEvent` was never dispatched

Configuration/Backend/Modules.php
See https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#confval-access
This PR makes the modules selectable for editors and groups again.
Edit the permissions of a user group.
Fixes: #3923
=> [BUGFIX] update acces to backend user modules

Configuration/TypoScript/Examples/Suggest/setup.typoscript
This PR fixes an exception in CLI mode due to the missing request object
See #3916
Fixes: #3916
=> [BUGFIX] Fix #3916: exception in CLI mode when using suggest TS example

Configuration/TypoScript/Examples/Suggest/setup.typoscript
This change fixes an exception in CLI mode due to the missing request object
Fixes: #3916
Ports: #3917
=> [BUGFIX:BP:11.5] Exception in CLI mode when using suggest TS example

Classes/System/Page/Rootline.php
Ensure method return value of root-page-UID is an integer System\Page::getRootPageId()
Fixes: #3928
Ports: #3929
=> [BUGFIX:BP:11.5] Ensure method return value of root-page-UID is an integer

Classes/Search/AccessComponent.php
AccessComponent expects to find the TypoScriptFrontendController in $GLOBALS['TSFE'], and will cause an exception in CLI context.
To prevent this an additional check for TSFE in AccessComponent is added, similiar to other components like LastSearchesComponent.
Relates: #3675
Resolves: #3944
=> [BUGFIX] Prevent exception in AccessComponent

Tests/Unit/Domain/Variants/IdBuilderTest.php, Tests/Unit/SetUpUnitTestCase.php
Since TYPO3 12.4.11 and 11.5.35 the encryptionKey is not initialized in the default configuration, thus some unit tests will fail.
This commit ensures an encryptionKey is set for the unit tests.
Resolves: #3958
=> [TASK] Provide encryptionKey in unit tests

Tests/Unit/Domain/Variants/IdBuilderTest.php, Tests/Unit/UnitTest.php
Since TYPO3 12.4.11 and 11.5.35 the encryptionKey is not initialized in the default configuration, thus some unit tests will fail.
This commit ensures an encryptionKey is set for the unit tests.
Ports: #3959
Resolves: #3958
=> [TASK:BP:11.5] Provide encryptionKey in unit tests

Classes/ViewHelpers/PageBrowserRangeViewHelper.php
Fix for [BUG] tx_solr 11.5.5 and solrfluidgrouping 11.0.0 PHP 8.1 #3942
---
```
[BUGFIX] error with active EXT:solrfluidgrouping 11.0 within PHP 8.1
Fixes error with PHP 8.1if EXT:solrfluidgrouping 11.0 is installed: 
`Attempt to read property "start" on null in .../solr/Classes/ViewHelpers/PageBrowserRangeViewHelper.php line 68`
Fixes: #3942
```
=> Update PageBrowserRangeViewHelper.php solves #3942

Classes/Domain/Search/Query/QueryBuilder.php, Documentation/Configuration/Reference/TxSolrSearch.rst, Tests/Unit/Domain/Search/Query/QueryBuilderTest.php
Before this it's required to define a hardcoded comma separated list of page uids. Now it's possible to use the power of TypoScript to fill it with all sorts of things.
plugin.tx_solr.search.query.filter {
__pageSections = TEXT
__pageSections.data = leveluid:0
}
Fixes: #3936
=> Power up for magic filter __pageSections

Classes/Domain/Search/Query/QueryBuilder.php, Documentation/Configuration/Reference/TxSolrSearch.rst, Tests/Unit/Domain/Search/Query/QueryBuilderTest.php
Before this it's required to define a hardcoded comma separated list of page uids. Now it's possible to use the power of TypoScript to fill it with all sorts of things.
This can e.g. look like:
plugin.tx_solr.search.query.filter {
__pageSections = TEXT
__pageSections.data = leveluid:0
}
Ports: #3937
Resolves: #3936
=> [FEATURE:BP:11.5] Power up for magic filter __pageSection

Classes/Report/SolrVersionStatus.php, Docker/SolrServer/Dockerfile, Documentation/Appendix/VersionMatrix.rst, Resources/Private/Templates/Backend/Reports/SolrVersionStatus.html, composer.json
As incompatibilities can also occur in minor versions, all versions will be explicitly tested and listed.
Currently tested and supported versions are: 9.3.0, 9.4.0, 9.4.1, 9.5.0.
It is always recommended to use the latest tested version.
Resolves: #3955
=> [TASK] Support several Apache Solr versions

Classes/Report/SolrVersionStatus.php, Docker/SolrServer/Dockerfile, Documentation/Appendix/VersionMatrix.rst, Documentation/Releases/solr-release-11-5.rst, Resources/Private/Templates/Backend/Reports/SolrVersionStatus.html, Tests/Integration/Report/SolrVersionStatusTest.php, composer.json
As incompatibilities can also occur in minor versions, all versions will be explicitly tested and listed.
Currently tested and supported versions are: 8.11.1, 8.11.2., 8.11.3
It is always recommended to use the latest tested version.
Note: Apache Solr 8.11.3 contains a breaking change, see security fix "SOLR-14853: Make enableRemoteStreaming option global; not configSet". EXT:solr relies on stream bodies which aren't enabled by default since 8.11.3. EXT:solr 11.5.6 contains all required settings, but if you're updating and not using our Docker image, you have to set `solr.enableRemoteStreaming=true` and `solr.enableStreamBody=true`. TYPO3 reports module will print a warning if you have to reconfigure.
Ports: #3956
Resolves: #3955
=> [TASK:BP:11.5] Support several Apache Solr versions

Classes/Controller/Backend/Search/IndexQueueModuleController.php
When having more than one site the cannot be determined if the page root is selected. This patch makes the selectedSite truely optional
Have more than one site, e.g. a minimal, non-assigned autogenerated site.
Have no page in a site selected in the page tree (e.g. root page)
Open queue module
=> [BUGFIX] Prevent exception in queue module when no site can be determined

Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
If the label of a sorting field only consists of a stdWrap, the key “label” is not present, only “label.”.
Removes possible flooded TYPO3 log messages.
Create a simple sorting field with a label using stdWrap.
```
plugin.tx_solr {
search {
sorting = 1
sorting {
options >
options {
isnew {
label.data = LLL:EXT:extension/Resources/Private/Language/locallang.xlf:solr.sorting.isnew
field = sort_isnew_boolS
}
}
}
}
}
```
Fixes: #3997
=> [BUGFIX] Solves PHP Warning: Undefined array key "label".

Resources/Private/Language/fr.locallang.xlf, Resources/Private/Language/fr.locallang_be.xlf, Resources/Private/Language/fr.locallang_csh_pages.xlf, Resources/Private/Language/fr.locallang_mod.xlf, Resources/Private/Language/fr.locallang_mod_coreoptimize.xlf, Resources/Private/Language/fr.locallang_mod_indexadmin.xlf, Resources/Private/Language/fr.locallang_mod_indexqueue.xlf, Resources/Private/Language/fr.locallang_mod_info.xlf, Resources/Private/Language/fr.locallang_tca.xlf
Adds missing translations for French and normalize some terms likes "Index Queue" to "File d'indexation" instead of "File d'attente de l'index" or "File d'attente d'indexation".
Also fixes some other small mistakes.
Using a clean setup (no var/labels folder), activate and download French for backend. Change your user to French. Check that pages.no_search_sub_entries field has its label and description translated. In the module bar, check module names are in French. In about module, check the module and submodules information are translated. Explore the SOLR module and find no word in English. If found, the text is not found in translation files.
Fixes: #3983
=> [TASK] Full fixed french translation

Classes/ContentObject/Relation.php, Documentation/Configuration/Reference/TxSolrIndex.rst
Adds a new TypoScript option to allow stdWrap usages to build the actual label for indexing when resolving relations via SOLR_RELATION.
Index a field using SOLR_RELATION with the new option. E.g. try EXT:tt_address and use the provided example.
Fixes: #3975
=> [FEATURE] Support stdWrap to resolve relation label field

Resources/Public/JavaScript/suggest_controller.js
`suggest_controller.js` adds an autofocus on form submit to all forms with an autosuggest input containing `.tx-solr-suggest`. We have a form that contains an autosuggest input field and multiple other facets to filter for values. If you leave the search input empty and add activate some other facet filters, you can't submit the form. 
This pull request changes the submit event listener, to check for `.tx-solr-suggest-focus` instead of `.tx-solr-suggest` which is more intuitive, as it's already used for the initial focus made by `$form.find('.tx-solr-suggest-focus').focus();`.
Create an autosuggest searchfield and remove the `.tx-solr-suggest-focus` CSS class.
Fixes: #4004
=> [BUGFIX] Improve autosuggest_controller focus behavior

Classes/IndexQueue/PageIndexerRequest.php
We had the problem that the requests where cached by staticfilecache.
But we could not find any hint about that in the logs. 
Because the log would only show an empty body.
That is because the body was already read in the lines above the log message.
And it was a read once stream. (read more about read once streams: https://stackoverflow.com/a/6518288/5440709 )
Our solution is to keep the body in a variable so if there is a Problem we can send the body to the log message.
@dkd-kaehm
=> [BUGFIX] Fix debug output if response body is read once stream

Classes/ViewHelpers/SearchFormViewHelper.php
Problem:
Calling the `s:searchForm` ViewHelper with the `pageType` or `suggestPageType` argument with a value from a typoscript setting will lead to a TypeError
```html
<s:searchForm pageType="{settings.pageType}" suggestPageType="{settings.suggestPageType}">
```
`TYPO3\CMS\Extbase\Mvc\Web\Routing\UriBuilder::setTargetPageType(): Argument #1 ($targetPageType) must be of type int, string given, called in /var/www/html/private/typo3conf/ext/solr/Classes/ViewHelpers/SearchFormViewHelper.php`
Solution:
Cast both arguments to int
Fixes: #3927
Ports: #3728
=> [BUGFIX:P:11.5] Cast pageType and suggestPageType to int in SearchFormViewHelper

Classes/EventListener/PageIndexer/FrontendGroupsModifier.php, Tests/Integration/IndexQueue/Fixtures/can_index_sub_page_of_protected_page_with_extend_to_subpage.csv, Tests/Integration/IndexQueue/PageIndexerTest.php
When indexing a page, the authorized user is manipulated depending on which access is required to index.
Previously this did not take restrictions of parent pages into account when the page to index was not directly indexed.
1. Create a page called parent and restrict it to any fe_group
2. Check Extend to Subpages for the page parent
3. Create a subpage for the page parent called child
4. Index the pages
The subpage should be indexed now too.
Fixes #3969
=> [BUGFIX] Allow fe_group modification when indexing subpage of restricted page

Classes/Domain/Search/Score/ScoreCalculationService.php
Fixes issue after PHPStan 1.11 upgrade:
```
Parameter #1 $boost of class ApacheSolrForTypo3\Solr\Domain\Search\Score\Score constructor expects float, string given.
```
=> [BUGFIX] PHPStan 1.11+

Configuration/Backend/Modules.php
Fixes: #4052
Enables page tree for backend modules in v13
Open a Solr backend module in v13 backend
Fixes: #4052
=> [TASK] Update navigationComponent for page tree in v13

Classes/ViewHelpers/SearchFormViewHelper.php
Adds empty array defaults in SearchFormViewHelper::getExistingSearchParameters to prevent TYPO3 TypeError.
Setup ext:solr with "keepExistingParametersForNewSearches = 1"
Fixes: #4040
=> [BUGFIX] Add empty array defaults in SearchFormViewHelper

Classes/Domain/Search/LastSearches/LastSearchesService.php, Classes/Search/LastSearchesComponent.php, Classes/System/Configuration/TypoScriptConfiguration.php, Configuration/TypoScript/Solr/setup.typoscript, Documentation/Configuration/Reference/TxSolrSearch.rst
It introduces `plugin.tx_solr.search.lastSearches.mode = disabled` and in the 2nd commit set it to be new default
* Set the TypoScript.
* Make a search, that returns a result
* See no tracked keywords in database 
Fixes: #4003
=> Be able to disable tracking of last searches

Classes/Domain/Search/LastSearches/LastSearchesService.php, Classes/Search/LastSearchesComponent.php, Configuration/TypoScript/Solr/setup.typoscript, Documentation/Configuration/Reference/TxSolrSearch.rst
Currently last searches are always tracked, even if not displayed.
This introduces the new tracking mode 'disabled' to disable it.
plugin.tx_solr.search.lastSearches.mode = disabled
Relates: #4003
Ports: #4006
=> [FEATURE:BP:12] Be able to disable tracking of last searches

Classes/Report/SolrStatus.php, Classes/System/Solr/Service/SolrAdminService.php, Docker/SolrServer/Dockerfile, Documentation/Solr/ConfigurationStructures.rst, Resources/Private/Templates/Backend/Reports/SolrStatus.html, Tests/Integration/IntegrationTestBase.php
Drops the usage of content streams for Solr queries, this removes the dependency to SOLR_ENABLE_STREAM_BODY.
Resolves: #3750
=> [TASK] Remove content stream usage

Classes/Backend/SettingsPreviewOnPlugins.php
This commit add the row information as 5th argument in the function call of 'BackendUtility::getLabelFromItemListMerged()'.
Even the argument is optional for this function, it becomes a kind of required in the following nested function calls within TYPO3.
1. Install extension `gridelementsteam/gridelements`
2. Install extension `apache-solr-for-typo3/solr`
3. Add a page and place the search plugin into it
4. After saving and go back to the page module
5. There should not be any warnings be visible related to a missing pid
Fixes: #4080
=> [TASK] Call getLabelFromItemListMerged with the current row data

Resources/Public/JavaScript/facet_numericrange_controller.js
Previously the numeric range slider updated the UI and the facet setting continously during sliding. This caused a lot of get requests to the server. This PR implents the desired beviour to send update requests only once the user releases the slider. The UI still gets updated continously by using the separate slide-event for that.
Fixes: https://github.com/TYPO3-Solr/ext-solr/issues/4082
=> [BUGFIX] numeric facet range slider sends lot of requests to server

Classes/IndexQueue/PageIndexer.php
The 3rd argument of `PageIndexer::indexPage()` must be an integer or null, but under certein conditions, a string is passed (when page is access protected). 
This change ensures, that the 3rd argument for `indexPage()` function in `PageIndexer` is always an integer by typecasting the evaluated value.
Fixes: #3986
=> [BUGFIX] Typecast $userGroup to integer

Classes/IndexQueue/Initializer/Page.php, Tests/Integration/IndexQueue/Initializer/Fixtures/can_add_mount_pages.csv, Tests/Integration/IndexQueue/Initializer/PageTest.php
Allows non-overlayed mount points to be valid
Fixes: #4026
=> BUG [4026] treat non-overlayed mount points as valid

Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetParserTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeTest.php
This change fixes the range string calculation, so items for the given date are included until 23:59 of the target end date.
Fixes: #4087
Ports: #4090
=> [BUGFIX:P:11.5] Fix range string calculation in DateRange facet

Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetParserTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeTest.php
This change fixes the range string calculation, so items for the given date are included until 23:59 of the target end date.
Fixes: #4087
Ports: #4090
=> [BUGFIX:P:11.6] Fix range string calculation in DateRange facet

Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetParserTest.php, Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeTest.php
This change fixes the range string calculation, so items for the given date are included until 23:59 of the target end date.
Fixes: #4087
---
Ports wanted, before merging:
=> [BUGFIX] Fix range string calculation in DateRange facet

Classes/Backend/CoreSelectorField.php, Classes/Backend/IndexingConfigurationSelectorField.php
Fixes multiple issues within "Optimize index of a site" component.
Relates: #4102
Ports: #4104
=> [FIX:11.5] scheduler task "Optimize index of a site" is not functional

Classes/Backend/CoreSelectorField.php, Classes/Backend/IndexingConfigurationSelectorField.php
Fixes multiple issues within "Optimize index of a site" component.
Relates: #4102
---
Must be ported to release-11.5.x See: https://typo3.slack.com/archives/C02FF05Q4/p1720632402013839?thread_ts=1720535167.921059&cid=C02FF05Q4
=> [FIX:12] scheduler task "Optimize index of a site" is not functional

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/Domain/Index/Queue/UpdateHandler/GarbageHandler.php, Tests/Integration/GarbageCollectorTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/DataUpdateHandlerTest.php
If an index document has no representation in the index queue, EXT:solr fails to remove the item on deletions or updates of the corresponding record in TYPO3.
By adjusting the checks in the record monitor, garbage remover and update handler this issue is resolved. The
ConfigurationAwareRecordService is no longer using BackendUtility::getRecord() as this would return hidden records.
Resolves: #4107
=> [BUGFIX] Ensure index document is deleted

Classes/ViewHelpers/SearchFormViewHelper.php
This PR re-introduces the template variables in the SearchFormViewHelper
Check that variables are back in template. For instance by adding a <f:debug>{_all}</f:debug> to the Resources/Private/Partials/Search/Form.html template
Fixes: #4117
=> Re-added template variables

.github/dependabot.yml
This change enables Dependabot for all supported branches, by trying  to consume dependabot settings 
[`target-branch`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch) together with  [`commit-message.prefix`](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)
Fixes: #3168
---
This pull-request could be reverted, removed, or adapted after merging, if the setting will not work as expected:
* Create pull requests for solarium/solarium against
* Create pull requests for Dockerfile
=> [TASK] Enable dependabot for all supported branches

composer.json
Dependabot requires `config.platform.php` in composer.json to work correctly.
This will avoid troubles like:
```
Problem 1
- Root composer.json requires solarium/solarium 6.3.5 -> satisfiable by solarium/solarium[6.3.5].
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
```
Relates: #3168
=> [TASK:11.5] Enable dependabot for all supported branches: Use PHP platform

composer.json
Dependabot requires `config.platform.php` in composer.json to work correctly.
This will avoid troubles like:
```
Problem 1
- Root composer.json requires solarium/solarium 6.3.5 -> satisfiable by solarium/solarium[6.3.5].
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
```
Relates: #3168
=> [TASK:11.6] Enable dependabot for all supported branches: Use PHP platform

composer.json
Dependabot requires `config.platform.php` in composer.json to work correctly.
This will avoid troubles like:
```
Problem 1
- Root composer.json requires solarium/solarium 6.3.5 -> satisfiable by solarium/solarium[6.3.5].
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
```
Relates: #3168
=> [TASK:12.0] Enable dependabot for all supported branches: Use PHP platform

.github/dependabot.yml, composer.json
Dependabot requires `config.platform.php` in composer.json to work correctly.
This will avoid troubles like:
```
Problem 1
- Root composer.json requires solarium/solarium 6.3.5 -> satisfiable by solarium/solarium[6.3.5].
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
- solarium/solarium 6.3.5 requires php ^8.0 -> your php version (7.4.33) does not satisfy that requirement.
```
Relates: #3168
=> [TASK] Enable dependabot for all supported branches: Use PHP platform

Documentation/Releases/solr-release-12-0.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 12.4 LTS, which mainly fixes 2 regressions introduced in version 12.0.4:
* [TASK] Re-added template variables
* [BUGFIX] Fix index queue clearance
* [TASK] Update to solarium/solarium 6.3.5
https://github.com/TYPO3-Solr/ext-solr/releases/tag/12.0.5
---
* Provide patches through pull requests or review and comment on existing pull requests
* Go to www.typo3-solr.com or call dkd to sponsor the ongoing development of Apache Solr for TYPO3
Support us by becoming an EB partner:
https://shop.dkd.de/Produkte/Apache-Solr-fuer-TYPO3/
or …
=> [RELEASE] 12.0.5

Classes/Controller/SearchController.php, Classes/ViewHelpers/SearchFormViewHelper.php, Tests/Integration/SearchTest.php, Tests/Unit/IndexQueue/AbstractIndexerTest.php, Tests/Unit/Middleware/SolrRoutingMiddlewareTest.php, Tests/Unit/ViewHelpers/Facet/Area/GroupViewHelperTest.php, Tests/Unit/ViewHelpers/SearchFormViewHelperTest.php
This change resolves deprecation errors in TYPO3 Fluid stack 
and fixes the search within TYPO3 13 dev state on 2024.08.30.
Relates: #3995
=> [FIX] deprecations for Fluid viewHelpers and stack

Tests/Unit/System/ContentObject/ContentObjectServiceTest.php
ContentObjectServiceTest class contained double space in `namespace` definition.
=> [FIX] CS issue in Tests\Unit\System\ContentObject\ContentObjectServiceTest

Classes/System/Url/UrlHelper.php
Fixes PhpStan-issue:
```
------ -----------------------------------------------------------------
Line   Classes/System/Url/UrlHelper.php
------ -----------------------------------------------------------------
52     Variable $parameters in empty() always exists and is not falsy.
------ -----------------------------------------------------------------
```
=> [BUGFIX] PhpStan Variable $parameters in empty() always exists and is not falsy

Classes/Report/SchemaStatus.php, Classes/Report/SolrConfigStatus.php, Classes/System/Url/UrlHelper.php, Tests/Integration/ConnectionManagerTest.php, Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php, Tests/Integration/IndexQueue/PageIndexerTest.php, Tests/Integration/IndexQueue/QueueTest.php, Tests/Integration/IndexQueue/RecordMonitorTest.php
* [FIX] follow-up for removed queue.[indexConfig].table TypoScript setting
* [FIX] wrong Schema version in status checks
* [TASK] skip tests for mount-pages temporary
* [TASK] skip tests for acces restrictions stack temporary
* [BUGFIX] PhpStan Variable $parameters in empty() always exists and is not falsy
=> [TASK] TYPO3 13 compatibility 2024.09.19

Classes/ContentObject/Multivalue.php, Classes/FrontendEnvironment/Tsfe.php, Classes/System/Configuration/ConfigurationManager.php
To allow indexing various environments have to be simulated, in TYPO3 13
the ContentObjectRenderer of TSFE has to initialized with the simulated
request and the request attribute 'frontend.typoscript' hat to be set.
=> [TASK] Adapt simulated environment for TYPO3 13

Documentation/FAQ/Index.rst
The list was not diplayed properly and the slack link wasn't redirecting. Tested the changes with: https://www.tutorialspoint.com/online_restructure_editor.php
If you open this page:
https://docs.typo3.org/p/apache-solr-for-typo3/solr/11.0/en-us/FAQ/Index.html
You'll notice the broken list as first item. Also the slack link doesn't work.
=> Fix formatting and update Slack link on FAQ

composer.json
This change is required for deprecated DB configs, which are migrated in https://github.com/TYPO3/testing-framework/commit/0c5ee0bc307765f2d77f4847eb24b31ab592bf1c
=> [TASK] Upgrade typo3/testing-framework to dev-main 2024.10.15

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-11-5.rst, Documentation/Settings.cfg, ext_emconf.php
This is a maintenance release for TYPO3 11.5 and the last release that supports Apache Solr 8.11.
Next EXT:solr release for TYPO3 11.5 will be 11.6.0, it will contain support for Apache Solr 9 and some breaking improvements.
This maintenance release for TYPO3 11.5 LTS contains:
- [TASK] Modify column changed to int(11) unsigned, in respect…
- [TASK] Full fixed french translation
- [TASK] Fix tests on 11.5.x @2024.05.07
- [BUGFIX:P:11.5] Cast pageType and suggestPageType to int in SearchFormViewHelper
- [BUGFIX] Typos in last FR translation PR
- [BUGFIX:P:11.5] Fix range string calculation in DateRange facet
- [BUGFIX:11.5] scheduler task "Optimize index of a site" is not functional
- [TASK] Apache Solr 8.11.4 compatibility …
=> [RELEASE] 11.5.7

Classes/Controller/SuggestController.php, Configuration/TypoScript/Examples/Suggest/setup.typoscript, Resources/Public/JavaScript/suggest_controller.js, Tests/Integration/Controller/SuggestControllerTest.php
This change removes the callback logic
in the Suggest AJAX Call via JSONP, as JSONP
is known to be used to call untrusted third-party
code, and can thus be removed, as custom suggest
code is done anyway via custom JS implementations.
See https://en.wikipedia.org/wiki/JSONP#Security_concerns
See if suggest still works as expected.
=> [TASK] Remove JSONP callback in suggest

Classes/Domain/Search/SearchRequest.php
This introduce a new method that removes the query-string from `SearchRequest`. Other active filters e.g. selected categories are not removed from `SearchRequest`.
This is especially usefull when `allowEmptyQuery` is set in TS-config:
```
plugin.tx_solr {
search {
query {
allowEmptyQuery = 1
}
}
```
This can be used in a custom `ViewHelper`:
```php
class RemoveQueryViewHelper extends AbstractUriViewHelper
{
/**
* @param array $arguments
* @param \Closure $renderChildrenClosure
* @param RenderingContextInterface $renderingContext
* @return string
*/
public static function renderStatic(array $arguments, \Closure $renderChildrenClosure, RenderingContextInterface $renderingContext)
{
$newRequest = static::getUsedSearchRequestFromRenderingContext($renderingContext)
->getCopyForSubRequest() …
```
=> Introduce method to remove the query-string from search-request

Classes/ConnectionManager.php, Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php, Classes/Domain/Site/Site.php, Classes/Domain/Site/SiteRepository.php, Classes/Report/SolrStatus.php, Classes/System/Configuration/ConfigurationManager.php, Classes/System/Records/Pages/PagesRepository.php, Classes/System/Util/SiteUtility.php, Configuration/Backend/Modules.php, Tests/Integration/GarbageCollectorTest.php, Tests/Unit/ConnectionManagerTest.php
Garbage collector and RecordMonitor triggered by RecordMonitor 
do not have infos about PID or Site. 
This change contains first step for refactoring of configuration retrieval. 
The delegation of TypoScriptConfiguration object, which will be moved to strict aggregation structure.
Fixes: #4203, #4207, #4208
Relates: #3995
=> [FIX] Garbage collector does not get configuration

Classes/Domain/Index/PageIndexer/PageUriBuilder.php, Classes/Domain/Index/Queue/UpdateHandler/AbstractUpdateHandler.php, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/Domain/Index/Queue/UpdateHandler/GarbageHandler.php, Classes/System/Configuration/ConfigurationManager.php, Documentation/FAQ/Index.rst, Documentation/Releases/solr-release-13-0.rst, Tests/Integration/ConnectionManagerTest.php, Tests/Integration/Fixtures/connection_basic.csv, Tests/Integration/Fixtures/connection_for_mounted_page.csv, Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_mounted_page_from_another_site.csv, Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_multiple_mounted_page.csv, Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_with_additional_fields_into_solr.csv, Tests/Integration/IndexQueue/FrontendHelper/Fixtures/does_not_die_if_page_not_available.csv, Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/DataUpdateHandlerTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/GarbageHandlerTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/SetUpUpdateHandler.php, composer.json, ext_emconf.php
Mount point indexing and corresponding tests have been adjusted for
TYPO3 13. Mount points are supported in general and the mounted pages
will be indexed like standard pages.
But there are some points to consider:
*   Cross-site mounts require that `config.index_enable = 1` is set
in the pagetree of the mounted page, as TYPO3 loads the
TypoScript of the mounted page.
This is probably a bug in the TYPO3 core and may change, due to
changes in RootlineUtility->generateRootlineCache() the mount page
pid isn't used any more.
*   Pages in a pagetree without a site configuration cannot be
indexed, in fact TYPO3 currently can't mount a page from a page
tree without a site configuration and an exeception occurs.
Test procedure in PageIndexerTest has been improved and now uses
the PageUriBuilder to …
=> [TASK] Adjust mount point indexing

Classes/EventListener/Extbase/PersistenceEventListener.php, Classes/Search/FacetingComponent.php, Classes/Search/LastSearchesComponent.php, Classes/Search/StatisticsComponent.php, Configuration/Services.yaml
All entries in Services.yaml become the `shared` setting dependent on its implementation and context.
All non-Singleton-Like classes are set to `shared: false` which could stuck with objects states:
* on Builder-Objects
* on Query-Objects
* on other object, those state change is not global relevant
Some classes were commented and notated with todos.
Relates: #3995
Fixes: #4183, #4246
---
=> [TASK] Evaluate all entries in Services.yaml regarding to `shared` setting

Classes/Controller/Backend/Search/InfoModuleController.php, Classes/Domain/Search/Statistics/StatisticsFilterDto.php, Classes/Domain/Search/Statistics/StatisticsRepository.php, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/Backend/Search/InfoModule/Index.html, Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
Relates: #4228
Backport for TYPO3v11
Adds a time frame filter in the statistics module.
Per default the typoscript constants are used, which are then overwritten by the selected timeframe.
Go to the statistics module and select the desired timeframe
Fixes: #4228
=> [FEATURE] Add timeframe filter to statistics module

Classes/Controller/Backend/Search/InfoModuleController.php, Classes/Domain/Search/Statistics/StatisticsFilterDto.php, Classes/Domain/Search/Statistics/StatisticsRepository.php, Resources/Private/Language/locallang.xlf, Resources/Private/Templates/Backend/Search/InfoModule/Index.html, Resources/Public/JavaScript/SearchStatistics.js, Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
Backport for TYPO3v12
Adds a time frame filter in the statistics module.
Per default the typoscript constants are used, which are then overwritten by the selected timeframe.
Go to the statistics module and select the desired timeframe
Fixes: #4228
=> [FEATURE:BP:12.0] Add timeframe filter to statistics module

Classes/Controller/Backend/Search/IndexQueueModuleController.php
In multi site setups a null pointer exception is thrown when opening the Index Queue TYPO3 module without having a solr-enabled page selected in the page tree. The NPE is thrown in `::initializeAction()` before the original handling of the "no site selected" case in `::indexAction()`.
Fixes: 3ea271319 ("[TASK:BP:11.6] Consider queue initialization status")
Brings back the existing "No site could be found."  error message to the Index Queue TYPO3 module.
Open the Index Queue TYPO3 module in an PHP 8.2, TYPO3 v11.5.41, EXT:solr v11.6.0 installation, that contains at least two sites with solr enabled. Select the root page (imaginary page with uid=0) in the page tree.
=> [BUGFIX] NPE in Index Queue module when no site is selected

Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/Node.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/NodeTest.php
Currently, the GetHasChildNodeSelected function in \ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Hierarchy\Node only checks whether a direct child is selected. With hierarchical filters, however, it makes sense to check whether any child is selected in this hierarchy branch. E.g. because this should be expanded in the frontend.
```html 
<f:if condition="{childNode.hasChildNodeSelected}">
<f:variable name="detailsState" value="open" />
</f:if>
```
The PR implements this recursive check.
Fixes: #4155
=> [BUGFIX] Make getHasChildNodeSelected recursive

Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/Node.php, Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/NodeTest.php
Currently, the GetHasChildNodeSelected function in \ApacheSolrForTypo3\Solr\Domain\Search\ResultSet\Facets\OptionBased\Hierarchy\Node only checks whether a direct child is selected. With hierarchical filters, however, it makes sense to check whether any child is selected in this hierarchy branch. E.g. because this should be expanded in the frontend.
```html 
<f:if condition="{childNode.hasChildNodeSelected}">
<f:variable name="detailsState" value="open" />
</f:if>
```
The PR implements this recursive check.
Fixes: #4155
Ports: #4156
=> [BUGFIX:P:main] Make getHasChildNodeSelected recursive

Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php
By fixing this issue (https://github.com/TYPO3-Solr/ext-solr/issues/4107), the ConfigurationAwareRecordService no longer uses BackendUtility::getRecord(). As a result, the default Restrictions are now applied to the query.
If you have an already published and indexed article and modify the startdate to schedule the article for future publication, the queue item will be deleted and not reinserted due to the StarttimeRestriction, which removes the item from the result list.
In EXT:solr v11, the behavior is different. After modifying the start date, the item will be deleted from tx_news_domain_model_news and reinserted for further indexing.
Relates: #4168
Fixes: #4176
---
=> [BUGFIX] Add StartTimeRestriction to ConfigurationAwareRecordService

Classes/Controller/Backend/Search/AbstractModuleController.php, Classes/Domain/Site/SiteRepository.php, Classes/Report/SiteHandlingStatus.php, Tests/Unit/Domain/Site/SiteRepositoryTest.php
Use PHP generator with yield to process just the available sites needed How to test
With over 300 root pages it needs over 30 seconds to build up all available sites. With help of a PHP generator we can stop processing all available sites if just the first site is requested. It's also helpful to just check, if there are available sites.
This should speed up performance a lot.
* Remove cache storing from <has> methods of SiteRepository
* Use hasAvailableSites in ModuleController
* Remove cache-set check from tests for SiteRepository
* Move check for duplicate sites to getAvailableSites. PhpStan
Fixes: #3939
Replaces: #4154
=> [FEATURE] Use PHP generator to prevent processing of all available site

Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php, Classes/IndexQueue/AbstractIndexer.php
TYPO3 BE context properties from `$GLOBALS['TYPO3_REQUEST']` is used on actions  from TYPO3 BE modules.
Most probably no usage of `$GLOBALS['TYPO3_REQUEST']` in EXT:solr context required at all,  but leaving it for possible page-indexing context, which it is just fine to use original TYPO3 core bootstrapped FE stack.
Fixes: #4221
Relates: #3995
=> [FIX] Indexing fails with SOLR_* cObj in TypoScript

Classes/System/Solr/SolrConnection.php
By editing records in BE TypoScript settings are not resolvable due of  missing propagation of `TypoScriptConfiguration` object on
* `\ApacheSolrForTypo3\Solr\System\Solr\SolrConnection::buildReadService()`
* `\ApacheSolrForTypo3\Solr\System\Solr\SolrConnection::buildWriteService()`
Relates: #3995
=> [FIX] missing TypoScript configuration on RecordMonitor stack

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/IndexQueue/Initializer/Page.php, Classes/IndexQueue/RecordMonitor.php, Classes/Traits/SkipRecordByRootlineConfigurationTrait.php, Tests/Integration/IndexQueue/Fixtures/mount_page_updates.csv, Tests/Integration/IndexQueue/RecordMonitorTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/DataUpdateHandlerTest.php, Tests/Unit/ViewHelpers/Uri/Facet/AddFacetItemViewHelperTest.php, Tests/Unit/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelperTest.php
EXT:solr fails to detect changes on mounted pages correctly in some special occasions:
* mounted pages not considered during garbage removal / ce updates
* no_search_sub_entries flag not respected by GarbageRemover
strategies
* existing queue items of mounted pages not updated
By adjusting the monitoring related components the issues are fixed,
affected components:
* GarbageRemover strategies
* page initializer
* RecordMonitor
* DataUpdateHandler
- Mount a page located in a sys_folder with enabled option no_search_sub_entries
- Test updates of page and content elements and check the index queue updates
Fixes: #4275
=> [BUGFIX] Fix monitoring of mounted pages

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/IndexQueue/Initializer/Page.php, Classes/IndexQueue/RecordMonitor.php, Classes/Traits/SkipRecordByRootlineConfigurationTrait.php, Tests/Integration/IndexQueue/Fixtures/mount_page_updates.csv, Tests/Integration/IndexQueue/RecordMonitorTest.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/DataUpdateHandlerTest.php, Tests/Unit/ViewHelpers/Uri/Facet/AddFacetItemViewHelperTest.php, Tests/Unit/ViewHelpers/Uri/Facet/RemoveAllFacetsViewHelperTest.php
EXT:solr fails to detect changes on mounted pages correctly in some special occasions:
* mounted pages not considered during garbage removal / ce updates
* no_search_sub_entries flag not respected by GarbageRemover
strategies
* existing queue items of mounted pages not updated
By adjusting the monitoring related components the issues are fixed,
affected components:
* GarbageRemover strategies
* page initializer
* RecordMonitor
* DataUpdateHandler
- Mount a page located in a sys_folder with enabled option no_search_sub_entries
- Test updates of page and content elements and check the index queue updates
Fixes: #4275
=>  [BUGFIX:P:13.0] Fix monitoring of mounted pages

Classes/Domain/Site/SiteRepository.php
If there's no solr configuration for any site, saving pages or content results in a PHP exception:
Uncaught TYPO3 Exception: Cannot traverse an already closed generator | Exception thrown in file .../Classes/Domain/Site/SiteRepository.php in line 135
The added check prevents this error.
Fixes: #4284
=> [BUGFIX] Add check if generator is valid before traversing it

.github/workflows/ci.yml, Build/Test/cibuild_docker.sh
Currently on Apache Solr 9.8.0 the cores can not boot up, because of
```
Plugin init failure for [schema.xml] fieldType "string_collated": Error loading class 'solr.ICUCollationField'
```
but the tests suite does not fail at all.
This change fixes the issue, which was caused by `prettyPrintOrExitOnError 0`
Ports: f52a50ec from #4290
---
Following actions jobs must succeed:
=> [FIX] docker image tests do not fail if core can not start

Documentation/Configuration/Reference/ExtensionSettings.rst
I was surprised to not see the actual integer values of the other two options in the documentation of `monitoringType`.
=> [DOCS] Actually mention the values of monitoringType

Classes/FrontendEnvironment/Tsfe.php
initialize TSFE should set contentFromPid in PageInformation because ContentObjectRenderer calls getContentFromPid method
=> [BUGFIX] set PageInformation contentFromPid

Classes/Controller/SuggestController.php, Configuration/TypoScript/Examples/Suggest/setup.typoscript, Documentation/Releases/solr-release-12-0.rst, Resources/Public/JavaScript/suggest_controller.js, Tests/Integration/Controller/SuggestControllerTest.php
This change removes the callback logic
in the Suggest AJAX Call via JSONP, as JSONP
is known to be used to call untrusted third-party
code, and can thus be removed, as custom suggest
code is done anyway via custom JS implementations.
See https://en.wikipedia.org/wiki/JSONP#Security_concerns
Fixes: #2556
Ports: #4201
=> !!![TASK] Remove JSONP callback in suggest

Classes/Domain/Search/Score/ScoreCalculationService.php
Fix exception
```
Exception: PHP Warning: Undefined array key 0 in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Domain/Search/Score/ScoreCalculationService.php line 101, in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:141 - {"exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key 0 in /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Domain/Search/Score/ScoreCalculationService.php line 101
```
Ports: #4253
=> [BUGFIX:BP:12.0] Fix notice exception in ScoreCalculationService

Classes/Domain/Site/SiteRepository.php, Classes/Event/Site/AfterDomainHasBeenDeterminedForSiteEvent.php, Tests/Unit/Domain/Site/SiteRepositoryTest.php
When running the TYPO3 backend on a different domain the the TYPO3 frontend via a hostVariant it is impossible to get the correct domain in the backend. This has an impact on indexing, clearing the index, and much more. This event allows to modify the domain used for a site.
Adds an event that allows to modify the domain used for a site.
Use an EventListener to modify that domain.
Fixes: #4265
=> [FEATURE] Add an event for modifying the domain used for a site

Build/Test/cibuild_docker.sh
Missing volume creation after cleanup led to missing logs in build artifacts from Docker container run for modified container.
---
=> [FIX] Docker tests suite does not contain all logs

Docker/SolrServer/Dockerfile, Docker/SolrServer/docker-entrypoint-initdb.d-as-sudo/fix-CVE-2025-24814.sh, Docker/SolrServer/docker-entrypoint-initdb.d/0_as-sudo-tweaks.sh, Documentation/GettingStarted/Solr.rst, Documentation/Releases/solr-release-13-0.rst, Resources/Private/Solr/solr.xml
Previously the absolute paths were used for `typo3lib` `solr.xml` file, 
this works on Docker and few linux-distributions. 
Using relative path, will allow to use the EXT:solr config sets in all possible installation variants.
---
=> [TASK] Use relative path to typo3lib in Apache Solr config

Docker/SolrServer/Dockerfile, Docker/SolrServer/docker-entrypoint-initdb.d-as-sudo/fix-CVE-2025-24814.sh, Docker/SolrServer/docker-entrypoint-initdb.d/0_as-sudo-tweaks.sh, Documentation/GettingStarted/Solr.rst, Documentation/Releases/solr-release-12-0.rst, Resources/Private/Solr/solr.xml
Previously the absolute paths were used for `typo3lib` `solr.xml` file,
this works on Docker and few linux-distributions.
Using relative path, will allow to use the EXT:solr config sets in all possible installation variants.
Ports: #4310
=> [TASK:BP:12.0] Use relative path to typo3lib in Apache Solr config

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-12-0.rst, Documentation/Releases/solr-release-13-0.rst, Documentation/guides.xml, ext_emconf.php
This is a security release for TYPO3 12.4 LTS, containing:
* !!![SECURITY] Update to Apache solr 9.8.0 : CVE-2025-24814
* and other fixes
* https://github.com/TYPO3-Solr/ext-solr/releases/tag/13.0.1
* https://docs.typo3.org/p/apache-solr-for-typo3/solr/13.0/en-us/Releases/solr-release-13-0.html#release-13-0-1
---
* Provide patches through pull requests or review and comment on existing pull requests
* Go to www.typo3-solr.com or call dkd to sponsor the ongoing development of Apache Solr for TYPO3
Support us by becoming an EB partner: …
=> [RELEASE] 13.0.1

.github/ISSUE_TEMPLATE/bug_report.md, Documentation/Releases/solr-release-12-0.rst, ext_emconf.php
This is a security release for TYPO3 12.4 LTS, containing:
* !!![SECURITY] Update to Apache solr 9.8.0 : CVE-2025-24814
* !!![TASK] Remove JSONP callback in suggest
* and other fixes
* https://github.com/TYPO3-Solr/ext-solr/releases/tag/12.0.6
* https://docs.typo3.org/p/apache-solr-for-typo3/solr/12.0/en-us/Releases/solr-release-12-0.html#release-12-0-6
---
* Provide patches through pull requests or review and comment on existing pull requests
* Go to www.typo3-solr.com or call dkd to sponsor the ongoing development of Apache Solr for TYPO3
Support us by becoming an EB …
=> [RELEASE] 12.0.6

Classes/System/Configuration/ExtensionConfiguration.php
Excluding the `_` parameter from cHash to solve the issue for auto-suggest component by TYPO3 instances with enabled [enforceValidation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CachingFramework/Index.html#confval-enforcevalidation) setting.
Fixes: #3919
=> [BUGFIX] 404 on auto-suggest with enabled TYPO3 enforceValidation setting

Classes/System/Configuration/ExtensionConfiguration.php
Excluding the `_` parameter from cHash to solve the issue for auto-suggest component by TYPO3 instances with enabled [enforceValidation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CachingFramework/Index.html#confval-enforcevalidation) setting.
Fixes: #3919
Ports: #4318
=> [BUGFIX:BP:12.0] 404 on auto-suggest with enabled TYPO3 enforceValidation setting

Tests/Unit/ViewHelpers/Backend/IsStringViewHelperTest.php
Fixes PhpUnit `IsStringViewHelperTest` for typo3fluid/fluid v 4.1.+.
=> [BUGFIX] PhpUnit IsStringViewHelperTest for typo3fluid/fluid v 4.1.+

Classes/Task/ReIndexTaskAdditionalFieldProvider.php
The existing file path wouldn't work with composer installation and the directory is not correct either.
This pull request updates the path to use an extension-relative EXT: path instead.
=> Update hardcoded legacy css resource filepath

Tests/Integration/GarbageCollectorTest.php, Tests/Integration/IndexQueue/RecordMonitorTest.php, Tests/Integration/Task/EventQueueWorkerTaskTest.php
TYPO3 13.4.x-dev requires mocking of Scheduler components since: https://github.com/TYPO3/typo3/commit/9b9861bc7dc3ab2c323278190c91cf51813e1ce4
=> [TASK] fix integration tests for TYPO3 13.4.10+

.github/workflows/ci.yml
This PR also updates all required actions in .github/workflow/ci.yml and adds a new publish-docker-hub job to the pipeline.
Fixes: #2891
Replaces: #3501
=> [FEATURE] Add arm64 and ppc64le platforms to docker-images

Resources/Private/Partials/Search/Form.html
inserting `maxlength="50"` to input field of search form 
focus a search field with active auto suggest function. hold down the space key and fill the input field with spaces.
before:
watch the server log as requests with longer and longer search string appear until the server is locked up
after: 
just a few request appear as after 50 characters no further changes to the input text appear and trigger further AJAX requests
Fixes: #4341
=> #4341 Form.html: maxlength for search text input field

.github/workflows/ci.yml
This PR also updates all required actions in .github/workflow/ci.yml and adds a new publish-docker-hub job to the pipeline.
Fixes: #2891
Replaces: #3501
Ports: #4359
=> [FEATURE:P:12.0] Add arm64 and ppc64le platforms to docker-images

.github/dependabot.yml
The release-11.6.x branch was locked and moved to non public ELTS repository. No merges are possible against release-11.6.x, therefore the dependabot PRs against that branch are useless.
Relates: #4333
=> [TASK] disable dependabot on release-11.6.x branch

Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php, Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php, Classes/Domain/Index/Queue/QueueItemRepository.php, Classes/Domain/Index/Queue/RecordMonitor/Helper/MountPagesUpdater.php, Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php, Classes/Domain/Site/Site.php, Classes/IndexQueue/Initializer/Page.php, Classes/IndexQueue/PageIndexer.php, Tests/Integration/Fixtures/mount_page_garbage.csv, Tests/Integration/Fixtures/translated_mount_page_garbage.csv, Tests/Integration/GarbageCollectorTest.php, Tests/Integration/IndexQueue/RecordMonitorTest.php, Tests/Integration/IntegrationTestBase.php, Tests/Unit/Domain/Index/Queue/UpdateHandler/DataUpdateHandlerTest.php, Tests/Unit/IndexQueue/PageIndexerTest.php
EXT:solr failed to delete indexed mounted pages if a mount point is deleted or deactivated, this issue is fixed by extending the PageStrategy.
Additionally it's ensured, that changes to the slug of a mount page triggers a reindexing of the mounted pages as the indexed slug has become invalid.
Resolves: #4314
=> [BUGFIX] Fix mount point garbage collection

Classes/IndexQueue/AbstractIndexer.php
Since the first versions of EXT:solr the AbstractIndexer contains a workaround allowing to use IMAGE cObj in indexing configuration. To resolve an issue determining the image file, the current work directory is changed to the public web folder.
This workaround is no longer required and thus removed.
Ports: #4377
Resolves: #4374
=> [TASK:BP:12] Drop workaround for cObj IMAGE

Classes/ContentObject/Relation.php
Set `''` as third parameter `$defaultValue` for `$contentObject->stdWrapValue()` as fallback
Fixes: #4381
=> Avoid PHP warning if related record was not found

Classes/Event/IndexQueue/AfterIndexQueueHasBeenInitializedEvent.php
AfterIndexQueueHasBeenInitializedEvent requires AbstractInitializer instead of the interface IndexQueueInitializer, this prevents the usage of own implementations not based on the abstract initializer, e.g. an initializer for external data.
By requiring the interface instead of the AbstractInitializer this issue is fixed.
Resolves: #4402
=> [BUGFIX] Allow initializer interface in event

Classes/Domain/Search/ApacheSolrDocument/Builder.php, Classes/Eid/ApiEid.php, Tests/Unit/Domain/Search/ApacheSolrDocument/BuilderTest.php
This change
* adds the fields to the documents, which will be renamed to native fields without `_stringS` in EXT:solr 13.1.x+:
* `typo3Context_stringS`
* `domain_stringS`
* adds `typo3Context` as response data of ApiEid, to be able to set that field by external index writers
Relates: #4411
Ports: #4413
---
Fixes: #3459
Ports: #4413
=> [FEATURE:BP:12.0] add typo3Context[_stringS] and domain[_stringS] fields to documents

Classes/Domain/Search/ApacheSolrDocument/Builder.php, Classes/Eid/ApiEid.php, Tests/Unit/Domain/Search/ApacheSolrDocument/BuilderTest.php
This change
* adds the fields to the documents, which will be renamed to native fields without `_stringS` in EXT:solr 13.1.x+:
* `typo3Context_stringS`
* `domain_stringS`
* adds `typo3Context` as response data of ApiEid, to be able to set that field by external index writers
Relates: #4411
Fixes: #3459
* **Don't squash**
=> [FEATURE] add typo3Context[_stringS] and domain[_stringS] fields to documents
