- ext_tables.php
Move the addSingleIcons() outside of the TYPO3_MODE == 'BE'
to assure that the icons in the BE module are always visible.
Also when configuration cache is build by frontend call.
> [BUGFIX] Always load sprite icons

- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/IndexQueueModule/Index.html
- ext_tables.php
It is not possible to reset the error currently.
This pull request add an button to the backend module to flush the error field.
> [FEATURE] Add flush errors button to backend module

- PiResults/FrequentSearchesCommand.php
While the check for the root page id or language is present for the sql query generation, it wasn't taken into account for the cache identifier generation. This fixes the problem of items from other language or sites being shown out of the cache.
> [BUGFIX] Do not show frequent search terms from other languages or sites in a multisite environment

- Classes/FieldProcessor/Service.php
- Classes/FieldProcessor/TimestampToUtcIsoDate.php
- Classes/Util.php
- Configuration/TypoScript/Solr/setup.txt
- ext_autoload.php
this is especially important for endtime because otherwise
DocExpirationUpdateProcessorFactory might be too early
or too late in removing a document
> [BUGFIX] endtime has to be indexed in UTC (3.1.x)

- Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
- Configuration/TypoScript/Examples/IndexQueueNewsAdditional/setup.txt
- ext_tables.php
The SOLR_RELATION for the EXT:news field "content_elements" in Configuration/TypoScript/Examples/IndexQueueNews/setup.txt should be disabled by default since it depends on the activation of this feature in EXT:news configuration in EM (records.contentElementRelation) where it is disabled by default.
Related to [Forge issue #50146](https://forge.typo3.org/issues/50146).
> [TASK] moves indexing of additional news content elements to separate TypoScript template

- Classes/Facet/HierarchicalFacetHelper.php
* Added '/' as separator to menu entry prefix
to prevent wrong assignments. Before 2-144/27/28 would be assigned
as child of 1-144/2, not only 2-144/27.
> [BUGFIX] Fixed menu generation for facets.

- Classes/Template.php
With commit bf74217 there was a patch by Stefan Galinsiki merged which he authored 2012-07-26.
A year later (2013-08-19), Ingo Renner introduced patch cc79a22b with `escapeMarkers()`.
Thus `$value = str_replace('#', '&#35;', $value);` seems to be superfluous. Furthermore it creates problems with the field `fileReferenceUrl` which is used by EXT:solrfal. This field stores URLs with anchor links which break with this str_replace.
> [BUGFIX] remove superfluous replacement of #

- Classes/Facet/SimpleFacetRenderer.php
- Classes/SolrService.php
- Classes/SpellChecker.php
- composer.json
The ManagedSynonymsFilterFactory was moved from indexAnalyzer to
queryAnalyzer, therefore we must look there in the schema in order
to determine the language.
Resolves: #65676
Change-Id: I63e99c240f0d019dc411d7fe56204b273e1d715c
> [BUGFIX] ManagedSynonyms language determination

- Resources/Shell/install-multi-solr-existing-tomcat.sh
- Resources/Shell/install-solr-existing-tomcat.sh
We needed to setup this with a Tomcat 7 and had to change all this values. It maybe handy to do this just in one place.
Originally opened at https://github.com/TYPO3-extensions/solr/pull/6
> Store Tomcat version in own value, for easy replacement

- Classes/Backend/SolrModule/AdministrationModuleManager.php
- Classes/Controller/AdministrationController.php
- Classes/Service/ModuleDataStorageService.php
Since 6.1 the method "create" in the objectManager has been
marked as deprecated.
The method "get" is available, with the same purpose.
Fixes #17
> [TASK] Avoid using deprecated methods in objectmanager

- Classes/IndexQueue/FrontendHelper/AuthorizationService.php
The getUser() method in the frontend helper
Tx_Solr_IndexQueue_FrontendHelper_AuthorizationService
returns a zero interger as UID in the user data array to prevent
database errors during the session initialization.
Resolves issue #35
> [BUGFIX] Return zero as UID in the Frontend authorization service

- Classes/ContentObject/Relation.php
The RelationHandler doesn't respect enableFields of the table
behind the MM-relation. Because this has been in place for quite a
long time. A new option *respectEnablefieldsMM* is introduced, which
can be set as configuration parameter when using SOLR_RELATION to
filter e.g. hidden categories.
Resolves [#65692](https://forge.typo3.org/issues/65692)
> [TASK] SOLR_RELATION respect enableFields on MM-related records

- ext_tables.php
using the old style definition, backend crashes on "new content element" dialog
> ext_table.php 7.3.x compat

- Classes/Typo3PageIndexer.php
Backslashes before the FQCN are not allowed any more in TYPO3 7.
> Remove backslash at the beginning of makeInstance parameter

- composer.json
In the typo3/cms-core version constraint, "~6.2.14" is used. That resolves to >=6.2.14 <6.3.0. We should use >=6.2.14 instead.
> [BUGFIX] Fix version constraint for typo3/cms-core

- Classes/Template.php
Fixes the view helper class prefix from lowercase **tx_solr** to ucwords **Tx_Solr**.
Change-Id: I17dc1ed41bfe3f3f8ce24b7a1b3895caa697f3ab
> Fix view helper class name prefix case

- composer.json
In 7.5.x the new class alias loader is used which requires Migration maps to be added differently.
I kept the old section because in 6.x the old one still applies and added the new one additionally.
> [BUGFIX] migration map loading in 7.5.x

- Classes/ContentObject/Relation.php
Please see https://forge.typo3.org/issues/66179 for details.
I am not sure if the dupe check at the end is needed any longer here, in the maintenance release from TER it is in, in your master branch it's gone. Maybe this is done in a different function now or has been removed.
> [BUGFIX] Implement enableRecursiveValueResolution for MM relations

- Classes/Backend/IndexingConfigurationSelectorField.php
In 7.5 the selectorfield does not accept a comma separated list anymore but requires an array of values.
> [BUGFIX] correctly render selected items for 7.5 in index queue selector

- Classes/IndexQueue/AbstractIndexer.php
- Classes/Util.php
I think it would be better to call settingLocale when initializing tsfe, therefore it will also not be required to be called in AbstractIndexer.
> [TASK] Util::initializeTsfe call settingLocale

- Classes/Access/Rootline.php
- Classes/IndexQueue/PageIndexer.php
Tx_Solr_Access_Rootline::getAccessRootlineByPageId() now accepts
an additional parameter for the current mount point.
In the page indexer the mount point parameter is used to build
correct access rootlines for mounted pages.
> [BUGFIX] Respect mount point in access rootline

- Classes/FieldProcessor/PageUidToHierarchy.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/Typo3PageIndexer.php
- Classes/Util.php
The mount parameter that is used to access a page is now passed on
to the page indexer and will be added to the page document ID if
it is not empty. This allows a page to appear multiple times in the
index in its different mount point contexts.
> [BUGFIX] Use mount point parameter in page document ID

- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/RecordMonitor.php
- ext_tables.sql
The handling of mount points of pages is improved. A unique identifier
for the different mount points is added to prevent overriding
existing data in the index queue item table when there are multiple
mount points pointing to the same page.
> [BUGFIX] Handling of multiple mount points to the same page

- Classes/IndexQueue/RecordMonitor.php
- Configuration/TypoScript/Solr/setup.txt
When a page is stored in the Backend and a mount point page points
to it with overlay enabled the record monitor will now also add
the overlayed page to the index queue.
Pages with disabled mount point overlay will now be indexed as
normal pages by adjusting the default additionalWhereClause config
option.
> [BUGFIX] Respect overlay settings of mount points

- Classes/Util.php
As settingLocale sets locale setting by using setlocale we alson eed to call it when retrieving TSFE from cache.
> [BUGFIX] settingLocale also needs to be called when retrieving TSFE from cache

- Classes/ContentObject/Relation.php
The foreign_match_fields configuration of foreign tables is now
considered in the SOLR_RELATION content object.
> [FEATURE] foreign_match_fields in SOLR_RELATION content object

- Classes/Template.php
If you use composer in TYPO3 CMS 7.x without legacy classes you get an exception because class can not found
> [BUGFIX] Load Viewhelper by Namespace if old class name not exist

- Classes/Backend/IndexingConfigurationSelectorField.php
The operator used in ``version_compare()`` is surrounded by spaces which leads ``version_compare()`` to return null.
> [BUGFIX] Fix invalid operator in version_compare

- Classes/Facet/UsedFacetOptionsRenderer.php
- Classes/Facet/UsedFacetRenderer.php
Added hook to overwrite the label of a used facet. Can be used like this:
```php
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['processUsedFacetText'][] = 'MyClass';
```
> [TASK] Implement hook in UsedFacetRenderer 

- Classes/PingFailedException.php
- Classes/Report/SolrStatus.php
- Classes/SolrService.php
* Refactored Report to be more robust
* Added method "getPingRoundTripRuntime" to get the timing value of a ping
* Fixed getSolrconfigName when provided config file is no valid XML
> [BUGFIX] #114 PingQueryTime in report is allways 1000ms

- Classes/Query/LinkBuilder.php
Since a2ff9e4c085cdd019cd245445407d0edc3f1e52e the rendered
link in the hidden url field is wrong because $queryGetParameter
is appended now instead of prepended like before in getQueryUrl().
This broke the generated url for numericRange facets with a query
keyword.
This patch restores the prior parameter order from getQueryUrl() in
getQueryLink().
Resolves: #104
> [BUGFIX] Restore behaviour of getQueryUrl in getQueryLink

- Classes/Task/IndexQueueWorkerTask.php
As mentioned in https://github.com/TYPO3-Solr/ext-solr/issues/132
HTTP_HOST is used by default for typolink in ContentObjectRenderer (also 6.2), see:
https://git.typo3.org/Packages/TYPO3.CMS.git/blob/refs/heads/TYPO3_6-2:/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#l6042
So it should also be set without realurl
> [TASK] initializeHttpHost without realurl

- Classes/JavascriptManager.php
Applied patch from review.typo3.org (https://review.typo3.org/#/c/29747/4/typo3/sysext/frontend/Classes/Page/PageGenerator.php)  also on JavascriptManager.php
Fixes #135
> config.absRefPrefix = auto not handled correct by JavascriptManager #135

- Classes/Util.php
It is necessary to clean up TSFE object if initializeTsfe = false, otherwise checks regarding existing TSFE object in Backend will produce the wrong result (e.g. \TYPO3\CMS\Rtehtmlarea\RteHtmlAreaApi::writeTemporaryFile).
For instance, in 7.6.0 if one has a text element with RTE and saves (without closing) the linkhandler will not open as the generated url is missing the necessary ../
> [BUGFIX] cleanup TSFE if initializeTsfe = false

- Classes/Backend/IndexInspector/IndexInspectorRemoteController.php
- Classes/Plugin/Results/ResultsCommand.php
- Classes/Search.php
- Classes/Template.php
- Configuration/TypoScript/Solr/setup.txt
Implemented escaping of fields directly after retrieval from solr and added configuration for fields that should not be escaped "plugin.tx_solr.search.skipEscapeFields". And also removed htmlspecialchar calls from Template.php
Fix for issue #122
> [BUGFIX] Move escaping from Template.php to the point right after the retrieval from solr

- Classes/IndexQueue/PageIndexerRequest.php
Assign the pid of the currently processed record to the undefined ``$pageId`` variable.
> [BUGFIX] Assign undefined variable $pageId

- ext_emconf.php
Fixes failed installation in non composer mode on 7.6.0
> [BUGFIX] Added missing trailing namespace back slashes.

- Classes/Task/IndexQueueWorkerTask.php
Usefull to add postprocessing after the indexing. Some cache clearing in my case.
> [FEATURE] Add signal after IndexQueueWorkerTask::indexItems

- Classes/AbstractDataHandlerListener.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/RecordMonitor.php
- Configuration/TypoScript/Solr/setup.txt
- Tests/Build/IntegrationTests.xml
- Tests/Build/UnitTests.xml
- Tests/Integration/Fixtures/can_collect_garbage_from_subPages_when_page_is_set_to_hidden_and_extendToSubpages_is_set.xml
- Tests/Integration/Fixtures/can_collect_garbage_from_subPages_when_page_is_set_to_hidden_and_extendToSubpages_is_set_multiple_subpages.xml
- Tests/Integration/Fixtures/can_queue_a_page_and_remove_it_with_the_garbage_collector.xml
- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IndexQueue/Fixtures/queue_is_not_filled_when_item_is_set_to_hidden.xml
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_extendToSubpages_set_and_hidden_removed.xml
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_hidden_set_and_extendToSubpage_removed.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
Added functionality apply recursive changes in RecordMonitor and GarbageCollector when a combination of values in the Record and ChangeSet match to a configured configuration.
* Added tests for RecordMonitor and GarbageCollector
* Implemented recursive indexing and deletion, when "extendToSubpage" and "hidden" occures in the relevant combination
* Refactored RecordMonitor and GarbageCollector to have a shared BaseClass "AbstractDataHandlerListener"
Fixes: #53
> [Bugfix] Added functionallity to resolve affected pages when "extendToSubpages" is set and "hidden" flag is changed

- Classes/Util.php
- Remove Util::getFileDocumentId because it is only needed by solrfile
Fixes #85
> Removed "Util::getFileDocumentId" because it is only required by solrfile which is not working with TYPO3 >= 6

- ext_tables.php
The TYPO3 backend throws an error the ClearCacheActionsHookInterface
has to be implemented. This is resolved by adding the class identifier
instead of a string in the hook configuration.
> Add class identifier to prevent errors in TYPO3 8 backend

- Classes/Backend/IndexInspector/IndexInspector.php
- Classes/BackendItem/ContextMenuActionJavascriptRegistration.php
- Classes/ViewHelpers/Backend/ScriptViewHelper.php
- Classes/ViewHelpers/Backend/StyleViewHelper.php
Retrieving the PageRenderer has been removed from several locations
in the TYPO3 core, so a new instance of the PageRenderer class has
to be created in order to use it properly.
> Use PageRenderer instance

- ext_localconf.php
Using cache group all to clear the cache when the "Flush general cache" is used on TYPO3
Fixes: #215
> [BUGFIX] Fixed wrong cache group configuration.

- Classes/Query.php
- Configuration/TypoScript/Solr/setup.txt
- Tests/Unit/QueryTest.php
Can be used to enable "hl.useFastVectorHighlighter" to improve the highlighting performance.
Fixes: #193
> Added configuration "plugin.tx_solr.results.resultsHighlighting.useFastVectorHighlighter" to use a faster highlighter when needed.

- Configuration/TypoScript/Solr/setup.txt
I propose to add url as default trustedField because & charcters could be in there and would get escaped, what is not wanted in this case.
Fixes: #219
> [BUGFIX] Add url as default trusted fields because of & in the url

- ext_localconf.php
Register new defaultContentRendering for tt_content.search when compatibility6 is installed
Fixes: #128
> [TASK] Overwrite definition of search content element when compatibility6 extension is loaded and search

- Classes/AdditionalFieldsIndexer.php
- Classes/Configuration/ConfigurationManager.php
- Classes/Configuration/TypoScriptConfiguration.php
- Classes/ConnectionManager.php
- Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/JavascriptManager.php
- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Classes/Plugin/Results/ResultsCommand.php
- Classes/Query.php
- Classes/Search.php
- Classes/SolrService.php
- Classes/Template.php
- Classes/Typo3Environment.php
- Classes/Typo3PageContentExtractor.php
- Classes/Typo3PageIndexer.php
- Classes/Util.php
- Classes/ViewHelper/Date.php
- Classes/ViewHelper/Facet.php
- Classes/ViewHelper/Link.php
- Classes/ViewHelper/Lll.php
- Classes/ViewHelper/SolrLink.php
- Classes/ViewHelper/Ts.php
- Tests/Integration/Fixtures/can_search.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/SearchTest.php
- Tests/Unit/Configuration/TypoScriptConfigurationTest.php
- Tests/Unit/ViewHelper/TsTest.php
This patch streamlines the typoscript configuration handling.
At various places the typoscript configuration path plugin.tx_solr. is
used, also in context of a content object. So typoscript settings that
should affect a single content element path like plugin.tx_solr_PiResults_Results.
was ignored. Also the flexform settings are merged in the main
configuration object now.
The TypoScriptConfiguration object support array access for backwards compatibility.
In the long run, we should use speaking methods or "getObjectByPath" or "getValueByPath"
For now it does not support nested solr plugins.
Resolves: #163
This pull request is based on @Mabahe pull request with the addition that, the configuration object can be used with array access operators for backwards compatibility and adds some …
> [TASK] Introduce main configuration object

- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
Make sure that parsed content is supposed to be UTF-8.
Fixes #218
> [BUGFIX] Charset not respeceted in Typo3PageContentExtractor::excludeContentByClass

- Classes/IndexQueue/RecordMonitor.php
Backports the fix from #48 (Indexing of records crash when indexing configuraiton and table name is different when new record created) to the 3.0.x branch.
> Backport fix for #48 to 3.0.x

- Classes/Domain/Search/ResultSet/SearchResult.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- ext_localconf.php
Added SearchResult object and configuration to be able to configure an own class as search result object.
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['searchResultClassName ']
Fixes: #251
> Added SearchResult object and configuration to be able to configure an own class as search result object.

- CONTRIBUTING.md
- Tests/Build/cibuild.sh
- composer.json
php-cs-fixer should be installed via composer instead of require a global binary
> Install php-cs-fixer via composer

- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Classes/Plugin/Search/Search.php
- Classes/SolrService.php
For PHP7 the signature of a method should be identical to the parent class.
> [BUGFIX] PHP7 compatibility for several classes

- Classes/Plugin/PluginBase.php
- Tests/Integration/Plugin/Results/ResultsTest.php
Retrieve configured labels from typoscriptConfiguration and assign them in the plugin.
Fixes: #267
> Overwritting labels with TypoScript not working

- Classes/JavascriptManager.php
Remove versioned file name from JavaScript manager, because this is done one by the PageRenderer now.
This pr resolved the issue for 3.1.x we need to apply it on master as well. I would create a seperate pr for this.
Fixes: #264
> [BUGFIX] JavaScript files get lost when concatenation and compression is enabled

- Classes/JavascriptManager.php
Remove versioned file name from JavaScript manager, because this is one by the PageRenderer now.
Fixes: #264
> [BUGFIX] JavaScript files get lost if concatenation and compression are enabled

- Classes/IndexQueue/Queue.php
Removed method IndexQueue/Queue::getListOfPagesFromRoot since it is private and no where in use
Fixes: #279
> [TASK] Remove IndexQueue/Queue::getListOfPagesFromRoot 

- Classes/Report/SolrConfigStatus.php
- Resources/Solr/typo3cores/conf/solrconfig.xml
Since the mm parameter is set as default value for the search request handler q.op has no effect and should be removed
Fixes: #283
> [TASK]  Remove q.op

- .travis.yml
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/Plugin/CommandPluginBase.php
- Classes/ViewHelpers/Backend/AbstractSolrBackendViewHelper.php
- Classes/ViewHelpers/Backend/AbstractSolrTagBasedViewHelper.php
- Classes/ViewHelpers/Backend/AbstractSolrViewHelper.php
- Classes/ViewHelpers/Backend/Button/HelpButtonViewHelper.php
- Classes/ViewHelpers/Backend/Menu/CoreSelectorMenuViewHelper.php
- Classes/ViewHelpers/Backend/Menu/SiteSelectorMenuViewHelper.php
- Classes/ViewHelpers/Backend/ScriptViewHelper.php
- Classes/ViewHelpers/Backend/SitesViewHelper.php
- Resources/Private/Templates/SynonymsModule/Index.html
- ext_emconf.php
- ext_tables.php
* Icon was not showing in TYPO3 8.0
* Remove Hook registration by reference in UserGroupDetector since it is allready a singleton and registration with & is deprecated
* Added base class for ViewHelpers with new properties escapeOutput and escapeChildren
* Remove usage of $GLOBALS['TT']
Fixes: #273
> [TASK] Fixed 8.0 compatibility issues

- Classes/Task/ReIndexTask.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/Task/Fixtures/can_reindex_task_fill_queue.xml
- Tests/Integration/Task/IndexQueueWorkerTaskTest.php
- Tests/Integration/Task/ReIndexTaskTest.php
ReIndex task was not running, because deprecated method was used.
Fixes: #288
> [BUGFIX] ReIndex task is not working

- Classes/AdditionalFieldsIndexer.php
- Classes/Domain/Index/IndexService.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/Util.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_with_additional_fields_into_solr.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
- ext_tables.php
* Use TypoScriptConfiguration during indexing in
* AdditionFieldsIndexer
* PageFieldMappingIndexer
* IndexService
* Make GarbageCollector as Singleton since registration by reference is deprecated
and is not allowed since TYPO3 8.0
Fixes: #228
> [TASK] Avoid array usage of configuration

- Classes/Domain/Index/IndexService.php
- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
* Remove legacy code for TYPO3 Versions below 7.6 LTS
* Small refactoring with guard clause for early return
Fixes: #293
> [TASK] Remove legacy code for TYPO3 Versions below 7.6

- Classes/JavascriptManager.php
- Classes/Util.php
* Moved logic from JavaScriptManager into Util
* Refactore usage in JavaScriptManager and Util::initializeTsfe
Fixes: #276
> [BUGFIX] absRefPrefix auto is now resolved as in the TYPO3 core - RELEASE-3.1.x

- Classes/HtmlContentExtractor.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/Typo3PageContentExtractor.php
- Classes/Util.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
- Tests/Unit/Typo3PageContentExtractorTest.php
Checked content now if one of the strings exist and do dom initialization only
when a configured excludeClass was found.
Fixes: #227
> [BUGFIX] excludeContentByClass is slowing down indexing - dev-master

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
- Classes/Plugin/Results/ErrorsCommand.php
- Tests/Integration/Plugin/Results/ResultsTest.php
Searches with whitespaces only are handled now as a search with an empty query string ""
Fixes: #236
> [BUGFIX] Search with whitespace only should be threated as empty search

- Classes/System/Configuration/ConfigurationManager.php
- Classes/Util.php
- Tests/Integration/Plugin/Results/ResultsTest.php
The configurationManager returns the same configuration only in the same context (rootPage, configurationArray, language and TypoScript path)
Fixes: #311
> [BUGFIX] The ConfigurationManager should return the same configuration only for the same arguments.

- Classes/IndexQueue/Indexer.php
Cache for language information is not kept across instances of the indexer. Each new record
requires a new instance of the indexer but language information does not change between creation of
indexer instances. Language information is obtained by instantiating TSFE and parsing TS templates.
This can take 0.5-2 seconds depending on the amount of TypoScript. It makes sense to cache this
information statically. It helps to shorten indexing times dramatically and lower CPU usage on
the server.
> [TASK] Improve performance of record indexer

- Classes/IndexQueue/RecordMonitor.php
- Classes/Util.php
- Tests/Unit/UtilTest.php
Util::getConfigurationFromPageId  will now return an empty TypoScriptConfiguration as expected and annotated.
* Also added a unit test
* Allow to skip caching
Fixes: #315
> [BUGFIX] Util::getConfigurationFromPageId is returning an array instead of an empty TypoScriptConfigruation

- Classes/Query.php
- Tests/Unit/QueryTest.php
Before only the usage of "hello world" as a phrase was supported. The usage of more complex phrase queries e.g. `"hello world" or "hello planet"`was not supported.
This pull request:
1. adds test cases for the escape method of the query for the previous use cases
2. implements the context depending (inside or outside a phrase) escaping for multiple phrases
Fixes: #307
> [TASK] Support phrases inside a query string - release-3.1.x

- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
Pass $forcedChangeTime to updateItem() instead of creating it within the function depending on itemType pages
fixes #231
> [BUGFIX] Re-Index after deleting a content element - release-3.1.x

- Classes/IndexQueue/AbstractIndexer.php
- Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
- Tests/Unit/AbstractIndexerTest.php
Adds function AbstractIndexer::isAllowedToOverrideField  in AbstractIndexer and use it in
* AbstractIndexer::addDocumentFieldsFromTyposcript 
* PageFieldMappingIndexer::getMappedFields
Fixes: #232
> [BUGFIX] Added AbstractIndexer::isAllowedToOverrideField to check if a field is allowed  to be overwritten with the typoscript configuration.

- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/ErrorsCommand.php
- Classes/Plugin/Results/Results.php
Searches with whitespaces only are handled now as a search with an empty
query string "" unless an empty search query is explicitly allowed.
Fixes: #236
> [BUGFIX] Search with whitespace only should be threated as empty search - release-3.1.x

- Classes/Query.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Tests/Integration/Plugin/FrequentSearches/Fixtures/can_render_frequentSearches_plugin.xml
- Tests/Integration/Plugin/Results/Fixtures/can_render_results_plugin.xml
- Tests/Integration/Plugin/Search/Fixtures/can_render_search_plugin.xml
- Tests/Unit/QueryTest.php
The FastVectorHighlighter will now be used by default when a fragmentSize larger then 17 is configured.
Fixes: #193
> [TASK] Use FastVectorHighlighter by default without configuration

- Classes/Backend/IndexInspector/IndexInspectorRemoteController.php
The search index inspector didn't support multi value fields, it simply
showed "null" and additionally a warning was generated. Now up to 10
values of multi value fields will be shown.
Fixes: #351
> [BUGFIX] Add support of multi value fields to search index inspector

- Classes/Plugin/PluginBase.php
Frontend should not show PHP error in Frontend when connection is not initialized.
Fixes: #356
> [BUGFIX] Frontend should not show PHP error in Frontend when connecion is not initialized

- Classes/IndexQueue/Initializer/Page.php
Hi there,
after I installed 4.0.0 of ext-solr, I ran into an exception message while I was trying to "Queue Selected 
Items for Indexing" in the Search backend module. 
https://github.com/TYPO3-Solr/ext-solr/issues/363
It would be great if you would accept this change. If not like this, then maybe in a similar fashion.
Thanks,
Gerald
> Bugfix Issue #363 Fixing FlashMessageQueue::addMessage

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Plugin/PluginBase.php
- Tests/Integration/Plugin/Results/ResultsTest.php
Parent plugin is not passed to search result set service in PluginBase
* Passed parent plugin to SearchResultSet service
* Added regression test
Fixes: #366
> [BUGFIX] Parent plugin is not passed to search result set service in PluginBase - release-4.0.x

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Plugin/PluginBase.php
- Tests/Integration/Plugin/Results/ResultsTest.php
Parent plugin is not passed to search result set service in PluginBase
* Passed parent plugin to SearchResultSet service
* Added regression test
Fixes: #366
> [BUGFIX] Parent plugin is not passed to search result set service in PluginBase - dev-master

- Classes/IndexQueue/Queue.php
- Classes/Util.php
If you are in FE mode and the root page for a record is requested that
is located in a different tree, you should get the root page from the
record and not the one of the current frontend.
Resolves: #370
> [BUGFIX] Force root line fallback for getting root page id of records

- Classes/Backend/SolrModule/AbstractModuleController.php
- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/Initializer/Page.php
- Tests/Integration/IndexQueue/Initializer/Fixtures/can_add_mount_pages.xml
- Tests/Integration/IndexQueue/Initializer/PageTest.php
If invalid mount points were found while initializing the page index
queue, flash messages are added to a flash message queue, but
addMessage() mustn't be called statically and backend module has to
consider the queue initializer flash massages.
Fixes: #363
> [BUGFIX] Fix flash message queue usage and display of flash messages

- Classes/Backend/SolrModule/AbstractModuleController.php
- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/Initializer/Page.php
- Tests/Integration/IndexQueue/Initializer/Fixtures/can_add_mount_pages.xml
- Tests/Integration/IndexQueue/Initializer/PageTest.php
If invalid mount points were found while initializing the page index
queue, flash messages are added to a flash message queue, but
addMessage() mustn't be called statically and backend module has to
consider the queue initializer flash massages.
Fixes: #363
> [BUGFIX] Backport fix of flash message queue usage and display of flash messages to release-4.0.x

- Classes/Backend/SolrModule/AbstractModuleController.php
- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/Initializer/Page.php
- Tests/Integration/IndexQueue/Initializer/Fixtures/can_add_mount_pages.xml
- Tests/Integration/IndexQueue/Initializer/PageTest.php
If invalid mount points were found while initializing the page index
queue, flash messages are added to a flash message queue, but
addMessage() mustn't be called statically and backend module has to
consider the queue initializer flash massages.
Fixes: #363
> [BUGFIX] Backport fix of flash message queue usage and display of flash messages to release-3.1.x

- Classes/Domain/Search/SearchRequest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
Sorting key in SearchRquest should be sorting name instead of solr field name.
Fixes: #409
> [BUGFIX] Sorting key in SearchRquest should be sorting name instead of solr field name.

- Classes/Domain/Search/SearchRequest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
* Adds a unique id to the request object
* Fixed a bug that the stateChanged property is set when the setResultsPerPage method is called
Fixes: #414
> [TASK] Add a unique id to the request

- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/System/Util/ArrayAccessor.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
- Tests/Unit/System/Util/ArrayAccessorTest.php
* Use ArrayAccessor::set and reset
* Added unit tests
Fixes: #420
> [BUGFIX] TypoScript configuration should use configurationAccess also for writing

- Classes/ContentObject/Relation.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_direct_relationAndAdditionalWhere.xml
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_mm_relationAndAdditionalWhere.xml
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
* Only check once for duplicate values
* As the code could be replaced with same approach as done in another
function, use core API instead of custom implementation and reduce
code
* Also refactor sql query to own method
* This allows to configure different fields for same relation with
additional where clauses.
E.g. to select different categories by there parent.
Fixes: #426
> [TASK] Add additionalWhereClause to SOLR_RELATION

- Classes/Query/FilterEncoder/Range.php
- Tests/Unit/Query/FilterEncoder/RangeTest.php
Configuring numeric ranges containing negative numbers leads to invalid
queries, since the filter decoding couldn't handle negative numbers.
This commit improves the filter part detection, forces integer values
and extends the existing unit tests. 
Fixes: #448
> [BUGFIX] Numeric range facet doesn't support negative numbers

- Classes/ContentObject/Multivalue.php
- Classes/ContentObject/Relation.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_direct_relationAndAdditionalWhere.xml
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_mm_relationAndAdditionalWhere.xml
Rename the setting to have a consitent naming.
Fixes: #459
> [BUGFIX] Rename "additionalWhere" to "additionalWhereClause" to have a consistent naming

- Classes/Site.php
* As objects aren't the same, the comparison always failed
* That lead to wrong configuration if someone edited and
saved the record without noticing the mistake
> [BUGFIX] Keep selected site in scheduler task

- Classes/Site.php
* As selected site can be null, we check this situation before calling
methods on null.
Resolves: #560
Relates: #557, #553
> [BUGFIX] Method call on null

- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
This PR fixes the broken test for the variants against solr6
Reason: Only string and numeric fields should be used for field collapsing. In the testcase we used a text field.
This worked in Apache Solr 4.10.4 but not in 6.1.0 and was not intendet to work at all.
Since the error message in Apache Solr is missleading an Issue was created for that:
https://issues.apache.org/jira/browse/SOLR-9409
Because of that, the testcase was changed to use the numeric "pid" field for the grouping.
> [BUGFIX] Test with collapse field is broken with "64 bit numeric collapse fields are not supported"

- Resources/Solr/cores/arabic/core.properties
- Resources/Solr/cores/armenian/core.properties
- Resources/Solr/cores/basque/core.properties
This commits fixes wrong schema and token usage of arabic,
armenian and basque default cores.
Related: #569
> [BUGFIX] Fix core definitions

- .travis.yml
- Classes/Plugin/FrequentSearches/FrequentSearches.php
- Classes/Plugin/Search/Search.php
This pull request backports the runtime notice fixes for Search.php and FrequentSearches.php
The php-cs-fixer was pinned to 1.11.6 since the release was build with this version.
> [TASK] Backport other runtime fixes for Search.php and FrequentSearches.php

- .travis.yml
- Build/Test/cibuild.sh
- composer.json
* Pinned version to 1.11.7
* Make sure to use php-cs-fixer NOT as require dev dependency an do a global install in .travis.yml
* Use new vendor namespace php php-cs-fixer (friendsofphp)
Fixes: #612
> [TASK] Pin php-cs-fixer version to v1.11.7

- Classes/IndexQueue/Queue.php
In some cases you want to index external records for example
products from a ecommerce platform. In this case the records
are not in the TYPO3 database and we need only the id to index
them with our own indexer.
> [FEATURE] Add hook to manupilate data after they are fetch from database

- ext_tables.php
DataHandler (TceMain) hooks are registered also in frontend mode when the TSFE_EDIT post parameter array is present.
Fixes: #647
> [BUGFIX] Have index updated when using frontend editing

- .travis.yml
The PSR-2 violations have allready been fixed by @irnnr in this commit: 
https://github.com/TYPO3-Solr/ext-solr/commit/043dac2862578931727f9b26d98028a63eeab0bd
So we can use the latest version of php-cs-fixer again.
Fixes: #611
> [TASK] Removed pin to revision of php-cs-fixer

- Classes/IndexQueue/PageIndexer.php
getSolrConnectionsByItem tried to add a solr connection for every page
overlay found as an accessible solr connection, even non-existing ones.
This patch checks, if a solr connection for a language id actually exists
before adding it to the accessible connections array.
Fixes ext-solr issue #233.
> [FIX] Check if a solr connection for a found page overlay exists.

- Classes/Plugin/Results/PageBrowser.php
- Classes/Template.php
The method ContentObjectRenderer::fileResource has been marked
as deprecated and should not be used anymore.
Resolves: https://github.com/TYPO3-Solr/ext-solr/issues/665
> [TASK] Replace usages of deprecated method cObj->fileResource

- Classes/Site.php
When processing multisites - you need to be able to clear the sitePagesCache - between each iterations or else the pages to be indexed will be mixed up
> [TASK] Clear the sitePagesCache

- Classes/Command/SolrCommandController.php
- ext_localconf.php
Make updateConnections task available through the Extbase CommandController
without adding a "_cli_solr" TYPO3 backend user.
This is useful e.g. as a task after syncing database from production to stage/dev
environment where the solr connections are different (TYPO3_CONTEXT).
> [FEATURE] Add updateConnections available through CommandController

- Resources/Private/Templates/IndexQueueModule/ShowError.html
Render indexing errors in a pre tag to make them better readable as
linebreaks and whitespaces are interpreted.
> Make rendering errors better readable in the backend

- Classes/Plugin/PluginBase.php
The baseWrap function still used the old way to access the TypoScript configuration. This patch makes use of the TypoScript configuration object to make the baseWrap functional again.
> [BUGFIX] use TypoScript configuration object for plugin baseWrap

- Resources/Private/Install/install-solr.sh
Let solr only listen to 127.0.0.1 when using the install script.
Fixes: #620
> [TASK] Bind jetty to 127.0.0.1 when installed with installer

- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
* Rename method getMonitoredTables to getIndexQueueMonitoredTables
* Add new method getIndexQueueIsMonitoredTable and use it in the RecordMonitor
* Refactored RecordMonitor to return immediatly when a non monitored record is handled.
Follow up for: #714
> [TASK] Refactor usage of getMonitoredTables in TypoScriptConfiguration

- Classes/Query.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
Make the number of facet options configurable. Especially if
using a bigger hierarchical facet, the default limit of 100 can
be too low which would lead to an incomplete rendering.
By using plugin.tx_solr.search.faceting.facetLimit, the limit can be
now configured.
Resolves: #724
> [FEATURE] Make it possible to define facet.limit

- Classes/ConnectionManager.php
- Configuration/Backend/AjaxRoutes.php
- ext_tables.php
The used ajax handler has been marked as deprecated and
must be replaced.
Resolves: #726
> [TASK] Replace usage of deprecated ajax handler

- Classes/Typo3PageIndexer.php
The code can be cleaned up by removing usage of $this->page->renderCharset.
- The 2nd argument of the constructor has been removed years ago
- The renderCharset has been marked as deprecated
Resolves: #733
> [TASK] Remove usage of deprecated renderCharset

- Classes/ViewHelpers/Backend/Menu/CoreSelectorMenuViewHelper.php
- Classes/ViewHelpers/Backend/Menu/SiteSelectorMenuViewHelper.php
As the Backend ViewHelpers outpout HTML, it's content must not be escaped.
> [BUGFIX] Set escapeOutput to false for ViewHelpers in Backend

- Classes/Util.php
This change implements a memoizer to remember each resolved
TS configuration array based on input arguments. During certain
RecordMonitor operations the SQL database gets hammered with
repeated requests to retrieve the exact same SQL resource (and
parse the result using semi-expensive logic). E.g. when indexing
multiple records on the same page.
Since TS output is the same for any page ID + language + path,
always, the problem can be solved by remembering the output
in the Util::getConfigurationFromPageId.
> [TASK] Prevent SQL hammering in getConfigurationFromPageId

- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/update_unexisting_item_will_remove_queue_entry.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
* Extracting the method getRecordPageId from RecordMonitor::processDatamap_afterDatabaseOperations.
* Return immeditaly when $record is empty
* Extract operations on pages after update into method doPagesPostUpdateOperations
> [TASK] Reduce the complexity of RecordMonitor::processDatamap_afterDatabaseOperations

- Classes/IndexQueue/FrontendHelper/PageIndexer.php
$GLOBALS['T3_VAR']['getUserObj'] - is not used in anymore (TYPO3 8.x). Use SingletonInterface instead.
> [TASK] PageIndexer support TYPO3 8.4

- Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
* Set attachments = 1
* Changed field from related_files to fal_related_files
* Allow all file extensions
* Add constant for detailPid
Fixes: #773
> [TASK] File indexing for news example configuration

- Classes/SolrService.php
- Classes/System/Solr/Service/StopWordParser.php
- Classes/System/Solr/Service/SynonymParser.php
- Classes/ViewHelpers/AbstractSolrTagBasedViewHelper.php
- Classes/ViewHelpers/AbstractSolrViewHelper.php
- Classes/ViewHelpers/Backend/Menu/CoreSelectorMenuViewHelper.php
- Classes/ViewHelpers/Backend/Menu/SiteSelectorMenuViewHelper.php
- Classes/ViewHelpers/Format/ImplodeViewHelper.php
- Resources/Private/Templates/StopWordsModule/Index.html
- Tests/Integration/SolrServiceTest.php
- Tests/Unit/SolrServiceTest.php
- Tests/Unit/ViewHelpers/Format/ImplodeViewHelperTest.php
* This pull request refactors the SolrService to initialize StopWords and Synonyms endpoints only when they are needed.
* The result is, that the schema will only be retrieved when it's needed in the backend.
* Beside that a bug was fixed, that the stopwords in the backend have beend rendered with additional whitespaces
Fixes: #775
> [TASK] Avoid schema retrieval on every call

- Classes/ViewHelpers/Backend/SitesViewHelper.php
Fix: Class 'ApacheSolrForTypo3\Solr\ViewHelpers\Backend\AbstractSolrViewHelper' not found in solr/Classes/ViewHelpers/Backend/SitesViewHelper.php on line 40
> [BUGFIX] Fix class name error AbstractSolrViewHelper in SitesViewHelper.php

- Classes/Domain/Index/Queue/RecordMonitor/Helper/MountPagesUpdater.php
- Classes/IndexQueue/RecordMonitor.php
Moves the mountmpoint logic of the record monitor into an own class and uses it, to simplify the RecordMonitor.
Fixes: #800
> [TASK] Extract mount point logic from record monitor

- Classes/GarbageCollector.php
- Classes/IndexQueue/Queue.php
* Announces the deprecation and removeall in 7.0
Queue::getIndexingConfigurationByItem
GarbageCollector::cleanIndex
> [TASK] Announce deprecation of methods and trigger deprecation log

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
* Add the field facet_counts to the empty fake respone
Followup of: #803
> [BUGFIX] Add missing field facet_counts to faked empty search response

- Classes/Domain/Search/ResultSet/Facets/RenderingInstructions/FormatDate.php
- Classes/System/DateTime/FormatService.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Releases/solr release 6.0.md
- Tests/Unit/Domain/Search/ResultSet/Facets/RenderingInstructions/FormatDateTest.php
This PR adds a rendering instruction, that can be used to format dates when they are used in option facets.
Fixes: #828
> [TASK] Add renderingInstruction for dates as options

- Documentation/FAQ/Index.rst
- Documentation/GettingStarted/Solr.rst
- Documentation/Releases/solr release 6.0.md
* Enhances documentation, how to use the default container
* Bind port 8983 to 127.0.0.1 in examples
* Document new port
Fixes: #682
> [TASK] Enhance docker documentation

- Classes/Site.php
Since solrfal and potentially other places have a large amount of identical calls to getAvailableSites it would make sense to cache the $sites
Fixes: #838
> [FEATURE] Add Cache in getAvailableSites 

- Classes/Domain/Index/IndexService.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
* This PR adds the signals beforeIndexItems, beforeIndexItem and afterIndexItem to the IndexService to provide better possibilities to reacht on indexing events
* Adds unit test for the IndexService
Fixes: #835
> [TASK] Add more signals to IndexService

- Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/Typo3PageIndexer.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_custom_pagetype_into_solr.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
When a custom page index configuration is used, that defines custom fields that differ from the pages configuration they have not been recognized because the default configuration of pages was used.
This PR fixes this and adds an integration test for the PageIndexer.
Fixes: #842
> [BUGFIX] Allow custom fields for own page index configuration.

- Classes/Facet/HierarchicalFacetHelper.php
- Classes/Facet/HierarchicalFacetRenderer.php
- Classes/FieldProcessor/AbstractHierarchyProcessor.php
- Classes/FieldProcessor/PageUidToHierarchy.php
- Classes/FieldProcessor/PathToHierarchy.php
- Classes/Query/FilterEncoder/Hierarchy.php
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Unit/FieldProcessor/PathToHierarchyTest.php
- Tests/Unit/Query/FilterEncoder/HierarchyTest.php
In order to be able to differentiate between 0-foo and 0-foobar
when using facet.prefix it is necessary to use a trailing slash
that way when using facet.prefix 0-foo/ only the 0-foo/ will
be found and not also 0-foobar/
Resolves: #683
> [BUGFIX] hierarchical fields need to add trailing slash

- Classes/Backend/SolrModule/IndexMaintenanceModuleController.php
- Classes/Task/ReIndexTask.php
We're currently doing work on reducing the number of commits against our solr installation to improve scalability and cache efficiency.
Looking through the typo3 extension these two particular cases struck me as particularly bad. Essentially it seems the author was unsure of whether his deleteByQuery would delete non-committed documents and so issues an extra commit first, which is completely unnecessary since solr by default will delete both committed and pending documents.
I'm unsure of whether this may have been necessary at some point, but in 4.10+ it is not.
> Do not issue commits before deletes

- Classes/Response/Processor/StatisticsWriter.php
- Classes/Search/StatisticsComponent.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrStatistics.rst
Only if advancedStatistics is set the debugModes is appended to the search query. Since there is a performance issue it makes sense to split it into 2 configurations.
> [FEATURE] Adding plugin.tx_solr.statistics.addDebugData

- Classes/GarbageCollector.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/Task/ReIndexTask.php
- Documentation/Configuration/Reference/TxSolrIndex.rst
The option makes it possible to disable implicit solr commits, which
can improve scalability and performance when a solr core is shared
between many installations.
This affects the garbageCollector (used by the indexQueue) and the special reIndexTask.
This doesn't preclude manually triggering commits and the deleteByType function will still issue commits by default, but that can be explicitly disabled, and changing that would cause unnecessary API breakage.
I still need to test this a bit more, so please don't merge it yet.
Fixes: #870
> [FEATURE] Add plugin.tx_solr.index.enableCommits option.

- .travis.yml
- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- composer.json
This pull request allows to run all tests against the current TYPO3 dev-master (8.6-dev) and applies the required changes that are needed for the moved testing framework.
> [TASK] Allow to use new testing framework of TYPO3 8

- Classes/ConnectionManager.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/System/ContentObject/ContentObjectService.php
- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/Examples/ConnectionFromConfVars/setup.txt
- Documentation/Configuration/Reference/TxSolrSolr.rst
- Documentation/FAQ/Index.rst
- Tests/Integration/System/Configuration/TypoScriptConfigurationTest.php
- Tests/Unit/System/ContentObject/ContentObjectServiceTest.php
This feature allows you use cObjects in the solr typoscript configuration. This enables you to read the configuration
e.g. from the AdditionConfiguration.php, which is most likely the place to put environment specific settings in deployment scenarios.
The following example shows the usage:
Addition to AdditionalConfiguration.php:
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['host'] = 'mysolrserver.de';
```
Usage in typoscript:
```
plugin.tx_solr.solr {
host = TEXT
host {
value = localhost
override.data = global:TYPO3_CONF_VARS|EXTCONF|solr|host
}
}
```
Fixes: #868
> [TASK] Add cObject support for solr settings

- Resources/Private/Layouts/Default.html
* The id="typo3-inner-docbody" was removed since this is not required
Fixes: #883
> [TASK] Scrolling bar in backend not visible

- Classes/Controller/Backend/PageModuleSummary.php
- Resources/Private/Templates/Backend/PageModule/Summary.html
- Tests/Integration/Controller/Backend/Fixtures/fakeFlexform.xml
- Tests/Integration/Controller/Backend/PageModuleSummaryTest.php
- ext_localconf.php
This PR:
* Uses the FluidStandaloneView to render the backend summary
* Adds an integration test for the summary
* Move the class to Classes/Controller/Backend/PageModuleSummary.php
Fixes: #731
> [TASK] Streamline Backend Summary

- .travis.yml
- Tests/Integration/SearchTest.php
* Fixed instanciation of Query in SearchTest
* Dissallow broken builds for PHP 7.1
Fixes: #911
> [BUGFIX] Fix failing test with PHP 7.1

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
The option `search.query.allowEmptyQuery` does not work due to a `empty()` check against the query parameter.
It must not be checked if the query paremter is `empty()` but if it is `null` to not get a false positive for an empty string.
Fixes #918
> Fix allowEmptyQuery option

- Classes/GarbageCollector.php
- Tests/Integration/Fixtures/can_remove_content_element.xml
- Tests/Integration/Fixtures/can_remove_page.xml
- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IntegrationTest.php
This PR adds integration tests for the following use cases of the garbage collector:
* content element is deleted (page should be reindexed)
* content element is set to hidden (page should be reindex)
* content element start time is set to date in future (page should be reindex)
* content element end time is set to date in past (page should be reindex)
* page is deleted (page should be removed from the index and index queue)
* page is set to hidden (page should be removed from the index and index queue)
During the tests have been added a bug was fixed, related to the start end endtime usecase.
The check if an item for this record is in the queue does not work correctly for tt_content and pages_language_overlay items since for
the the page with the pid should be checked.
Fixes: #920
> [TASK] Add integration tests for GarbageCollector

- Classes/AbstractDataHandlerListener.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Tests/Integration/IndexQueue/Fixtures/update_page_with_recursive_update_fields_configured.xml
- Tests/Integration/IndexQueue/Fixtures/update_page_without_recursive_update_fields_configured.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
Add new constant plugin.tx_solr.index.queue.pages.recursiveUpdateFields to ensure that recursive update of pages can be done - there remains two TODO's use of queue configuration and functional test.
Solves solve the issue #355
> [FEATURE] Recursive update of pages

- Classes/IndexQueue/AbstractIndexer.php
At the moment it is not possible to override the unAllowedOverrideFields array.
This change allows to override / modify the array in an own Indexer class.
> [BUGFIX] Use static instead of self

- Classes/Domain/Site/SiteHashService.php
- Classes/Domain/Variants/IdBuilder.php
- Classes/Domain/Variants/IdModifier.php
- Classes/Eid/SiteHash.php
- Classes/Eid/Suggest.php
- Classes/IndexQueue/Indexer.php
- Classes/Query.php
- Classes/Search/AccessComponent.php
- Classes/Site.php
- Classes/Typo3PageIndexer.php
- Classes/Util.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Domain/Site/Fixtures/can_resolve_site_hash.xml
- Tests/Integration/Domain/Site/SiteHashServiceTest.php
- Tests/Unit/Domain/Site/SiteHashServiceTest.php
- Tests/Unit/Domain/Variants/CustomIdModifier.php
- Tests/Unit/Domain/Variants/IdBuilderTest.php
- Tests/Unit/QueryTest.php
- Tests/Unit/UtilTest.php
This PR changes the behaviour of `query.allowedSites`; the behavior `*` has been changed:
* Before: `*` was the same as `__all`, which means all sites in the system
* After: `__all` is still handled as `__all` sites in the system, but `*` now means every site (same as no check at all)
During the implementation the following things have been done
* Move SiteHash related logic from Util* to SiteHashService* and make them non static (See: http://wiki.c2.com/?AbuseOfUtilityClasses)
* Mark SiteHash related method in Util deprecated and announce removal
* Added Tests for Query and SiteHashService modifications
* If variants should be used across multiple instances the `variantId` needs to be unique by system (not by site!). As of now the `variantId` only contains (type/uid), to have a unique …
> [!!!][TASK] Allow to disable siteHash check by setting query.allowedSites to *

- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/Domain/Index/IndexService.php
- Classes/IndexQueue/Queue.php
- Tests/Integration/IndexQueue/Fixtures/can_get_item_count_by_site.xml
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
This PR resolve performance issues in the IndexQueueWorkerTask.
The reason was:
* The configuration is fetched in the constructor of IndexService but only needed when items get really processed.
The solution is:
* Fetch the configuration indexItems, then it will not be fetched when just the progress is calculated
Beside that:
* The database logic was move to the IndexQueue because this class should be responsible to do database operations on 'tx_solr_indexqueue_item' (Related issue: #904)
* Tests have been added for the IndexQueue methods
* It is tested that the configuration is only fetched when records get indexed
Fixes: #928
> [TASK] Check performance of IndexQueueWorkTask::getProgress

- Classes/Task/IndexQueueWorkerTask.php
Solves #921 - I have tested it and links still seem to be generated properly both from cli and BE.
In addition a have created a patch for the dev-branch of SolrFal
> [BUG] Wrapped CliEnvironment to be used only in cli-mode

- Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/IndexQueue/Fixtures/update_record_outside_siteroot.xml
- Tests/Integration/IndexQueue/Fixtures/update_record_outside_siteroot_from_two_sites.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
- ext_localconf.php
With the configuration "additionalPageIds" it was possible to add additional page ids to an indexing configuration.
When these external records have been updated in the backend by now the RecordMonitor does not recognize these updates.
This PR allows the RecordMonitor to determine all responsible site roots and add the entry to the queue when the queue get's intialized.
Fixes: #485
> [TASK] RecordMonitor does not track records outside the siteroot.

- Classes/Backend/IndexInspector/IndexInspector.php
- Classes/BackendItem/ContextMenuActionJavascriptRegistration.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Resources/JavaScript/ExtJs/Ext.grid.RowExpander.js
- ext_localconf.php
- ext_tables.php
Removed $GLOBALS['PATH_solr'] , $GLOBALS['PATHrel_solr'], ExtensionManagementUtility::extRelPath('solr') and temp fix for #948
> [TASK] Fix deprecations with TYPO3 8.x

- Classes/IndexQueue/Indexer.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_configuration_in_rootline.xml
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_overwrite_configuration_in_rootline.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
* It is possible to overwrite the configuration for pages and records in the rootline now (previously only for pages)
* Beside that testcases for both use cases have been added
Fixes: #956
> [TASK] This PR unifies the handling of overwritten configuration in the rootline for records and pages

- Classes/Task/IndexQueueWorkerTask.php
In the check for enabling CliEnvironment - the check needs to use single & and NOT && in order to work. Should fix #968
> [BUG] Fixed that checks uses single & and NOT &&

- Classes/IndexQueue/RecordMonitor.php
The method processDatamap_afterDatabaseOperations in RecordMonitor needs a to filter multiple processings of identical record to a a "bug" in TYPO3 core
This also gains some performance when copying trees performance when copying trees - should solve #943
> [TASK] Added runtime cache to RecordMonitor

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/Util.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
- ext_localconf.php
Use cache_runtime instead in RootPageResolver instead of "own" cache. In addition made some cleanup and fixed tests. 
Fixes: #970
> [TASK] Deprecate Util::isRootPage - moved to RootPageResolver 

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
The method getRootPageId should always return an int
Fixes:  #1077
> [BUG] getIsRootPageId must handle 0 

- Tests/Integration/Controller/Backend/PageModuleSummaryTest.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/SolrServiceTest.php
Since the core introduced a method getFixturePath with another meaning,
we should rename two methods in the base class for integration tests:
* getFixturePath => getFixturePathByName
* getFixtureContent => getFixtureContentByName
Fixes: #1087
> [BUGFIX] Change name of getFixturePath and getFixtureContent

- Classes/System/Logging/DebugWriter.php
- Classes/System/Logging/SolrLogManager.php
- Documentation/Configuration/Reference/TxSolrLogging.rst
- Tests/Unit/System/Logging/DebugWriterTest.php
- ext_localconf.php
In #1086 the usage of devLog was replaced with the SolrLogManager that
uses the TYPO3 logging framework.
Since the setting tx_solr.plugin.logging.debugDevLogOutput does not make any sence
without the devLog it was renamed to tx_solr.plugin.logging.debugOutput.
To still output the log messages to the console (in the backend) or in the frontend when
tx_solr.plugin.logging.debugOutput is set to 1 the SolrLogManager needs to use the DebugWriter
to do that.
This PR:
* Renames the DevLogDebugWriter to DebugWriter
* Refactors the SolrLogManager to use the DebugWriter
* Adapts the existing tests
Impact:
When you set `tx_solr.plugin.logging.debugOutput = 1` the log messages in the frontend are
shown as debug message and in the backend in the TYPO3 console. When the setting is disabled
you do not …
> [TASK] Refactor DevLogDebugWriter to work with SolrLogManager

- Classes/Site.php
Use the uid of the root page as unique cache identifier to prevent conflicts when calling the getPages() method multiple times from the same script.
Fixes #488
> [BUGFIX] Replace `SITE_ROOT` with the actual value as cache identifier

- Tests/Integration/IndexQueue/Fixtures/can_initialize_multiple_sites.xml
- Tests/Integration/IndexQueue/QueueTest.php
This is a followup for the fix of #488 and adds a regression test that makes sure
that the index queue contains the expected items when multiple sites get initialized
in on process.
Related: #488
> [TASK] Add regression for #488

- Documentation/Configuration/Reference/TxSolrIndex.rst
This pr fixes the wrong path the documentation.
Fixes: #964
> [TASK] Fixed wrong path in documentation for plugin.tx_solr.index.queue.pages.indexer.*

- Classes/System/Configuration/ConfigurationPageResolver.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Classes/Util.php
- Documentation/Configuration/Index.rst
- Documentation/Configuration/Reference/ExtensionSettings.rst
- Tests/Integration/System/Configuration/ConfigurationPageResolverTest.php
- Tests/Integration/System/Configuration/Fixtures/can_get_closest_template_page_id.xml
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
- ext_conf_template.txt
By now, when the configuration is fetched the real pageId is used to retrieve it.
The drawback of this approach is, that in many systems this is an overhead,
because the configuration is only set on the rootlevel or some subpages
(except when e.g. conditions are used).
This pull request introduces an ext_conf_template setting that forces ext_solr
to use the closest page id with a typoscript configuration to retrieve the
configuration. The result is, that the configuration cache has more hits and
the performance in the backend is better
Fixes: #937
> [TASK] Allow to use closest typoscript template to retrieve configuration

- Tests/Unit/Domain/Search/ApacheSolrDocument/BuilderTest.php
Adds a test if the tagsH1 field is properly set by the Builder for ApacheSolrDocument object.
> [TASK] Add test canSetTagFieldsForApacheSolrDocument for Builder

- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/Domain/Index/Queue/Statistic/QueueStatistic.php
- Classes/IndexQueue/Item.php
- Classes/IndexQueue/Queue.php
- Resources/Private/Templates/IndexQueueModule/Index.html
- Resources/Private/Templates/IndexQueueModule/ShowError.html
- Tests/Integration/IndexQueue/Fixtures/can_get_statistics_by_site.xml
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Unit/Domain/Index/Queue/Statistic/QueueStatisticTest.php
- Tests/Unit/IndexQueue/ItemTest.php
To simplify the migration to doctrine in the next release, this pr moves direct access
to the index queue item table from the controller to the IndexQueue class
Fixes: #908
> [TASK] Move access to IndexQueue from IndexQueueModuleController to IndexQueue

- Classes/ConnectionManager.php
- Classes/Util.php
- Configuration/TypoScript/Solr/setup.txt
Using TEXT objects for configuration, can be overwritten by e.g. $TYPO3_CONF_VARS['SOLR']
Relates: #868
Releases: master
> [FEATURE] Add TypoScript TEXT object support for plugin.tx_solr.solr.values

- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/Domain/Index/IndexService.php
- Classes/IndexQueue/Queue.php
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
This pr:
* Removes the direct database access in IndexService
* Uses the method getStatisticsBySite instead
* deprecates Queue::getItemsCountBySite
* deprecates Queue::getRemainingItemsCountBySite
* Adapts the tests
Fixes: #1128
> [TASK] Remove database access from IndexService

- Classes/Domain/Index/IndexService.php
- Classes/Domain/Index/Queue/Statistic/QueueStatistic.php
- Classes/Task/IndexQueueWorkerTask.php
- Tests/Unit/Domain/Index/Queue/Statistic/QueueStatisticTest.php
Currently the IndexQueueWorkerTask does a direct read in the database.
To optimize the code structure and simplify the migration to doctrine, this
pr migrates the IndexQueueWorker task to use the logic from the Queue to retrieve
the count of failed documents.
Fixes: #1129
> [TASK] Remove direct database access in IndexQueueWorkerTask

- Classes/System/Solr/Parser/SchemaParser.php
- Tests/Integration/Report/Fixtures/can_check_status_fail_on_invalid_connection.xml
- Tests/Integration/Report/SolrStatusTest.php
- Tests/Unit/System/Solr/Parser/SchemaParserTest.php
When the report is checked with an invalid solr connection you get an error in the backend.
This PR:
* Fixes the error
* Adds an integration test for an invalid solr server and checks if a report can be rendered
Fixes: #1152
> [BUGFIX] Report is broken when invalid solr connection is configured

- Classes/Domain/Search/SearchRequest.php
Make sure all context aware settings and config is also copied in SearchRequest::getCopyForSubRequest() so target page and language 
are correct for all created urls.
> [BUGFIX] Copy context config in getCopyForSubRequest

- Documentation/Solr/IndexMaintenance.rst
We do not recommend anymore to optimize cores manually.
This closes #1125
> [TASK] Remove a hint about optimize index scheduler task from docs.

- Classes/Report/SolrConfigurationStatus.php
- Resources/Private/Templates/Reports/RootPageFlagStatus.html
- Tests/Unit/Report/SolrConfigurationStatusTest.php
This PR:
* Changes the SolrConfigurationStatus report to trigger a warning instead of an error when the indexing is disabled for a site
* This warning is only triggered when solr is enabled for that site (plugin.tx_solr.enabled)
* Adds a unit test for that case
* Refactors the rendering with FluidStandaloneView to reduce the complexity
Fixes: #1184
> [TASK] Report should trigger a warning when indexing is disabled but tx_solr enabled

- .scrutinizer.yml
This pr adds QA limits when
* The testcoverage decreases by more then 10%
* There are new spacing, doc comment or coding style issues
* Major issues get introduced
* The code rating is less then 8 (Currently 8.3)
Fixes: #1102
> [TASK] Add scrutinizer QA limits

- Classes/SolrService.php
- Tests/Integration/SolrServiceTest.php
We need to encode the url for deleting stop words on Apache Solr
machines behind frontend proxies.
Fixes: #1206
Needs Up-Merge
> [FIX] Deleting stop words with umlauts on ext-solr behind frontend proxies

- Classes/SolrService.php
- Tests/Integration/SolrServiceTest.php
This pr makes sure that urlencode is used when synonyms and stopwords are deleted.
This is not a problem with a default solr installation, but when you have a proxy before the solr server that does not allow utf8 urls.
Related:
#1205 
#1206
> [TASK] Use urlencode when deleting synonyms and stopwords

- Classes/SolrService.php
- Tests/Integration/SolrServiceTest.php
We need to encode the url for deleting synonyms on Apache Solr
machines behind front-end proxies with default configs.
Closes: #1205
> [FIX] Deleting synonyms with umlauts behind fronted proxies

- Classes/Backend/SolrModule/IndexMaintenanceModuleController.php
- Classes/SolrService.php
- Tests/Unit/SolrServiceTest.php
This PR:
* Extracts the logic into the method getCoreBasePath
* Adds unit tests for getCoreBasePath and getCoreName
Fixes: #1209
> [BUGFIX] Core reload fails when core path consists of more then two segments - release 6.0.x

- Classes/SolrService.php
- Tests/Unit/SolrServiceTest.php
This PR:
* Extracts the logic into the method getCoreBasePath
* Adds unit tests for getCoreBasePath and getCoreName
Fixes: #1209
> [BUGFIX] Core reload fails when core path consists of more then two segments

- Tests/Integration/Fixtures/does_not_remove_updated_content_element_with_not_set_endtime.xml
- Tests/Integration/GarbageCollectorTest.php
- Tests/Unit/System/TCA/TCAServiceTest.php
As followup of #1213 added tests that makes sure that a solr document still exists, when a custom record was updates.
Closes #1214
> [TASK] Add tests for #1213 GarbageCollector check on endtime=0

- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_configuration_in_rootline.xml
This PR changes the dokytpe to 254 in the fixture file to make sure the storage behaves like a sysfolder.
Fixes: #1266
> [BUGFIX] Change type to 254 in fixture

- Documentation/FAQ/Index.rst
Security issues should always be reported to the TYPO3 security team and not to the extension author.
See https://typo3.org/teams/security/ for details.
> Adjust documentation about reporting security issues

- Tests/Unit/System/Logging/DebugWriterTest.php
This pr:
* Removes an unused use statement of the Class DevLogDebugWriter
Fixes:
#1285
> [BUGFIX] Remove unused use statement in DebugWriterTest

- Tests/Unit/System/Logging/DebugWriterTest.php
This pr:
* Removes an unused use statement of the Class DevLogDebugWriter
Fixes:
#1285
> [BUGFIX] Remove unused use statement in DebugWriterTest - 6.1.x-dev

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/Domain/Site/SiteRepository.php
- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/Item.php
- Classes/IndexQueue/Queue.php
- Tests/Integration/ConnectionManagerTest.php
- Tests/Integration/Fixtures/can_find_connection_for_mouted_page.xml
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_mounted_page.xml
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_multiple_mounted_page.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/Initializer/Fixtures/mouted_shared_non_root_page_from_different_tree_can_be_indexed.xml
- Tests/Integration/IndexQueue/Initializer/Fixtures/mouted_shared_page_from_multiple_trees_can_be_queued.xml
- Tests/Integration/IndexQueue/Initializer/Fixtures/mouted_shared_root_page_from_different_tree_can_be_indexed.xml
- Tests/Integration/IndexQueue/Initializer/PageTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
Fixed Indexer mounted page resolving stack.
Incomplete testcase added for PageIndexer, which ends with:
`Failed to execute Page Indexer Request.`
This fixes #953
> [BUGFIX] Mounted pages from outside of the page tree lead to index queue errors

- ext_tables.php
Registration of context menu items was changed since TYPO3 8 LTS to use item providers.
To keep the backwards compatibility in EXT:solr 6.1.0 for TYPO3 7 LTS both ways where supported.
Since we drop the support of 7.6 LTS, we can remove the old context menu registration as well.
Fixes:
#1295
> [TASK] Remove legacy context menu registration in ext_tables.php

- Classes/IndexQueue/Indexer.php
- Classes/Util.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_outside_site_root.xml
- Tests/Integration/IndexQueue/IndexerTest.php
When a record outside the siteroot was indexed the following exception was thrown:
* TYPO3\CMS\Core\Error\Http\ServiceUnavailableException: No TypoScript template found! in TypoScriptFrontendController.php:2554
This PR:
* Uses the configuration of the siteroot when no configuration is present
* Uses the root page id of the site to generate the document id of the record
Fixes: #1291
> [BUGFIX] Indexing record outside siteroot throws exception

- Classes/IndexQueue/Indexer.php
- Classes/Util.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_outside_site_root.xml
- Tests/Integration/IndexQueue/IndexerTest.php
When a record outside the siteroot was indexed the following exception was thrown:
* TYPO3\CMS\Core\Error\Http\ServiceUnavailableException: No TypoScript template found! in TypoScriptFrontendController.php:2554
This PR:
* Uses the configuration of the siteroot when no configuration is present
* Uses the root page id of the site to generate the document id of the record
Fixes: #1291
> [BUGFIX] Indexing record outside siteroot throws exception - release-6.1.x

- Classes/Command/SolrCommandController.php
This parameter allows to initialize the connections for a particular rootpage.
This parameter is optional: if it is not passed, the connections for all the rootpages
will be initialized.
Usage:
`php ./typo3/cli_dispatch.phpsh extbase solr:updateconnections --rootpageid 121`
Fixes #1288
> [FEATURE] Add --rootpageid parameter to the CLI command solr:updateconnections

- Classes/Controller/Backend/Search/AbstractModuleController.php
- ext_tables.php
To improve the usabillity the selected site stay active when the module is changed.
Currently stored only between submodules of solr main module.
fixes: #1304
> [TASK] Keep the selected site across solr backend modules

- Build/generate_documentation.sh
This fixes the incompatible configuration with current sphinx version
We are staying with Sphinx 1.5.6 until we make the configuration for new Sphinx working.
See sphinx-doc/sphinx/ issue 3543
> [BUGFIX] Sphinx does not render PDF file

- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Frontend/Concepts.rst
- Tests/Integration/Controller/Frontend/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/Frontend/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Domain/Search/ApacheSolrDocument/Fixtures/can_get_apacheSolrDocuments.xml
- Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml
- Tests/Integration/Domain/Search/ResultSet/Fixtures/fe_user_page.xml
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
This pr:
* Removes uneeded methods from TypoScriptConfiguration (not needed anymore because of switch to fluid)
* Removes the rendering instructions from the documentation and the fixtures since they are not supported anymore.
> [TASK] Remove uneeded code

- Classes/ContentObject/Relation.php
This fixes the order in which related items are returned.
`RelationHandler` makes sure to sort items using the appropriate `sorting` key, but when the list of ids is fed to a query which only uses an `IN(a,b,...)` condition, the order is lost.
Cf. #1322
> Preserve sort order when fetching related records

- Classes/Domain/Index/IndexService.php
`getTrace()` returns references to the functions called which is a problem, because devlog calls `serialize()` on the data, leading to a `Serialization of 'Closure' is not allowed` exception.
With the typo3 logging system (so tx_solr 6.1+) this is apparently not a problem, because it uses `json_encode` which just produces `{}` for closures.
Fixes: #1342
> Fix logging of error when devlog is enabled

- Classes/Domain/Index/IndexService.php
As requested in #1341 
This is not a bugfix per se, because Typo3's log writers currently use `json_encode` to store the data which falls back to `{}` for closures.
However, `getTrace()` output has caused problems in the past (with `serialize()`).
> Log trace as string

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Tests/Integration/IndexQueue/Fixtures/update_record_outside_siteroot_from_other_siteroot.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
This PR:
* Fixes the bug (uses the recordPageId instead of the rootPageId to resolve the relevant rootPages)
* Adds an integration test
Fixes: #1347
> [BUGFIX] Tracking changes in record from other siteroot is not working as expected

- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/Examples/Facets/OptionsToggle/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/FAQ/Index.rst
- Documentation/Frontend/Concepts.rst
- Documentation/Frontend/Facets.rst
- Resources/Private/Partials/Facets/OptionsToggle.html
This PR:
* Remove the setting selectingSelectedFacetOptionsRemovesFilter from the documentation
* Documents how this can be done with Fluid core features
* Adds an example and faq entry
* Fixes wrong ts path in documentation
Fixes: #1351
> [TASK] Remove selectingSelectedFacetOptionsRemovesFilter and document alternatives

- Build/Test/cibuild.sh
The build should fail when only the unit tests fail.
> [TASK] Build not failing on failed unit test

- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
This pr:
* Updates the documentation to use lowercase asc / desc
* Makes the TyposcriptConfiguration object more robust, by lowercasing the setting before
* Adds unit tests for the method
Fixes: #1375
> [BUGFIX] Little documentation error sorting default order

- .scrutinizer.yml
- .travis.yml
- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Build/Test/publish_coverage.sh
- Tests/Integration/Controller/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Integration/IntegrationTest.php
- Tests/Unit/UnitTest.php
- composer.json
* Use  nimut/testing-framework
* Remove hhvm from scrutinizer
* Extract publishing of coverage to script
* Install build tools (php-cs-fixer, occular and typo3-repository-client) in bootstrap
> [TASK] Optimize test setup

- Classes/Plugin/FrequentSearches/FrequentSearches.php
Missing parameter type leads to warning in PHP7
> [BUGFIX] Missing parameter type in FrequentSearches::postInitializeTemplateEngine

- Dockerfile
Fixes #1278 for 6.1.* by cherrypicking d9fa187 into the release-6.1.x branch.
> [FEATURE] Explicitly create data folder before fixing permissions

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Query/Modifier/Elevation.php
- Classes/Query/Modifier/Faceting.php
- Classes/Search/DebugComponent.php
- Classes/Search/StatisticsComponent.php
- Tests/Unit/Query/Modifier/ElevationTest.php
- Tests/Unit/Query/Modifier/FacetingTest.php
- Tests/Unit/Search/StatisticsComponentTest.php
This PR:
* Reduces the amount of Util::getSolrConfiguration calls in the frontend to a minimum, by passing a reference when possible or
using SearchRequest::getContextTypoScriptConfiguration when possible.
Fixes: #1389
> [TASK] Avoid multiple calls of Util::getSolrConfiguration on frontend requests

- Classes/Domain/Search/ApacheSolrDocument/Repository.php
- Classes/Domain/Search/Query/Helper/EscapeService.php
- Classes/Domain/Search/Query/ParameterBuilder/Faceting.php
- Classes/Domain/Search/Query/ParameterBuilder/Filters.php
- Classes/Domain/Search/Query/ParameterBuilder/Grouping.php
- Classes/Domain/Search/Query/ParameterBuilder/Highlighting.php
- Classes/Domain/Search/Query/ParameterBuilder/ParameterBuilder.php
- Classes/Domain/Search/Query/ParameterBuilder/QueryFields.php
- Classes/Domain/Search/Query/ParameterBuilder/ReturnFields.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Query.php
- Classes/Query/Modifier/Faceting.php
- Classes/Search/HighlightingComponent.php
- Classes/SuggestQuery.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Unit/Domain/Query/Helper/EscapeHelperTest.php
- Tests/Unit/Domain/Query/ParameterBuilder/QueryFieldsTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/QueryTest.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
This PR reduces the amount of methods in the Query class by:
* Remove the usage of escapeMarkers since this was marked to be removed, when the old templating was dropped
* Extracting the escape logic into a seperate EscapeService since this is not directly related to the query itself and more about the formatting of the querystring itself
* Introducing the concept of ParameterBuilders
** ParameterBuilders are able to build the solr query parameters for a certain query part. This helps to split the logic into several components instead of having everything in the query.
** ParameterBuilders are available for "Faceting, Filters, Grouping, Highlighting, QueryFields and ReturnFields"
The following methods have been marked as deprecated:
* Query::setQueryFieldsFromString use …
> [!!!][TASK] Refactor the Query class

- Classes/Report/SolrConfigurationStatus.php
Use PagesRepository::findAllRootPages instead of $GLOBALS['TYPO3_DB']
Fixes: #1372
> [TASK] Migrate SolrConfigurationStatus::getPages to use PagesRepository (#1372)

- Classes/Domain/Search/ResultSet/Facets/AbstractFacet.php
- Classes/Domain/Search/ResultSet/Facets/FacetCollection.php
- Classes/Domain/Search/ResultSet/Facets/RequirementsService.php
- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
- Tests/Unit/Domain/Search/ResultSet/Facets/RequirementsServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
This pr:
* Adds the evaluation for requirements again.
* Requirements are evaluated on usedFacats and the property is requirementMet is set to false, when a facet has requirments that are not met.
Fixes: #1399
> [TASK] Add support for requirements again

- Classes/IndexQueue/Indexer.php
- Classes/Site.php
- Tests/Integration/IndexQueue/Fixtures/can_index_with_rootPage_set_to_hide_default_language.xml
- Tests/Integration/IndexQueue/IndexerTest.php
If the root page is set to 'hide default translation of page' this causes a 404 in TypoScriptFrontendController with initializing the TSFE. To avoid this a language uid has to be thrown to the initialize function.
> [FEATURE] Rootpage without defautllanguage

- Classes/IndexQueue/Indexer.php
- Classes/Site.php
- Tests/Integration/IndexQueue/Fixtures/can_index_with_rootPage_set_to_hide_default_language.xml
- Tests/Integration/IndexQueue/IndexerTest.php
If the root page is set to 'hide default translation of page'
this causes a 404 in TypoScriptFrontendController with initializing
the TSFE. To avoid this a language uid has to be thrown to the
initialize function.
* hand over a language uid to getSysLanguageMode:
if the default language is hidden on root page, use
another configured language uid. This avoid the 404
error during TSFE initializing.
* don't use solr defautl connection if no default lang is used:
if the default language is not in use, the default solr connection
must not be used.
* add integration test for hide default lang:
This integration test ensures, that there is no default solr connection
if default language is disabled on root page and no 404 error occures
with initialising TSFE.
> [TASK] allow 'hide default translation of page' on root page

- Classes/Domain/Search/LastSearches/LastSearchesWriterProcessor.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
- Tests/Integration/Controller/SearchControllerTest.php
This PR:
* Passes the SearchRequest instead of the rawQuery when possible in the SearchResultSetService
* Adds tests for the initial search with preconfigured and empty query
Fixes: #1407
> [TASK] Pass SearchRequest in SearchResultSetService instead of rawQuery when possible 

- Classes/IndexQueue/Indexer.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_translated_record_with_l_param.xml
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_translated_record_without_l_param.xml
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_translated_record_without_l_param_and_content_fallback.xml
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IntegrationTest.php
This PR:
* Removes the cache for $TSFE->sys_language_contentOL and intializes tsfe for every record (Util::initializeTsfe is cached anyways)
* Adds an integration test for the scenario (config.sys_language_mode = content_fallback; 0)
Fixes: #1416
> [BUG] Language is lost for link in custom record with sys_language_mode = content_fallback

- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Build/Test/cibuild.sh
- Build/Test/publish_coverage.sh
- Classes/ContentObject/Relation.php
- Classes/IndexQueue/Queue.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
- Tests/Integration/IndexQueue/Fixtures/fake_extension_table.sql
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_page_with_relation_to_page.xml
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_language_overlay_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_table.sql
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
Table pages has different handling over overlays. Now the ContantObject/Relation handles these correctly.
Takes the initial patch from #1400 and adds an integration test for the scenario.
Fixes: #1421
> [BUGFIX] Relation handler should handle pages overlays correctly

- Resources/Private/Templates/Search/Results.html
This PR:
* Adds a check to the default template if the frequentSearches, lastSearches, faceting or sorting is active and only render the partial when this is the case.
Note: If you do not use these features, please remove the rendering from your templates.
Fixes: #1423
> [TASK] Check in default template if several partials should be used

- Classes/Query.php
The method GeneralUtility::removeXSS has been deprecated in CMS8 ans
has been removed in CMS9. Replace it by calls to htmlspecialchars().
Resolves: #1439
> [TASK] Remove usage of GeneralUtility::removeXSS

- Classes/Backend/IndexingConfigurationSelectorField.php
The method FormResultCompiler::JStop has been deprecated in CMS8 and has been
removed in CMS9. Replace its usage with FormResultCompiler::addCssFiles.
Resolves: #1368
> [BUGFIX] Remove usage of FormResultCompiler::JStop

- Classes/ViewHelpers/Backend/Button/HelpButtonViewHelper.php
- Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
As the render method is deprecated and compilable is faster
there is no reason not to change the ViewHelper.
Resolves: #1453
> [TASK] Make HelpButtonViewHelper compilable

- Classes/Util.php
The NullTimeTracker has been deprecated with CMS8 and removed with
CMS9. Switch to the regular TimeTracker.
Resolves: #1461
> [BUGFIX] Fix usage of NullTimeTracker

- Classes/Access/RootlineElement.php
- Classes/Backend/IndexingConfigurationSelectorField.php
- Classes/ContentObject/Relation.php
- Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php
- Classes/Domain/Search/Query/ParameterBuilder/Faceting.php
- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/Query.php
- Classes/Query/Modifier/Faceting.php
- Classes/Site.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/System/Logging/DebugWriter.php
- Classes/System/TCA/TCAService.php
- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
switch from `==` to `===`. Not done currently if compared to empty string or with integers to avoid side effects
Resolves: #1479
> [TASK] Use strict string comparion

- Classes/Controller/Backend/PageModuleSummary.php
- Classes/Controller/SearchController.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/System/UserFunctions/FlexFormUserFunctions.php
- Configuration/FlexForms/Form.xml
- Configuration/FlexForms/Results.xml
- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrView.rst
- Tests/Integration/Controller/Backend/Fixtures/fakeFlexform.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Unit/System/UserFunctions/FlexFormUserFunctionsTest.php
Until version 6.1.x you can define a custom entry template e.g. with
plugin.tx_solr.templateFiles.results = EXT:solr/Resources/Templates/PiResults/results.htm
Due to the move to FLUID this setting was moved to the "view" section.
plugin.tx_solr.view.templateFiles.results = EXT:solr/Resources/Templates/PiResults/results.htm
Beside that it also supports(and this is also recommended) to just use the templateName
plugin.tx_solr.templateFiles.results = MyResults
By using this, you can benefit from the fallback that FLUID provides
To make the life easier for editors, you can also define a set of availableTemplates, that are selectable in the flexform:
Example:
```
plugin.tx_solr.view.templateFiles.results.availableTemplates {
default {
label = Default Searchresults Template
file = Results
} …
```
> [!!!][TASK] Make custom templates configureable

- Classes/ConnectionManager.php
- Classes/Domain/Index/IndexService.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/IndexQueue/PageIndexerRequest.php
- Classes/Query.php
- Classes/SolrService.php
- Classes/SuggestQuery.php
- Classes/System/Logging/SolrLogManager.php
- Tests/Unit/ConnectionManagerTest.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
- Tests/Unit/Domain/Search/ApacheSolrDocument/RepositoryTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
- Tests/Unit/Query/Modifier/FacetingTest.php
- Tests/Unit/QueryTest.php
- Tests/Unit/SolrServiceTest.php
- Tests/Unit/SuggestQueryTest.php
During the investigation for #1469 i recognized that the unit tests depend on a proper logger configuration. This is because the SolrLogManager is instanciated in many places and directly evaluatest the configuration.
To make the unit tests in dependent it should be possible to pass the SolrLogManager from outside and mock it.
Allong with that we should make sure that the logger is only instanciated when really something is logged.
Fixes: #1489
> [TASK] Make sure that UnitTest do not depend on proper logger configuration

- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Resources/Private/Templates/Search/Results.html
- Tests/Integration/Controller/SearchControllerTest.php
This pr:
* Enables the setting searchUsingSpellCheckerSuggestion for the FLUID templating
* Adds a test case
* Set's the default Setting of numberOfSuggestionsToTry to 1 since 0 as default makes no sence
Fixes: #1468
> [BUGFIX] searchUsingSpellCheckerSuggestion not supported.

- .travis.yml
This pr:
* Readds TYPO3 dev-master with allow_failure to keep track of problems with the current TYPO3 master
Fixes: #1499
> [TASK] Test against TYPO3 dev-master with allow_failure

- Classes/Util.php
Remove the following methods which are unused:
- `camelize`
- `camelCaseToLowerCaseUnderscored`
- `underscoredToUpperCamelCase`
- `pageExists`
These methods have been used only for the old templating. If you need an implementation of that, please
use the previous code in your extension.
Fixes: #1503
> [!!!][TASK] Remove unused functions from Util

- Classes/ViewHelpers/Widget/Controller/ResultPaginateController.php
- Classes/ViewHelpers/Widget/ResultPaginateViewHelper.php
By using the following code it is now possible to override the path of the
ResultPaginateViewHelper by defining the path in the configuration attribute:
<s:widget.resultPaginate
resultSet="{resultSet}"
configuration="{templatePath:'EXT:theme/Resources/Private/Templates/Solr/Paginate.html'}"
>
> [FEATURE] Allow to set the template of s:widget.resultPaginate

- Classes/Domain/Site/SiteRepository.php
- Classes/Report/SolrConfigurationStatus.php
- Classes/Site.php
- Classes/System/Service/SiteService.php
- Documentation/FAQ/Index.rst
- Documentation/Releases/solr-release-7-0.rst
- Resources/Private/Partials/Backend/NoSiteAvailable.html
- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
- Tests/Integration/Domain/Site/Fixtures/can_get_site_by_page_id.xml
- Tests/Integration/Domain/Site/SiteRepositoryTest.php
- Tests/Integration/SiteTest.php
- Tests/Unit/System/Service/SiteServiceTest.php
For some environments (e.g. automated deployment / cloud provides) the domain name can be provided by the environment and using the sys_domain record is complicated since it needs to be created by environment on the instance.
This pr allows:
* To configure the domains in $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['sites'][#
##rootPageId###]['domains'] = ['mydomain.com'];
* When nothing is configured there, a fallback to the sys_domain record is used.
* As soon as this is available in the TYPO3 core (maybe v 9.0) we will read the domain configuration from the central configuation.
* The calculation of the siteHash and of the solrConfiguration was moved to the repository to avoid doing this on each call.
Fixes: #1511
> [TASK] Get rid of dependency to sys_domain record.

- Classes/Backend/SolrModule/AdministrationModuleManager.php
- Classes/CommandResolver.php
- Classes/Facet/FacetRendererFactory.php
- Classes/Plugin/PluginCommand.php
This PR:
During the update from 6.1.x the localconf.php as a cached state that uses removed code. To avoid this we readd only the signature of those methods to avoid an php error.
The following signatures have been readded (and will be removed after the release of EXT:solr 7.0.0):
* AdministrationModuleManager::registerModule
* CommandResolver::registerPluginCommand
* PluginCommand
* FacetRendererFactory::registerFacetType
Allong with that it makes sence to clear the cache in your TYPO3 project after the autoloader dump:
```
"scripts": {
"post-autoload-dump": [
"rm -Rf {$web-dir}/typo3temp/Cache/*"
]
},
```
Fixes: #1518
> [TASK] Avoid error on update from 6.1.x

- .gitattributes
By using a .gitattributes file it is possible to reduce
the size of the project when using composer as all
files and directories with 'export-ignore' are not included then
> [TASK] Provide .gitattributes files

- Classes/Domain/Search/Score/ScoreCalculationService.php
Related Issue: https://github.com/TYPO3-Solr/ext-solr/issues/1444
Comes from: https://github.com/TYPO3-Solr/ext-solr/pull/1445/files
Fixes: #1444
> [TASK]Backport: Properly escape output of viewhelpers.

- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Build/Test/cibuild.sh
- Build/Test/publish_coverage.sh
- Classes/ContentObject/Relation.php
- Classes/IndexQueue/Queue.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_translated_record_with_mm_relation_to_a_page.xml
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_bar_tca.php
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
- Tests/Integration/IndexQueue/Fixtures/fake_extension_table.sql
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_page_with_relation_to_page.xml
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_language_overlay_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_table.sql
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
Table pages has diferent handling over overlays. Now the
ContantObject/Relation handles these correctly. Along with that, the functionallity
was added in the tests to import an ext_tables.sql like database definition.
Fixes: #1421
> [BUGFIX] Backport - Relation handler should handle pages overlays correctly (#1422)

- Configuration/FlexForms/Form.xml
- Configuration/FlexForms/Results.xml
Type "group" does not need a render type.
Resolves: #1537
> [BUGFIX] Remove wrong renderType

- Resources/Private/Templates/ViewHelpers/Widget/ResultPaginate/Index.html
To prevent the HTML tag from rendering in the final output add the fluid namespace data attribute.
Fixes: #1545
> [BUGFIX] Add fluid namespace data attribute to html tag

- Resources/Private/Templates/ViewHelpers/Widget/ResultPaginate/Index.html
To prevent the HTML from rendering in the final output add the fluid namespace data attribute
Fixes: #1545
> [BUGFIX] Add fluid namespace data attribute to html tag (#1546)

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
This pr:
Remove the method "setUseQueryAwareComponents" since it is not used anymore and the default value is true.
Fixes: #1558
> [TASK] Remove method SearchResultSetService::setUseQueryAwareComponents

- Classes/Domain/Search/Statistics/StatisticsRepository.php
TYPO3 CMS QueryBuilder before 8.7.4 does not accept 'as' for select aliases.
Fixes: #1562
> [BUGFIX] QueryBuilder does not quote aliases if 'as' is lower cased

- Configuration/TypoScript/Solr/constants.txt
- Configuration/TypoScript/Solr/setup.txt
To allow simple configuration of enabled Solr connections, this commit
introduces a constant for plugin.tx_solr.enabled.
Fixes: #1567
> [TASK] Introduce constant for plugin.tx_solr.enabled

- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
* fixed "top 5" and "search statistics" queries for correct calculations
* removed PHP calculations where possible and replace it with SQL
* adapted StatisticsRepositoryTest for SQLs results
Fixes: #1584
Backport from #1582
> [BUGFIX] Backport Fix sorting and counts in statistics module

- Classes/Domain/Search/Statistics/StatisticsRepository.php
* replace excl. MySQL functions with pure math in getQueriesOverTime()
* fixes faulty calculation, because bucket and calculated timestamp was calculated for wrong day
* closes #1556, because using new date column requires database migrations
Fixes: #1575
> [BUGFIX] MySQL Query for search buckets is faulty

- Classes/Domain/Search/Statistics/StatisticsRepository.php
after merging two PRs countByRootPageId() was defined twice
removed one definition of them
> [BUGFIX] remove second definition of countByRootPageId()

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Queue.php
Following functions extracted from Queue to QueueItemRepository
| Queue old | QueueItemRepository new | comment |
|-----------|:-----------------------|:-----------------------:|
| getLastIndexedRow() | findLastIndexedRow() | removed |
| getErrorsBySite() | findErrorsBySite() | delegation |
| resetAllErrors() | flushAllErrors() | delegation |
| updateExistingItem() | updateExistingItemByItemTypeAndItemUidAndRootPageId() | removed |
| addNewItem() | add() | delegation |
| getPageItemChangedTime() | getPageItemChangedTimeByPageUid() | delegation |
| getLocalizableItemChangedTime() | getLocalizableItemChangedTime() | removed |
| containsItem() | containsItem() | delegation |
| containsItemWithRootPageId() | containsItemWithRootPageId() | delegation |
| containsIndexedItem() | …
> [TASK] Extract queries from Queue to repository

- Classes/Domain/Search/Statistics/StatisticsRepository.php
* replace excl. MySQL functions with pure math in getQueriesOverTime()
* fixes faulty calculation, because bucket and calculated timestamp was calculated for wrong day
* Backport comes from #1591
Fixes: #1602, related #1575
>  [BUGFIX] Backport: MySQL Query for search buckets is faulty

- Classes/IndexQueue/PageIndexer.php
* using PagesRepository::findTranslationOverlaysByPageId()
inside PageIndexer::getSolrConnectionsByItem() instead of fetching from SQL directly
Fixes: #1597
> [TASK] Extract Queries from PageIndexer to Repo and rewrite to doctrine

- .travis.yml
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fakeResponse.json
This pr:
* Changes the expected id since the encryption key of the testing framework was changed (https://github.com/TYPO3/testing-framework/commit/ec72500b23d651862ca681d366393c428f957e4f).
* Allows master build to fail against 8.x-dev since there is another problem with FLUID fallbacks
Fixes: #1607
> [TASK] Check why master build fails

- .travis.yml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
This pr:
* Sets the path to "module.tx_solr" because the test is running in the backend context
* We need to find a solution to run it in a real frontend context
> [TASK] Check why custom template is not used

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/Initializer/Page.php
SQL building still happens in AbstractInitializer but SQL is executed by Doctrine DBAL
So other DBMS platforms should work and CMS 9 compatibility is provided
Following Methods were changed:
* AbstractInitializer::logInitialization() and usages adapted for new implementation,
which will be removed after rewriting to doctrine. Also Initializer\Page::addMountedPagesToIndexQueue()
* AbstractInitializer::initialize() uses QueueItemRepository::initializeByNativeSQLStatement()
* added QueueItemRepository::initializeByNativeSQLStatement()
Fixes: #1610
> [TASK] rewrite/extract queries from IndexQueue\Initializer\AbstractInitializer

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/System/Records/Pages/PagesRepository.php
Following Methods were changed:
| Initializer\Page old | QueueItemRepository new | comment for old method|
|-----------|:-----------------------|:-----------------------:|
| getPageIdsOfExistingMountPages() | findPageIdsOfExistingMountPagesByMountIdentifier() | removed |
| addMountedPagesToIndexQueue() | - | uses QueueItemRepository::initializeByNativeSQLStatement() instead of executing directly |
| addIndexQueueItemIndexingProperties() | findAllIndexQueueItemsByRootPidAndMountIdentifierAndMountedPids() | using in step |
| findMountPages() | PagesRepository::findAllMountPagesByWhereClause() | removed |
Fixes: #1599
> [TASK] rewrite/extract queries from Initializer\Page

- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
Following method added for BC:
* IntegrationTest::getDatabaseConnectionBC()
Following methods rewritten to doctrine:
* IntegrationTest::importDumpFromFixture()
* IntegrationTest::importExtTablesDefinition()
* GarbageCollectorTest::canQueueAPageAndRemoveItWithTheGarbageCollector()
* GarbageCollectorTest::canCollectGarbageFromSubPagesWhenPageIsSetToHiddenAndExtendToSubPagesIsSet()
* GarbageCollectorTest::canCollectGarbageFromSubPagesWhenPageIsSetToHiddenAndExtendToSubPagesIsSetForMultipleSubpages()
* RecordMonitorTest::canUpdateRootPageRecordWithoutSQLErrorFromMountPages()
* RecordMonitorTest::canQueueSubPagesWhenExtendToSubPagesWasSetAndHiddenFlagWasRemoved()
* RecordMonitorTest::canQueueSubPagesWhenHiddenFlagIsSetAndExtendToSubPagesFlagWasRemoved()
* …
>  [TASK] rewrite queries from Tests/* to doctrine

- Classes/Domain/Index/Queue/Statistic/QueueStatisticsRepository.php
- Classes/IndexQueue/Queue.php
| Queue old | *Repository new | comment for old method|
|-----------|:-----------------------|:-----------------------:|
| Queue::getItemCount() | count() delegated via Queue::getAllItemsCount() directly | removed |
| Queue::getStatisticsBySite() | QueueStatisticsRepository::findOneByRootPidAndOptionalIndexingConfigurationName() | delegation |
| Queue::buildIndexConfigurationConstraint() | - | removed |
Fixes: #1621
> [TASK] extract query from Queue to QueueItemRepository

- Configuration/TypoScript/Solr/setup.txt
The following ts pathes have been removed in 7.0.0 but should be kept with the fluid equivalent:
* tx_solr_PiResults_Results
* tx_solr_PiSearch_Search
* tx_solr_PiFrequentSearches_FrequentSearches
This pr adds those typoscript pathes again and renders the extbase controller
Fixes: #1561
> [BUGFIX] Make plugin.tx_solr_PiSearch_Search available again

- Classes/Domain/Index/Queue/Statistic/QueueStatisticsRepository.php
- Tests/Integration/IndexQueue/Fixtures/can_get_statistics_by_site_and_custom_indexing_configuration.xml
- Tests/Integration/IndexQueue/QueueTest.php
added test case for fetching statistics by custom indexingConfigurationName
Fixes: #1630
> [BUGFIX] doctrines query builder doesn't add 'where' append

- Classes/Domain/Index/Queue/IndexQueueIndexingPropertyRepository.php
- Classes/IndexQueue/Item.php
Following was changed:
| Item old | IndexQueueIndexingPropertyRepository new | comment for old method |
|-----------|:-----------------------|:-----------------------:|
| Item::removeIndexingProperties() | removeByRootPidAndIndexQueueUid() | removed using directly in Item::storeIndexingProperties() |
| Item::writeIndexingProperties() | bulkInsert() | delegation |
| Item::loadIndexingProperties() | findAllByIndexQueueUid() | delegation |
Fixes: #1620
> [TASK] extract queries from Item to IndexQueueIndexingPropertyRepository

- Classes/IndexQueue/Initializer/Page.php
- Classes/System/Records/AbstractRepository.php
- Classes/Utility/DatabaseUtility.php
* deprecated DatabaseUtility class and replaced with doctrines transaction methods
* added AbstractRepository::getConnectionForAllInTransactionInvolvedTables()
* replaced usages of DatabaseUtility::*
Fixes: #1622
> [TASK] Deprecate DatabaseUtility and replace it with native Doctrine

- Classes/ContentObject/Relation.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_multiple_mm_relations.xml
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
- Tests/Integration/IndexQueue/IndexerTest.php
The old MySQL-Only native function "FIELD(uid..." is not supported by other platforms,
therefore we need to order it in PHP
Fixes: #1370
> [TASK] Use doctrine in ApacheSolrForTypo3\Solr\ContentObject\Relation

- Configuration/TypoScript/Solr/constants.txt
- Configuration/TypoScript/Solr/setup.txt
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fakeResponse.json
This pr:
* Changes the expected id since the encryption key of the testing framework was changed.
* since CMS 8.7.5 templates -, partials - and layout paths must be set
* Sets the path to "module.tx_solr" because the test is running in the backend context
* We need to find a solution to run it in a real frontend context
Comes From: #1611, #1616, #1625, 
Fixes: #1644, fixes: #1633
> [TASK] Backport: Check why build fails

- Configuration/TypoScript/Solr/setup.txt
The following ts pathes have been removed in 7.0.0 but should be kept with the fluid equivalent:
* tx_solr_PiResults_Results
* tx_solr_PiSearch_Search
* tx_solr_PiFrequentSearches_FrequentSearches
This pr adds those typoscript pathes again and renders the extbase controller
comes from PR: #1629
Fixes: #1632
> [BUGFIX] Backport: Make plugin.tx_solr_PiSearch_Search available again

- Documentation/Solr/IndexMaintenance.rst
With the current command, i'll end up with a datadir of `/<installation-path>/server/solr/core_de/dataDir=../../data/german/`
> IndexMaintenance documentation: fix params in create core call

- Classes/ViewHelpers/TranslateViewHelper.php
- Classes/Widget/AbstractWidgetViewHelper.php
- Resources/Private/Templates/ViewHelpers/Widget/ResultPaginate/Index.html
This pr:
* Enabled the escaping for the Translate and AbstractWidgetViewHelper to avoid the output of unwanted content.
> [TASK] Enable escaping in TranslateViewHelper and AbstractWidgetViewHelper

- Classes/Controller/AbstractBaseController.php
- Classes/Controller/SearchController.php
- Classes/Controller/SuggestController.php
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Controller/SearchControllerTest.php
Currently the solr server is pinged before every request. In the most cases the solr server is available and the unavailablility is an exception. Therefore we do not ping the solr server and catch a missing connection in the catch block. By using this approach we need to do only one request to the solr server in the most cases instead of two before. This finally improves the speed of the search.
Fixes: #1404
> [TASK] Do not ping solr server before search

- Classes/Domain/Search/Query/ParameterBuilder/Faceting.php
- Classes/Domain/Search/ResultSet/Facets/DefaultFacetQueryBuilder.php
- Classes/Domain/Search/ResultSet/Facets/SortingExpression.php
- Tests/Unit/Domain/Search/ResultSet/Facets/SortingExpressionTest.php
- Tests/Unit/Query/Modifier/FacetingTest.php
This pr:
* Allows to overwrite the sorting on facet base back to count
* Extracts the logic to generate the sorting into an own class
* Uses this class in the DefaultFacetQueryBuilder and Faceting parameter builder
Fixes: #1666
> [BUGFIX] Can not overwrite facet sortBy to count

- Classes/Domain/Search/ResultSet/Result/Parser/AbstractResultParser.php
- Classes/Domain/Search/ResultSet/Result/Parser/DefaultResultParser.php
- Classes/Domain/Search/ResultSet/Result/Parser/ResultParserRegistry.php
- Tests/Unit/Domain/Search/ResultSet/Result/Parser/DefaultParserTest.php
To allow a simple registration, there should not be a constructor dependency to TypoScriptConfiguration for the result parsers.
> [TASK] Remove constructor dependency to TypoScriptConfiguration from ResultParser

- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fakeResponse.json
A change of the encryptionkey in the testingframework was the reason for
failing builds in the master branch. This pr backports the fix for the 6.5.x branch.
Relates: #1607
> [BUGFIX] Backport fix for encyptionkey change in testingframework

- Classes/ContextMenu/ItemProviders/InitializeConnectionProvider.php
The identifier field of AbstractProvider is defined as being of type string.
The RootPageResolver expects an int as argument for the call to getIsRootPageId(). This mismatch
causes a check for pageId 0 to fail
> [BUGFIX] Convert function argument to int to match signature

- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/Examples/Facets/Options/setup.txt
- Resources/Public/JavaScript/facet_options_controller.js
The javascript to toggle the visibility of facet options was missing.
This pr, adds the facet_options_controller.js that add's the toggeling again.
Beside that an example typoscript file for the options facet was added, that
includes this javascript file in TYPO3.
Fixes: #1713
> [TASK] "Show more" and "Show less" javascript is missing

- Classes/Domain/Search/ResultSet/Facets/OptionBased/OptionCollection.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/Option.php
- Classes/ViewHelpers/Facet/Options/Group/Prefix/LabelFilterViewHelper.php
- Classes/ViewHelpers/Facet/Options/Group/Prefix/LabelPrefixesViewHelper.php
- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/Examples/Facets/OptionsPrefixGrouped/setup.txt
- Documentation/Development/ViewHelpers.rst
- Documentation/Frontend/Facets.rst
- Resources/Private/Partials/Facets/OptionsPrefixGrouped.html
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionCollectionTest.php
- Tests/Unit/ViewHelpers/Facet/Options/Group/Prefix/LabelFilterViewHelperTest.php
- Tests/Unit/ViewHelpers/Facet/Options/Group/Prefix/LabelPrefixesViewHelperTest.php
This pr:
* Adds the possibility to group facet options by a prefix
* This can be used, e.g. to group the facet options alphabetically by the first letter
* Adds an example configuration "Search - (Example) Options grouped by prefix" that uses the logic to group the author options by starting letter
Fixes: #1715
> [TASK] Allow to group facet options by prefix

- Classes/ViewHelpers/Widget/Controller/ResultPaginateController.php
- Resources/Private/Templates/Search/Results.html
fix start attribute for <ol> tag by calculating and adding a proper count into the pagination data.
Resolves: #1681
> [BUGFIX] broken count in pagination #1681

- Classes/ContentObject/Classification.php
- Classes/Domain/Index/Classification/Classification.php
- Classes/Domain/Index/Classification/ClassificationService.php
- Classes/IndexQueue/AbstractIndexer.php
- Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
- Classes/IndexQueue/PageIndexer.php
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Tests/Unit/ContentObject/ClassificationTest.php
- Tests/Unit/Domain/Index/Classification/ClassificationServiceTest.php
- Tests/Unit/IndexQueue/AbstractIndexerTest.php
- Tests/Unit/IndexQueue/InvalidSerializedValueDetector.php
- Tests/Unit/IndexQueue/ValidSerializedValueDetector.php
- ext_localconf.php
This pr:
* Adds the SOLR_CLASSIFICATION cObject that can be used to classify documents based on configured patterns.
Example:
```
plugin.tx_solr.index.queue.pages.fields.topic_stringM = SOLR_CLASSIFICATION
plugin.tx_solr.index.queue.pages.fields.topic_stringM {
field = __solr_page_content
classes {
programming {
patterns = php, java, javascript, go
class = programming
}
cms {
patterns = TYPO3, joomla
class = cms
}
database {
patterns = mysql, MariaDB, postgreSQL
class = database
}
}
}
```
Fixes: #1722
> [TASK] Add SOLR_CLASSIFICATION content object

- Configuration/TypoScript/Solr/constants.txt
- Configuration/TypoScript/Solr/setup.txt
Furthermore use the constants as primary location and define extension
templates as default fallback. This allows to define own paths with
the need to copy all templates / partials / layouts to that new location.
Fixes: ##1727
> [BUGFIX] Use view constants correctly in setup configuration

- Documentation/Configuration/Reference/TxSolrSearch.rst
This pr:
Add's the missing option "partialName" to the TypoScript reference.
Fixes: #1673
> [BUGFIX] Add [facet].partialName to reference

- Classes/Task/AbstractSolrTask.php
- Classes/Task/IndexQueueWorkerTask.php
- Classes/Task/ReIndexTask.php
- Tests/Unit/Task/ReIndexTaskTest.php
When a task for an invalid site is configured the scheduler shows an exception message.
This pr:
* Catches and logs the exception
* Shows and error message in the desription that the scheduler task should be recreated
Fixes: #1669
> [BUGFIX] Scheduler unuseable with invalid site

- Classes/Domain/Search/ApacheSolrDocument/Repository.php
- Classes/Domain/Search/Query/QueryBuilder.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/Suggest/SuggestService.php
- Tests/Unit/Domain/Search/ApacheSolrDocument/RepositoryTest.php
- Tests/Unit/Domain/Search/Suggest/SuggestServiceTest.php
This pr:
* Extracts the QueryBuilder from the SearchResultSetService and SuggestService to centralize the logic where queries get build
Fixes: #1736
> [TASK] Extract QueryBuilder from SearchResultSetService and SuggestService

- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/Examples/Facets/OptionsFiltered/setup.txt
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Partials/Facets/OptionsFiltered.html
- Resources/Public/JavaScript/facet_options_controller.js
When you have an options facet with a lot of items you might want to allow the user to filter those options with a seperat filter field.
This pr:
* Add's an options partial "OptionsFiltered" that renders a search box above the facet that allows to filter the options
Fixes: #1436
> [TASK] Add filtered options partial

- Classes/System/Service/ConfigurationService.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Unit/System/Service/ConfigurationServiceTest.php
This pr:
* Adds quotes to filters defined in the flexform to allow filters with whitespaces
Fixes: #1742
> [BUGFIX] Add quotes for filters from flexform

- Resources/Private/Php/SolrPhpClient/Apache/Solr/Response.php
If a field is an array, an array should be returned within Solr
document. This is necessary for e.g. be able to iterate over a property
in a Fluid file. If returning either an array or a string, an exception
in Fluid is thrown because it expects an array.
Resolves: #1689
> [BUGFIX] Always return value as expected

- Configuration/FlexForms/Form.xml
This pr:
* Removes the deprecated options "show_thumbs" and "wizards" from the flexform
See also:
https://docs.typo3.org/typo3cms/extensions/core/8.7/Changelog/8.6/Deprecation-79440-TcaChanges.html
Fixes: #1750
> [TASK] Remove deprecated "show_thumbs" and "wizards" from Forms action flexform

- Documentation/FAQ/Index.rst
This pr:
* Add's an faq entry, how to build a facet where the options remain and options with a count of 0 keep displayed.
Fixes: #1749
> [TASK] Add faq about faceting.minimumCount

- Classes/Search.php
This pr:
* Deprecates unused code in the Search class to be removed in EXT:solr 9.0.0
Fixes: #1755
> [TASK] Deprecate unused code in Search class

- Classes/HtmlContentExtractor.php
- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
This pr:
* Escapes < when it is not used in the context of a tag to allow to index it as character of the content
* Add's several unit tests for the Typo3PageContentExtractor
Fixes: #1541
> [BUGFIX] Allow < as character in the content

- Classes/Domain/Search/Query/ParameterBuilder/Faceting.php
- Classes/Domain/Search/ResultSet/Facets/AbstractFacetItem.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/AbstractOptionFacetItem.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/Option.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilder.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsPackage.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/Domain/Search/ResultSet/Fixtures/fake_solr_response_with_multiple_fields_facets.json
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilderTest.php
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fake_solr_response_with_jsonfacets.json
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fake_solr_response_with_multiple_fields_facets.json
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fake_solr_response_with_two_used_facets.json
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fake_solr_response_with_used_facet.json
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
- Tests/Unit/Query/Modifier/FacetingTest.php
Since Apache Solr 5.x there is a new json faceting api available that enhances the possibility of facetting with solr.
This pr:
* Migrates the options facets to use the new json faceting api
* Allows to use the configuration minimumCount, sortBy and facetingLimit on a facet base
* Adds a new feature called "metrics" that allow to collect statistical data of facetted items
Thanks to Jens Jacobsen who worked on that at the codesprint 2017 and ueberbit that sponsored his working time for that.
Fixes: #1137
> [TASK] Support json faceting for options facet

- Classes/Domain/Search/ResultSet/Facets/OptionBased/OptionCollection.php
- Classes/ViewHelpers/Facet/Options/Group/Prefix/LabelFilterViewHelper.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionCollectionTest.php
- Tests/Unit/ViewHelpers/Facet/Options/Group/Prefix/LabelFilterViewHelperTest.php
This pr:
* Replaces the usage of the substr and strlen methods for the facet grouping by prefix to allow multibyte characeters
* Add's unit tests for this
Fixes: #1780
> [BUGFIX] FacetGroupByPrefix should handle multibyte characters correctly

- composer.json
Pin's the testing framework to 2.0.1. Afterwards we should fix the sql strict issues and
update to 2.0.2 of the testing framework again.
Fixes: #1786
> [TASK] Pin testing framework to 2.0.1

- Classes/Domain/Search/ResultSet/Facets/AbstractFacetItemCollection.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionCollectionTest.php
When the method getByValue is called on an FacetItemCollection the value is used
as internal accessor. Therefore the key needs to be set, when the collection is copied to be able
to access the value afterwards.
Fixes: #1711
> [BUGFIX] Missing array keys in facet options after manual sorting

- composer.json
- ext_emconf.php
This pr:
* Makes the version constraint in composer.json more precise
* Allows to install in 9.0 by ext_emconf.php constraint
* Changes the depedency to the TYPO3 core by using typo3/cms-core instead of typo3/cms
Fixes: #1782
> [TASK] Allow to install with TYPO3 9 CMS

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/Domain/Search/LastSearches/LastSearchesRepository.php
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Domain/Index/Queue/Fixtures/update_has_indexing_properties_flag.xml
- Tests/Integration/Domain/Index/Queue/QueueItemRepositoryTest.php
- Tests/Integration/Domain/Search/LastSearches/LastSearchesRepositoryTest.php
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_language_overlay_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_table.sql
- composer.json
This pr:
* Uses the latest version of the testing framwork again (with strict sql mode)
* Add's missing default values for custom sql fixtures
* Fixes a bug in the QueueItemRepository::updateHasIndexingPropertiesFlagByItemUid
* Changes the port in can_render_error_message_when_solr_unavailable.xml to avoid port collisions
Fixes: #1785
> [TASK] Allow to run with strict SQL mode

- Classes/Domain/Search/ResultSet/SearchResult.php
- Classes/Domain/Search/ResultSet/SearchResultBuilder.php
- Classes/Search.php
Replaces calls to GeneralUtitlity::logDeprecatedFunction with trigger_error, since GeneralUtility::logDeprecatedFunction will be removed and the extension scanner in TYPO3 9 suggest to replace it.
Fixes: #1797
> [TASK] Replace calls to GeneralUtility::logDeprecatedFunction with trigger_error(..., E_USER_DEPRECATED);

- Classes/IndexQueue/PageIndexerRequest.php
This pr:
* Removes the usage of TYPO3_user_agent and uses the configuration of $GLOBALS['TYPO3_CONF_VARS']['HTTP']['headers']['User-Agent'] instead
Fixes: #1800
> [TASK] Remove usage of constant TYPO3_user_agent

- Configuration/TCA/Overrides/sys_template.php
- Configuration/TypoScript/Examples/IntroPackageSearchBox/setup.txt
- Documentation/FAQ/Index.rst
This pr:
* Add's an FAQ entry, how the searchbox can be added on every page
* Removes the Introduction example to add the searchbox, since there is no searchbox in the introduction package anymore
Fixes: #869
> [TASK] Add example to add searchbox on every page

- Classes/Domain/Search/SearchRequest.php
- Classes/Domain/Search/Uri/SearchUriBuilder.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
When a facet is changed, the paginations of the groups should be resetted since the number
of results might change and the page is not valid anymore.
Fixes: #1808
> [TASK] Group pagination should be resetted when facet is changed

- Classes/ContentObject/Relation.php
- Tests/Integration/ContentObject/Fixtures/solr_relation_can_fallback_to_pages_table_if_no_tca_for_local_field.xml
- Tests/Integration/ContentObject/Fixtures/solr_relation_can_get_related_items_using_original_uid_if_sys_lang_overlay_has_no_tca.xml
- Tests/Integration/ContentObject/RelationTest.php
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
missing column settings in TCA for pages_language_overlay must be fetched from pages TCA
Backported from: #1816
Fixes: #1812
> [BUGFIX] fallback to pages on SOLR_RELATION on missing TCA for pages_language_overlay

- .scrutinizer.yml
- .travis.yml
- Build/Test/bootstrap.sh
- Classes/ContentObject/Relation.php
- Classes/Domain/Search/Query/QueryBuilder.php
- Classes/System/Records/Pages/PagesRepository.php
- Classes/System/Records/SystemDomain/SystemDomainRepository.php
- Classes/ViewHelpers/Widget/FrequentlySearchedViewHelper.php
- Classes/ViewHelpers/Widget/GroupItemPaginateViewHelper.php
- Classes/ViewHelpers/Widget/LastSearchesViewHelper.php
- Classes/ViewHelpers/Widget/ResultPaginateViewHelper.php
- Classes/Widget/AbstractWidgetViewHelper.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Report/Fixtures/can_detect_indexing_disabled.v9.xml
- Tests/Integration/Report/Fixtures/can_detect_missing_rootpage.v9.xml
- Tests/Integration/Report/Fixtures/can_get_green_solr_configuration_status_report.v9.xml
- Tests/Integration/System/Records/SystemDomain/Fixtures/sys_domain.v9.xml
- Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/FacetRegistryTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/ResultSet/Sorting/SortingTest.php
- composer.json
This pr:
* Updates the testing framework to 3.x
* Fixes issues in the tests that are related to the update
* Use inject* Methods inject of injection Annotations since this is a compatible way for TYPO3 8 and 9
* Updates scrutinizer configuration to allow to exclude the typo3/cms-install package
Fixes: #1823
> [TASK] Update nimut/testing-framework to 3.x and allow to install with TYPO3 9.1

- .scrutinizer.yml
- Classes/IndexQueue/PageIndexerRequest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
This pr:
* Readds the missing User-Agent: prefix that was removed during the removal of the TYPO3_user_agent constant.
See also: #1801
Fixes: #1827
> [BUGFIX] User-Agent not properly set for http header

- Classes/System/Solr/SolrConnection.php
During to the `SolrService/SolrConnection` refactoring, the method `__toString()` is missing, but still called in 
`Classes/IndexQueue/FrontendHelper/PageIndexer.php` (line 303) causing in Fatal (but recoverable) PHP Errors while indexing.
The patch adds the missing method again, which works just fine for our use cases (TYPO3 v9, solr-master)
> SolrConnection should have a string representation

- Classes/System/Records/Pages/PagesRepository.php
- Classes/System/Records/SystemLanguage/SystemLanguageRepository.php
For TYPO3 v9, pages can have multiple languages.
If TYPO3 v9 has translated pages, the siteroot
is checked for that translated page as well.
Currently, solr fetches connections for all
is_siteroot pages, setting up too many connections.
Additionally, only fetch languages which are
not hidden in the system to create connections.
> [TASK] Limit pages to default language

- Documentation/Configuration/Reference/TxSolrSearch.rst
This pr:
* Add's the missing setting plugin.tx_solr.spellchecking.searchUsingSpellCheckerSuggestion to the reference
Fixes: #1825
> [TASK] Add spellchecking.searchUsingSpellCheckerSuggestion to reference

- Classes/Domain/Search/SearchRequest.php
- Classes/Domain/Search/Uri/SearchUriBuilder.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
This pr:
* Allows to use solr queries as $groupItemValue and generate proper urls
Fixes: #1852
> [BUGFIX] SearchRequest::setGroupItemPage should be able to handle a solr group query as $groupItemValue

- Classes/Domain/Search/Query/ParameterBuilder/Grouping.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Unit/Domain/Search/Query/ParameterBuilder/GroupingTest.php
This pr:
* Moves the setting from a grouped based setting to a global grouping setting, since the sorting can not be set on a group base in apache solr
Fixes: #1855
> [TASK] sortBy should be a global grouping setting, not on a group base

- Classes/ViewHelpers/SearchFormViewHelper.php
- Tests/Unit/ViewHelpers/SearchFormViewHelperTest.php
This pr:
* Passes $pageUid after merging arguments and TypoScript configuration
* Add's a testcase for all scenarios
Fixes: #1860
> [BUGFIX] targetPageId is not used in SearchFormViewHelper

- Classes/ViewHelpers/Backend/Security/IfHasAccessToModuleViewHelper.php
This pr:
* Add's a render method to IfHasAccessToModuleViewHelper to avoid a warning with TYPO3 8
* The method can be removed when TYPO3 8 support is dropped
Fixes: #1864
> [BUGFIX] PHP Warning in BE module "Index Queue"

- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetServiceTest.php
The "search" method in the SearchResultSetService is very long an complex and could be split into multiple methods.
This pr:
* Splits the method into multiple methods
* Add's unit tests for several use cases
Fixes: #1871
> [TASK] Reduce complexity of search method in SearchResultSetService

- Classes/Domain/Search/ResultSet/Sorting/SortingHelper.php
- Classes/Search/SortingComponent.php
- Classes/Sorting.php
- Tests/Unit/Domain/Search/ResultSet/Sorting/SortingHelperTest.php
- Tests/Unit/Domain/Search/ResultSet/Sorting/SortingTest.php
- Tests/Unit/Search/SortingComponentTest.php
This pr:
* Moves the logic fom ApacheSolrForTypo3\Solr\Sorting to ApacheSolrForTypo3\Solr\Domain\Search\ResultsSet\Sorting\SortingHelper
* Deprecated the methods getSortFields and getSortOptions since they are not used anymore
Fixes: #1872
> [TASK] Move Sorting to Domain/Search/ResultSet/Sorting/SortingHelper

- Classes/Controller/Backend/AjaxController.php
In TYPO3 v9, all Routes should return a PSR-7 compatible Response object.
However "updateConnections"  does not do so, resulting in a PHP error.
Also valid for EXT:solr v8.0.1
> [BUGFIX] Ensure AjaxController returns a response

- Build/Test/bootstrap.sh
This pr:
* Add's the flag "--use-defaults" to the bootstrap.sh script
* This allows use to use "source ./Builds/Test/bootstrap.sh --use-defaults" in the devbox to bootstrap the testing environment on the devbox
Fixes: #1851
> [TASK] Add --use-defaults to bootstrap.sh script

- Classes/Controller/Backend/AjaxController.php
* [BUGFIX] Ensure AjaxController returns a response
In TYPO3 v9, all Routes should return a PSR-7 compatible Response object.
However "updateConnections"  does not do so, resulting in a PHP error.
* Return an empty Response object for ClearCacheMenu item
> [BUGFIX] Ensure AjaxController returns a response (#1875)

- Classes/Domain/Search/ResultSet/Result/SearchResult.php
- Classes/Domain/Search/Suggest/SuggestService.php
- Resources/Public/JavaScript/suggest_controller.js
This pr:
* Adapts the SuggestService to render the grouping value
* Set the category from the group in the suggest_controller.js
* This allows to render groups in the suggest as well when solrfluidgrouping is installed
Fixes: #1881
> [TASK] Groups should be respected in suggest as well

- Classes/Domain/Search/Query/Helper/Pagination.php
Changes the default value for $resultPerPage to 10
> [BUGFIX] Default value for $resultsPerPage should be 10

- Classes/Controller/Backend/PageModuleSummary.php
- Resources/Private/Templates/Backend/PageModule/Summary.html
- Tests/Integration/Controller/Backend/PageModuleSummaryTest.php
This commit extends the hook PageModuleSummary displaying information about
the plugins flexform settings in the page module. Now the plugin name will
be displayed and linked to the edit form, similiar to the default behaviour.
Fixes: #1896
> [TASK] Display plugin name in page module

- Classes/IndexQueue/PageIndexerResponse.php
When using an nginx server and libcurl 7.57.0 indexing did not work with libcurl error 61. This was because Content-Encoding "gzip" was requested but "normal" was returned. To prevent this I changed the header to send a Content-Type instead of Content-Encoding. This also works with apache. It should also work behind Varnish, but this needs to be tested.
> [BUGFIX] prevent CURLE_BAD_CONTENT_ENCODING

- Build/Test/bootstrap.sh
This pr:
* Uses bash_source instead $0 to be able to bootstrap also when $0 is not set (e.g. docker)
Fixes: #1898
> [BUGFIX] Use bash_source instead of $0

- Classes/Controller/Backend/PageModuleSummary.php
- Resources/Private/Templates/Backend/PageModule/Summary.html
- Tests/Integration/Controller/Backend/PageModuleSummaryTest.php
This commit extends the hook PageModuleSummary displaying information about
the plugins flexform settings in the page module. Now the plugin name will
be displayed and linked to the edit form, similiar to the default behaviour.
Fixes: #1896
> [TASK] Display plugin name in page module (#1897)

- Classes/IndexQueue/PageIndexerResponse.php
When using an nginx server and libcurl 7.57.0 indexing did not work with
libcurl error 61. This was because Content-Encoding "gzip" was requested
but "normal" was returned. To prevent this I changed the header to send
a Content-Type instead of Content-Encoding. This should also work with
apache and also behind Varnish, but should be tested.
> [BUGFIX] prevent CURLE_BAD_CONTENT_ENCODING (#1895)

- Classes/Domain/Search/SearchRequest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
* Add's a testcase and fixes the bug
Fixes: #1903
> [BUGFIX] SearchRequest::getHighestGroupPage should return 1 even when group was passed

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/Site.php
- Tests/Integration/Domain/Index/Queue/Fixtures/can_count_items.xml
- Tests/Integration/Domain/Index/Queue/Fixtures/can_delete_item_by_type.xml
- Tests/Integration/Domain/Index/Queue/Fixtures/can_delete_item_by_type_and_uid.xml
- Tests/Integration/Domain/Index/Queue/Fixtures/can_find_items.xml
- Tests/Integration/Domain/Index/Queue/QueueItemRepositoryTest.php
This pr:
* Add's a new method deleteItems to the QueueItemRepository class
* Uses this method internally when it is possible
* Add's testcases for uncovered parts
Fixes: #1918
> [TASK] Make find/delete/count of queue items more flexible

- Build/Test/bootstrap.sh
This pr:
* Installs symfony/finder:4.0.6 when TYPO9 is installed
Fixes: #1929
> [TASK] Check why master build is broken with TYPO3 9

- Resources/Private/Templates/Search/Results.html
Due to the introduction of the `QueryStringContainer` the `keywordsCleaned` isn't directly accessible through `resultSet.usedQuery` anymore. Now is't accessible through `resultSet.usedQuery.queryStringContainer.keywordsCleaned`.
> [BUGFIX] Use correct property to show searched keywords

- Resources/Private/Partials/Search/Form.html
- Resources/Public/JavaScript/suggest_controller.js
Using an additional class makes it possible to disable setting the
focus without using a own copy of the suggest javascript.
Resolves: #1922
> [TASK] Use additional class for focus on search query input

- Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
Two options:
* datetime as a string
* datetime as a date field
Closes #1943
> Add datetime to tx_news indexer

- .travis.yml
- Classes/ViewHelpers/TranslateViewHelper.php
- Tests/Integration/ContentObject/RelationTest.php
- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_mulitple_mm_relations.v9.xml
- Tests/Integration/IndexQueue/Fixtures/queue_entry_stays_when_overlay_set_to_hidden.v9.xml
- Tests/Integration/IndexQueue/IndexerTest.php
This pr:
* Skips the test RelationTest::canFallbackToPagesTableIfPagesLanguageOverlayTCAHasNoDefinitionForLocalColumn in TYPO3 9 since it is not required for TYPO3 9, because pages_language_overlay is dropped and therefore the TCA for that is allways not defined
* Make the TranslateViewHelper compatible for the optimizations that have been introduced with: https://github.com/TYPO3/TYPO3.CMS/commit/e6f470ebd2ddac7f0c864fd7c18c3d12a9009c30
* Fixes some GarbageCollector tests that pass an instance of Item instead of the pageId to the TSFE initialization
Fixes: #1953
> [TASK] Fix build against TYPO3 9.2

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Queue.php
- Tests/Integration/IndexQueue/Fixtures/can_flush_errors.xml
- Tests/Integration/IndexQueue/QueueTest.php
This pr:
* Add's a method flushErrorsBySite to the QueueItemRepository
* Add's a method resetErrorsBySite to the Queue
* Refactors QueueItemRepository:flushAllErrors to use the same logic as QueueItemRepository::flushErrorsBySite
Fixes: #1953
> [TASK] Allow to flush queue errors by site in the API

- Documentation/Frontend/Autosuggest.rst
This pr:
* Removes the jQueryUi information from the Autosuggest.rst since it is not used anymore
Fixes: #1917
> [BUGFIX] Remove jQuery ui related information from autosuggest documentation

- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
To avoid exceptions shown to the user, this exception must be caught and logged.
Fixes: #1974
> [TASK] Catch NoPidException in RecordMonitor

- Classes/IndexQueue/RecordMonitor.php
- Classes/System/TCA/TCAService.php
- Classes/Util.php
- Tests/Unit/System/TCA/TCAServiceTest.php
This pr:
* Moves the method Util::isLocalizedRecord to the TCAService
* Add's tests for those methods
* Refactors the RecordMonitor to use these methods of the TCAService
Fixes: #1978
> [TASK] Move Util::isLocalizedRecord to TCAService

- Classes/Domain/Search/SearchRequest.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
Till solr version 6.5.x all parameters of the plugin namespace was
added to the facet or sorting url again.
This patch adds a setting to be able to enable this behavior again,
but only with a whitelist of argument names.
Resolves: #1984
> [BUGFIX] Add setting to be able to add additional persistent arguments

- Resources/Private/Templates/Search/Results.html
Due to the introduction of the `QueryStringContainer` the `keywordsCleaned` isn't directly accessible through `resultSet.usedQuery` anymore. Now is't accessible through `resultSet.usedQuery.queryStringContainer.keywordsCleaned`.
> [BUGFIX] Use correct property to show searched keywords (#1926)

- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
This setting is not used anymore. It was replaced by a label in fluid in
version 7.
Resolves: #1970
> [TASK] Remove setting search.spellchecking.wrap

- Classes/Domain/Search/SearchRequest.php
This pr:
* Uses an empty array when the configured fields are null
Fixes: #1994
> [TASK] Fix warnings in tests for SearchRequest

- Classes/Domain/Search/ResultSet/Sorting/SortingHelper.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
This option has no effect since version 7 (fluid rewrite)
It can be achieved by adapting the partial for one particular sorting and or using the option defaultOrder.
Resolves: #1968
> [TASK] Remove option fixedOrder

- Classes/Controller/Backend/Search/IndexQueueModuleController.php
- Classes/Domain/Index/IndexService.php
- Classes/Domain/Search/LastSearches/LastSearchesService.php
- Classes/IndexQueue/Exception/DocumentPreparationException.php
- Classes/IndexQueue/Exception/IndexingException.php
- Classes/IndexQueue/PageIndexer.php
- Classes/System/Mvc/Frontend/Controller/OverriddenTypoScriptFrontendController.php
- Classes/Typo3PageIndexer.php
- Classes/Util.php
- Tests/Integration/ContentObject/RelationTest.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/does_not_die_if_page_not_available.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/System/Configuration/TypoScriptConfigurationTest.php
- Tests/Unit/ConnectionManagerTest.php
- ext_localconf.php
* add IndexingException, DocumentPreparationException to handle errors on Indexing process properly
* add OverriddenTypoScriptFrontendController extended from CMS::TypoScriptFrontendController
** use it in Util and in ext_localconf.php if Frontend-Helping things are triggered
** define EXT_SOLR_INDEXING_CONTEXT on indexing processes and handle then differently
** on __construct of IndexService and in ext_localconf
* add test case with dieing part of TYPO3 CMS for pages indexing
Fixes: #1658 
Fixes: #1993
> [TASK] Do not die on indexing process

- .travis.yml
- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/Util.php
- composer.json
This pr:
* Fixes errors during indexing in TYPO3 9.3
* Additional changes are required when TYPO3 8.7 compatibility will be dropped
> [TASK] Allow basic usage with TYPO3 9.3

- Classes/Domain/Index/IndexService.php
- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Queue.php
With this PR the IndexService takes care of updating the item queue
record when the value of the changed property changed during indexing.
Now an indexer could force the indexing queue to index an item at
a future timestamp again.
Resolves: #2018
> [FEATURE] Update Item changed timestamp when value changed during indexing

- ext_emconf.php
This pr:
* Allows to install with TYPO3 9.3
* Just for development and testing TYPO3 9 is not officially supported yet.
> [TASK] Allow to install with TYPO3 9.3

- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
This pr:
* Fixes the downloads of synonyms and stopwords by sending, contents and headers and doing an exit afterwards
Fixes: #2016
> [BUGFIX] Download of stopwords and synonyms not working

- Classes/Controller/SearchController.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Search.php
- Resources/Private/Templates/Search/Results.html
- Tests/Integration/Controller/Fixtures/customTemplates/Search/MyResults.html
- Tests/Integration/Controller/Fixtures/customTemplates/Search/Results.html
This pr:
* Deprecates the methods Search::getHasSearched and SearchResultSetService::getHasSearched
* Deprecates the global template variable hasSearch
Impact:
* Use SearchResultSet::getHasSearched instead or resultSet.hasSearched in the template
* Will be removed in EXT:solr 9.0.0
Fixes: #2031
> [TASK] Deprecate Search::getHasSearched and SearchResultSetService::getHasSearched

- Classes/Controller/SuggestController.php
- Classes/Domain/Search/Query/ParameterBuilder/Filters.php
- Classes/Domain/Search/Query/Query.php
- Classes/Domain/Search/Query/QueryBuilder.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
- Classes/Domain/Search/Suggest/SuggestService.php
- Classes/ViewHelpers/SearchFormViewHelper.php
- Tests/Unit/Domain/Search/Query/QueryBuilderTest.php
- Tests/Unit/Domain/Search/Suggest/SuggestServiceTest.php
This pr:
* Moves the addtional filters that have been passed as global argument "filters" before as tx_solr[additionalFilters]
* Makes sure that these filters get applied in addition to the filters that have been configured in (plugin.tx_solr.search.query.filters) to the suggestions and topResults
Impact: If you have passed the "filters" arguments somewhere from your own code, you now need to use tx_solr[additionalFilters] now.
Fixes: #2025
Fixes: #1885
Fixes: #1884
> [!!!][WIP][TASK] Unify filter handling in suggest

- Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeUrlDecoder.php
- Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeUrlDecoderTest.php
This change allows to use the DateRangeFacet with an open end or open begin like:
?tx_solr[q]=*&tx_solr[filter][0]=created:-201701010000
?tx_solr[q]=*&tx_solr[filter][0]=created:201701010000-
Fixes: #2041
> [FEATURE] Allow open query in the DateRangeFacet

- Classes/ViewHelpers/TranslateViewHelper.php
This pr:
* Uses the new ViewHelperNode class from the new namespace TYPO3Fluid\Fluid\Core\Parser\SyntaxTree
Fixes: #2043
> [BUGFIX] Warning in TranslateViewHelper

- .travis.yml
This pr:
* Fixes the installation of java 8 in the travis container by overwritting the download urls
Fixes: #2046
> [BUGFIX] Fix installation of java 8 in travis container

- Configuration/TypoScript/Solr/setup.txt
This pr:
* Changes "lib.solr_extbase_bootstrap" to use a copy for settings, persistence and view since they are no TypoScript objects
Fixes: #2040
> [BUGFIX] Use copy instead of reference

- Classes/HtmlContentExtractor.php
- Tests/Unit/HtmlContentExtractorTest.php
This pr:
* Reduces multiple whitespace of the page content to single whitespaces to remove these useless characters
Fixes: #2039
> [BUGFIX] Unify multiple whitespaces to a single whitespace

- Classes/Domain/Search/ResultSet/Grouping/GroupItem.php
- Classes/Domain/Search/ResultSet/Result/Parser/AbstractResultParser.php
- Classes/Domain/Search/ResultSet/Result/Parser/DefaultResultParser.php
- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Search.php
- Classes/ViewHelpers/Document/RelevanceViewHelper.php
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupItemTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/Parser/DefaultParserTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/Parser/Fixtures/fakeResponse.json
- Tests/Unit/ViewHelpers/Document/RelevanceViewHelperTest.php
By now the maximumScore is not calculated over all groups, when solrfluidgrouping is active.
To change this, some changes in the API are required:
* A ResultParser now get's the SearchResultSet passed and also retrieves it.
* The ResultParser is responsible to, parse the search results and the maximum score.
* SearchResultSet::getMaximumScore can be used to retrieve the maximum score
* The RelevanceViewHelper uses SearchResultSet::getMaximumScore to calculate the percentage in relation to the maximum score of all results. In addition the argument "maximumScore" can be used to overwrite that, e.g. to use the maximum score from the group.
Deprecations:
* Search::getMaximumResultScore is deprecated, use SearchResultSet::getMaximumScore now. The parsers for default and grouped results are …
> [!!!][TASK] Make RelevanceViewHelper compatible for solrfluidgrouping

- Classes/Domain/Search/ResultSet/Grouping/GroupItem.php
- Classes/Domain/Search/ResultSet/Result/Parser/DefaultResultParser.php
- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
- Classes/Search.php
- Classes/ViewHelpers/Widget/Controller/GroupItemPaginateController.php
- Classes/ViewHelpers/Widget/Controller/ResultPaginateController.php
- Resources/Private/Templates/Search/Results.html
- Tests/Integration/Controller/Fixtures/customTemplates/Search/MyResults.html
- Tests/Integration/Controller/Fixtures/customTemplates/Search/Results.html
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupItemTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/Parser/DefaultParserTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/Parser/Fixtures/fake_solr_response_with_query_fields_facets.json
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
This pr:
* Changes the default templates to use resultSet.allResultCount instead of resultSet.usedSearch.numberOfResults
* Moves the parsing of all allResultCount to the default parser
* Changes the method GroupItem::getNumFound to GroupItem::getAllResultCount to be consistent with SearchResultSet
* Use getAllResultCount where previously getNumberOfResults was used
* Deprecate GroupItem::getNumFound
* Deprecate Search::getNumberOfResults
Deprecations:
* GroupItem::getNumFound is deprecated now, please use GroupItem::getAllResultCount now, will be removed in EXT:solr 10
* Search::getNumberOfResults is deprecated now, please use SearchResultSet::getAllResutCount now, will be removed in EXT:solr 10
Fixes: #2057
> [!!!][TASK] Use SearchResultSet::getAllResultCount instead of Search:::getNumberOfResults

- Documentation/Solr/IndexMaintenance.rst
Also indicates the removal of the Schedular task. Ticket #1125 was closed without really making the change.
> Remove the tip about optimize as no longer needed

- Classes/System/Solr/SolrConnection.php
- Tests/Unit/System/Solr/SolrConnectionTest.php
This pr:
* Adjust the __toString method of the SolrConnection to contain the core.
Fixes: #2083
> [BUGFIX] String representation of SolrConnection does not contain core

- Classes/System/Solr/Document/Document.php
- Tests/Unit/Domain/Search/ResultSet/Result/SearchResultTest.php
This pr:
* When an unexisting field is requested from the solr document, no exception is throwen anymore and instead "null" is returned.
Fixes: #2082
> [BUGFIX] Do not throw exception when unexsting field is retrieved from documents

- Classes/Domain/Search/Query/QueryBuilder.php
- Tests/Integration/Controller/SearchControllerTest.php
This pr:
* Set's the required parameter omitHeaders to false to include the timing information in the response
* Add's an assertion to the integration tests
Fixes: #2086
> [BUGFIX] Execution time of query not shown

- Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
- Tests/Unit/Domain/Search/Statistics/StatisticsWriterProcessorTest.php
The root_pid in the statistics table was always set to the root page of
the current search page. If the search configuration is below that page in
the page tree, statistics are not shown.
This pr:
* Uses the siteRepository to get the related site and rootPageId
Fixes: #2088
> [BUGFIX] Determine root_pid depending on the configuration

- Classes/System/Solr/Service/SolrWriteService.php
This pr:
* Changes the extractByQuery method to also accept an instance of the solarium extract and not only the inheriting ExtractQuery
Fixes: #2096
> [TASK] Allow to pass solarium extract query

- Classes/Search.php
- Tests/Unit/SearchTest.php
This pr:
* Fixes the bug and add's a testcase
Fixes: #2098
> [BUGFIX] Limit argument in Search::search not evaluated

- Classes/Controller/Backend/Search/AbstractModuleController.php
- Resources/Private/Partials/Backend/NoSiteAvailable.html
By now you get the message that no solr site is configured when you select e.g. a sysfolder in the pagetree outside a site, even when other sites exists
This pr:
* When no sites exis on the system => show the setup instructions
* When you are on the root page or on a page where no sites exists but there are sites in the system => show message to select another site in the pagetree
Fixes: #2095
> [BUGFIX] Improve solr backend message for sites without solr connection

- .scrutinizer.yml
- Classes/ConnectionManager.php
- Classes/System/Hooks/Backend/Toolbar/ClearCacheActionsHook.php
- ext_tables.php
This pr:
* Moves the manipulateCacheActions hook to a seperate class and deprecates the old method
Fixes: #1471
> [TASK] Move manipulateCacheActionsHook to seperate class

- Classes/Domain/Search/ResultSet/Facets/SortingExpression.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Controller/Fixtures/can_sort_by_metric.xml
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/SortingExpressionTest.php
With the introduction of json faceting you should be able to sort facet options by a metric:
```
pid {
label = Content Type
field = pid
metrics {
newest = max(created)
}
sortBy = metrics_newest desc
}
```
This is not working because the sortingName is filtered out.
This pr:
* Fixes the bug and add's a test for it.
Fixes: #2109
> [BUGFIX] Sort facet options by metric is not working

- Classes/Domain/Search/ResultSet/Facets/SortingExpression.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Controller/Fixtures/can_sort_by_metric.xml
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/SortingExpressionTest.php
With the introduction of json faceting you should be able to sort facet options by a metric:
```
pid {
label = Content Type
field = pid
metrics {
newest = max(created)
}
sortBy = metrics_newest desc
}
```
This is not working because the sortingName is filtered out.
This pr:
* Fixes the bug and add's a test for it.
Fixes: #2109
> [BUGFIX] Sort facet options by metric is not working (#2110)

- Classes/Controller/Backend/Search/IndexAdministrationModuleController.php
- Classes/ViewHelpers/Backend/IsTYPO3VersionBelow9ViewHelper.php
- Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
The resetting of the index queue (in the admin module) from the index queue module is not working since the link to the other module does not work.
This pr:
* Add's a compatible form for TYPO3 9 and the redirect back to the index queue module.
Fixes: #2021
> [BUGFIX] The resetting of the index queue from the queue module is not working

- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
This pr:
* Fixes the ReQueue link by adding the route
Fixes: #2121
> [BUGFIX] ReQueue from index inspector not working in TYPO3 9.4

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilder.php
- Tests/Unit/Domain/Search/ResultSet/Facets/DefaultFacetQueryBuilderTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilderTest.php
- Tests/Unit/Query/Modifier/FacetingTest.php
Exclude tags should only be added when keepAllFacetsOnSelection and/or keepAllOptionsOnSelection is configured.
This pr:
* Fixes makes sure that exclude tags are only added when keepAllOptionsOnSelection or keepAllFacetsOnSelection is active
Resolves: #2127
> [BUGFIX] Excludetags not properly generated for json faceting

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilder.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilderTest.php
This pr:
* Allows to configure "minumCount" to 0 for all facets
* Add's testcases for that usecase
Fixes: #2128
> [BUGFIX] Allow global minimumCount configuration of 0 for facets

- Classes/System/Solr/ResponseAdapter.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
The ResponseAdapter need to implement the Countable interface for backwards compatibility.
This pr:
* Add's the implementation of the Countable interface
* Add's a testcase the reproduces the error from the reports
Resolves: #2125
> [BUGFIX] Response Adapter need to implement Countable interface

- composer.json
A TYPO3 extension should not require `typo3/cms`.
See: https://insight.helhum.io/post/148886148725/composerjson-specification-for-typo3-extensions
> Use package typo3/cms-core instead of typo3/cms

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParser.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/Fixtures/fake_solr_response_with_hierachy_facet_with_slash_in_title.json
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParserTest.php
fixes wrong behavior on facet-otions with slash in name/title
unit tests for this BUG added
thanks on sitegeist media solutions GmbH for reporting and funding of this BUGFIX
Ported from: #2142
Fixes: #2140
> [BUGFIX] selected Hierarchical Facet option with slash in name destroing facets

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParser.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/Fixtures/fake_solr_response_with_hierachy_facet_with_slash_in_title.json
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParserTest.php
fixes wrong behavior on facet-otions with slash in name/title
thanks on sitegeist media solutions GmbH for reporting and funding of this BUGFIX
Backported from: #2142
Fixes: #2140
> [Backport:BUGFIX] selected Hierarchical Facet option with slash in name destroing facets

- Classes/System/UserFunctions/FlexFormUserFunctions.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Unit/System/UserFunctions/FlexFormUserFunctionsTest.php
* use field name as array key in flex form select items
* use new presentation format for options labels in select flex form
`field_name (Facet Label: "usedLabelOrLLLTranslationLabel")`
`field_name (Facet Label: "cObject[...faceting.facets.someFacet.label]")`
* implement tests for this case
Fixes: #2156
> [BUGFIX:PORT] fields in flex forms filter are not available on duplicate facets label

- Classes/System/UserFunctions/FlexFormUserFunctions.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Unit/System/UserFunctions/FlexFormUserFunctionsTest.php
* use field name as array key in flex form select items
* use new presentation format for options labels in select flex form
`field_name (Facet Label: "usedLabelOrLLLTranslationLabel")`
`field_name (Facet Label: "cObject[...faceting.facets.someFacet.label]")`
* implement tests for this case
Fixes: #2156
> [BUGFIX] fields in flex forms filter are not available on duplicate facets label

- Classes/System/Solr/Service/SolrReadService.php
If solr runs behind a proxy and solr is down the proxy returns status
"502 Bad Gateway".
Instead of having the thrown SolrCommunicationException uncaught
throw a SolrUnavailableException in this case.
Resolves: #2186
> [TASK] Handle bad gateway as not available

- Classes/ViewHelpers/Uri/Facet/AbstractValueViewHelper.php
- Classes/ViewHelpers/Uri/Facet/AddFacetItemViewHelper.php
- Classes/ViewHelpers/Uri/Facet/RemoveFacetItemViewHelper.php
- Classes/ViewHelpers/Uri/Facet/SetFacetItemViewHelper.php
You could create now a facet item link (add, set, remove) somewhere else
in the results view where no facet object is available.
Beside {s:uri.facet.setFacetItem(facet: facet, facetItem: option)}
you could create a set link now with this vh arguments:
{s:uri.facet.setFacetItem(facetName: 'type', facetItemValue: 'pages',
resultSet: resultSet)}
Resolves: #2191
> [FEATURE] More flexible facet uri viewhelpers with optional facet object

- ext_emconf.php
This pr:
* Adapts the version constraint to allow an installation with TYPO3 9 LTS
Fixes: #2203
> [TASK] Adapt version constraint to allow installation with 9 LTS

- Classes/Domain/Search/Uri/SearchUriBuilder.php
- Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
This pr:
* Deactivates the in memory cache for typolink calls for facet links for TYPO3 9 since the site handling requires a cHash for all links
Fixes: #2211
> [BUGFIX] Generate cHash for every link with TYPO3 9

- Classes/Domain/Search/Uri/SearchUriBuilder.php
- Classes/System/Url/UrlHelper.php
- Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
- Tests/Unit/System/Url/UrlHelperTest.php
This pr:
* Reverts the changes from #2222
* Removes a cHash that was generated when a link is generated for the in memory link cache
Fixes: #2211
> [BUGFIX] Remove cHash from in memory cache template

- Classes/ViewHelpers/SearchFormViewHelper.php
- Resources/Private/Partials/Search/Form.html
- Tests/Unit/ViewHelpers/SearchFormViewHelperTest.php
When the pageId and the languageId is encoded in the path segment of the url e.g. "/en/search", there is no need,
to keep the in the form as hidden arguments. Nevertheless we need to make sure that they are added when no speaking urls are used (e.g. in a 8 LTS default environment).
This pr:
* Add's variable(addPageAndLanguageId) to the form that indicates if the L and id parameter are required as hidden fields
* The variable is set to false when we have a site in TYPO3 9 LTS managed with the site management because then these arguments are encoded in the path segment of the url
Fixes: #2217
> [BUGFIX] Do not render id and L param for form for sites managed with site management

- Classes/Controller/SearchController.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
The filters in the autosuggest currently get added twice. Once from TypoScript and once
from the passed additionalFilters (That originally also come from the TypoScript of the previous request).
Since we can access the TypoScript from the suggest controller as well we should not pass those filters as additionalFilters.
Nevertheless we should keep the evaluation of additionalFilters to allow additionalFilters on a view base.
Related: #2212
> [BUGFIX] Filters in autosuggest get added twice

- Classes/Domain/Search/Query/AbstractQueryBuilder.php
- Tests/Unit/Domain/Search/Query/QueryBuilderTest.php
When a filter is passed twice (e.g. by passing it as additional filter), it should be ignored.
This pr:
* Ignores a filter when it is passed twice and keeps the filter that was passed first.
Related: #2212
> [BUGFIX] Ignore filter when it was passed twice with the same name

- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Controller/Fixtures/can_render_path_facet_with_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Integration/Controller/Fixtures/can_render_suggest_controller.xml
- Tests/Integration/Controller/Fixtures/can_sort_by_metric.xml
The TypoScript setting "singleFacetMode", was removed and could be replaced by rendering a facet with the partial "OptionsSinglemode".
This pr:
* Removes the left settings in fixtures and default configuration
* Deprecates the method TypoScriptConfiguration::getSearchFacetingSingleFacetMode
Fixes: #2189
> [TASK] Remove singleFacetMode from fixtures and code

- Classes/Domain/Search/ApacheSolrDocument/Repository.php
- Classes/System/Solr/Service/AbstractSolrService.php
When a core is unavailable this should not prevent the backend module from rendering.
This pr:
* Catches a SolrCommunicationException in the document repository as well
* Makes sure that "ping" returns false for an unconfigured core by catching the HttpException thrown by Solarium
Fixes: #2220
> [BUGFIX] Fix backend info module with missing core

- Classes/Domain/Index/IndexService.php
- Classes/IndexQueue/Indexer.php
During indexing we should catch solarium HttpException's on several places in order to proceed the indexing process.
Fixes: #2233
> [BUGFIX] Catch solarium HttpExceptions

- Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
Adding a `CASE` structure in order to use the `externalurl` and `internalurl` fields if needed. With this change, Solr for TYPO3 will not generate links to empty news detail views which only exist in the search results.
Related Slack discussion: https://typo3.slack.com/archives/C02FF05Q4/p1548323535173700 and ff
> [TASK] Consider external and internal news URLs

- Classes/Domain/Index/PageIndexer/Helper/UriBuilder/AbstractUriStrategy.php
- Classes/Domain/Index/PageIndexer/Helper/UriBuilder/SolrSiteStrategy.php
- Classes/Domain/Index/PageIndexer/Helper/UriBuilder/TYPO3SiteStrategy.php
- Classes/Domain/Index/PageIndexer/Helper/UriStrategyFactory.php
- Classes/IndexQueue/PageIndexer.php
- Classes/System/Url/UrlHelper.php
- Classes/System/Util/SiteUtility.php
- Classes/ViewHelpers/SearchFormViewHelper.php
- Tests/Unit/Domain/Index/PageIndexer/Helper/UriBuilder/SolrSiteStrategyTest.php
- Tests/Unit/Domain/Index/PageIndexer/Helper/UriBuilder/TYPO3SiteStrategyTest.php
- Tests/Unit/IndexQueue/PageIndexerTest.php
- Tests/Unit/System/Url/UrlHelperTest.php
When the site management in TYPO3 9 is used, the language and pageId parameter are part of the encoded url. In previous versions of EXT:solr we build the frontend url by our own by adding the id, L and MP parameter.
This pr:
* Refactors the url generation by extracting the code into strategy classes
* Implements a SolrSiteStrategy that is able to build the indexing uri as before with index.php?id=xx&L=yy
* Implements a TYPO3SiteStrategy that uses the router to build the indexing uri
* Prepares a different indexing url handling with site management
**Important**: By now the old urls with id and L parameter are used also when site management is active since the urls that are generated by the router could produce urls that lead to a 404 error.
Related: #2234
> [TASK] Prepare different url generation when site management is active

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilder.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Unit/Query/Modifier/FacetingTest.php
Add's the excludeTags for both cases. This is required when both is activated at the same time.
Enable both at the same time and check that the options and counts stay for the facets when you select an option.
Fixes: #2244
> [BUGFIX] KeepAllFacetsOnSelection is not evaluated when KeepAllOptionsOnSelection is used.

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetQueryBuilder.php
- Classes/Query/Modifier/Faceting.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Releases/solr-release-9-0.rst
- Tests/Unit/Query/Modifier/FacetingTest.php
* Add's the setting ```additionalExcludeTags``` to a facet to exclude custom tags from the count of that facet
* Add's the setting ```addFieldAsTag``` to a facet to force the creation of a tag for that facet
Configure ```addFieldAsTag``` for the tagged facet and add that field with ```addtionalExcludeTags``` to a facet and see if the exclude tag will be applied
Fixes: #2195
> [FEATURE] Individual additional exclude tags for facets

- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
* Uses the new method getCorePath instead of getPath to avoid the deprecation error.
Go to the info module and check the error log for that error. Should be gone with new default partial
Fixes: #2247
> [BUGFIX] Deprecated method getPath called in default template

- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
* Uses the new method getCorePath instead of getPath to avoid the deprecation error.
Go to the info module and check the error log for that error. Should be gone with new default partial
Fixes: #2247
> [BACKPORT][BUGFIX] Deprecated method getPath called in default template

- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/can_create_new_page.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
* Fixes the bug by return only l10n_parent when it is greater then zero and add's a test case for that.
* Create a new, unhidden page in TYPO3 9 LTS and check if it get's queued in the index queue when a proper configuration is in place.
Fixes: #2248
> [BUGFIX] A new created page is not added to the queue in TYPO3 9 LTS

- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/can_create_new_page.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
* Fixes the bug by return only l10n_parent when it is greater then zero and add's a test case for that.
* Create a new, unhidden page in TYPO3 9 LTS and check if it get's queued in the index queue when a proper configuration is in place.
Fixes: #2248
> [BACKPORT][BUGFIX] A new created page is not added to the queue in TYPO3 9 LTS

- Resources/Private/Php/ComposerLibraries/composer.json
- Resources/Private/Php/ComposerLibraries/composer.lock
- composer.json
* Updates the composer.json file and the bundled TER libraries to 4.2.x
* After running ```composer update``` version 4.2.x of solarium should be kept
Fixes: #2260
> [BUGFIX] Restrict used solarium version to 4.2.x

- Classes/ContentObject/Classification.php
- Classes/Domain/Index/Classification/Classification.php
- Classes/Domain/Index/Classification/ClassificationService.php
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Tests/Unit/ContentObject/ClassificationTest.php
- Tests/Unit/Domain/Index/Classification/ClassificationServiceTest.php
* Splits the patterns into ```matchPatterns``` and ```unmatchPatterns``` to allow the removal of classs by an unmatch pattern
* Keeps the ```patterns``` configuration for backwards compatibility
* Check if the old classification configuration still works
* Configure a ```matchPatterns``` with an ```unmatchPatterns``` configuration and make sure classes with matching ```unmatchPatterns``` are not assigned to the document.
Fixes: #2265
> [TASK] Split patterns into matchPatterns and unmatchPatterns

- Classes/Domain/Index/IndexService.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
* Uses the domain from the site instead from the first domain record. In case when you use domain records this is the same,
but when domains are configure with ```$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['sites'][$rootPageId]['domains']``` instead the correct domain is used then.
* Check if domains are configured with ```$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['solr']['sites'][$rootPageId]['domains']``` i if domain is set correct in IndexService
Fixes: #2275
> [BUGFIX] Use domain from Site object instead of allways first domain record

- Classes/Task/AbstractSolrTask.php
Exclusion of the logger instance from the record during save to database.
Prevent hard-coded logfile paths in database record.
Set the logger at runtime if the task is executed.
Fixes: #2279
> [BUGFIX] Exclude logger from serialize on save for scheduler task

- .travis.yml
- composer.json
* Removes the replace section for the package name "solr" since packages without a vendor are not supported anymore
* Executes composer validate --no-check-lock in .travis.yml
Installing EXT:solr with composer does not create a deprecation message
Fixes: #2253
> [BUGFIX] Fix composer deprecation message

- Classes/Controller/Backend/Search/AbstractModuleController.php
- Classes/Controller/Backend/Search/IndexAdministrationModuleController.php
- Tests/Integration/Controller/Backend/Search/Fixtures/can_reload_index_configuration.xml
- Tests/Integration/Controller/Backend/Search/IndexAdministrationModuleControllerTest.php
- Tests/Unit/Controller/Backend/Search/IndexAdministrationModuleControllerTest.php
* Replaces the usage of the deprecated method ```getCoreName()``` with ```getPrimaryEndpont()->getCore()```
No deprecation notice is triggered anymore. When a core is reloaded or an index is emptied.
Fixes: #2286
> [BUGFIX] Remove usage of deprecated method getCoreName in IndexAdministrationModuleController

- Classes/System/Service/ConfigurationService.php
- Tests/Unit/System/Service/ConfigurationServiceTest.php
* Removes the quoting if a numeric value for the filter was configured in the flexform.
Configure a numeric filter in the flexform and check the frontend.
Fixes: #2293
> [BUGFIX] Do not quote integer values for flexform filters

- Classes/Typo3PageContentExtractor.php
- Tests/Unit/HtmlContentExtractorTest.php
- Tests/Unit/Typo3PageContentExtractorTest.php
In the process of extracting content from HTML, the &nbsp;
entity is being decoded into an UTF-8 char, which in the
end is destroyed with non unicode aware preg_replace calls
which finally leads to json_encode to fail due to encoding errors
and the page indexing fails.
To fix this, we remove unecessary decoding of entities early in the process
so that we later can cleanly remove &nbsp; with a space.
> [BUGFIX] Correctly replace non breaking space entity

- Classes/Util.php
- Tests/Unit/UtilTest.php
With first call of getConfigurationFromPageId()
the parameter initializeTsfe is checked and processed.
With a second call to getConfigurationFromPageId()
we now check, if TSFE has to be initialized also while
retrieving data from cache.
Resolves: #2150
It initializes TSFE also, if configuration was fetched from configurationObjectCache
A perfect instruction you can find here: https://github.com/TYPO3-Solr/ext-solr/issues/2150
Fixes: #2150
> [BUGFIX] Initialize TSFE, if conf of page was cached

- Classes/IndexQueue/Indexer.php
- Tests/Integration/Fixtures/fake_extension_table.sql
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_outside_site_root_with_template.xml
- Tests/Integration/IndexQueue/IndexerTest.php
This PR checks, if page configured with additionalStoragePid is part of current rootline. If not, the foreign TSFE can't be used for indexer configuration.
See Functional Test. I have created a new fixture xml file
Fixes: #2303
> Check rootline before index

- Classes/System/Url/UrlHelper.php
- Tests/Unit/System/Url/UrlHelperTest.php
The UrlHelper does currently not work with colons as it
just appends the port to the domain. It must add a `:`
between the domain and the port.
Fix bug where UrlHelper does not add a colon before the port in the url
Run unit tests
Fixes #2325
> [BUGFIX] UrlHelper does not add colon before port

- Classes/System/Cache/TwoLevelCache.php
If the function \ApacheSolrForTypo3\Solr\System\Cache\TwoLevelCache::get is used, currently every time the secondLevelCache is fetched again as the result is never stored in the firstLevelCache. This is very expensive as it means fetching the result from database (default backend cache) and unserialize the information (as it is stored serialized by default).
> [BUGFIX] Fill firstLevelCache with secondLevelCache result

- Classes/Query/Modifier/Faceting.php
To be able to combine facets from _GET and from flexforms, the key of the facets must be set to a proper name. Otherwise the index would be overriden.
Resolves: #2301
> [BUGFIX] Add facet name to facet filters

- Documentation/Configuration/Reference/TxSolrSearch.rst
This settings are unused since the fluid templates integration.
> [BUGFIX] Remove obsolete pagebrowser settings from documentation

- Classes/Domain/Search/Query/ParameterBuilder/Grouping.php
Fixes a regression from switching to Solarium. Set query option "rows" with
value from grouping.numberOfGroups, when grouping is enabled.
Resolves: #2350
> [BUGFIX] Set value of grouping.numberOfGroups

- Classes/IndexQueue/AbstractIndexer.php
This change set a multivalue field in one call instead of one call per value.
So, the field type is always an array, even if the multivalue field contains
only one value.
This fix one major issue where only the first value of a rootline field get indexed.
1. Index a document with a SOLR_RELATION and multiValue=1 (like a relation to sys_category).
With a relation with only one element: the field's value in the json payload sent to solr must be an array of one element.
Before the fix, for a relation with one element, the field's value in the json payload was an int an not an array.
2. Index a document with a field with a categoryUidToHierarchy as fieldProcessingInstructions.
The hierarchy must be correctly stored as a multivalue field in solr.
Before the fix, only the first level of the …
> [BUGFIX] Send a consistent type for SOLR_RELATION multivalue

- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Introduction/Index.rst
This pull-request fixes the spelling of the english adjective “faceted” in the documentation.
Look into the British Oxford-Dictionary and the American New-Oxford-Dictionary for the spelling of the adjective “faceted”. It does not contain a second “t”. 
Fixes: #2321
> Fix spelling of adjective “faceted” in documentation

- Classes/Util.php
In addition to #2323 TSFE needs to get a proper initialization also
on a TwoLevelCache hit. Otherwise you get different TSFE objects when
indexing records via additionalPageIds outside the normal page tree for
the first indexing (without TwoLevelCache hit) and second indexing
(with TwoLevelCache hit).
Resolves: #2328
> [BUGFIX] Initialize TSFE on 2nd level cache hit

- Classes/IndexQueue/PageIndexerRequestHandler.php
ob_end_clean should not be called if buffer wasn't used
> [FIX] Only clean buffer if used

- Classes/ConnectionManager.php
- Classes/Controller/Backend/Search/InfoModuleController.php
- Classes/Domain/Index/PageIndexer/Helper/UriStrategyFactory.php
- Classes/Domain/Site/LegacySite.php
- Classes/Domain/Site/Site.php
- Classes/Domain/Site/SiteHashService.php
- Classes/Domain/Site/SiteInterface.php
- Classes/Domain/Site/SiteRepository.php
- Classes/Domain/Site/Typo3ManagedSite.php
- Classes/System/Records/SystemLanguage/SystemLanguageRepository.php
- Classes/System/Util/SiteUtility.php
- Configuration/SiteConfiguration/Overrides/sites.php
- Resources/Private/Partials/Backend/NoSiteAvailable.html
- Tests/Unit/ConnectionManagerTest.php
- Tests/Unit/Domain/Site/SiteRepositoryTest.php
- Tests/Unit/System/Util/SiteUtilityTest.php
With version 9 the concept of sites has been introduced in TYPO3. A site in TYPO3 can be used to configure everything that is related to domains and languages.
In the solr extension we also had a site concept before. The site concept in EXT:solr collects all connection information from the TypoScript configuration and stores that in the sys_registry. In addition the configuration ```$GLOBALS['TYPO3_CONF_VARS]['EXTCONF']['solr']['sites']```could be used to configure domains, when no TYPO3 domain record was configured.
Since the addtional domain record configuration was only developt because this was  not supported by the core, we should now get rid of that configuration. 
In addition the parsing the TypoScript and storing the connection information was only required to have a good …
> [FEATURE] Use TYPO3 site configuration for solr connection info

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
Adds support for indexing items stored in a distinct database (as defined in [`$GLOBALS['TYPO3_CONF_VARS']['DB']['TableMapping']`](https://docs.typo3.org/typo3cms/CoreApiReference/8.7/ApiOverview/Database/Configuration/#configuration))
> 1. Add a new `Extern` connection in `$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']`
> 2. Set the `Extern` connection to be used for a custom record type (you can also use `tx_news_domain_model_news` or any pre-existing if you want) in `TableMapping`:
>     ```php
>     $GLOBALS['TYPO3_CONF_VARS']['DB']['TableMapping'] = [
>         'my_custom_record` => `Extern`
>     ]
>     ```
> 3. Add a queue configuration for your record type:
>     ```typoscript
>     plugin.tx_solr.queue {
>       custom_records = 1
>       custom_records {
>         table = …
```
> [BUGFIX] Respect TableMapping parameter

- Classes/HtmlContentExtractor.php
- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
It is related to #1541.
I changed the decoding of html so that all literals are preserved, not just `<`.
I extended the test created by #1767. Otherwise just add xml-like content to a page and index it, it will be removed from the content.
Fixes: #2348
> don't remove content that is visible to the user

- ext_localconf.php
Adds tx_solr_statistics table to "Table garbage collection" scheduler task.
Check if the scheduler task mentioned above shows the table tx_solr_statistics with a default of 180 days.
Fixes: #2305
> [FEATURE] Add tx_solr_statistics to table garbage collection

- Classes/ViewHelpers/SearchFormViewHelper.php
- Resources/Private/Partials/Search/Form.html
Re-implement the feature 'keepExistingParametersForNewSearches': When doing a new search, existing parameters like filters will be carried over to the new search.
The TypoScript setting and documentation already exist from an earlier version (feature got lost in a rewrite)
Select one or more facets, type new search words and search. With this patch, the selected facets remain active for the new search.
Fixes: #1626
> [FEATURE] Re-implement 'keepExistingParametersForNewSearches' (#1626)

- Classes/ConnectionManager.php
- Classes/Domain/Site/LegacySite.php
- Classes/Domain/Site/Site.php
- Classes/Domain/Site/SiteRepository.php
- Classes/System/Records/SystemDomain/SystemDomainRepository.php
- Tests/Unit/Domain/Site/SiteRepositoryTest.php
* Add's the deprecation log message for methods that have been marked as deprecated with the introduction of the site handling
* Migrate the unit tests to use the site handling logic
* Fixed getAvailableSites to respect legacy sites and TYPO3 managed sites
* Check if getAvailableSites returns all configured sites
Fixes: #2368
> [TASK] Add deprecation logs

- Classes/Util.php
- Tests/Integration/System/Configuration/ExtensionConfigurationTest.php
- ext_tables.php
Implements switching between legacy and new site handling configurations.
Disables the "Initialize Solr connections" Buttons in Backend.
Fixes: #2364
> [FEATURE] Add legacy site mode

- Classes/Domain/Site/SiteRepository.php
Languages set to "disabeld in Frontend" in Site Handling Configuration should not be tried to indexed.
- create a Frontend-Page in the Site Module and disable "Visible in Frontend "
- Try to index that Page results in an Error
Fixes: #2391
> [BUGFIX] do not index hidden Frontend Languages (#2391)

- Classes/Controller/Backend/Search/IndexQueueModuleController.php
- Classes/Domain/Site/SiteRepository.php
- Classes/System/Util/SiteUtility.php
- Configuration/SiteConfiguration/Overrides/sites.php
- Tests/Unit/Domain/Site/SiteRepositoryTest.php
* add a Flag in Site Configuration to disable Solr for one whole Site
* by editing the YML Site Configuration File you can also disable Solr per Site-Language
* initialize EXTENSION Configuration array for Unit-Test
disable Solr in one Site, all Solr-BE-Modules should show the "solr is not configured" message
Fixes: #2398
> [TASK] add a Flag in Site Configuration to disable Solr  (#2398)

- Classes/Domain/Site/SiteHashService.php
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Unit/Domain/Site/SiteHashServiceTest.php
* Fixes canRenderDetailAction by adapting the hash in the test to a valid hash
* Fixes canFacetOnHierarchicalTextCategory by fixing a bug in the SiteHashService. When the setting "query.allowedSites" is not defined at all, it should use ```__solr_current_site```
as defined in the documentation. Previously the hash was calculated over an empty string, what accidentally matched on an undefined domain
* All tests are green
* query.allowedSites can be used as documented
Related: #2397
> [BUGFIX] Fix skipped tests in search controller test

- Configuration/TCA/Overrides/sys_template.php
* Labels the TypoScript example template to use TYPO3_CONV_VARS as deprecated
* Label is prefixed with "Deprecated:" in the TypoScript object browser
Fixes: #2405
> [TASK] Label template "Use connections settings from TYPO3_CONF_VARS" as deprecated

- Classes/Command/SolrCommandController.php
- ext_localconf.php
* Only register the updateConnections command when the legacy mode is active
* The updateConnections command is only available when legacy mode is active
Fixes: #2406
> [TASK] Only register updateConnections command with active legacy mode

- Classes/Domain/Site/SiteRepository.php
- Tests/Unit/Report/SolrConfigurationStatusTest.php
keeps the rootPageId as array_keys in when fetching available Sites
Fix Creation of Scheduler Task
Fix Unit-Tests for SolrConfigurationStatus
create a new Scheduler Task, Reindex Site and/or Index Queue Worker
Fixes: #2414
> [BUGFIX] keep rootPageId as array_key, fix tests (#2414)

- Tests/Integration/IndexQueue/Initializer/Fixtures/mouted_shared_page_from_multiple_trees_can_be_queued.xml
- Tests/Integration/IndexQueue/Initializer/PageTest.php
This merge request:
* Fixes the broken tests when mounted pages get initialized with the index queue
Note:
* There are still related issues in the TYPO3 core for cross domain mount points with TYPO3 9.5 (https://review.typo3.org/c/Packages/TYPO3.CMS/+/59915)
Fixes: #2396
> [TASK] Queue initialization with mountpoints

- Tests/Integration/ConnectionManagerTest.php
- Tests/Integration/Fixtures/ConnectionManagerTest_basic_connections.xml
* use default test site configuration for integration tests
* implement tests for `getConnectionBy*`
* replace `exceptionIsThrownForUnAvailableSolrConnectionOnGetConfigurationByRootPageId` with:
* `exceptionIsThrownForUnAvailableSolrConnectionOnGetConnectionByRootPageId`
* `exceptionIsThrownForUnAvailableSolrConnectionOnGetConnectionByPageId`
Fixes: #2401
> [TASK] evaluate Integr./Con.ManagerTest skipped tests and reenable them

- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/FrontendHelper/TestAdditionalPageIndexer.php
* Fixed the failing test by replacing the usage of the deprecated method getField with the usage of ['fieldName']
Check if this test is executed in the travis-ci pipeline and green
Fixes:  #2437
> [TASK] Fix failing PageIndexerTest

- Tests/Integration/Controller/Backend/Search/IndexAdministrationModuleControllerTest.php
* Fixes and re-enabled the admin controller tests by adapting the assertions to the site managed scenario.
Check if the integration tests for the admin controller pass on travis-ci
Fixes: #2402
> [TASK] Fix index admin controller tests

- Classes/ConnectionManager.php
- Classes/Domain/Site/SiteRepository.php
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Controller/SearchControllerTest.php
* Fixes the SearchController tests that test the unavailability of solr
* Refactors the ConnectionManager by extracting the logic for the NoSolrConnection found exception
All SearchController tests are now executed again
> [BUGFIX] Fix no search available tests

- Classes/ConnectionManager.php
- Classes/Controller/AbstractBaseController.php
- Classes/Domain/Site/SiteRepository.php
- Classes/Util.php
* Fixes the broken reports when no site is configured
* Shows the solrNotAvailableAction in the frontend when the solr site is not configured
No error is shown in the TYPO3 system when solr is installed but not configured
Fixes: #2442
> [BUGFIX] Connection errors are not properly catched

- Classes/Domain/Search/ResultSet/Facets/RequirementsService.php
- Tests/Unit/Domain/Search/ResultSet/Facets/RequirementsServiceTest.php
Fixes the bug and add's unit tests for that case.
A facet is only rendered when all requirements are met. Note: A single requirement is met when only one *value* matches (as mentioned in the documentation), so really multiple requirements need to be configured.
Fixes: #2375
> [BUGFIX] Fix getAllRequirementsMet returns true as soon as one requirement is met

- Classes/ViewHelpers/SearchFormViewHelper.php
Pass empty string to UriBuilder if addQueryStringMethod parameter is not set in SearchFormViewhelper
Fixes: #2449
> [TASK] Pass empty string if addQueryStringMethod is not set #2449

- Resources/Private/Solr/zoo.cfg
* Add's a default zoo keeper configuration because the Apache Solr Docker image requires to have that file in places
* Check if the docker container can be added to a docker setup and does not throw an error.
Fixes: #2465
> [BUGFIX] Add default zoo.cfg

- Classes/Domain/Site/Typo3ManagedSite.php
- Classes/Report/SiteHandlingStatus.php
- Resources/Private/Templates/Backend/Reports/SiteHandlingStatus.html
- Tests/Integration/Report/SiteHandlingStatusTest.php
- ext_tables.php
implements following status checks for site handling configuration:
* Entry Point[base] scheme expects -> http[s]
* Entry Point[base] authority expects -> [user-info@]host[:port]
Fixes: #issue (Please create an related issue first and mark it as fixed here with your pr)
> [TASK] Add status report for current site handling configuration.

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Tests/Integration/Domain/Index/Queue/Fixtures/can_keep_indexing_properties.xml
- Tests/Integration/Domain/Index/Queue/QueueItemRepositoryTest.php
* Add's a fix that only deletes indexing properties for records that are not referenced in any index queue item. Previously they get deleted and are therefore also lost for other indexing configuration
* Add's a functional test for that bug
* Create a record with indexing properties that is referenced with to indexing configurations
* Delete one item from index indexing queue, e.g. by re initializing them
* The indexing properties should remain for the other index queue item with the same record information but other index queue name
Fixes: #2335
> [BUGFIX] Indexing properties should only be deleted when not referenced anymore

- Classes/System/Solr/SolrConnection.php
Enable the Plugin 'postbigrequest'
configure around 20 facets, so the query going to solr is really big.
previously to this change we would get: ``resulted in a `414 URI Too Long` response``
related: #1675
> [FEATURE] automatically send big solr queries via POST

- Docker/SolrServer/Dockerfile
* Removes the volume declaration (since for 8.2  it is allready defined in the base Dockerfile)
* Simplifies the Dockerfile since switching user is only needed to remove the default configuration
* Check if the container can be used with and without a volume definition for "/var/solr/data/data"
Fixes: #2477
> [BUGFIX] Docker container does not start when no volum is configured

- Classes/Access/Rootline.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Tests/Integration/Access/Fixtures/user_protected_page.xml
- Tests/Integration/Access/RootlineTest.php
* Disables the user permission check when building the access rootline since this is required to build an access rootline for user restricted pages
* Test to index pages with and without user restrictions
Fixes: #2477
> [BUGFIX] Indexing user protected pages does not work as expected

- Classes/Domain/Index/Queue/GarbageRemover/StrategyFactory.php
- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php
- Classes/GarbageCollector.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_pages_language_overlay_tca.php
- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/fake_extension3_table.sql
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
* Remove the leftovers where the pages_language_overlay logic is still present.
* The table pages_language_overlay is not used anymore in the extension
Fixes: #2482
> [BUGFIX] Remove pages_language_overlay leftovers

- Classes/Domain/Index/PageIndexer/Helper/UriBuilder/TYPO3SiteStrategy.php
- Classes/Report/SiteHandlingStatus.php
- Resources/Private/Templates/Backend/Reports/SiteHandlingStatus.html
- Tests/Integration/Report/SiteHandlingStatusTest.php
Show status check for "Entry Point[base]" settings of site:
Try Following:
1. Valide URL in global base 
\+ languages:
base = /da/
base = /de/
2. Invalide URL in global base(no scheme) 
\+ languages:
base = /
base = Valide URL 
base = /da/
3. Disable some language
Fixes: #2480
> [TASK] Site configuration status check - incl. languages config fallback

- Classes/Domain/Index/PageIndexer/Helper/UriBuilder/TYPO3SiteStrategy.php
getRecordUid() returns database result as string and requires typecasting.
> [Bugfix] add typecasting (#2486)

- Classes/Domain/Index/PageIndexer/Helper/UriBuilder/TYPO3SiteStrategy.php
getRecordUid() returns database result as string and requires typecasting.
No type error should be thrown
Fixes: #2486
> [Bugfix] add typecasting (#2487) - backport

- .travis.yml
- Resources/Private/Install/install-solr.sh
* Uses openjdk for that branch for now since oracle jdk in that age is no longer available
> [BUGFIX] Fix travis build

- .travis.yml
- Build/Test/bootstrap.sh
- Build/Test/publish_coverage.sh
- Tests/Integration/UtilTest.php
- composer.json
* Moves a unit test to the functional tests, since a cache was added in the core
* Updates the nimut testing framework and phpunit to the latest possible version
* Use occular as phar since a conflict with different symfony console dependecy versions could not be resolved.
Travis build is green now and all tests get executed
> [BUGFIX] Update test dependencies and fix broken build
