- Classes/FieldProcessor/Service.php
- Classes/FieldProcessor/TimestampToUtcIsoDate.php
- Classes/Util.php
- Configuration/TypoScript/Solr/setup.txt
- ext_autoload.php
Split of Bugfix from https://github.com/TYPO3-Solr/ext-solr/pull/7 for v3.0.x
> Bugfix: endtime in UTC for 3.0.x

- Resources/Private/Language/PluginResults.xml
Some french translation were missing.
> Added some french translation.

- composer.json
composer.json should include the replace statement to work with composer.json exts that have requirements to solr
> [TASK] add replace to composer json

- Classes/Search/SortingComponent.php
- Classes/ViewHelper/SortUrl.php
replace makeInstance calls from ApacheSolrForTypo3\\Solr\\Tx_Solr_Sorting to ApacheSolrForTypo3\\Solr\\Sorting
> use namespaced class Tx_Solr_Sorting (#30)

- Classes/IndexQueue/AbstractIndexer.php
See https://github.com/TYPO3-Solr/ext-solr/issues/54
Not sure if this is the best solution, see possibilities in ticket but I think it is the only one without any breaking change.
> [BUGFIX] only execute detectSerializedValue if isSerialized is FALSE

- Classes/IndexQueue/RecordMonitor.php
Pull request for the 3.0.x branch, for details see: https://forge.typo3.org/issues/66180
> [BUGFIX] Index Queue not updated when changing properties of rootpage

- composer.json
Hallo Ingo,
wie gerade auf Slack hier der „mini“ fix für die composer.json
> [TASK] update 3rd party PHP path in composer.json

- ext_emconf.php
Changed version constraint to cover 7.6 LTS
> [TASK ] Changed version constraint to cover 7.6 LTS Versions

- Classes/Backend/SolrModule/AbstractModuleController.php
- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/IndexQueueModule/Index.html
- Resources/Private/Templates/IndexQueueModule/ShowError.html
* Added new action in IndexQueueModuleControlle to show the error message of a queue item
> [BUGFIX] Fix for issue #116 "Show error" not working in Index Queue

- Classes/Controller/AdministrationController.php
- Classes/Site.php
- Classes/Util.php
- Classes/ViewHelpers/Backend/SitesViewHelper.php
- Resources/Private/Layouts/Default.html
- Resources/Private/Templates/Administration/Index.html
- Reinitialize Site in BackendModule when invalid site was retrieved from backend users uc data.
- Improved error message when no site is initialized.
Fixes: #142
> Sites of backend user should be reset when not valid

- Classes/IndexQueue/Initializer/Page.php
> [BUGFIX] Make constant a string

- Classes/Facet/AbstractFacetRenderer.php
> [BUGFIX] Make marker for facet type available again

- .travis.yml
- Classes/ViewHelper/Ts.php
- Tests/Build/UnitTests.xml
- Tests/Build/bootstrap.sh
- Tests/Build/cibuild.sh
- Tests/Build/cleanup.sh
- Tests/Unit/ContentObject/MultivalueTest.php
- Tests/Unit/Facet/SimpleFacetRendererTest.php
- Tests/Unit/FieldProcessor/PathToHierarchyTest.php
- Tests/Unit/FieldProcessor/ServiceTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
- Tests/Unit/IndexQueue/PageIndexerResponseTest.php
- Tests/Unit/Query/FilterEncoder/DateRangeTest.php
- Tests/Unit/Query/FilterEncoder/HierarchyTest.php
- Tests/Unit/Query/FilterEncoder/RangeTest.php
- Tests/Unit/QueryTestCase.php
- Tests/Unit/SolrUnitTest.php
- Tests/Unit/ViewHelper/TsTest.php
- composer.json
- Add ci environment as present for ext-tika
- Added .travis.yml
- Skipped failing tests for now, need to be reworked
To run the test in your dev enviroment:
1. Got to <solr-ext> root
2. Choose TYPO3 Version
export TYPO3_VERSION="dev-master"
3. Run bootstrapping
./Test/Build/bootstrap.sh
4. Run the test suite
./Test/Build/cibuild.sh
> Introduced travis-ci for unit tests.

- Tests/Build/FunctionalTests.xml
- Tests/Build/cibuild.sh
- Tests/Functional/Fixtures/can_get_all_sites.xml
- Tests/Functional/FunctionalTest.php
- Tests/Functional/SiteTest.php
- Tests/Unit/ContentObject/MultivalueTest.php
- Tests/Unit/Facet/SimpleFacetRendererTest.php
- Tests/Unit/FieldProcessor/PathToHierarchyTest.php
- Tests/Unit/FieldProcessor/ServiceTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
- Tests/Unit/IndexQueue/PageIndexerResponseTest.php
- Tests/Unit/Query/FilterEncoder/DateRangeTest.php
- Tests/Unit/Query/FilterEncoder/HierarchyTest.php
- Tests/Unit/Query/FilterEncoder/RangeTest.php
- Tests/Unit/QueryTestCase.php
- Tests/Unit/UnitTest.php
- Tests/Unit/ViewHelper/TsTest.php
- ext_emconf.php
Added a first functional test and improved naming structure
> Added functional test suite and a first example

- Classes/Controller/AdministrationController.php
Set the site property when re-initialize from first available site
> Set site property during re-initialization

- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
- Tests/Functional/FunctionalTest.php
- Tests/Functional/IndexQueue/Fixtures/update_mount_point_is_updating_the_mount_point_correctly.xml
- Tests/Functional/IndexQueue/RecordMonitorTest.php
* Added fix to avoid generating broken SQL when page is saved in the backend with propery set "is_rootpage"
* Added regression test
> [BUGFIX] Added regression test and fix for issue #155 (SQL error when calling getDestinationMountPropertiesByRootLine)

- Classes/ViewHelper/Facet.php
Fallback to the current page when no target page was configured.
> Added fallback to current page when no targetPage is configured

- Classes/Site.php
> [TASK] Show page titles rootline as site label

- Classes/IndexQueue/RecordMonitor.php
- Tests/Functional/FunctionalTest.php
- Tests/Functional/IndexQueue/Fixtures/fake_extension_table.sql
- Tests/Functional/IndexQueue/Fixtures/fake_extension_tca.php
- Tests/Functional/IndexQueue/Fixtures/new_non_pages_record_is_using_correct_configuration_name.xml
- Tests/Functional/IndexQueue/RecordMonitorTest.php
- Tests/Functional/SiteTest.php
- Tests/Functional/TemplateTest.php
- Fixed bug in RecordMonitor
- Added regression Test and improved Testing Codebase
Fixes #48
> Wrong configuration name was use when a new, non pages record was processed in TCEMain.

- .travis.yml
- README.md
- Tests/Build/bootstrap.sh
- Tests/Build/cibuild.sh
Moved environment variables for integration tests to travis.yml and added introduction in the README.md
> Documented how to run the testsuite locally and move database settings to .travis.yml 

- composer.json
Readd the version property for 3.1.x
> Readded version property in composer.json in 3.1.x branch

- Classes/System/Cache/TwoLevelCache.php
- Classes/Util.php
- Tests/Unit/System/Cache/TwoLevelCacheTest.php
- ext_localconf.php
Added caching framework to Util::getConfigurationFromPageId and refactored method.
Fixes: #182
> Applied patch to use caching framework in getConfigurationFromPageId and refactored code

- .travis.yml
- Resources/Solr/typo3cores/conf/solrconfig.xml
- Fixed wrong path in solrconfig.xml
- Set TYPO3 Version to 7.6.2 in .travis.yml
> Bugfix/205 minor config issue in solr 4.10.4

- CONTRIBUTING.md
- README.md
- Tests/Build/bootstrap.sh
Added current state of CONTRIBUTING.md
Optimized bootstrap for local runs
Removed from README.md what is now in CONTRIBUTING.md and add a link in the README.md file
> Task: Add contributing md

- Classes/Report/SolrConfigStatus.php
- Resources/Solr/typo3cores/conf/solrconfig.xml
> Raised solrconfig version as followup of ticket #204

- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
- Classes/Plugin/CommandPluginBase.php
- Classes/Plugin/FrequentSearches/FrequentSearches.php
- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Classes/Plugin/Search/Search.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/Plugin/AbstractPluginTest.php
- Tests/Integration/Plugin/FrequentSearches/Fixtures/can_render_frequentSearches_plugin.xml
- Tests/Integration/Plugin/FrequentSearches/FrequentSearchesTest.php
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Integration/Plugin/Search/Fixtures/can_render_search_plugin.xml
- Tests/Integration/Plugin/Search/SearchTest.php
- Tests/Unit/Domain/Search/ResultSet/Fixtures/fakeResponse.json
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/ResultSet/TestSearchResponseProcessor.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/UnitTest.php
Fixes: #235 
* Added UnitTest for SearchResultSetService
* Added IntegrationTest for FrequentSearchesPlugin
* Added IntegrationTest for SearchPlugin
* Refactored all Plugins to use SearchResultSetService
> Refactored ResultsPlugin to move SearchLogic into SearchResultsSetService

- .travis.yml
Run the Test against TYPO3 dev-master with PHP 7.0 only
> Run dev-master tests only with PHP7 and raised TYPO3 7.6 version to 7.6.4

- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
Added missing . in TypoScript path.
Fixes: #244
> Added testcase and fix for bug

- Classes/Backend/IndexInspector/IndexInspector.php
Loaded required file from new location and load ExtDirect dependency.
Fixes: #241
> Load Ext.grid.RowExander.js and include ExtDirectCode

- Classes/Backend/IndexInspector/IndexInspector.php
Backport for 3.1.x
Fixes: #241
> Load Ext.grid.RowExander.js and include ExtDirectCode for 3.1.x

- Classes/Backend/ContentElementWizardIconProvider.php
- ext_tables.php
The locallang file has been changed form xml to xlf and has been moved to a subfolder.
The path to the file has not been updated.
> [BUGFIX] Fix path to backend locallang file

- Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php
- Classes/Domain/Search/LastSearches/LastSearchesService.php
- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Plugin/Results/FrequentSearchesCommand.php
- Classes/Plugin/Results/LastSearchesCommand.php
- Tests/Unit/Domain/Search/FrequentSearches/FrequentSearchesServiceTest.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesServiceTest.php
* Moved logic from FrequentSearchesCommand into FrequentSearchesService and added test case
* Moved logic from LastSearchesCommand into LastSearchesService and added test case
Fixes: #243
> Moved logic from FrequentSearchesCommand and LastSearchesCommand into own service class

- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/Domain/Index/IndexService.php
- Classes/Task/IndexQueueWorkerTask.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/IndexQueueModule/Index.html
* Moved functionallity from scheduler task to IndexService to allow Indexing from different locations
* Added backend controller action to index a few documents from the backend
Fixes: #275
> [TASK] Allow indexing from backend index queue module

- Classes/Search.php
Remove deprecated methods.
Fixes: #295
> [TASK] Remove deprecated methods that have been announced to be removed in 4.0

- Classes/JavascriptManager.php
- Classes/Util.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_absRefPrefix_url.xml
- Tests/Integration/IndexQueue/IndexerTest.php
* Moved logic from JavaScriptManager into Util
* Refactore usage in JavaScriptManager and Util::initializeTsfe
* Added regression test
Fixes: #276
> [BUGFIX] absRefPrefix auto is now resolved as in the TYPO3 core - dev-master

- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
- Classes/Plugin/Results/NoResultsCommand.php
- Configuration/TypoScript/Examples/EverythingOn/setup.txt
- Resources/Templates/PiResults/results.htm
- Tests/Integration/Plugin/Results/Fixtures/can_render_results_plugin.xml
- Tests/Integration/Plugin/Results/ResultsTest.php
* Added autocorrection markup to default template
* Enabled autocorrection in EverythingOn template
* Added integration test for autocorrection
* Refactored NoResultsCommand to use SearchResultsSetService to reuse code
Fixes: #224
> [TASK] support auto correction

- Classes/Util.php
* Makes Util::buildTypoScriptConfigurationFromArray static
Fixes: #299
> [TASK] Util::buildTypoScriptConfigurationFromArray should be static

- Classes/Task/ReIndexTask.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Task/ReIndexTaskTest.php
Fixed method call and added regression test.
Fixes: #304
> [BUGFIX]  cleanUpIndex is not using indexConfiguration names for cleanup

- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
> [BUGFIX] Re-Index after deleting a content element

- Classes/Query.php
- Tests/Unit/QueryTest.php
Before only the usage of "hello world" as a phrase was supported. The usage of more complex phrase queries e.g. `"hello world" or "hello planet"`was not supported.
This pull request:
1. adds test cases for the escape method of the query for the previous use cases
2. implements the context depending (inside or outside a phrase) escaping for multiple phrases
Fixes: #307
> [TASK] Support phrases inside a query string

- Documentation/solr release 4.0.md
Draft of the release notes for 4.0.0
Fixes: #302
> [TASK] Add draft for release notes of 4.0.0

- Classes/IndexQueue/Indexer.php
* Used site to get the languageMode and pass it instead of retrieving the site twice
Fixes: #326
> [TASK] Avoid to retrieve the site twice

- ext_tables.sql
* Update type of entry_value of table sys_registry to longblob
Fixes: #253
> [BUGFIX] Can not save many sites in sys_registry

- ext_tables.sql
* Update type of entry_value of table sys_registry to longblob
Fixes: #253
> [BUGFIX] Can not save many sites in sys_registry - release-3.1.x

- Classes/Domain/Search/LastSearches/LastSearchesService.php
- Classes/ResultsetModifier/LastSearches.php
* Moved logic save logic from modifier into service and use the service
Fixes: #338
> [TASK] Saving of LastSearches should be done with LastSearchesService instead of LastSearches ResultSetModifier

- Classes/Controller/AdministrationController.php
- Resources/Private/Layouts/Default.html
- Resources/Private/Layouts/Error.html
- Resources/Private/Partials/NoSiteAvailable.html
- Resources/Private/Templates/Administration/NoSiteAvailable.html
- ext_tables.php
Added action, when no site is available.
Fixes: #342
> [BUGFIX] Backend module does not handle empty state

- Documentation/solr release 3.1.2.md
Add release notes with short description of all bugfixes and improvements.
Fixes: #345
> [TASK] Add release notes for 3.1.2 release

- Resources/Private/Partials/FlashMessages.html
Avoid usage of FlashMessage::renderMode to support TYPO3 8.0
> [BUGFIX] Avoid usage of FlashMessage::renderMode to support TYPO3 8.0

- Classes/Backend/SolrModule/IndexQueueModuleController.php
- Classes/Domain/Index/IndexService.php
- Resources/Private/Language/locallang.xlf
After indexing from backend a flashMessage should be shown.
Fixes: #350
> [TASK] Render FlashMessage after indexing from backend

- Documentation/solr release 4.0.md
Adds a snipped for the auto correction.
> [TASK] Add missing snipped to release notes of 4.0.0

- Configuration/TypoScript/Solr/setup.txt
> [TASK] fix indendation and little typo

- .travis.yml
- Build/Release/ter_tag_uploader.sh
- composer.json
* Create a symlink before upload to have the expected structure for determining the extesion key.
* Use global upload script instead of composer dependency and do cleanup before upload
> [TASK] Create a symlink for extension folder before uploading to TER - release 4.0.x

- .travis.yml
- Build/Release/ter_tag_uploader.sh
- composer.json
* Create a symlink before upload to have the expected structure for determining the extension key.
* Use global upload script instead of composer dependency and do cleanup before upload
> [TASK] Create a symlink for extension folder before uploading to TER - dev-master

- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/Queue.php
- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Classes/Plugin/Search/Search.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/Util.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
* Remove deprecated code
* Fixed missed leftovers
Fixes: #360
> [TASK][!!!] Remove deprecated code

- Documentation/solr release 4.0.1.md
- ext_emconf.php
* Added release notes
* Set version to 4.0.2
Fixes: #382
> [TASK] prepare release for version 4.0.2

- Resources/Solr/typo3cores/conf/basque/schema.xml
* Applies bugfix also on master
Fixes: #384
> [BUGFIX] Fixed typo in basque core - dev-master

- Classes/Domain/Search/SearchRequest.php
- Classes/Plugin/Results/Results.php
- Classes/System/Util/ArrayAccessor.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/System/Util/ArrayAccessorTest.php
* Extended request object to be able to retrieve page, resultsPerPage, facetNames
* Added possiblility to create a sub request that keeps persistent arguments(q, and tx_solr:filter)
> [TASK]  As developer i want to access the arguments by using the request object

- Classes/Site.php
- Classes/Util.php
- Tests/Integration/Fixtures/can_get_default_language.xml
- Tests/Integration/SiteTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/System/Util/ArrayAccessorTest.php
* Added test for Site::getDefaultLanguage
* Fixed bug and refactored other usages
* Fixed psr-2 violations in other tests
Fixes: #392
> [TASK] Util::getConfigurationFromPageId with $path should return the expected path - dev-master

- Classes/Domain/Search/SearchRequest.php
- Classes/Plugin/Results/Results.php
- Tests/Integration/Plugin/AbstractPluginTest.php
- Tests/Integration/Plugin/FrequentSearches/FrequentSearchesTest.php
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
* Added arguments to the constructor
* Assign them in ResultsPlugin
* Added unit and integration test
Fixes: #395
> [TASK] Allow to get contextPageUid and contextSystemLanguageUid from SearchRequest

- Classes/Facet/HierarchicalFacetHelper.php
Small changes to provide IFSUB  submenu functionality for hierarchical facets. Changes ITEM_STATE variable in menu array
Fixes: #397
> [TASK] Small changes to provide IFSUB Menu functionality.

- Classes/Domain/Search/SearchRequest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
Add possibility to remove facet value from request.
Fixes: #401
> [TASK] Allow to remove a facet value from the search request

- Classes/Domain/Search/SearchRequest.php
- Classes/System/Util/ArrayAccessor.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/System/Util/ArrayAccessorTest.php
* Added possibility to set and remove the sorting
* Added possibility to to remove all facets
Fixes: #403
> [TASK] As developer i want to use the request object to set the sorting and remove facets

- Resources/Templates/PiResults/pagebrowser.htm
fixes 
```html
<div **class**="tx-solr-pagination-page-browser" **class**="tx-pagebrowse-pi1">
```
> [BUGFIX] removed duplicate class atrribute

- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/System/Util/ArrayAccessor.php
Use ArrayAccessor also in TypoScriptConfiguration
* Use central logic of ArrayAccessor also in the TypoScriptConfiguration
Fixes: #412
> [TASK] Use ArrayAccessor also in TypoScriptConfiguration

- Classes/Domain/Search/Score/Score.php
- Classes/Domain/Search/Score/ScoreCalculationService.php
- Classes/ResultDocumentModifier/ScoreAnalyzer.php
- Tests/Unit/Domain/Search/Score/Fixtures/fakeSolrDebugData.txt
- Tests/Unit/Domain/Search/Score/ScoreCalculationServiceTest.php
* Moved code into service class
* Added unit tests
* Added score value object to hold the score data
Fixes: #416
> [TASK] Move score calucation into ScoreCalculationService to make it reuseable

- Classes/Domain/Search/SearchRequest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
Allow to get active facet values by a certain facet name from the request.
Fixes: #418
> [TASK] Allow to get active facet values by a certain facet name from the request.

- Classes/Facet/NumericRangeFacetRenderer.php
Load css file for numericRangeFacet correctly.
Fixes: #429
> [BUGFIX] Load css file for numericRangeFacet correctly

- Classes/Domain/Search/SearchRequest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
As developer i want to remove all facet values by name from the request:
* Adds method SearchRequest::removeAllFacetValuesByName and test
Fixes: #431
> [TASK] As developer i want to remove all facet values by name from the request

- Classes/Query.php
- Tests/Integration/Plugin/Results/Fixtures/can_render_results_plugin.xml
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Unit/QueryTest.php
* Fixed bug
* Added integration test
Fixes: #433
> [BUGFIX] Highlighting wrap is not working when title and content field is used for highlighting

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Plugin/AbstractPluginTest.php
Added method getDocumentById to SearchResultSetService
* Added method and test
Fixes: #436
> [TASK] Added method getDocumentById to SearchResultSetService

- ext_tables.php
* As missing title will break the whole info module
> BUGFIX: Language path for info module

- .travis.yml
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/SearchTest.php
- Tests/Integration/TemplateTest.php
- Tests/Unit/ContentObject/MultivalueTest.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/Facet/SimpleFacetRendererTest.php
- Tests/Unit/QueryTest.php
- Tests/Unit/UnitTest.php
- Tests/Unit/ViewHelper/TsTest.php
Replaces usage of getMock with getMockBuilder
Fixes: #435
> [TASK] Fixed build warnings and update travis target versions

- Classes/ConnectionManager.php
- Classes/Sorting.php
- Classes/Typo3Environment.php
- Classes/ViewHelper/Date.php
- Classes/ViewHelper/Multivalue.php
- Classes/ViewHelper/Relevance.php
- Classes/ViewHelper/SortUrl.php
- Tests/Unit/ConnectionManagerTest.php
- Tests/Unit/Typo3EnvironmentTest.php
- Tests/Unit/ViewHelper/AbstractViewHelperTest.php
- Tests/Unit/ViewHelper/DateTest.php
- Tests/Unit/ViewHelper/MultivalueTest.php
- Tests/Unit/ViewHelper/RelevanceTest.php
- Tests/Unit/ViewHelper/SortUrlTest.php
> [BUGFIX] Fix usage of TypoScript configuration object

- Resources/Private/Templates/OverviewModule/Index.html
Adds link to backend module
Fixes: #438
> [TASK] Added link to hosted-solr.com to allow simple solr setup for new users.

- Classes/Typo3Environment.php
> [TASK] Mark Typo3Environment as deprecated

- Resources/Private/Templates/IndexQueueModule/ShowError.html
* Only one leftover was found.
Fixes: #348
> [TASK] Replaced class name with new class from bootstrap 3.0

- CONTRIBUTING.md
Adds older versions of Solr plugins and addons to the CONTRIBUTING.md file
> [TASK] Add version combinations for older versions to the CONTRIBUTING.md file

- Classes/Typo3Environment.php
> [BUGFIX] Add missing use statement for GeneralUtility

- Documentation/solr release 5.0.md
Adds the release notes for 5.0.0
Fixes: #451
> [TASK] Prepare release notes for 5.0.0

- Documentation/Backend/BackendModule.rst
- Documentation/Configuration/Reference/TxSolr.rst
- Documentation/Configuration/Reference/TxSolrCssFiles.rst
- Documentation/Configuration/Reference/TxSolrGeneral.rst
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Documentation/Configuration/Reference/TxSolrJavaScriptFiles.rst
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Configuration/Reference/TxSolrSolr.rst
- Documentation/Configuration/Reference/TxSolrStatistics.rst
- Documentation/Configuration/Reference/TxSolrTemplateFiles.rst
- Documentation/FAQ/Index.rst
- Documentation/GettingStarted/ConfigureExtension.rst
> [TASK] Fixed formatting and added questions to FAQ.

- Build/Release/ter_tag_uploader.sh
> [TASK] Symlink extension directory before TER upload.

- Classes/Util.php
- Tests/Unit/UtilTest.php
Adds a cache to getSiteHashForDomain to reduce the calls of sha1
Fixes: #318
> [TASK] Add cache for Util::getSiteHashForDomain

- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrLogging.rst
> [BUGFIX] Fix intention in TypoScript and Since => 5.0 in documentation

- Documentation/Releases/solr release 5.0.md
Add final changes to the release notes.
> [TASK] Finalize release notes

- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
Fixed label for de and added translation for nl.
Fixes: #493
> [BUGFIX] Fixed label for de and nl

- Classes/Domain/Index/IndexService.php
- Classes/Task/IndexQueueWorkerTask.php
- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
- Resources/Private/Language/ModuleScheduler/de.locallang.xlf
- Resources/Private/Language/ModuleScheduler/locallang.xlf
- Resources/Private/Language/ModuleScheduler/nl.locallang.xlf
Backport for #491 on the 4.0.x branch.
Fixes: #491
Thx to @jigal for the patch.
> [BUGFIX] absRefPrefix auto for records is not working in the cli context

- Classes/Domain/Index/IndexService.php
- Classes/System/Environment/CliEnvironment.php
- Classes/System/Environment/WebRootAllReadyDefinedException.php
- Classes/Task/IndexQueueWorkerTask.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/System/Environment/CliEnvironmentTest.php
- Tests/Unit/Task/IndexQueueWorkerTaskTest.php
Extract cli initialization to CliEnvironment class.
Fixes: #497
> [TASK] Extract cli initialization to CliEnvironment class

- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
> [BUGFIX] Fixed label for indexqueueworker_field_forcedWebRoot

- Build/Test/bootstrap.sh
Checkout TYPO3 core from source during CI.
> [TASK] Checkout TYPO3 core from source during CI

- Build/Test/bootstrap.sh
Use sources for TYPO3 core in CI.
> [TASK] Checkout TYPO3 core from source during CI (#555)

- Tests/Unit/Access/RootlineElementTest.php
Adds unit tests for the RootlineElement class
> [TASK] Add unit test for RootlineElement

- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Tests/Build/bootstrap.sh
Backport fix for runtime notices in PluginBase.php and Results.php
> [TASK] Backport runtime notice fix

- Resources/Solr/configsets/ext_solr_6_0_0/conf/chinese/schema.xml
- Resources/Solr/configsets/ext_solr_6_0_0/conf/japanese/schema.xml
- Resources/Solr/configsets/ext_solr_6_0_0/conf/korean/schema.xml
- Resources/Solr/configsets/ext_solr_6_0_0/conf/solrconfig.xml
- Resources/Solr/configsets/ext_solr_6_0_0/conf/thai/schema.xml
This commit replaces deprecated filters and tokenizers for the chinese, japanese, korean and thai language
Related: #569
> [BUGFIX] Replace deprecated filters/tokenizers

- Resources/Solr/configsets/ext_solr_6_0_0/conf/solrconfig.xml
> [BUGFIX] Reenable Access filter plugin

- Resources/Private/Templates/IndexMaintenanceModule/Index.html
- Resources/Private/Templates/IndexQueueModule/Index.html
- Resources/Private/Templates/StopWordsModule/Index.html
- Resources/Public/StyleSheets/ModuleAdministration.css
* Makes sure everything is aligned properly
* Removes some whitespace, giving the module content more room
> Backend module layout fixes

- Classes/Search.php
Fixed suggestion in a structure that is useable with solr 6.x.
> [BUGFIX] Make suggestion working with Apache Solr 6.1

- Classes/Search.php
* Fix psr2 violation in Search.php
> [BUGFIX] Fix psr2 violation in Search.php

- Dockerfile_full
Signed-off-by: Patrick Oberdorf <p.oberdorf@raphael-gmbh.de>
> [TASK] added volume definition to Dockerfile_full

- Documentation/GettingStarted/Solr.rst
- Documentation/Solr/ConfigurationStructures.rst
- Documentation/Solr/Index.rst
This commit adds a basic documentation for the new installer and the configuration structure for Apache Solr 6.1
> [TASK] Add basic documentation for structure and install script

- Classes/Backend/SolrModule/IndexFieldsModuleController.php
- Classes/Backend/SolrModule/OverviewModuleController.php
- Resources/Private/Templates/IndexFieldsModule/Index.html
> BUG Fixed unhandled exception in Index Fields backend module

- Classes/Eid/Suggest.php
> [BUGFIX] Added rawurldecode for filters to use the decoded json string

- Documentation/Releases/solr release 5.1.md
* Adds release notes for the upcomming version 5.1.0
> [TASK] Add release notes for 5.1.0

- .travis.yml
- Build/Test/cibuild.sh
- composer.json
* Pinned version to 1.11.7
* Make sure to use php-cs-fixer NOT as require dev dependency an do a global install in .travis.yml
Fixes: #612
> [TASK] Pin php-cs-fixer version to v1.11.7 - release-5.0.x

- .travis.yml
- Build/Test/cibuild.sh
- composer.json
* Pinned version to 1.11.7
* Make sure to use php-cs-fixer NOT as require dev dependency an do a global install in .travis.yml
Fixes: #612
> [TASK] Pin php-cs-fixer version to v1.11.7 - release-4.0.x

- .travis.yml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Resources/Private/Install/install-solr.sh
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Plugin/AbstractPluginTest.php
- Tests/Integration/SearchTest.php
- Tests/Integration/Task/ReIndexTaskTest.php
- composer.json
* Removes sudo from travis.yml (not needed with new installer)
* Adapt jdk installation for container based builds
* Use autoCommit instead of active wait to speedUp integration tests
* Add the download folder of the installer to the travis caches
* Disable xdebug for now since the code coverage is not used (by now)
>  [TASK] Remove sudo from .travis.yml and optimize performance

- Build/Release/pre_upload_check.php
- Classes/Backend/SolrModule/SearchStatisticsModuleController.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/SearchStatisticsModule/Index.html
- Resources/Public/JavaScript/Chart.js
- Resources/Public/JavaScript/SearchStatistics.js
- Tests/Integration/Domain/Search/StatisticsRepository/Fixtures/can_get_statistics.xml
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
- ext_tables.sql
Adds a graph / line chart of queries over time at the top of the new statistics module
Resolves #601
> [TASK] Add statistics graph

- .scrutinizer.yml
> [TASK] Add a basic scrutinizer.yml

- Classes/Query.php
- Classes/SuggestQuery.php
- Tests/Unit/SuggestQueryTest.php
* Cleanup code in Query.php
* Avoid initialization of fieldCollapsing in SuggestQuery
* Added unit test for SuggestQuery
Fixes: #626
> [BUGFIX] Make suggest working when variants are used

- .travis.yml
- Classes/Plugin/Results/FrequentSearchesCommand.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Task/IndexQueueWorkerTaskTest.php
- Tests/Integration/Task/ReIndexTaskTest.php
Fixed broken tests with dev-master and all 8.x versions
> [TASK] check broken tests with TYPO3 8.x versions and dev-master

- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
1. Adapted cHash to new cHash calculation
2. Caluclated days in testcase dynamically to match to fixture
Fixes: #654
> [BUGFIX] Fixed broken tests in dev-master

- README.md
* As documentation was moved to docs.typo3.org
> [TASK] Update documentation link

- Classes/ContentObject/Relation.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_direct_relation.xml
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_direct_relationAndAdditionalWhere.xml
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_directrelated_tca.php
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
> [BUGFIX] Use the configured localField instead of foreignLabelField (#629)

- Classes/AbstractDataHandlerListener.php
- Classes/Backend/IndexingConfigurationSelectorField.php
- Classes/Domain/Search/ResultSet/SearchResultSet.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Classes/Facet/DateRangeFacetRenderer.php
- Classes/Facet/Facet.php
- Classes/Facet/LinkBuilder.php
- Classes/IndexQueue/FrontendHelper/AuthorizationService.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/PageIndexer.php
- Classes/IndexQueue/PageIndexerRequest.php
- Classes/IndexQueue/PageIndexerRequestHandler.php
- Classes/IndexQueue/PageIndexerResponse.php
- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/Report/SchemaStatus.php
- Classes/Report/SolrVersionStatus.php
- Classes/Search.php
- Classes/Site.php
- Classes/SuggestQuery.php
- Classes/System/Environment/CliEnvironment.php
- Classes/Task/IndexQueueWorkerTask.php
- Classes/Template.php
> [TASK] Fix typos

- Resources/Private/Partials/NoSiteAvailable.html
Improve the error message by using a callout
Resolves: https://github.com/TYPO3-Solr/ext-solr/issues/663
> [TASK] Improve error message in BE

- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
* Fix some scrutinizer violations in PluginBase.php and Results.php
> [BUGFIX] Fix some scrutinizer violations in PluginBase.php and Results.php

- Classes/Site.php
- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
Use styled classes and force count of documents to integer.
Resolves: #671
> [BUGFIX] Use styled fields for the scheduler tasks

- .scrutinizer.yml
- Classes/Access/Rootline.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Search/AccessComponent.php
- Classes/Typo3PageIndexer.php
- Tests/Integration/Domain/Search/ResultSet/Fixtures/fe_user_page.xml
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/IntegrationTest.php
* Adds an integration test for frontend restircted pages (fe_users)
* Tweeks some codeparts of the tested code
* Increases the scrutinizer timeout to make sure code coverage is present
> [TASK] Added integration test for frontend restricted page 

- Classes/Plugin/Results/Results.php
> [TASK] Do not use implicit boolean checks in overrideTyposcriptWithFlexformSettings

- Classes/ContentObject/Relation.php
- Classes/Controller/AdministrationController.php
- Classes/Domain/Index/IndexService.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Facet/AbstractFacetRenderer.php
- Classes/HtmlContentExtractor.php
- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/Item.php
- Classes/IndexQueue/Queue.php
- Classes/System/Configuration/ConfigurationManager.php
- Classes/System/Configuration/TypoScriptConfiguration.php
Fixed several CGL issues reported by scrutinizer.
> [TASK] Fix several scrutinizer CGL issues

- Classes/Domain/Search/SearchRequest.php
* Use guard clause in getCopyForSubRequest
* Use array functions and closures when possible
* Fixed documentation issues
> [TASK] Reduce the complexity of the SearchRequest class

- Classes/Query.php
- Tests/Unit/QueryTest.php
* Extracted method applyConfiguredFacetSorting
* Simplyfied testcase
> [TASK] Extract method applyConfiguredFacetSorting

- Classes/Query.php
- Tests/Unit/QueryTest.php
This commit adds tests for the Query class and  comments how complex parts can be refactored.
> [TASK] Add more unit tests for Query class

- Classes/Query.php
- Tests/Unit/QueryTest.php
Add unit tests to query class to allow refactoring.
> [TASK] Add additional unit tests to query class

- Classes/ContentObject/Relation.php
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_direct_relation.xml
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_directrelated_tca.php
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
- Tests/Integration/IndexQueue/IndexerTest.php
- Fix recursive value resolution
- Add integration tests for specific foreignLabelField and
enableRecursiveValueResolution settings
Fixes: #690
> [BUGFIX] Fix recursive value resolution in SOLR_RELATION

- Classes/ContentObject/Relation.php
> [BUGFIX] Fix configuration backup

- Classes/Query.php
Removed duplicated code and simplified some methods.
> [TASK] Reduced complexity of query class

- Classes/Access/RootlineElement.php
- Classes/AdditionalFieldsIndexer.php
- Classes/ConnectionManager.php
- Classes/ContentObject/Relation.php
- Classes/GarbageCollector.php
* Removed unused code
* Fixed documentation
> [TASK] Fixed Scrutinizer violations

- Classes/ContentObject/Relation.php
* Removed unused code
* Use instanciation with ::class
* Use short array initialization with []
* Use guard clauses and early returns when possible
> [TASK] Fix scrutinizer violations in Relation class

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
Fixed scrutinizer Issues in SearchResultSetService and SearchRequest
> [TASK] Fix scrutinizer issues in SearchResultSetService SearchRequest

- Documentation/GettingStarted/Solr.rst
- Documentation/Solr/ConfigurationStructures.rst
- Documentation/Solr/IndexMaintenance.rst
* Explain how to deploy the configSet into a plain solr server
* Explain the structure of a configSet
* Explain how to create a core with the restApi
Fixes: #681
> [TASK] Add documentation for Apache Solr 6 and configSets

- Build/Release/ter_tag_uploader.sh
Fixed typo in ter_tag_uploader.sh
REPRONAME => REPOSITORY_NAME
> [TASK] Fixed typo in ter_tag_uploader.sh

- Classes/Backend/SolrModule/SearchStatisticsModuleController.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
Fixed groupBy statement in mysql strict mode.
Fixes: #703
> [BUG] Fixed group by and statement in Statistics

- Classes/Report/SolrStatus.php
- Resources/Private/Templates/Reports/SolrStatus.html
Instead of using a custom template solution, use a fluid standalone view
Resolves: #735
> [TASK] Cleanup SolrStatus report

- Resources/JavaScript/ContextMenu/initializesolrconnectionsclickmenuaction.js
Use the notifications instead of the flash messages which don't
work in 8 anymore.
Resolves: #741
> [BUGFIX] Use correct notification API

- Classes/Report/AccessFilterPluginInstalledStatus.php
- Classes/Report/AllowUrlFOpenStatus.php
- Classes/Report/FilterVarStatus.php
- Classes/Report/SchemaStatus.php
- Classes/Report/SolrConfigStatus.php
- Classes/Report/SolrConfigurationStatus.php
- Classes/Report/SolrVersionStatus.php
- Resources/Private/Templates/Reports/AccessFilterPluginInstalledStatusIsOutDated.html
- Resources/Private/Templates/Reports/AccessFilterPluginInstalledStatusNotInstalled.html
- Resources/Private/Templates/Reports/SchemaStatus.html
- Resources/Private/Templates/Reports/SolrConfigStatus.html
- Resources/Private/Templates/Reports/SolrConfigurationStatusDomainRecord.html
- Resources/Private/Templates/Reports/SolrConfigurationStatusIndexing.html
- Resources/Private/Templates/Reports/SolrVersionStatus.html
Using fluid instead of a custom template solution improves the code quality
and makes later changes easier.
Furthermore the output has been improved by using proper tags like <code> for paths and versions</code>
Resolves: #739
> [TASK] Use fluid to render reports

- Classes/ViewHelper/Lll.php
> [TASK] Remove usage of deprecated GeneralUtility:readLLLfile

- Classes/IndexQueue/PageIndexerRequest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
Remove https check since it was not working and https should be allowed.
Fixes: #750
> [TASK] Remove https check since it was not working and https should be allowed

- Classes/IndexQueue/PageIndexerRequestHandler.php
> [TASK] Use ::class and [] syntax in PageIndexerRequestHandler

- Classes/IndexQueue/NoPidException.php
- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/exception_is_triggered_without_pid.xml
- Tests/Integration/IndexQueue/Fixtures/queue_is_not_filled_when_item_is_set_to_hidden.xml
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_extendToSubpages_set_and_hidden_removed.xml
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_hidden_set_and_extendToSubpage_removed.xml
- Tests/Integration/IndexQueue/Fixtures/unexisting_record_can_not_be_added_to_queue.xml
- Tests/Integration/IndexQueue/Fixtures/update_mount_point_is_updating_the_mount_point_correctly.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
* Returns an integer for a numeric value
* Throws an Exception when getPID returns false
Fixes: #755
> [BUGFIX] DataHandler getPID can return false

- Classes/IndexQueue/Initializer/Page.php
- Tests/Integration/IndexQueue/Fixtures/mount_pages_are_added_once.xml
- Tests/Integration/IndexQueue/Fixtures/mount_pages_initialize_queue_as_expected.xml
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
* Apply and adapt the initial patch from dimitry
* Added testcases to verify fix
Fixes: #715
> [BUGFIX] Duplicate entries in the index queue with mount points

- Documentation/FAQ/Index.rst
> [TASK] Added example how to index an https / ssl page.

- Classes/IndexQueue/RecordMonitor.php
Extracts method getParentPageIdsFromRootLine in RecordMonitor to reduce complexity.
> [TASK] Extract method getParentPageIdsFromRootLine from RecordMonitor to reduce complexity

- Classes/Util.php
Use ::class in all instanciations in Util.
> [TASK] Use ::class in Util for instanciation

- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/change_content_element.xml
- Tests/Integration/IndexQueue/Fixtures/change_translated_content_element.xml
- Tests/Integration/IndexQueue/Fixtures/localized_page_is_added_to_the_queue.xml
- Tests/Integration/IndexQueue/Fixtures/localized_page_is_not_added_to_the_queue_when_parent_hidden.xml
- Tests/Integration/IndexQueue/Fixtures/queue_entry_stays_when_overlay_set_to_hidden.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
* Fixed the bug
* Added several test cases
Fixes: #766
> [BUGFIX] Page is not added to queue when page_language_overlay record changed

- Documentation/FAQ/Index.rst
> [TASK] Wrong reference syntax

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Search.php
- Classes/SolrService.php
- Tests/Unit/SolrServiceTest.php
* This pull request adds a cache to the method performPingRequest in order to reduce http request to the ping handler
* The cache in SearchResultSetService is therefore not needed anymore
* Add tests for the SolrService
* Fixes scrutinizer issues in SolrService
Fixes: #509
> [TASK] Reduce ping requests

- Documentation/FAQ/Index.rst
Add's FAQ entry for using a SOLR_MULTIVALUE field with a user function.
> [TASK] Add FAQ entry for SOLR_MULTIVALUE usage with a userFunc

- Classes/Site.php
- Tests/Integration/Fixtures/can_get_all_pages_from_sites.xml
- Tests/Integration/SiteTest.php
* Added tests
* Reduce complexity of getPages
* Replace ::class and [] when possible
> [TASK] Simplified method getPages by splitting one method into two methods

- Classes/Query.php
- Tests/Unit/QueryTest.php
* Add's a method to remove a filter by the value "key:value"
* Adds tests
* Uses ::class when possible
* Replaces usage of array() with []
Fixes: #607
> [TASK] Added method Query::removeFilterByValue

- .travis.yml
- Classes/Report/SolrConfigurationStatus.php
* Fixed group by in reports
* Pinned php-cs-fixer to 1.13.1
* Run tests on mysql 5.6
Fixes: #796 
See: https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/
> [TASK] Adapt build to latest travis image changes

- Classes/SolrService.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Documentation/Configuration/Reference/TxSolrSolr.rst
- Tests/Unit/SolrServiceTest.php
* This PR takes the initial patch (See: #795)
* Adds a unit test
* Moves logic into SolrService
* Adds documentation
Fixes: #794
> [TASK] Allow to configure connection timeout for solr

- Documentation/Releases/solr release 6.0.md
Added release notes for 6.0.0.
Fixes: #792
> [TASK] Add release notes for 6.0.0

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/IntegrationTest.php
* This pull request adds a workaround for SOLR-9616
* After the release of Apache Solr 6.4, we can update to 6.4 and remove this workaround
Fixes: #668
> [TASK] Add workaround for Apache Solr Bug SOLR-9616

- Classes/ConnectionManager.php
- Tests/Integration/ConnectionManagerTest.php
- Tests/Integration/Fixtures/can_initialize_connections.xml
- Tests/Integration/Fixtures/can_initialize_two_connections.xml
* This PR adds Tests for the ConnectionManager
* Uses the ::class and short array syntax in the ConnectionManager
* Reduces duplicate code
> [TASK] Use ::class and short array syntax in ConnectionManager

- Classes/FieldProcessor/PageUidToHierarchy.php
- Classes/FieldProcessor/Service.php
- Classes/IndexQueue/FrontendHelper/AuthorizationService.php
- Classes/IndexQueue/FrontendHelper/Dispatcher.php
- Classes/IndexQueue/FrontendHelper/PageFieldMappingIndexer.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/PageIndexer.php
- Classes/System/Configuration/ConfigurationManager.php
Use the ::class syntax in:
* PageUidToHierarchy
* Service
* AuthorizationService
* Dispatcher
* PageFieldMappingIndexer
* PageIndexer
* Page
* PageIndexer
* ConfigurationManager
> [TASK] Use ::class in some classes

- Documentation/Releases/solr release 6.0.md
Just some minor tweaks and fixing some typos and names.  
Also made lines break after about 80 characters.
> Tweak wording, typos in release notes

- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Classes/System/Configuration/TypoScriptConfiguration.php
This PR removes code that has been marked and announced as deprected
Fixes: #809
> [!!!][TASK] Remove deprecated code

- Classes/SolrService.php
- Tests/Unit/SolrServiceTest.php
* Adds test cases for setScheme
* Refactors the method by using guard clauses
> [TASK] Refactor SolrService::setScheme

- Classes/Util.php
This pr:
* Improves the caching in getConfigurationFromPageId by adding the results allways to the in memory cache
* Extracts the generation of the configuration array into an own method
> [FEATURE] Improve caching in getConfigurationFromPageId

- Classes/Util.php
> [BUG] Optimize call in isDraftRecord with respect to workspaces

- Documentation/Configuration/Reference/TxSolrSolr.rst
- Documentation/Releases/solr release 6.0.md
Adds missing changes to release notes.
> [TASK] Add missing pull requests to release notes and fixed documentation

- Documentation/Releases/solr release 6.0.md
Move changes to non breaking changes, which are not breaking
> [BUGFIX] Move changes to non breaking changes, which are not breaking

- Documentation/GettingStarted/Solr.rst
- Documentation/Releases/solr release 6.0.md
Adds the feedback from ingo to the release notes.
> [TASK] Add feedback from ingo

- Classes/SolrService.php
This PR extracts the code from requestServlet that is triggering the request with the transport backend. Beside that setting $rawPost = '' was removed, since.
* method == HEAD is not handled below and $rawPost is not used, when method == GET.
> [TASK] Extract method from requestServlet and remove unneeded code

- .scrutinizer.yml
- Classes/Typo3PageIndexer.php
- Documentation/Development/Index.rst
- Documentation/Development/Indexing.rst
- Documentation/Index.rst
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IndexQueue/FrontendHelper/TestAdditionalPageIndexer.php
- Tests/Integration/IndexQueue/FrontendHelper/TestPostProcessor.php
* Add integration tests
* Simplified code
* Added documentation for possible points to extend the indexing
> [TASK] Refactor Typo3PageIndexer

- .travis.yml
- Tests/Integration/IndexQueue/Fixtures/change_translated_content_element.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Unit/ConnectionManagerTest.php
- Tests/Unit/ViewHelper/AbstractViewHelperTest.php
* Changes the build configuration to build agains 8.5 & master
* Adds PHP 7.1
Fixes: #848
> [TASK] Change build configuration for 8 and fixed broken tests

- .travis.yml
> [TASK] Allow tests against TYPO3 master to fail

- Classes/ConnectionManager.php
- Configuration/TypoScript/Solr/setup.txt
> [FEATURE] Add stdWrap support for plugin.tx_solr.solr values

- Classes/AdditionalFieldsIndexer.php
- Classes/System/ContentObject/ContentObjectService.php
- Tests/Unit/System/ContentObject/ContentObjectServiceTest.php
> [TASK] Use ContentObjectService in AdditionalFieldsIndexer

- Classes/Controller/AdministrationController.php
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Unit/ConnectionManagerTest.php
- Tests/Unit/ContentObject/MultivalueTest.php
- Tests/Unit/Domain/Search/FrequentSearches/FrequentSearchesServiceTest.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Facet/SimpleFacetRendererTest.php
- Tests/Unit/SolrServiceTest.php
- Tests/Unit/System/Cache/TwoLevelCacheTest.php
- Tests/Unit/Typo3PageContentExtractorTest.php
- Tests/Unit/ViewHelper/AbstractViewHelperTest.php
- Tests/Unit/ViewHelper/RelevanceTest.php
- Tests/Unit/ViewHelper/SortUrlTest.php
- Tests/Unit/ViewHelper/TsTest.php
> [TASK] Use ::class notation in getDumbMock

- Classes/Plugin/Results/SortingCommand.php
> [BUGFIX] Fixed typehint in SortingCommand

- Classes/Backend/SolrModule/IndexMaintenanceModuleController.php
- Classes/SolrService.php
- Tests/Integration/SolrServiceTest.php
> [TASK] Use the logic in SolrService to reload a core from the backend module

- Classes/ConnectionManager.php
> [BUGFIX] Take language into account when configuration is fetched

- Classes/Backend/SolrModule/AdministrationModuleManager.php
- Classes/CommandResolver.php
- Classes/Eid/Api.php
- Classes/Eid/SiteHash.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/AbstractIndexer.php
- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/Queue.php
- Classes/Plugin/CommandPluginBase.php
- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/ErrorsCommand.php
- Classes/Plugin/Results/ResultsCommand.php
- Classes/Search.php
- Classes/Search/SearchComponentManager.php
- Classes/Typo3PageIndexer.php
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Documentation/Releases/solr release 3.1.md
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Task/IndexQueueWorkerTaskTest.php
- Tests/Unit/ContentObject/MultivalueTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/QueryTest.php
> [TASK] Use ::class notation in implement interface

- Classes/Facet/FacetRendererFactory.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/PageIndexerRequestHandler.php
- Classes/Search/AnalysisComponent.php
- Classes/Search/ElevationComponent.php
- Classes/Search/FacetingComponent.php
- Classes/Search/HighlightingComponent.php
- Classes/Search/LastSearchesComponent.php
- Classes/Search/StatisticsComponent.php
- Classes/Service/ModuleDataStorageService.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
> [TASK] Added ::class notation in various other places

- ext_localconf.php
- ext_tables.php
> [TASK] Use ::class notation in configuration files

- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Plugin/AbstractPluginTest.php
- Tests/Integration/Plugin/FrequentSearches/FrequentSearchesTest.php
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Integration/Plugin/Search/SearchTest.php
- Tests/Integration/TemplateTest.php
- Tests/Unit/ContentObject/MultivalueTest.php
- Tests/Unit/Domain/Search/FrequentSearches/FrequentSearchesServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
- Tests/Unit/Facet/SimpleFacetRendererTest.php
- Tests/Unit/Query/Modifier/FacetingTest.php
- Tests/Unit/QueryTest.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
- Tests/Unit/System/Util/ArrayAccessorTest.php
- Tests/Unit/ViewHelper/RelevanceTest.php
- Tests/Unit/ViewHelper/TsTest.php
> [TASK] use bracket notation instead of array() in Tests

- ext_localconf.php
> [BUG] Fixed that BackendSummary->getSummary is configured falsely

- Classes/GarbageCollector.php
- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/System/TCA/TCAService.php
- Tests/Unit/System/TCA/TCAServiceTest.php
* Introduces a TCAService class that allows to perform TCA related checks for records
* Add unit tests for TCAService
* Replaces usage in RecordMonitor and GarbageCollector
Fixes: #903
> [TASK] Introduce TCAService

- LICENSE.txt
Should solve #845 - took the one from TYPO3 - OK?
> [TASK] Added GPL-2 license file

- Build/Test/cibuild.sh
> [TASK] Addjust pathes for bootstrapping

- Classes/Domain/Index/Queue/RecordMonitor/Helper/MountPagesUpdater.php
- Documentation/Database/Index.rst
- Documentation/Index.rst
- ext_tables.sql
Added som important indexes to the pages table to speed up certain solr  
operations while copying big sites solves #939
> [TASK] Added some important indexes to pages 

- Documentation/FAQ/Index.rst
Question and answer for „how to replace jQuery“ to FAQ added.
Link to configuration reference for Js files added to answer.
> [TASK] Add jQuery replacement guide to FAQ

- Classes/Util.php
This also gains some performance when copying trees - should solve #940
> [TASK] Added runtime-cache to isRootPage in Util Class

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/Site.php
- Classes/Util.php
- Tests/Integration/IndexQueue/QueueTest.php
> [TASK] Only fetch necessary data in BackendUtility::getRecord

- Classes/Query.php
- Tests/Unit/QueryTest.php
> [TASK] Mark addSortField and getSortingFields as deprecated

- Classes/IndexQueue/Queue.php
This also gains some performance when copying trees performance when copying trees - should solve #942
> [TASK] Added run-time cache to addNewItem

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/Site.php
- Classes/Util.php
> [TASK] Deprecated Util::getRootPageId and moved it to RootPageResolver

- Classes/FieldProcessor/TimestampToIsoDate.php
- Classes/FieldProcessor/TimestampToUtcIsoDate.php
- Classes/Plugin/Results/ResultsCommand.php
- Classes/Query/FilterEncoder/DateRange.php
- Classes/System/DateTime/FormatService.php
- Classes/Util.php
- Tests/Unit/System/DateTime/FormatServiceTest.php
Deprecated them in Util. Added some Unit tests too.
Fixes: #957
> [TASK] Moved Time related methods to FormatService 

- Classes/ConnectionManager.php
> [TASK] Fix scrutinizer issues in ConnectionManager

- Classes/Site.php
- Classes/Util.php
- Tests/Integration/Fixtures/can_create_instance_with_non_root_site.xml
- Tests/Integration/Fixtures/can_create_instance_with_root_site.xml
- Tests/Integration/SiteTest.php
> [TASK] Fix scrutinizer issues in Site

- Classes/SpellChecker.php
> [TASK] Fix scrutinizer issues in SpellChecker

- Classes/ViewHelper/Facet.php
> [TASK] Fix scrutinizer issues in Facet

- Classes/Query/LinkBuilder.php
> [TASK] Fix scrutinizer issues in LinkBuilder

- Classes/Plugin/Results/SuggestFormModifier.php
> [TASK] Fix scrutinizer issues in SuggestFormModifier

- Classes/Plugin/Results/QueryAnalyzerFormModifier.php
> [TASK] Fix scrutinizer issues in QueryAnalyzerFormModifier

- Classes/Plugin/Results/FormCommand.php
> [TASK] Fix scrutinizer issues in FormCommand

- Classes/JavascriptManager.php
> [TASK] Fix scrutinizer issues in JavascriptManager

- Classes/Plugin/Results/ParameterKeepingFormModifier.php
> [TASK] Fix scrutinizer issues in ParameterKeepingFormModifier

- Classes/Facet/AbstractFacetRenderer.php
> [TASK] Fix scrutinizer issues in AbstractFacetRenderer

- Classes/Facet/SimpleFacetOptionsRenderer.php
> [TASK] Fix scrutinizer issues in SimpleFacetOptionsRenderer

- Classes/Domain/Search/Score/ScoreCalculationService.php
> [TASK] Fix scrutinizer issues in ScoreCalculationService

- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
> [TASK] Fix scrutinizer issues in StatisticsRepository

- Classes/Facet/FacetRendererFactory.php
> [TASK] Fix scrutinizer issues in FacetRendererFactory

- Classes/GarbageCollector.php
> [TASK] Fix scrutinizer issues in GarbageCollector

- Classes/IndexQueue/RecordMonitor.php
- Classes/System/TCA/TCAService.php
- Tests/Unit/System/TCA/TCAServiceTest.php
> [TASK] Fix scrutinizer issues in RecordMonitor

- Classes/Facet/HierarchicalFacetRenderer.php
> [TASK] Fix scrutinizer issues in HierarchicalFacetRenderer

- Classes/Plugin/Results/ErrorsCommand.php
> [TASK] Fix scrutinizer issues in ErrorsCommand

- Classes/Plugin/Results/FacetingCommand.php
> [TASK] Fix scrutinizer issues in FacetingCommand

- Classes/Plugin/Results/FrequentSearchesCommand.php
> [TASK] Fix scrutinizer issues in FrequentSearchesCommand

- Classes/Plugin/Results/LastSearchesCommand.php
> [TASK] Fix scrutinizer issues in LastSearchesCommand

- Classes/Plugin/Results/NoResultsCommand.php
> [TASK] Fix scrutinizer issues in NoResultsCommand

- Classes/Plugin/Results/ResultsCommand.php
> [TASK] Fix scrutinizer issues in ResultsCommand

- Classes/Plugin/Results/ResultsPerPageSwitchCommand.php
> [TASK] Fix scrutinizer issues in ResultsPerPageSwitchCommand

- Classes/Plugin/Results/SortingCommand.php
> [TASK] Fix scrutinizer issues in SortingCommand

- Classes/System/Cache/TwoLevelCache.php
> [TASK] Fix scrutinizer issues in TwoLevelCache

- Classes/ViewHelper/SortUrl.php
> [TASK] Fix scrutinizer issues in SortUrl

- Classes/Query/FilterEncoder/QueryGroup.php
> [TASK] Fix scrutinizer issues in QueryGroup

- Classes/SolrService.php
> [TASK] Fix scrutinizer issues in SolrService

- Classes/Util.php
> [BUG] Signature of getRootPageId should be static

- Classes/System/Configuration/TypoScriptConfiguration.php
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
> [TASK] Fix scrutinizer issues in TypoScriptConfiguration

- Classes/Backend/SolrModule/IndexQueueModuleController.php
> [TASK] Fix scrutinizer issues in IndexQueueModuleController

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
> [TASK] Fix scrutinizer issues in SearchResultSetService

- Classes/Facet/LinkBuilder.php
> [TASK] Fix unused variables LinkBuilder

- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
> [TASK] Fix scrutinizer issues IndexQueueWorkerTaskAdditionalFieldProvider

- Classes/Facet/UsedFacetRenderer.php
> [TASK] Fix scrutinizer issues in UsedFacetRenderer

- Classes/SolrService.php
> [TASK] Fix Apache_Solr_HttpTransportException issue

- Classes/Facet/DateRangeFacetRenderer.php
> [TASK] Fix scrutinizer issues in DateRangeFacetRenderer

- Classes/IndexQueue/Queue.php
Should fix #1012. @timohund please have a look at the deprecations
> [TASK] Fix scrutinizer issues in Queue

- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
> [TASK] Fix scrutinizer issues in ReIndexTaskAdditionalFieldProvider

- Classes/Typo3PageIndexer.php
> [TASK] Fix scrutinizer issues in Typo3PageIndexer

- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
> [TASK] Use method for instanceOfCheck

- Classes/Backend/SolrModule/AdministrationModuleInterface.php
- Classes/Controller/AdministrationController.php
> [TASK] Fix scrutinizer issues in AdministrationController

- Classes/Access/Rootline.php
- Classes/Backend/SolrModule/AbstractModuleController.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php
- Classes/Domain/Search/LastSearches/LastSearchesService.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/Item.php
- Classes/IndexQueue/Queue.php
- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/NoResultsCommand.php
- Classes/Query.php
- Classes/Query/FilterEncoder/Range.php
- Classes/Search.php
- Classes/Site.php
- Classes/SolrService.php
- Classes/SuggestQuery.php
- Classes/System/Configuration/ConfigurationPageResolver.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Classes/System/DateTime/FormatService.php
- Classes/System/TCA/TCAService.php
- Classes/Task/IndexQueueWorkerTask.php
- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
- Classes/Template.php
- Classes/ViewHelper/Crop.php
- Classes/ViewHelper/Split.php
Fixes: #1100 - in order to reduce number of Scrutinizer issues
> [TASK] Cleanup Scrutinizer issues spacing etc

- Classes/Backend/SolrModule/AbstractModuleController.php
- Classes/ContentObject/Content.php
- Classes/ContentObject/Multivalue.php
- Classes/ContentObject/Relation.php
- Classes/Facet/HierarchicalFacetHelper.php
- Classes/Facet/NumericRangeFacetRenderer.php
- Classes/Facet/QueryGroupFacetRenderer.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/FrontendHelper/AbstractFrontendHelper.php
- Classes/IndexQueue/FrontendHelper/AuthorizationService.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/Item.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/Plugin/PluginBase.php
- Classes/Plugin/Results/Results.php
- Classes/System/Configuration/ConfigurationManager.php
- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
> [TASK] Final scrutinizer issues

- Classes/Domain/Search/Repository/ApacheSolrDocumentRepository.php
> [BUGFIX] Error when select IndexInspector on page "0"

- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/Domain/Search/Score/ScoreCalculationServiceTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
- Tests/Unit/System/Solr/Parser/SchemaParserTest.php
- Tests/Unit/System/Solr/Parser/StopWordParserTest.php
- Tests/Unit/System/Solr/Parser/SynonymParserTest.php
- Tests/Unit/TemplateTest.php
- Tests/Unit/UnitTest.php
> [TASK] Renaming of getFixturePath and getFixtureContent

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Documentation/Configuration/Reference/ExtensionSettings.rst
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
- ext_conf_template.txt
> [FEATURE] Added feature flag useConfigurationTrackRecordsOutsideSiteroot

- Documentation/FAQ/Index.rst
Added Question: What is Core(Apache)
> [TASK] FAQ from Slack-Channel Questions for Feb. 2017

- Documentation/FAQ/Index.rst
Added: Where is chat channel for EXT:solr?
> [TASK] FAQ from Slack-Channel Questions for Oct. 2016

- Tests/Build/cibuild.sh
> [TASK] Make php-cs-fixer verbose - 3.1.x branch

- Build/Test/cibuild.sh
> [TASK] Make php-cs-fixer verbose

- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Tests/Integration/IndexQueue/Fixtures/update_page_use_configuration_monitor_tables.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
- ext_conf_template.txt
Added useConfigurationMonitorTables
Fixes: #1115
> [FEATURE] Added extension configuration for MonitorTables

- Classes/IndexQueue/PageIndexerRequest.php
- Documentation/FAQ/Index.rst
This PR:
* implements the usage of self signed ssl certificates for indexing
Fixes: #1134
> [TASK] Allow self signed certificates when using https

- Classes/Domain/Index/IndexService.php
- Classes/IndexQueue/Item.php
- Classes/IndexQueue/Queue.php
> [TASK] Move updateIndexedTime to Queue and rename

- Classes/ConnectionManager.php
- Configuration/TypoScript/Solr/constants.txt
- Configuration/TypoScript/Solr/setup.txt
- Tests/Unit/ConnectionManagerTest.php
This pr:
* Adds a constant for the username and password
* Adds a test if no authentication is done, when username is empty
Fixes: #1127
> [TASK] Add constant for username and password

- Classes/Domain/Search/Statistics/StatisticsRepository.php
> [BUG] Fix missing default values for limit and withoutHits

- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
> [BUG] Added default value for $taskInfo in initialize 

- Build/generate_documentation.sh
- Documentation/Appendix/DynamicFieldTypes.rst
- Documentation/Backend/BackendModule.rst
- Documentation/Backend/Index.rst
- Documentation/Configuration/Index.rst
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Documentation/Configuration/Reference/TxSolrJavaScriptFiles.rst
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Configuration/Reference/TxSolrViewHelpers.rst
- Documentation/FAQ/Index.rst
- Documentation/Index.rst
- Documentation/Solr/ConfigurationStructures.rst
- Documentation/Solr/Index.rst
all errors are gone, some warnings still present.
This closes #1153
> [TASK] Fix errors and warnings in RSTs @master

- Documentation/Releases/solr release 6.1.md
This pr:
* Adds the first state of the release notes for 6.1.0
Fixes: #1098
> [TASK] Add release notes for 6.1

- Classes/Domain/Site/SiteRepository.php
- Tests/Unit/Domain/Site/SiteRepositoryTest.php
This PR:
* Adds the unit tests for SiteRepository
* Fixes a small in getAllLanguages
Fixes: #1138
> [TASK] Add unit test for SiteRepository

- Tests/Integration/IndexQueue/Fixtures/can_get_last_index_time.xml
- Tests/Integration/IndexQueue/QueueTest.php
> [TASK] Added int test for getLastIndexTime

- Classes/Domain/Index/IndexService.php
If a batch of documents is processed by the index queue worker send an explicit commit command to the Solr servers for that site.
Fixes #1158
> [FEATURE] Force commit after indexing documents

- Classes/IndexQueue/Queue.php
- Tests/Integration/IndexQueue/Fixtures/can_get_last_indexed_item_id.xml
- Tests/Integration/IndexQueue/QueueTest.php
Use common getLastIndexedRow.
Fixes: #1147
> [TASK] Add test for getLastIndexedItemId 

- Tests/Integration/IndexQueue/Fixtures/can_mark_item_as_failed.xml
- Tests/Integration/IndexQueue/QueueTest.php
> [TASK] Added int. test for markItemAsFailed

- Tests/Integration/IndexQueue/Fixtures/can_update_index_time_by_item.xml
- Tests/Integration/IndexQueue/QueueTest.php
> [TASK] Added int-test for updateIndexTimeByItem

- Classes/SolrService.php
This PR:
* Streamlines the logging methods in the SolrService to use one method.
> [TASK] Streamline logging in SolrService

- Classes/IndexQueue/PageIndexerRequest.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Documentation/Configuration/Reference/ExtensionSettings.rst
- Documentation/Releases/solr release 6.1.md
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
- ext_conf_template.txt
> [FEATURE] Added allowSelfSignedCertificates

- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
> [TASK] Use array_flip getIsUseConfigurationMonitorTables

- Classes/ConnectionManager.php
- Configuration/TypoScript/Solr/constants.txt
- Configuration/TypoScript/Solr/setup.txt
- Tests/Unit/ConnectionManagerTest.php
This pr:
* Adds a constant for the username and password
* Adds a test if no authentication is done, when username is empty
Fixes: #1127
> [TASK] Add constant for username and password [6.0.x]

- Classes/System/Configuration/ConfigurationPageResolver.php
- Tests/Unit/Domain/Search/ResultSet/TestSearchResponseProcessor.php
- ext_localconf.php
> [TASK] Finalise ::class and array() cleanup

- Classes/IndexQueue/Indexer.php
- Tests/Integration/IndexQueue/Helpers/DummyAdditionalIndexQueueItemIndexer.php
- Tests/Integration/IndexQueue/Helpers/DummyIndexer.php
- Tests/Integration/IndexQueue/IndexerTest.php
> [!!!][TASK] Fix assignment by reference in Indexer plus test

- Classes/Plugin/CommandPluginBase.php
- Classes/Plugin/PluginBase.php
> [TASK] Remove by-reference for GeneralUtility

- ext_tables.sql
> [TASK] Removed white spaces

- Classes/FieldProcessor/CategoryUidToHierarchy.php
- Classes/System/Records/AbstractRepository.php
- Classes/System/Records/SystemCategory/SystemCategoryRepository.php
- Tests/Integration/FieldProcessor/CategoryUidToHierarchyTest.php
- Tests/Integration/FieldProcessor/Fixtures/sys_category.xml
- Tests/Integration/System/Records/SystemCategory/Fixtures/sys_category.xml
- Tests/Integration/System/Records/SystemCategory/SystemCategoryRepositoryTest.php
This pr:
* Extracts the access to the table sys_category to a class SystemCategoryRepository
* Adds tests
* Refactors the usage
Fixes: #1193
> [TASK] Extract access to sys_category into SystemCategoryRepository

- ext_tables.sql
> [TASK] Removed a second forgotten whitespace

- Classes/System/TCA/TCAService.php
> [BUGFIX] GarbageCollector fails to check endtime correctly

- Classes/ConnectionManager.php
- Resources/Private/Language/locallang.xlf
> [BUG] Fix Initialize Solr Connection again

- Documentation/Releases/solr release 6.1.md
Adds latest changes to to release notes.
> [TASK] Update Releasenotes

- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
This PR:
* Changes the build process to allow to run all tests with the latest testing framework changes in the master branch.
Fixes: #1224
> [TASK] Adapt changes due to testing framework

- Classes/IndexQueue/RecordMonitor.php
The original cause has been solved in TYPO3 8 and backportet to TYPO3 7.
Fixes: #1217
> [TASK] Remove method hasRecordBeenProcessed in RecordMonitor

- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
This PR:
* Updates the testing-framwork to 1.0.1
> [TASK] Update testing framework to 1.0.1

- ext_localconf.php
It should be possible to set the logging configuration in AdditionalConfiguration.php,
we should check if a configuration exists and only if not, apply the default configuration.
Fixes: #1235
> [BUGFIX] Allow to overwrite logging configuration

- .travis.yml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
This PR:
* Changes the tests to run against 8.7.0
Fixes: #1232
> [TASK] Test against 8.7.0

- Classes/Response/Processor/StatisticsWriter.php
Search without results and enabled statistices produces sql error
Fixes: #1243
> [BUGFIX] Search without results and enabled statistices produces sql error

- Documentation/GettingStarted/ConfigureExtension.rst
* ConfigureExtension confusion with static TS
Related: #1222
> [TASK] Documenation improvements ConfigureExtension

- Documentation/Backend/Scheduler.rst
- Documentation/Frontend/Languages.rst
- Documentation/GettingStarted/Solr.rst
- Documentation/Solr/ConfigurationStructures.rst
there are typo fixes for first half of doc.
> [TASK] Documenation improvements typos in 1/2 of Doc

- Documentation/Backend/Scheduler.rst
- Documentation/Configuration/Reference/TxSolr.rst
- Documentation/Configuration/Reference/TxSolrCssFiles.rst
- Documentation/Configuration/Reference/TxSolrIndex.rst
- Documentation/Frontend/Languages.rst
- Documentation/GettingStarted/Solr.rst
- Documentation/Solr/ConfigurationStructures.rst
removed reference for removed fields
> [TASK] Documenation improvements removed TS fields

- Documentation/FAQ/Index.rst
added AQ for available command.
> [TASK] FAQ from Slack Channel Oktober 2016: Commands

- Documentation/FAQ/Index.rst
added AQ for available FE plugins.
> [TASK] FAQ from Slack Channel Oktober 2016: FE plugins

- ext_tables.php
> [CLEANUP] Remove CType=search TCA override related to ext:compatibility6

- .travis.yml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Classes/BackendItem/ContextMenuActionJavascriptRegistration.php
- Classes/ConnectionManager.php
- Tests/Integration/IntegrationTest.php
- Tests/Unit/UnitTest.php
- composer.json
- ext_emconf.php
This pr:
* Drops 7.6 LTS compatibility
* Removes compatibility switches from the code
Fixes: #950
> [TASK] Drop 7.6 LTS compatibility

- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
> [TASK] Remove test for removed deprecated method

- Classes/System/Configuration/ConfigurationPageResolver.php
- Classes/System/Records/SystemTemplate/SystemTemplateRepository.php
- Tests/Integration/System/Records/SystemTemplate/Fixtures/sys_template.xml
- Tests/Integration/System/Records/SystemTemplate/SystemTemplateRepositoryTest.php
- Added an integration test
- Use it in ConfigurationPageResolver
- Use doctrine to execute queries
resolves #1202
> [TASK] Extract access to sys_template to SystemTemplateRepository

- Classes/ConnectionManager.php
- Classes/System/Records/SystemLanguage/SystemLanguageRepository.php
- Tests/Integration/System/Records/SystemLanguage/Fixtures/sys_language.xml
- Tests/Integration/System/Records/SystemLanguage/SystemLanguageRepositoryTest.php
added Integration Tests
removed usages from ConnectionManager
moved access to SystemLanguageRepository
Fixes: #1201
> [TASK] Extract access to sys_language to the SystemLanguageRepository

- Classes/Report/SolrConfigurationStatus.php
- Classes/System/Records/SystemDomain/SystemDomainRepository.php
- Tests/Integration/System/Records/SystemDomain/Fixtures/sys_domain.xml
- Tests/Integration/System/Records/SystemDomain/SystemDomainRepositoryTest.php
- Tests/Unit/Report/SolrConfigurationStatusTest.php
added SystemDomainRepository and extracted sql calls from SolrConfigurationStatus
fixed Unit SolrConfigurationStatusTest with mocks
Resolves: #1199
> [TASK] Extract sys_domain to SystemDomainRepository

- Classes/ConnectionManager.php
- Classes/System/Records/Pages/PagesRepository.php
- Tests/Integration/System/Records/Pages/Fixtures/pages.xml
- Tests/Integration/System/Records/Pages/PagesRepositoryTest.php
extracted the query to the PagesRepository
added Integration test case
Fixes: #1200
> [TASK] Extract access to pages to PagesRepository

- Dockerfile
> [FEATURE] Explicitly create data folder, Fixes #1278

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
> [BUGFIX] Ignore workspaces in RootPageResolver

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
> [BUGFIX] Ignore workspaces in RootPageResolver - dev-master

- Classes/Controller/Backend/Search/AbstractModuleController.php
By selecting a non root marked page in the page tree the backtrace was shown.
Fixes: #1315
> [BUGFIX] Selecting a page outside a siteroot do not throw exception

- Classes/Controller/Backend/Search/AbstractModuleController.php
- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
- Classes/Controller/Backend/Search/IndexAdministrationModuleController.php
- Classes/Controller/Backend/Search/IndexQueueModuleController.php
- Classes/Controller/Backend/Search/InfoModuleController.php
- Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
Added conditions and checks in action, which checking all dependencies,
needed for processing backend module request.
Fixes: #1316
> [BUGFIX] Show proper message in modules if nothing is configured

- Classes/Controller/Frontend/SearchController.php
- Configuration/FlexForms/Results.xml
- Configuration/TypoScript/Solr/setup.txt
- Tests/Integration/Controller/Frontend/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/Frontend/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Integration/Controller/Frontend/Fixtures/customTemplates/Search/MyResults.html
- Tests/Integration/Controller/Frontend/Fixtures/customTemplates/ViewHelpers/Frontend/Widget/ResultPaginate/Index.html
- Tests/Integration/Controller/Frontend/SearchControllerTest.php
- Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml
- Tests/Integration/Domain/Search/ResultSet/Fixtures/fe_user_page.xml
This pr:
* Adds support to overwrite the entry template by the typoscript path plugin.tx_solr.templateFiles.actionName = TemplateFile
* Beside that the flexform configuration for the Results plugin was added
* Testcase has been added
* Configuration of templates from old fixtures have been removed
Fixes: #1280
> [TASK] Allow to configure custom entry template in typoscript or flexform

- Documentation/FAQ/Index.rst
This pr:
* Adds an FAQ entry how to build a custom type without overwriting the build in type field.
Fixes: #1172
> [TASK] Add FAQ entry for custom type

- Documentation/Frontend/Languages.rst
> [TASK] Adding missing languages to the documentation

- Classes/Controller/Backend/PageModuleSummary.php
- Tests/Integration/Controller/Backend/Fixtures/fakeFlexform.xml
- Tests/Integration/Controller/Backend/PageModuleSummaryTest.php
This PR:
* Updates the fields to match the solr fluid flexform key
* Uses core code for parsing instead of own code
Fixes: #1333
> [BUG] Plugin Summary not showing configuration

- Classes/Controller/Frontend/SearchController.php
Before arithemtic operations are done with the page argument we should cast it to an integer.
Fixes: #1336
> [TASK] Make sure tx_solr[page] is an integer

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Tests/Integration/IndexQueue/Fixtures/update_record_outside_siteroot_from_other_siteroot.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
This PR:
* Fixes the bug (uses the recordPageId instead of the rootPageId to resolve the relevant rootPages)
* Adds an integration test
Fixes: #1347
> [BUGFIX] Tracking changes in record from other siteroot is not working as expected

- Classes/Domain/Search/ResultSet/Facets/AbstractFacet.php
- Classes/Domain/Search/ResultSet/Facets/FacetCollection.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetTest.php
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
This PR:
* Evaluates the configuration includeInAvailableFacets and includeInUsedFacets and allows to hide a facet with these settings
Fixes: #1324
> [TASK] Respect setting includeInAvailableFacets and includeInUsedFacets

- Classes/Controller/Backend/PageModuleSummary.php
- Tests/Integration/Controller/Backend/Fixtures/fakeFlexform.xml
- Tests/Integration/Controller/Backend/PageModuleSummaryTest.php
Adds the template to the summary.
> [BUGFIX] Wrong key for templateFile in PageModuleSummary

- Build/Test/cibuild.sh
The build should fail on any error.
> [TASK] Build not failing on failed unit test

- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
This pr:
* Fixes the broken test
Fixes: #1359
> [BUGFIX] RootPageResolverTests is failing

- Classes/Domain/Search/ResultSet/Facets/AbstractFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetParser.php
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
This PR:
* Add faceting.facets.[facetName].excludeValues to add an exclude list with options that should be removed.
* Adds Tests
Fixes: #504
> [TASK] Add excludeValues configuration to exclude values from option based facets

- Classes/ViewHelpers/Widget/Controller/ResultPaginateController.php
Returns the configured items per page. When nothing is configured 10 will be returned.
Fixes: #1366
> [BUGFIX] Possible devision by zero in ResultPaginateController

- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/FAQ/Index.rst
This PR:
Adds the configured "plugin.tx_solr.search.trustedFields" to the documentation.
Fixes: #1365
> [TASK] Add trustedFields to documentation

- Classes/ContentObject/Relation.php
- Classes/IndexQueue/PageIndexerRequest.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/Report/SolrConfigurationStatus.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Classes/System/Util/ArrayAccessor.php
Fixes several scrutinizer issues.
> [TASK] Fix scrutinizer issues

- Classes/Query.php
This PR:
* Reduces the amount of duplicate code in the Query class by introducing the methods setQueryParameterWhenStringOrUnsetWhenEmpty and appendToArrayQueryParameter
> [TASK] Reduce redundant code in Query

- Resources/Private/Layouts/Backend/WithPageTree.html
> [BUGFIX] Flashmassages not visible in new backend

- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Frontend/Concepts.rst
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Controller/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Integration/Domain/Search/ApacheSolrDocument/Fixtures/can_get_apacheSolrDocuments.xml
- Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml
> [TASK] Remove plugin.tx_solr.search.results.fieldProcessingInstructions from documentation

- Tests/Integration/IndexQueue/Fixtures/can_index_custom_translated_record_with_mm_relation_to_a_page.xml
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_bar_tca.php
- Tests/Integration/IndexQueue/Fixtures/fake_extension2_table.sql
- Tests/Integration/IndexQueue/IndexerTest.php
This integration test checks, if a relation of to a translated page is resolved and the value is used in solr.
> [TASK] Add testcase for translated relation to a page

- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Documentation/Frontend/Concepts.rst
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Controller/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Unit/System/Configuration/TypoScriptConfigurationTest.php
This pr:
* Removes facetLinkATagParams and removeFacetLinkText from the documentation
* Documents the removall in the conceptional changes in the frontend
Fixes: #1425
> [TASK] Remove facetLinkATagParams and removeFacetLinkText

- Classes/IndexQueue/Indexer.php
This pr:
* Extracts the added logic from #1409 into a method to reduce the complexity of getSolrConnectionsByItem
> [TASK] Extract method getTranslationOverlaysWithConfiguredSite

- Classes/Query/Modifier/Faceting.php
This pr:
* Reduces the complexity of addFacetQueryFilters by extraxting the methods getFilterTag and and getFilterParts
> [TASK] Reduce complexity of Faceting::addFacetQueryFilters

- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/locallang_mod.xlf
- Resources/Private/Language/locallang_mod_coreoptimize.xlf
- Resources/Private/Language/locallang_mod_indexadmin.xlf
- Resources/Private/Language/locallang_mod_indexqueue.xlf
- Resources/Private/Language/locallang_mod_info.xlf
- ext_tables.php
This pr:
* Adds metadata and a description for the new backend modules
Fixes: #1381
> [TASK] Add metadata and decription for new backend modules

- Documentation/Frontend/Concepts.rst
- Documentation/Releases/solr-release-7-0.rst
This pr:
* Adds the current state of the release notes for EXT:solr 7.0.0
Fixes: #1431
> [TASK] Add release notes for 7.0.0

- Classes/Domain/Search/Score/ScoreCalculationService.php
- Classes/ViewHelpers/Debug/QueryViewHelper.php
> [BUGFIX] Properly escape output of viewhelpers.

- Resources/Private/Templates/Backend/Search/IndexAdministrationModule/Index.html
- Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
> [TASK] Remove usage of deprecated f:be.pageRenderer attributes

- README.md
Badges with useful information help users to get an overview of an extension.
> [TASK] Add more badges to Readme.md

- Classes/Controller/Backend/Search/AbstractModuleController.php
- Classes/Controller/Backend/Search/IndexAdministrationModuleController.php
- Classes/Controller/Backend/Search/InfoModuleController.php
- Classes/Controller/Backend/Web/Info/ApacheSolrDocumentController.php
- Classes/System/Mvc/Backend/Service/ModuleDataStorageService.php
- Classes/System/Service/ConfigurationService.php
- Avoid using @inject annotation and use makeInstance() instead
- Avoid the objectmanager if not required
Resolves: #1465
> [TASK] Simplify class instantiation

- Classes/Controller/Backend/Search/AbstractModuleController.php
Was replaced with the wrong class (ConfigurationManager).
> [BUGFIX] Instanciate ConnectionManager

- Classes/ViewHelpers/Document/RelevanceViewHelper.php
- Classes/ViewHelpers/Uri/Result/AddSearchWordListViewHelper.php
This pr:
* Removes escapeOutput=false where possible
> [TASK] Remove escapeOutput=false where possible

- Classes/ViewHelpers/Document/HighlightResultViewHelper.php
- Tests/Unit/ViewHelpers/Document/HighlightingResultViewHelperTest.php
This pr:
* Modifies the HighlightingResultViewHelper to escape everything except the configured highlighting wrap.
> [TASK] Escape everything in HighlightingResultViewHelper except configured wrap

- Classes/Controller/Backend/AjaxController.php
This pr:
* Adjusts the message in the AjaxController
> [BUGFIX] Fix message in AjaxController

- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Search/SearchRequest.php
- Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
- Classes/FieldProcessor/Service.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/Util.php
Use utf8 safe mb* function instead of strtolower
> [TASK] Use mb_strtolower instead of strtolower

- Classes/Controller/Backend/Web/Info/IndexInspectorController.php
added Partials path to StandaloneView in "IndexInspectorController"
Fixes: #1495
> [BUGFIX] Partials for Index Inspector are not set

- Classes/Domain/Search/LastSearches/LastSearchesWriterProcessor.php
- Classes/Search/LastSearchesComponent.php
- composer.json
* Remove minimum-stability
* Remove optimize-autoloader
* Add extension-key
* Fixes wrong namespace in LastSearchesWriterProcessor
> [TASK] Optimize composer.json

- Documentation/FAQ/Index.rst
added versions hints in the question about solrfluid.
Fixes: #1485
> [TASK] Update the hint about EXT:Solrfluid in FAQ

- Classes/IndexQueue/PageIndexerRequestHandler.php
- ext_localconf.php
don't use '&' to instantiate singleton.
Fixes: #1367
> [TASK] Replace deprecated reference syntax for '&' token

- Documentation/FAQ/Index.rst
- Documentation/Releases/solr-release-7-0.rst
* Adds latest changes to release notes
* Adds FAQ entry how to customize templates
Fixes: #1500
> [TASK] Adds latest changes to release notes

- Classes/Controller/Backend/Search/AbstractModuleController.php
added Autoselect functionality to select the only one available site.
Fixes: #1411
> [TASK] Autoselect site when only one site available

- Classes/Migrations/Migration.php
- Classes/Migrations/RemoveSiteFromScheduler.php
- Classes/Task/AbstractSolrTask.php
- Classes/Task/IndexQueueWorkerTask.php
- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
- Classes/Task/ReIndexTask.php
- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
- Documentation/Releases/solr-release-7-0.rst
- Tests/Integration/Task/IndexQueueWorkerTaskTest.php
- Tests/Integration/Task/ReIndexTaskTest.php
- class.ext_update.php
Saving a scheduler task failed, since the scheduler serializes the Task object.
To avoid this for the Site, we exclude it from serialization and fetch it on the first usage.
Fixes: #1513
> [BUGFIX] Error when saving scheduler task

- Resources/Private/Language/locallang.xlf
- Resources/Private/Partials/Backend/ApacheSolr/FieldTypesForSingleCore.html
- Resources/Private/Partials/Backend/ApacheSolr/SingleDocument.html
- Resources/Private/Templates/Backend/Reports/AccessFilterPluginInstalledStatusIsOutDated.html
- Resources/Private/Templates/Backend/Reports/AccessFilterPluginInstalledStatusNotInstalled.html
- Resources/Private/Templates/Backend/Reports/SchemaStatus.html
- Resources/Private/Templates/Backend/Reports/SolrConfigStatus.html
- Resources/Private/Templates/Backend/Reports/SolrStatus.html
- Resources/Private/Templates/Backend/Reports/SolrVersionStatus.html
- Resources/Private/Templates/Backend/Search/CoreOptimizationModule/Index.html
- Resources/Private/Templates/Backend/Search/IndexAdministrationModule/Index.html
- Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
- Resources/Private/Templates/Backend/Search/IndexQueueModule/ShowError.html
- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
- Use infobox only for infos, not for intros
- improve table styling
- error page back button
> [TASK] Improve Backend UI

- Configuration/FlexForms/Form.xml
- Configuration/FlexForms/Results.xml
Use proper code for the flexforms
> [TASK] Fix flexform

- .scrutinizer.yml
- .travis.yml
- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Build/Test/publish_coverage.sh
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Plugin/FrequentSearches/Fixtures/can_render_frequentSearches_plugin.xml
- Tests/Integration/Plugin/Results/Fixtures/can_render_results_plugin.xml
- Tests/Integration/Plugin/Results/ResultsTest.php
- Tests/Integration/Plugin/Search/Fixtures/can_render_search_plugin.xml
- Tests/Unit/UnitTest.php
- composer.json
* Use  nimut/testing-framework
* Remove hhvm from scrutinizer
* Extract publishing of coverage to script
* Install build tools (php-cs-fixer, occular and typo3-repository-client) in bootstrap
> [TASK] Optimize test setup

- composer.json
* removed minimum-stability
* remove optimize-autoloader
* added extension-key
related Issue: #1497
Fixes: #1526
> [TASK] Backport: Optimize composer.json

- Classes/Backend/SiteSelectorField.php
- Classes/Site.php
related Issue: no issue created
comes from https://github.com/TYPO3-Solr/ext-solr/pull/1523
Fixes: #1532
> [TASK] Backport: Properly escape variables in SiteSelecotrField. PR #1523

- Documentation/Releases/solr release 6.1.3.md
Adds the release notes for 6.1.3
> [TASK] Add release notes for 6.1.3

- Classes/Domain/Index/Queue/RecordMonitor/Helper/MountPagesUpdater.php
- Classes/System/Records/Pages/PagesRepository.php
- Tests/Integration/System/Records/Pages/Fixtures/can_find_mout_pages_in_rootline.xml
- Tests/Integration/System/Records/Pages/PagesRepositoryTest.php
Use PagesRepository and doctrine instead of direct access to DB
Fixes: #1371
> [TASK] Migrate MountPagesUpdater::getDestinationMountPropertiesByRootLine

- Classes/Domain/Search/LastSearches/LastSearchesRepository.php
- Classes/Domain/Search/LastSearches/LastSearchesService.php
- Classes/Domain/Search/LastSearches/LastSearchesWriterProcessor.php
- Classes/ViewHelpers/Widget/Controller/LastSearchesController.php
- Tests/Integration/Domain/Search/LastSearches/Fixtures/can_find_and_add_last_searches.xml
- Tests/Integration/Domain/Search/LastSearches/LastSearchesRepositoryTest.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesRepositoryTest.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesServiceTest.php
* extracted `LastSearchesService::getLastSearchesFromDatabase` to `LastSearchesRepository::findAllKeywords`
incl. doctrine query syntax
Fixes: #1542
> [TASK] Extract LastSearchesService::getLastSearchesFromDatabase to Repo

- Classes/Domain/Search/Statistics/StatisticsRepository.php
* all queries rewritten to doctrine
Fixes: #1543
> [TASK] Rewrite queries from StatisticsRepository to doctrine

- Classes/Domain/Search/FrequentSearches/FrequentSearchesService.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Classes/ViewHelpers/Widget/Controller/FrequentlySearchedController.php
- Tests/Unit/Domain/Search/FrequentSearches/FrequentSearchesServiceTest.php
* extracted queries to Repository
* adapdet Test classes
* removed $GLOBALS['TYPO3_DB'] usages
Fixes: #1544
> [TASK] Extract queries from FrequentSearchesService and rewrite to doctrine

- Classes/Domain/Search/LastSearches/LastSearchesService.php
- Classes/Domain/Search/LastSearches/LastSearchesWriterProcessor.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/System/Session/FrontendUserSession.php
- Classes/ViewHelpers/Widget/Controller/LastSearchesController.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetTest.php
- Tests/Unit/System/Session/FrontendUserSessionTest.php
This PR:
* Extracts the access to the frontend user session into System/Session/FrontendUserSession
* Simplifies the SearchResultSetService and LastSearchesService
Fixes: #1405
> [TASK] Extract access to frontend user session

- Classes/Domain/Search/ResultSet/SearchResultBuilder.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Classes/Domain/Variants/VariantsProcessor.php
This pr:
* Extracts the creation of the variants into a SearchResultSetProcessor
* Reduces the complexity of SearchResultSetService
> [TASK] Extract VariantsProcessor from SearchResultSetService

- Classes/Domain/Search/ResultSet/Facets/DefaultFacetQueryBuilder.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetQueryBuilder.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetQueryBuilderTest.php
Unifies the generation of excludeTags for QueryFacets.
Fixes: #1576
> [TASK] Unifiy generation of excludeTags

- Configuration/TypoScript/Examples/Ajaxify/setup.txt
- Configuration/TypoScript/OpenSearch/setup.txt
> [BUGFIX] Update additionalHeaders configuration

- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Controller/Fixtures/can_render_error_message_when_solr_unavailable.xml
- Tests/Integration/Controller/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplate.xml
- Tests/Integration/Controller/Fixtures/can_render_search_customTemplateFromTs.xml
- Tests/Integration/Domain/Search/ApacheSolrDocument/Fixtures/can_get_apacheSolrDocuments.xml
- Tests/Integration/Domain/Search/ResultSet/Fixtures/can_get_searchResultSet.xml
- Tests/Integration/Domain/Search/ResultSet/Fixtures/fe_user_page.xml
- Tests/Integration/SearchTest.php
- Tests/Unit/Domain/Search/Score/ScoreCalculationServiceTest.php
> [FEATURE] update queryFields: add description, abstract, subtitle, navtitle and author for search

- Classes/IndexQueue/Indexer.php
- Classes/System/Records/Pages/PagesRepository.php
* moved query from Indexer::getTranslationOverlaysForPage() method to PagesRepository
* Indexer uses PagesRepository now
Fixes: #1595
> [TASK] move SQL query from Indexer to PagesRepository

- .scrutinizer.yml
.scrutinizer.yml was indented with four spaces
> [TASK] fix YAML indentation to two whitespaces

- Classes/Domain/Search/LastSearches/LastSearchesRepository.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Classes/System/Records/AbstractRepository.php
- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
* fix "top 5" and "search statistics" queries for correct calculations
* remove PHP calculations where possible and replace it with SQL
fixes: #1579, closes: #1573, fixes: #1572
> [BUGFIX] Fix sorting and counts in statistics module

- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Records/Pages/PagesRepository.php
* moved query from updateCanonicalPages()
to PagesRepository::findPageUidsWithContentsFromPid()
Fixes: #1598
> [TASK] extract queries from RecordMonitor

- Configuration/TypoScript/Solr/constants.txt
- Configuration/TypoScript/Solr/setup.txt
> [BUGFIX] Add default typoscript view configuration

- Tests/Integration/IndexQueue/FrontendHelper/Fixtures/can_index_page_with_relation_to_category.xml
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
Adds a testcase for SOLR_RELATION form pages to sys_category
> [TASK] Add testcase for SOLR_RELATION from pages to sys_category

- Classes/Controller/Backend/PageModuleSummary.php
- Classes/Controller/Backend/Search/IndexAdministrationModuleController.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/Domain/Search/Query/ParameterBuilder/Filters.php
- Classes/Domain/Search/ResultSet/Facets/AbstractFacet.php
- Classes/Domain/Search/ResultSet/Facets/AbstractFacetPackage.php
Fixes several scrutinizer spacing issues
> [TASK] Fix scrutinizer spacing issues

- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_mulitple_mm_relations.xml
- Tests/Integration/IndexQueue/Fixtures/can_index_custom_record_with_multiple_direct_relations.xml
- Tests/Integration/IndexQueue/IndexerTest.php
This pr:
* Adds testcases for multiple direct and mm related records for SOLR_RELATION
Related: #1608
> [TASK] Add integration tests for mulitple relations with mm and direct relation

- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/IndexQueue/Item.php
* moved `Item::updateHasIndexingPropertiesFlag()`
to QueueItemRepository::updateHasIndexingPropertiesFlagByItemUid()
* added to Item @todo: Loose coupling from Repos
Fixes: #1636
> [TASK] extract item related queries from IndexQueue\Item to QueueItemRepository

- Classes/Domain/Search/Query/ParameterBuilder/Grouping.php
- Tests/Unit/QueryTest.php
Change wrong assignment for group.field parameter
> [BUGFIX] Fix wrong parameter value

- ext_tables.sql
> Adds index indexing_priority_changed

- Classes/Domain/Search/Query/ParameterBuilder/Grouping.php
- Tests/Unit/QueryTest.php
* fixed wrong assignment for group.field parameter
* added missing unit tests for build() method
Fixes: #1647
> [BUGFIX] Wrong parameter value for grouping fields

- Documentation/Releases/solr-release-7-0-2.rst
This pr:
* Adds release notes for 7.0.2
> [TASK] Add release notes for 7.0.2

- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
- Resources/Private/Php/SolrPhpClient/Apache/Solr/Response.php
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
There are several issues reported by scrutinizer about the access of ->response of Apache_Solr_Response.
This pr fixes some of them.
> [TASK] Fix scrutinizer issues for access for response property from \Apache_Solr_Response

- Classes/Domain/Search/Query/ParameterBuilder/Faceting.php
- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
- Classes/Domain/Search/ResultSet/SearchResultSetService.php
Implements the basic changes that are needed to implement a facet package that support json faceting.
Fixes: #1661
> [TASK] Prepare json faceting

- Resources/Private/Language/cn.locallang.xlf
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/dk.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/it.locallang.xlf
- Resources/Private/Language/jp.locallang.xlf
- Resources/Private/Language/kr.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
- Resources/Private/Language/pl.locallang.xlf
- Resources/Private/Templates/Search/Results.html
The translations have to be updated accordingly and I did not know what I should write in `browse.vm`.
> [TASK] add singular form for results_found

- Classes/Domain/Search/ResultSet/Grouping/Group.php
- Classes/Domain/Search/ResultSet/Grouping/GroupItem.php
- Classes/Domain/Search/ResultSet/Grouping/GroupItemCollection.php
- Classes/Domain/Search/ResultSet/Result/SearchResult.php
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupCollectionTest.php
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupTest.php
This pr:
* Split the Group class into Group and GroupItem
Fixes: #1677
> [TASK] Split Group into Group and GroupItem

- Classes/Domain/Search/ResultSet/Grouping/Group.php
- Classes/Domain/Search/ResultSet/Grouping/GroupCollection.php
- Classes/Domain/Search/ResultSet/Grouping/GroupItem.php
- Classes/Domain/Search/ResultSet/Result/Parser/ResultParserRegistry.php
- Classes/Domain/Search/ResultSet/Result/SearchResultCollection.php
- Classes/Domain/Search/SearchRequest.php
- Classes/Domain/Search/Uri/SearchUriBuilder.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Classes/ViewHelpers/Uri/Paginate/GroupItemPageViewHelper.php
- Classes/ViewHelpers/Widget/Controller/AbstractPaginateWidgetController.php
- Classes/ViewHelpers/Widget/Controller/GroupItemPaginateController.php
- Classes/ViewHelpers/Widget/GroupItemPaginateViewHelper.php
- Resources/Private/Templates/ViewHelpers/Widget/GroupItemPaginate/Index.html
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupCollectionTest.php
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupItemTest.php
- Tests/Unit/Domain/Search/ResultSet/Grouping/GroupTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/Parser/ResultParserRegistryTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/SearchResultCollectionTest.php
- Tests/Unit/Domain/Search/ResultSet/Result/SearchResultTest.php
- Tests/Unit/Domain/Search/SearchRequestTest.php
This pr:
* Adds the api to paginate in groups
> [WIP][TASK] Prepare API to paginate in groups

- Documentation/Configuration/Reference/TxSolrSearch.rst
> [TASK] Fixing typo in documentation

- Tests/Integration/ConnectionManagerTest.php
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/System/Environment/CliEnvironmentTest.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
- Tests/Unit/Domain/Search/ResultSet/Sorting/SortingTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
- Tests/Unit/SolrServiceTest.php
This pr:
* Replaces all calls to setExpectedException with expectException since it was
deprecated.
Fixes: #1688
> [TASK] Fix the broken master build

- Tests/Integration/ConnectionManagerTest.php
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/System/Environment/CliEnvironmentTest.php
- Tests/Unit/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolverTest.php
- Tests/Unit/Domain/Search/ResultSet/Sorting/SortingTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
- Tests/Unit/SolrServiceTest.php
This pr:
* Replaces all calls to setExpectedException with expectException since it was
deprecated.
Fixes: #1688
> [TASK] Fix the broken build - release-7.5.x

- Documentation/Releases/solr-release-7-5-0.rst
> [TASK] Add release notes for 7.5.0

- Documentation/Releases/solr release 6.5.0.md
Add's the release notes for 6.5.0
> [TASK] Add release notes for 6.5.0

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetParser.php
Objects allways references and need no override
to modify
> [TASK] Remove unnedded object override

- Classes/AbstractDataHandlerListener.php
This variable was not used in the foreach
> [TASK] Remove unused variable

- Classes/Backend/IndexingConfigurationSelectorField.php
This has the advantage that the code becomes
more readable and psr2 compliant
> [CLEANUP] Use TYPO3 style html in php

- Classes/ViewHelpers/Widget/Controller/AbstractPaginateWidgetController.php
- Resources/Private/Templates/Search/Results.html
Backports the fix for wrong result count.
* https://github.com/TYPO3-Solr/ext-solr/pull/1682
> [BUGFIX] Fix wrong count in result list

- Configuration/TypoScript/Examples/IndexQueueNews/setup.txt
Search results for news in other languages than default linked to the default language
> [BUGFIX] Index news links with language parameter

- Documentation/Appendix/DynamicFieldTypes.rst
Added missing and marked deleted as deleted
Fixes: #1706
> [TASK] renew docs for Dynamic Field Types

- Classes/Domain/Search/ResultSet/Facets/RequirementsService.php
- Tests/Unit/Domain/Search/ResultSet/Facets/RequirementsServiceTest.php
Consider only _selected_ facet options to check if a
facet's requirements are met.
Fixes #1729
> [BUGFIX] Facet requirements: React to selected values only

- Resources/Private/Partials/Facets/OptionsSinglemode.html
> [TASK] Add partial for facets with singleOptionMode

- Configuration/FlexForms/Results.xml
Fixes deprecations for the results plugin:
Related issue:  #1750
> [TASK] Fix deprecations in flexforms

- Classes/Domain/Search/ApacheSolrDocument/Builder.php
- Classes/IndexQueue/Indexer.php
- Classes/Typo3PageIndexer.php
- Tests/Integration/IntegrationTest.php
- Tests/Unit/Domain/Search/ApacheSolrDocument/BuilderTest.php
This pr:
* Extracts the method Indexer::getBaseDocument to Builder::fromRecord
Fixes: #1753
> [TASK] Extract method Indexer::getBaseDocument to Builder::fromRecord

- Resources/Private/Partials/Search/Form.html
* Changes the type to submit, to submit the form also on click
Fixes: #1759
> [BUGFIX] Change type to "submit"

- Classes/Search/SearchComponentManager.php
> [FEATURE] Allow unregistration of search components

- Classes/Domain/Search/Query/ParameterBuilder/AbstractFieldList.php
- Classes/Domain/Search/Query/ParameterBuilder/BigramPhraseFields.php
- Classes/Domain/Search/Query/ParameterBuilder/PhraseFields.php
- Classes/Domain/Search/Query/ParameterBuilder/TrigramPhraseFields.php
- Classes/Query.php
- Classes/Search/RelevanceComponent.php
- Classes/System/Configuration/TypoScriptConfiguration.php
- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrSearch.rst
- Tests/Integration/Fixtures/phrase_search.xml
- Tests/Integration/Fixtures/phrase_search_bigram.xml
- Tests/Integration/Fixtures/phrase_search_trigram.xml
- Tests/Integration/SearchTest.php
- Tests/Unit/QueryTest.php
This enables Apache Solrs' phrase search feature.
> [FEATURE] Make Phrase Search configurable

- Configuration/FlexForms/Results.xml
- Resources/Private/Templates/Backend/Search/IndexAdministrationModule/Index.html
> [TASK] Improve index administration template

- Classes/Domain/Search/LastSearches/LastSearchesRepository.php
- Classes/ViewHelpers/Widget/Controller/FrequentlySearchedController.php
remove all usages of old DatabaseConnection class
> [TASK] clean up old DatabaseConnection usages

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyTool.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyUrlDecoder.php
- Classes/FieldProcessor/PathToHierarchy.php
- Tests/Integration/Controller/CategoryPathProvider.php
- Tests/Integration/Controller/Fixtures/can_render_path_facet_with_search_controller.xml
- Tests/Integration/Controller/Fixtures/can_render_search_controller.xml
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/System/Solr/Service/SolrWriteServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Hierarchy/HierarchyUrlDecoderTest.php
- Tests/Unit/FieldProcessor/PathToHierarchyTest.php
This pr:
* Fixes the bug
* Add's testcases
Fixes: #1783
> [BUGFIX] Text in hierarchical text facet should contain slashes

- Resources/Private/Install/install-solr.sh
now the old and the new version string schema are supported
Fixes: #1794
> [BUGFIX] java 9 support

- Classes/SuggestQuery.php
- Tests/Unit/SuggestQueryTest.php
This pr:
* Applies the filter in the SuggestQuery to build a proper filter query.
Fixes: #1758
> [BUGFIX] Filters are not applied in suggest

- .scrutinizer.yml
Increases the timeout to wait for coverage reports from scrutinizer
> [TASK] Increase scrutinizer timeout to wait for coverage

- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/IntegrationTest.php
remove object manager from main IntegrationTest class
Fixes: #1814
> [BUGFIX] Functional Testing no proper fail Message

- Classes/ContentObject/Relation.php
- Tests/Integration/ContentObject/Fixtures/solr_relation_can_fallback_to_pages_table_if_no_tca_for_local_field.xml
- Tests/Integration/ContentObject/Fixtures/solr_relation_can_get_related_items_using_original_uid_if_sys_lang_overlay_has_no_tca.xml
- Tests/Integration/ContentObject/RelationTest.php
- Tests/Integration/IndexQueue/FrontendHelper/PageIndexerTest.php
missing column settings in TCA for pages_language_overlay must be fetched from pages TCA
Fixes: #1812
> [BUGFIX] fallback to pages on SOLR_RELATION on missing TCA for pages_language_overlay

- composer.json
> [TASK] Update licence to GPL3 or later in composer.json file

- Documentation/Development/Indexing.rst
Add's a documentation, how to add documents to solr with custom php code
> [DOCS] Add example about custom indexing

- Classes/IndexQueue/PageIndexerRequest.php
- Tests/Integration/Task/IndexQueueWorkerTaskTest.php
- Tests/Unit/IndexQueue/PageIndexerRequestTest.php
This pr:
* Uses the shipped guzzle client from TYPO3 to perform page indexing requests
* Takes the code from #1830 + tests
Fixes: #1836 
Fixes: #141
> [TASK] Use Guzzle API for HTTP Crawling Requests

- Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
This pr:
* Makes the method StatisticsWriterProcessor::applyIpMask more robust by casting the arguments to the expected value before
Fixes: #1831
> [BUGFIX] Make StatisticsWriterProcessor::applyIpMask more robust

- Resources/Public/StyleSheets/Frontend/results.css
This pr:
* Readds the css for the highlighting
Fixes: #1842
> [BUGFIX] Readd css for highlighting

- Documentation/Releases/solr-release-7-5-1.rst
> [TASK] Add release notes for EXT:solr 7.5.1

- Documentation/Releases/solr-release-8-0.rst
This pr:
* Add's the release notes for EXT:solr 8.0.0
Fixes: #1839
> [TASK] Add release notes for EXT:solr 8.0.0

- Classes/Search/SortingComponent.php
- Tests/Unit/Search/SortingComponentTest.php
This pr:
* Fixes the bug
* Add's testcases for the SortingComponent to cover this case
Fixes: #1874
> [BUGFIX] sortBy is not applied

- Resources/Private/Layouts/Split.html
> [BUGFIX] Removes the unnecessary div from the Split layout

- Classes/Util.php
Build the typoscript configuration depending on initializeTsfe.
Resolves: #1858
> [BUGFIX] Add initializeTsfe to cacheId for configurationObjectCache

- Resources/Public/JavaScript/suggest_controller.js
> [BUGFIX] Show suggests box next to query input field

- Resources/Private/Templates/ViewHelpers/Widget/ResultPaginate/Index.html
- Tests/Integration/Controller/SearchControllerTest.php
> [BUGFIX] Duplicate id attribute solr-pagination

- Classes/Controller/AbstractBaseController.php
- Classes/System/Service/ConfigurationService.php
- Tests/Unit/System/Service/ConfigurationServiceTest.php
- Tests/Unit/System/UserFunctions/FlexFormUserFunctionsTest.php
> [TASK] TypoScriptService moved from Extbase to Core

- Resources/Public/JavaScript/suggest_controller.js
> [BUGFIX] Show suggests box next to query input field (#1888)

- Classes/Controller/Backend/Search/IndexQueueModuleController.php
- Classes/Domain/Index/Queue/QueueInitializationService.php
- Classes/IndexQueue/Queue.php
- Classes/Task/ReIndexTask.php
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Unit/Domain/Index/Queue/QueueInitializerServiceTest.php
This pr:
* Extracts the QueueInitializationService from the Queue class
* Addapt the backend module to use it
Fixes: #1914
> [TASK] Extract QueueInitializationService from Queue

- Classes/IndexQueue/Item.php
- Tests/Unit/IndexQueue/ItemTest.php
This pr:
* Add's the methods getState and getHasErrors to the item class
* Add's testcases
* Add's missing documentations and annotations to some methods
Fixes: #1920
> [TASK] Add method getState and getHasErrors to Item class

- Classes/Site.php
- Tests/Integration/Fixtures/can_get_translations_for_root_site.v9.xml
- Tests/Integration/Fixtures/can_get_translations_for_root_site.xml
- Tests/Integration/SiteTest.php
Add an api method for the site class to fetch root page translation
language uids.
> [FEATURE] Allow to fetch translation language uids from a root page

- Documentation/GettingStarted/Solr.rst
- Documentation/Solr/IndexMaintenance.rst
13ea6feeff4e3e7707ad9291d0286bd64edb7541
> Backported documentation fix

- Documentation/GettingStarted/Solr.rst
Removed duplicate dataDir parameter in curl REST API example
> Fixed REST API example

- Configuration/TypoScript/Examples/EverythingOn/setup.txt
- Configuration/TypoScript/Solr/setup.txt
Thir pr:
* Changes the default configuration and the configuration for "Everything on" to anonymize the ip adresses by default.
Fixes: #1958
> [TASK] Anonymize ip adresses by default

- .travis.yml
* adds allow_failures in .travis.yml
Fixes: #1972
> [TASK] Allow failures against CMS 9 on 8.X Branch

- Classes/IndexQueue/FrontendHelper/Manager.php
- Tests/Unit/IndexQueue/FrontendHelper/InvalidFakeHelper.php
- Tests/Unit/IndexQueue/FrontendHelper/ManagerTest.php
Thir pr:
* Add's unit tests for the FrontendHelper/Manager
* Simplifies the method resolveAction by converting nested if/else to guard clauses
> [TASK] Add tests for FrontendHelper/Manager and simplify

- Classes/IndexQueue/RecordMonitor.php
This pr:
* Removes the third argument from the call.
Fixes: #1980
> [BUGFIX] Invalid argument $configurationName passed to Queue::updateItem

- Resources/Private/Language/cn.locallang.xlf
- Resources/Private/Language/de.locallang.xlf
- Resources/Private/Language/dk.locallang.xlf
- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/it.locallang.xlf
- Resources/Private/Language/jp.locallang.xlf
- Resources/Private/Language/kr.locallang.xlf
- Resources/Private/Language/locallang.xlf
- Resources/Private/Language/nl.locallang.xlf
- Resources/Private/Language/pl.locallang.xlf
- Resources/Private/Templates/Search/Results.html
- Tests/Integration/Controller/SearchControllerTest.php
> [BUGFIX] Use correct label in auto corrected result hint

- ext_localconf.php
> Removes broken reference to old EID suggest script

- Resources/Public/JavaScript/suggest_controller.js
> Reinit the suggest_controller after ajax response

- Classes/Domain/Search/Score/ScoreCalculationService.php
- Tests/Unit/Domain/Search/Score/Fixtures/fakeSolrDebugData.txt
- Tests/Unit/Domain/Search/Score/ScoreCalculationServiceTest.php
This pr:
* Fixes the pattern that is invalid with Apache Solr 6.6
* Adapts the testcase
Fixes: #1805
> [BUGFIX] No score analysis shown

- Resources/Public/JavaScript/suggest_controller.js
This pr:
* Remove the condition
* Add's the configuration triggerSelectOnValidInput: false,
Fixes: #1997
> [BUGFIX] No suggestions are shown when only one suggestion available

- Classes/Controller/AbstractBaseController.php
- Classes/Controller/SearchController.php
- Documentation/Development/Index.rst
- Documentation/Development/Signals.rst
> [TASK] Dispatch signals in search controller actions

- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
This pr:
* Fixes the export for TYPO3 9 as well with the change that was introduced in #2016
> [BUGFIX] Change order of ->send() and ->shutdown()

- Documentation/Releases/Index.rst
- Documentation/Releases/solr-release-8-1.rst
This pr:
* Add's the first version of the release notes for 8.1.0
Fixes: #2029
> [TASK] Add release notes for 8.1.0

- .travis.yml
> [TASK] Use oracle jdk from travis again

- Documentation/Development/Indexing.rst
This pr:
* Updates the custom indexing code example to work with the latest changes for solarium
Fixes: #2072
> [TASK] Update documentation code example

- Classes/ContentObject/Relation.php
- Classes/System/TCA/TCAService.php
This pr:
* Uses the TCA Service in the relation handler to move some logic from the Relation object to the TCAService
Fixes: #1041
> [TASK] Check where TCA Service can be used in addition

- Classes/ContentObject/Relation.php
- Classes/System/Language/FrontendOverlayService.php
This pr:
* Extracts the class FrontendOverlayService from the Relation class
Fixes: #2077
> [WIP][TASK] Extract FrontendOverlayService from Relation

- Classes/Domain/Search/Query/AbstractQueryBuilder.php
- Classes/Domain/Search/Query/ParameterBuilder/BigramPhraseFields.php
- Classes/Domain/Search/Query/ParameterBuilder/Elevation.php
- Classes/Domain/Search/Query/ParameterBuilder/Faceting.php
- Classes/Domain/Search/Query/ParameterBuilder/FieldCollapsing.php
- Classes/Domain/Search/Query/ParameterBuilder/Grouping.php
- Classes/Domain/Search/Query/ParameterBuilder/Highlighting.php
- Classes/Domain/Search/Query/ParameterBuilder/ParameterBuilder.php
- Classes/Domain/Search/Query/ParameterBuilder/PhraseFields.php
- Classes/Domain/Search/Query/ParameterBuilder/QueryFields.php
- Classes/Domain/Search/Query/ParameterBuilder/ReturnFields.php
- Classes/Domain/Search/Query/ParameterBuilder/Slops.php
- Classes/Domain/Search/Query/ParameterBuilder/Sorting.php
- Classes/Domain/Search/Query/ParameterBuilder/Sortings.php
- Classes/Domain/Search/Query/ParameterBuilder/Spellchecking.php
- Classes/Domain/Search/Query/ParameterBuilder/TrigramPhraseFields.php
- Classes/Domain/Search/Query/QueryBuilder.php
This pr:
* Extracts all non TYPO3 related logic from the QueryBuilder into the AbstractQueryBuilder
Fixes: #2080
> [TASK] Extract AbstractQueryBuilder from QueryBuilder

- Resources/Private/Solr/configsets/ext_solr_9_0_0/conf/chinese/schema.xml
- Resources/Private/Solr/configsets/ext_solr_9_0_0/conf/japanese/schema.xml
- Resources/Private/Solr/configsets/ext_solr_9_0_0/conf/korean/schema.xml
This pr:
* Adds lowercasing for the CJK based languages
Fixes: #1789
> [BUGFIX] Lowercase chines, japanese and korean text

- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/PageIndexer.php
- Tests/Unit/IndexQueue/PageIndexerTest.php
- Tests/Unit/System/Hooks/Backend/Toolbar/ClearCacheActionsHookTest.php
This pr:
* Adds unit tests for the PageIndexer and the ClearCacheActionsHook to allow further recatoring
> [TASK] Add unit tests for PageIndexer and ClearCachActionsHook

- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
- Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php
- Classes/Domain/Index/Queue/GarbageRemover/RecordStrategy.php
- Classes/Domain/Index/Queue/GarbageRemover/StrategyFactory.php
- Classes/GarbageCollector.php
This pr:
* Extract's the garbage removall from the GarbageCollector
Fixes: #2114
> [TASK] Extract garbage removall from GarbageCollector

- .travis.yml
- Build/Test/bootstrap.sh
- composer.json
- ext_emconf.php
* Adapted composer.json and ext_emconf.php
* Run travis tests for TYPO3 8.7 and dev-master
* Use latest release of nimut/testing-framework
* Some issues are pending see: https://github.com/Nimut/testing-framework/issues/94
Resolves: #2120
> [TASK] Allow to install with TYPO3 9.4

- Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
> [BUGFIX] Wrong return value in StatisticsWriterProcessor

- Resources/Private/Php/ComposerLibraries/composer.json
- Resources/Private/Php/ComposerLibraries/composer.lock
- composer.json
This pr:
* Updates the dependency to the solarium api to version 4.2.0
> [TASK] Install solarium 4.2.0

- Documentation/Releases/solr-release-9-0.rst
This pr:
* Add's the release notes for the upcoming version 9.0.0 of EXT:solr
Fixes: #2162
> [TASK] Add release notes for 9 LTS

- Documentation/Releases/solr-release-9-0.rst
This pr:
* Fixes the spelling in the release notes
> [TASK] Fix spelling in release notes

- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/TSFEBootstrapResult.php
- Tests/Integration/TSFETestBootstrapper.php
This pr:
* Catches the exception during initialization of TSFE since this is not relevant here
* Behaviour was in addition manually verified in a setup with frontend user restricted pages
Fixes: #2178, #2177
> [TASK] Fix failing test with TYPO3 9 LTS

- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
Added siteHash to deleteRecordInAllSolrConnections
> [BUG] Added siteHash as parameter to deleteRecordInAllSolrConnections

- Classes/ViewHelpers/SearchFormViewHelper.php
This pr:
* Ensures that no cHash is added to the suggest url, since the query is added dynamically.
Fixes: #2227
> [BUGFIX] Make sure no cHash is added to suggestUrl

- Classes/System/Solr/Service/AbstractSolrService.php
- Resources/Private/Templates/Backend/Reports/AccessFilterPluginInstalledStatusIsOutDated.html
- Resources/Private/Templates/Backend/Reports/AccessFilterPluginInstalledStatusNotInstalled.html
- Resources/Private/Templates/Backend/Reports/SchemaStatus.html
- Resources/Private/Templates/Backend/Reports/SolrConfigStatus.html
- Resources/Private/Templates/Backend/Reports/SolrStatus.html
- Resources/Private/Templates/Backend/Reports/SolrVersionStatus.html
- Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
* Add's the deprecation logging for deprecated methods in AbstractSolrService
Error with E_USER_DEPRECATED should be triggered when one of the methods is called.
Fixes: #2239
> [TASK] Add deprecation logging in AbstractSolrService

- Documentation/Releases/solr-release-9-0.rst
* Updates the release notes for TYPO3 9 with the latest changes
Read it ;) 
Fixes: #2242
> [TASK] Update release notes with the latest changes

- Documentation/Frontend/Facets.rst
Fix a typo in doc
Read the fixed doc
> [BUGFIX] Fix typo in facet documentation

- Classes/Domain/Index/IndexService.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
* Restores the variable in case of an exception to have the previous value present again.
* Index an item that throws an exception during indexing
* Check that ```$_SERVER['HTTP_HOST']``` is restored in that case
Fixes:  #2272
> [BUGFIX] Indexing from backend with errors leads to wrong value in $_SERVER['HTTP_HOST']

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php
This patch adds the possibility to do do individual stuff,
like applying a special sorting, after parsing the facet options.
Resolves: #2354
> [TASK] Dispatch signals in OptionsFacetParser

- Classes/Controller/SearchController.php
> [FEATURE] Provide arguments in results view

- Resources/Public/JavaScript/suggest_controller.js
Adds missing semicolon
Test if auto suggest still works or if dev tools console throws JS errors
Fixes: #2315
> [BUGFIX] Fix missing semicolon #2315

- Classes/HtmlContentExtractor.php
- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
same as #2349 but for master
fixes #2348
> don't remove content that is visible to the user (master)

- Classes/HtmlContentExtractor.php
- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
same as #2349 but for 9.0.x
fixes #2348
> don't remove content that is visible to the user (9.0.x)

- ext_localconf.php
Adds the Fluid namespace "solr" globally
Fixes: #1551
> [TASK] Register the fluid namespace "solr" globally #1551

- Classes/ContentObject/Relation.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/System/Language/FrontendOverlayService.php
- Classes/Util.php
s. SOLR_RELATION Part on
https://github.com/TYPO3-Solr/ext-solr/pull/2316
without the "TypoScript Config" Workaround, which is needed anymore
Fixes: #2316
> [BUGFIX] Fix language handling during indexing #2316

- Configuration/SiteConfiguration/Overrides/sites.php
move the Solr Configuration in own Tab in Site-Configuration
Should see the Solr Configuration in own Tab in Site-Configuration
Fixes: #2382
> [TASK] mv solr configuration in own tab (#2382)

- Classes/System/Configuration/ExtensionConfiguration.php
- Documentation/Configuration/Reference/ExtensionSettings.rst
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
- ext_conf_template.txt
Implements switching between legacy and new site handling configurations.
TBD
TBD
Fixes: #2364
> [FEATURE] Add legacy site mode

- Build/Test/bootstrap.sh
- Classes/ConnectionManager.php
- Classes/ContextMenu/ItemProviders/InitializeConnectionProvider.php
- Classes/Domain/Site/Exception/InvalidSiteConfigurationCombinationException.php
- Classes/Domain/Site/SiteRepository.php
- Classes/Util.php
- Tests/Integration/Domain/Site/SiteRepositoryTest.php
- ext_emconf.php
- ext_localconf.php
- ext_tables.php
Throws an exception by booting legacy site conf, 
if the legacy site mode is disabled.
Fixes: #2364
> [FEATURE] Add legacy site mode : exception on invalid site conf combi

- Classes/Report/SolrConfigurationStatus.php
- Classes/Util.php
This merge request:
* Removes Util::legacySiteModeIsEnabled and only uses ExtensionConfiguration
Fixes: #2408
> [TASK] Remove static function Util::legacySiteModeIsEnabled

- Classes/Domain/Search/Query/QueryBuilder.php
Removes Classes/Middleware/PageIndexer.php
Fixes: #2403
> [BUGFIX] Remove empty Middleware/PageIndexer.php file

- Classes/IndexQueue/RecordMonitor.php
Closes: #2430
Move record to another page.
The Record may be added/removed/updated in index queue
> Task: Trigger indexqueue update when moving records

- Classes/Domain/Search/Query/SuggestQuery.php
See #1286 for details. Solr throws exceptions when auto suggest AJAX requests are executed.
```
2019-09-05 13:47:17.115 INFO  (qtp12209492-333) [   x:core_production_de] o.a.s.c.S.Request [core_production_de]  webapp=/solr path=/select params={q.alt=*:*&facet.field=spell&json.nl=map&fl=spell&start=0&fq=moduleUid_intS:(4)&fq=siteHash:"13af776af1bfb6ffb0e0a8346a797c69b1bf00d9"&fq={!typo3access}-2,0,3,6,8&rows=10&facet.limit=10&q=&omitHeader=true&facet.prefix=sozia&facet.mincount=1&facet=on&wt=json} hits=3316 status=500 QTime=3209
2019-09-05 13:47:17.115 ERROR (qtp12209492-333) [   x:core_production_de] o.a.s.s.HttpSolrCall null:org.apache.solr.common.SolrException: Exception during facet.field: spell
at org.apache.solr.request.SimpleFacets.lambda$getFacetFieldCounts$0(SimpleFacets.java:809) …
```
> [TASK] Fix Solr exceptions on autosuggest #1286

- Classes/IndexQueue/RecordMonitor.php
* Trigger indexqueue update when moving records (#2431)
* When records are moved the index queue is updated
Fixes: #2431
> Task: Trigger indexqueue update when moving records (#2431)

- Classes/System/Util/SiteUtility.php
- Tests/Unit/System/Util/SiteUtilityTest.php
[BUGFIX] solr_use_write_connection setting has no influence
Makes `solr_use_write_connection` setting from sites config.yaml functional.
The setting `solr_use_write_connection: false` has no influence on resolution of connection. 
Defining any of `*_write` setings in `config.yaml` leads to usage of write connections by EXT:Solr. 
By using "Sites module" it is currently not possible to disable write connection once those was defined.
So by enabling or disabling of write connection via Sites module 
the write connection must be disabled and the EXT:Solr's Info module MUST show the read connection and NOT write connection. 
Fixes: #2400
> [BUGFIX] solr_use_write_connection setting has no influence

- Classes/Controller/Backend/Search/AbstractModuleController.php
* If only one site is available, this site is selected automatically. By now, in that case the root page is used as selectedPage. This is implemented for usability reasons, to not force the user to selected something that is not required.
* In this case we should only select the root page when no other selected page was passed, since this overwrites the selected page from the page tree
Selected pages in the page tree should allways retrieve the solr records of that page in the info module. This should be independent from the fact if you have one or more sites.
Fixes: #2425
> [BUGFIX] Backend module only show's solr documents from root page

- ext_localconf.php
- ext_tables.php
Replaces $_EXTKEY with string 'solr'
Fixes: #2448
> [TASK] Replace $_EXTKEY with solr #2448

- Classes/Report/SolrConfigurationStatus.php
This PR fixes the incorrect output of status report section "Domain Records".
Fixes: #2375
> [BUGFIX] configuration status for domain records

- .travis.yml
* Add's mysql for travis as service again
Functional tests are executed on travis again.
> [BUGFIX] Re'add mysql for travis

- FUNDING.yml
Add's funding information for github
> [TASK] Add FUNDING.YML configuration

- composer.json
Fixes the composer validate issues to enabled autoupdate on packagist again.
> [TASK] Fix composer validate issues for packagist

- Classes/System/Url/UrlHelper.php
> Add colon after user if password given

- Classes/Typo3PageContentExtractor.php
fixes deprecation notice emited since php 7.4
There is no unit test covering this issue
Havent tried running integration test yet
works on my machine (tm)
Fixes: #2552
> [BUGFIX] implode deprecation for php 7.4 (#2552)

- Configuration/TypoScript/Solr/setup.txt
- Documentation/Configuration/Reference/TxSolrIndex.rst
* aligns docs for actual default configuration 
Fixes: #2582
>  [BUGFIX] Documentation of allowedPageTypes

- Documentation/Releases/Index.rst
- Documentation/Releases/solr-release-11-0.rst
- composer.json
- ext_emconf.php
* Add's the release notes for EXT:solr 11
* Adjusts the ext_emconf and composer.json as preparation for 11
Read the release notes.
Fixes: #2602
> [TASK] Add release notes for EXT:solr 11

- Tests/Integration/ContentObject/RelationTest.php
- Tests/Unit/Task/IndexQueueWorkerTaskTest.php
>  [BUGFIX] remove TSFE::sys_language_uid usages

- Docker/SolrServer/Dockerfile
* Fixes the failing build on docker hub for 11.0.1
* Check if build on docker hub is green
Fixes: #2612
> [TASK] Use fixed groups instead of env variables

- Classes/Report/SolrConfigurationStatus.php
> [BUGFIX:Backport] Prevent SiteNotFoundException in reports module

- Classes/Report/SolrConfigurationStatus.php
> [BUGFIX] Prevent SiteNotFoundException in reports module

- Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
> [BUGFIX] use num_found in static db table #2667

- Classes/AbstractDataHandlerListener.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/Domain/Site/Site.php
- Classes/IndexQueue/Queue.php
- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/Domain/Site/Fixtures/can_get_all_pages_from_sites.xml
- Tests/Integration/IndexQueue/Fixtures/can_get_item_count_by_site.xml
- Tests/Integration/IndexQueue/Fixtures/update_record_outside_siteroot_with_additionalWhereClause.xml
- Tests/Integration/IndexQueue/Initializer/Fixtures/mouted_shared_page_from_multiple_trees_can_be_queued.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
Record Monitoring for multiple Sites loads wrong TypoScript Configuration
so different additionalWhereClauses in TypoScript Configuration do not work
Resolves: #2683
s. #2683 
run the integration tests
Fixes: #2683
> [BUGFIX] Record Monitoring #2683

- Build/Test/cibuild_docker.sh
- Tests/Integration/UtilTest.php
> [TASK] Fix failing integration tests since TYPO3 10.4.8

- Classes/IndexQueue/FrontendHelper/AbstractFrontendHelper.php
- Classes/IndexQueue/FrontendHelper/Dispatcher.php
- Classes/IndexQueue/FrontendHelper/Manager.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/IndexQueue/PageIndexerRequestHandler.php
- Classes/Middleware/FrontendUserAuthenticator.php
- Classes/Middleware/PageIndexerFinisher.php
- Classes/Middleware/PageIndexerInitialization.php
- Configuration/RequestMiddlewares.php
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/Controller/SuggestControllerTest.php
> [BUGFIX] Restricted pages are not being indexed in Typo3 10 

- .travis.yml
- Build/Test/cibuild_docker.sh
- Tests/Integration/UtilTest.php
> [TASK:BACKPORT:11] Fix failing integration tests since TYPO3 10.4.8

- Configuration/TypoScript/Examples/Suggest/setup.txt
- Documentation/Frontend/Autosuggest.rst
Fix the path of "suggest"
Fixes: #2677
> Fix path of suggest in typoscript settings

- Classes/IndexQueue/Indexer.php
Record indexing fails in solr 10.x
See #2520 
Fixes: #2520
> Fix record indexing with solr 10.x

- Docker/SolrServer/Dockerfile
> [TASK] Use minor version of solr docker image

- .travis.yml
- Build/Test/bootstrap.sh
- CONTRIBUTING.md
- README.md
- Tests/Integration/Controller/Backend/Search/IndexAdministrationModuleControllerTest.php
- Tests/Integration/Domain/Index/Queue/QueueItemRepositoryTest.php
- Tests/Integration/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
> [TASK] Fix integration tests : 2020.10.29

- Documentation/FAQ/Index.rst
> [DOCS] Use *_PORT variable for setting the port

- Documentation/FAQ/Index.rst
> [DOCS:PORT:MASTER] Use *_PORT variable for setting the port

- Documentation/FAQ/Index.rst
> [DOCS:BACKPORT:10] Use *_PORT variable for setting the port

- Classes/AdditionalPageIndexer.php
- Classes/Domain/Search/ApacheSolrDocument/Builder.php
- Classes/Domain/Search/ApacheSolrDocument/Repository.php
- Classes/Domain/Search/ResultSet/Result/SearchResultBuilder.php
- Classes/IndexQueue/Indexer.php
- Classes/SubstitutePageIndexer.php
- Classes/System/Solr/Service/SolrWriteService.php
- Tests/Unit/Domain/Search/ApacheSolrDocument/BuilderTest.php
Replace string Apache_Solr_Document with in the location used class name.
Nothing to test, since this PR only effects doc comments
Fixes: #2611
> [TASK] Remove mentions on \Apache_Solr_Document

- ext_localconf.php
- ext_tables.php
To avoid leaking variables the code wraps with anonymous functions.
This is part of TYPO3 best practice.
Fixes: #1493
> [TASK] Wrap code with anonymus function

- Classes/GarbageCollector.php
- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_hidden_and_extendToSubpage_flags_removed.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
> [BUGFIX] Unset extendToSubPages & hidden doesn't requeue subpages

- Classes/GarbageCollector.php
- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_hidden_and_extendToSubpage_flags_removed.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
> [BUGFIX:BACKPORT:10] Unset extendToSubPages & hidden doesn't requeue subpages

- Classes/GarbageCollector.php
- Classes/IndexQueue/RecordMonitor.php
- Tests/Integration/IndexQueue/Fixtures/reindex_subpages_when_hidden_and_extendToSubpage_flags_removed.xml
- Tests/Integration/IndexQueue/RecordMonitorTest.php
> [BUGFIX:BACKPORT:11] Unset extendToSubPages & hidden doesn't requeue subpages

- Classes/Access/Rootline.php
- Classes/Domain/Site/Site.php
- Classes/GarbageCollector.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/RecordMonitor.php
- Classes/System/Records/Pages/PagesRepository.php
- Configuration/TCA/Overrides/pages.php
- Resources/Private/Language/de.locallang_csh_pages.xlf
- Resources/Private/Language/de.locallang_tca.xlf
- Resources/Private/Language/locallang_csh_pages.xlf
- Resources/Private/Language/locallang_tca.xlf
- ext_tables.php
- ext_tables.sql
* adds `no_search_sub_entries` field  to page and storage folder
* updates the sub entries of page/storage marked as `no_search_sub_entries`
Todo: Add documentation incl. screenshots
Resolves: #2432
> [FEATURE] Exclude sub entries of page/storage recursively

- Classes/Query/Modifier/Faceting.php
- Tests/Unit/Query/Modifier/FacetingTest.php
The test case might be a bit weak and this PR does not regard any *en*coding of those values, since we're not using them in our projects, so I can't attest to it. However, this fixes my issues, so I'm looking for feedback…
Replace: #1657
Fixes: #1656
> [BUGFIX] Use rawurldecode on facets to handle (replace #1657)

- Classes/Domain/Search/Uri/SearchUriBuilder.php
- Classes/Report/SiteHandlingStatus.php
- Classes/System/Url/UrlHelper.php
- Classes/ViewHelpers/SearchFormViewHelper.php
- Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
- Tests/Unit/System/Url/UrlHelperTest.php
Make UrlHelper PSR-7 conform and inherit it from `\TYPO3\CMS\Core\Http\Uri`.
Unit test and integration tests should not fail.
Fixes: #2776
Fixes: #2758
> [TASK] Refactor class UrlHelper

- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
- Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php
- Tests/Integration/Fixtures/queue_item_stays_when_overlay_set_to_hidden.xml
- Tests/Integration/GarbageCollectorTest.php
* should not remove IndexQueue Item
* should not remove Pages of other languages
Resolves: #2797
Fixes: #2797
> [BUGFIX] garbage collector on translations #2797

- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
- Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php
- Tests/Integration/Fixtures/queue_item_stays_when_overlay_set_to_hidden.xml
- Tests/Integration/GarbageCollectorTest.php
should not remove IndexQueue Item
should not remove Pages of other languages
Resolves: #2797
> [BUGFIX:BACKPORT:10] garbage collector on translations #2797

- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
- Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php
- Tests/Integration/Fixtures/queue_item_stays_when_overlay_set_to_hidden.xml
- Tests/Integration/GarbageCollectorTest.php
should not remove IndexQueue Item
should not remove Pages of other languages
Resolves: #2797
> [BUGFIX:BACKPORT:11] garbage collector on translations #2797

- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
> [BUGFIX:BACKPORT:10] Enable unicode when fetching pages

- Classes/Typo3PageContentExtractor.php
- Tests/Unit/Typo3PageContentExtractorTest.php
> [BUGFIX:BACKPORT:11] Enable unicode when fetching pages

- composer.json
For more info please see https://github.com/TYPO3-Solr/ext-solr/pull/2844#issuecomment-769683895
Resolves: #2844
> [TASK] Adjust composer TYPO3 version constrains for EXT:Solr 11.0.4+

- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
> [FEATURE:BACKPORT:10] Allow stdWrap on sorting label

- Classes/Domain/Search/ResultSet/ResultSetReconstitutionProcessor.php
> [FEATURE:BACKPORT:11] Allow stdWrap on sorting label

- Classes/Backend/IndexingConfigurationSelectorField.php
> [BUGFIX] Use Iconfactory to retrieve record icons

- Classes/Backend/IndexingConfigurationSelectorField.php
> [BUGFIX:BP:11] Use Iconfactory to retrieve record icons

- Classes/Backend/IndexingConfigurationSelectorField.php
> [BUGFIX:BP:10] Use Iconfactory to retrieve record icons

- .travis.yml
Fixes builds on travis in PRs against release-11.0.x branch
> [TASK] Don't test against TYPO3 v10.4.8 explicitly

- Build/Test/bootstrap.sh
Since changes of TYPO3 10.4.16 upgrade to doctrine/dbal v2.13.1 the builds are failing on TYPO3 10.4.16.
This temporary change is applied to be able to run tests within TYPO3 10.4.
Related: #2930
> [TASK] Fix test builds 2021.05.11

- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
> [BUGFIX:BP:11] Delete documents for valid connections only

- Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeUrlDecoder.php
- Classes/FieldProcessor/Service.php
- Classes/FieldProcessor/TimestampToIsoDate.php
- Classes/FieldProcessor/TimestampToUtcIsoDate.php
- Classes/System/DateTime/FormatService.php
> [TASK] Code documentation

- Documentation/Releases/solr-release-11-1.rst
Prepares the release notes for EXT:solr 11.1, just an initial version
that has to be completed.
Check the prepared release notes for 11.1
> [TASK] Prepare release notes for 11.1

- Resources/Private/Templates/Backend/Search/CoreOptimizationModule/Index.html
> Fix typo in CoreOptimizationModule/Index.html

- Classes/System/Util/SiteUtility.php
- Tests/Unit/System/Util/SiteUtilityTest.php
This adds first level cache to SiteUtility
* Use xdebug 
* Blackfire.io with the SDK
Fixes: #2908
> [TASK] Add language cache to SiteUtility

- Classes/System/Util/SiteUtility.php
- Tests/Unit/System/Util/SiteUtilityTest.php
Fixes: #2908
Back ported from: #2909
> [TASK:BP:11] Add language cache to SiteUtility

- Classes/System/Util/SiteUtility.php
- Tests/Unit/System/Util/SiteUtilityTest.php
Fixes: #2908
Back ported from: #2909
> [TASK:BP:10] Add language cache to SiteUtility

- Classes/FrontendEnvironment/Tsfe.php
- Tests/Integration/FrontendEnvironment/Fixtures/initialize_tsfe_with_no_default_page_and_page_error_handler_do_not_throw_an_error.xml
- Tests/Integration/FrontendEnvironment/TsfeTest.php
> [BUGFIX] set base uri to face frontend request #issue-2914

- Classes/System/Util/SiteUtility.php
Fixes: #2986
Backported from: #2987
> [TASK:BP:11] Make language cache work with multi site setups

- Classes/System/Util/SiteUtility.php
Fixes: #2986
Backported from: #2987
> [TASK:BP:10] Make language cache work with multi site setups

- Classes/ViewHelpers/Widget/Controller/ResultPaginateController.php
> Use correct information about results per page in pagination

- Classes/FrontendEnvironment/Tsfe.php
- Tests/Integration/FrontendEnvironment/Fixtures/initialize_tsfe_with_no_default_page_and_page_error_handler_do_not_throw_an_error.xml
- Tests/Integration/FrontendEnvironment/TsfeTest.php
Fixes: #2914
closes: #2915
Backported from: #2982
> [BUGFIX:BP:11] set base uri to face frontend request

- Classes/Search/StatisticsComponent.php
- Documentation/FAQ/Index.rst
- Tests/Unit/Search/StatisticsComponentTest.php
> [FEATURE] Register a custom StatisticWriterProcessor

- Classes/Middleware/SolrRoutingMiddleware.php
> [BUG] Correct error message when path can not be resolved

- Resources/Private/Templates/Search/SolrNotAvailable.html
> Release 7.0.x

- Resources/Private/Templates/Search/SolrNotAvailable.html
> Release 7.5.x

- Resources/Private/Templates/Search/SolrNotAvailable.html
> Release 8.1.x

- Resources/Private/Templates/Search/SolrNotAvailable.html
> Release 9.0.x

- Resources/Private/Templates/Search/SolrNotAvailable.html
> Release 10.0.x

- Classes/System/Cache/TwoLevelCache.php
- Tests/Unit/System/Cache/TwoLevelCacheTest.php
Ensures that the cache id used in the TwoLevelCache is compatible with the  FrontendInterface::PATTERN_ENTRYIDENTIFIER.
Run the integrations test to be sure the TwoLevelCache still works like expected
Resolves: #3031
> [TASK] Ensure valid cache ids

- Classes/System/Cache/TwoLevelCache.php
- Tests/Unit/System/Cache/TwoLevelCacheTest.php
Backport for EXT:solr 11.1
Ensures that the cache id used in the TwoLevelCache is compatible with the FrontendInterface::PATTERN_ENTRYIDENTIFIER.
Run the integration tests to be sure the TwoLevelCache still works like expected
Resolves: #3031
> [TASK:BP:11-1] Ensure valid cache ids

- Resources/Private/Templates/Search/SolrNotAvailable.html
> [BUGFIX] Update SolrNotAvailable.html

- Resources/Private/Templates/Search/SolrNotAvailable.html
> [BUGFIX:BP-11.0.x] Update SolrNotAvailable.html

- Resources/Private/Templates/Search/SolrNotAvailable.html
> [BUGFIX:BP-11.1.x] Update SolrNotAvailable.html

- Classes/IndexQueue/PageIndexerDocumentsModifier.php
> [TASK] Int TypeCast for PageIndexerDocumentsModifier interface

- ext_tables.sql
> [TASK] Limit table key column length

- Documentation/GettingStarted/Solr.rst
- Resources/Private/Install/install-solr.sh
The installation script is fixed and marked as not recommended variant of setting up Apache Solr server.
Fixes: #3094
> [TASK] Replace mirrors for Apache Solr binaries on install-solr.sh

- Resources/Private/Language/cs.locallang.xlf
Backport of #3133
Relates: #3132
> [TASK] Add Czech translation (Backport 11.5.x)

- Resources/Private/Language/cs.locallang.xlf
Backport of #3133
Relates: #3132
> [TASK] Add Czech translation (Backport 11.1.x)

- Classes/Pagination/ResultsPagination.php
Fixes the exception in the page browser
Just go to the page with search results.
Fixes: #3221
> [BUGFUX] Fix #3221: exception in page browser

- Classes/GarbageCollectorPostProcessor.php
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/Controller/SuggestControllerTest.php
- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IndexQueue/QueueTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
There are changes required or lighted on EXT:solrfal.
> [TASK] TYPO3 11 LTS compatibility :: part 9 :: Follow-ups by EXT:solrfal

- Classes/IndexQueue/Indexer.php
> [BUGFIX] change detection of free mode records

- .gitignore
- Classes/Controller/Backend/Search/AbstractModuleController.php
- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
- Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRange.php
- Classes/Domain/Search/ResultSet/Facets/RangeBased/NumericRange/NumericRangeFacetQueryBuilder.php
- Classes/Domain/Search/Suggest/SuggestService.php
- Classes/EventListener/PageIndexer/FrontendGroupsModifier.php
- Classes/Middleware/SolrRoutingMiddleware.php
- Classes/Routing/RoutingService.php
- Classes/System/Configuration/ExtensionConfiguration.php
- Classes/System/Mvc/Backend/Service/ModuleDataStorageService.php
- Classes/System/Solr/ResponseAdapter.php
- Classes/System/UserFunctions/FlexFormUserFunctions.php
- Classes/ViewHelpers/Debug/DocumentScoreAnalyzerViewHelper.php
- Classes/ViewHelpers/Debug/QueryViewHelper.php
Follow-Up for:
* https://github.com/TYPO3/typo3/commit/0fb53e0
* https://github.com/TYPO3/coding-standards/pull/31
> [BUGFIX] Avoid yoda-style conditions in PHP

- .github/workflows/ci.yml
- Classes/IndexQueue/AbstractIndexer.php
- Classes/Pagination/ResultsPagination.php
- Classes/Report/SiteHandlingStatus.php
- Classes/System/Util/ArrayAccessor.php
- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/SearchTest.php
Fixes: CI TYPO3 coding standards issues
> [TASK] Sync with new TYPO3 coding standards

- Classes/GarbageCollector.php
What this pr does
Replaces explode with GeneralUtility::intExplode
Fixes: #3249
Ports: #3253
> [BUGFIX:main] Update GarbageCollector.php

- Classes/GarbageCollector.php
What this pr does
Replaces explode with GeneralUtility::intExplode
Fixes: #3249
Ports: #3253
> [BUGFIX:11.2] Update GarbageCollector.php

- Classes/System/Logging/DebugWriter.php
If debug logging is activated the DebugWriter
does append debug messages to the output. This
fails when running PageIndexerRequest as it
does return a json that must not be appended
with debug message output.
1. Activate debug logging by setting TypoScript `plugin.tx_solr.logging.debugOutput = 1`
2. Run a page indexer and validate that it does index successfully
Fixes: #3030
> Silence DebugWriter for PageIndexerRequest

- Classes/ViewHelpers/AbstractSolrFrontendViewHelper.php
- Classes/ViewHelpers/Uri/Search/StartNewSearchViewHelper.php
Fixes the frequent searches component.
Fixes: #3166
Todos:
> [BUGFIX:11.5] Frequent Searches plugin does not work

- Configuration/SiteConfiguration/Overrides/sites.php
- increase size for host field
- change arrangement of columns to 2x2 instead of a single row
- clear cache
- check arrangement in sites modules config solr tab
Fixes: #3295
> [TASK] Adapt column arrangement within sites config

- Classes/FieldProcessor/Service.php
- Documentation/Frontend/Facets.rst
- Tests/Unit/FieldProcessor/ServiceTest.php
- Tests/Unit/FieldProcessor/TestFieldProcessor.php
Relates: #1811
Be able to register custom field processors.
Execute the test `\ApacheSolrForTypo3\Solr\Tests\Unit\FieldProcessor\ServiceTest::customFieldProcessorTurnsFooIntoBar`
Fixes: #1811
> [FEATURE] Add custom field processors

- Classes/IndexQueue/RecordMonitor.php
- Tests/Unit/IndexQueue/RecordMonitorTest.php
- ext_localconf.php
> [BUGFIX:BP:11.2] Respect indexing configuration for new and updated subpages

- Classes/FrontendEnvironment/Tsfe.php
> [BUGFIX] fix infinite loop in Tsfe::getPidToUseForTsfeInitialization()

- ext_localconf.php
Follow up for https://github.com/TYPO3-Solr/ext-solr/commit/ad5c03932
> [BUGFIX] Do not include removed strptime()

- Classes/Domain/Search/Statistics/StatisticsWriterProcessor.php
- Documentation/Configuration/Reference/TxSolrStatistics.rst
> [TASK] Use TYPO3 IpAnonymizationUtility

- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Classes/ViewHelpers/TranslateViewHelper.php
- Tests/Integration/GarbageCollectorTest.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/Task/EventQueueWorkerTaskTest.php
- Tests/Integration/Task/IndexQueueWorkerTaskTest.php
- Tests/Integration/Task/ReIndexTaskTest.php
- Tests/Unit/UnitTest.php
- composer.json
Checks whether GitHub-Actions runs on pull-requests against TYPO3 12 compatibility branch.
Relates: #3382, #3376
> [TASK:T12] Fix GitHub - Actions :: basics

- Documentation/Settings.cfg
- ext_emconf.php
#standwithukraine #nowar
This is a maintenance release for TYPO3 10.4, containing:
- [BUGFIX] Prepend wrong fe language on empty cache (#3375)
- [TASK] Use TYPO3 IpAnonymizationUtility (#3262)
- [BUGFIX:BP:11.2] Shortcircuit work in SolrRoutingMiddleware (#3202)
- [TASK] Fix scrutinizer on release-11.2.x
- [BUGFIX:BP:11.2] Do not handle page updates on new page with uid 0 (#3338)
- [TASK] Remove not used strptime() adaption for windows.
- [BUGFIX] Respect indexing configuration for new and updated subpages (#3276)
- [BUGFIX] Ensure keywords string does not exceed database field length (#3321)
- [TASK:BP:11.2] Adapt column arrangement within sites config (#3295)
- [DOCS:BP:11.2] add missing doc for ..pageIndexed
- [BUGFIX] Fix PSR-4 Namespaces and Paths (#3285)
- [BUGFIX] Silence …
> 11.2.1 - Maintenance Release

- Classes/IndexQueue/FrontendHelper/PageIndexer.php
Fixes: #3403
See issue for more
> [BUGFIX] Proper check for config.index_enable

- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
- Configuration/Backend/Modules.php
- Configuration/Icons.php
- Configuration/Services.yaml
- ext_tables.php
Migrate the backend modules for TYPO3 12
Relates: #3376
> [TASK:T12] Migrate backend module registration

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
Fixes a PHP warning 
Fixes: #3410
---
Todo:
> [BUGFIX] Casting after check

- Tests/Unit/System/Url/UrlHelperTest.php
Depends on https://forge.typo3.org/issues/94872
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/70547
Fixes: #2756
> [TASK] Test PSR-7 UriInterface

- .github/workflows/ci.yml
- Build/Test/cibuild_docker.sh
>  [TASK] Docker version check on docker image build

- Classes/Controller/SearchController.php
- Classes/Controller/SuggestController.php
If SearchService is not defined, we are forwarding to action solrNotAvailable
Fixes: #3426
Ports: #3485
> [BUGFIX:P:11.5] Exception on search plugin if no Solr connection is configured

- Classes/Domain/Index/Queue/RecordMonitor/Helper/RootPageResolver.php
Verifies variables before access them.
-
Fixes: #3535
> [TASK:BP:11] Verify the record before accessing the pid

- Build/Test/cibuild.sh
- Classes/ContentObject/Relation.php
- Classes/Domain/Search/ApacheSolrDocument/Repository.php
- Classes/Routing/RoutingService.php
- Classes/System/Language/FrontendOverlayService.php
- Classes/System/TCA/TCAService.php
- Configuration/Services.yaml
- Tests/Integration/ContentObject/RelationTest.php
- Tests/Integration/Domain/Index/IndexServiceTest.php
- Tests/Integration/Domain/Search/ApacheSolrDocument/ApacheSolrDocumentRepositoryTest.php
- Tests/Integration/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/TSFETestBootstrapper.php
- composer.json
This pull request contains following sub tasks/commits as well:
* [TASK:T12] Fix Ingration tests :  ResultSetReconstitutionProcessorTest and ApacheSolrDocumentRepositoryTest
* [TASK:T12] Fix Integration\IndexServiceTest
> [TASK:T12] Migrate content object SOLR_RELATION to TYPO3 12 API

- Classes/Eid/ApiEid.php
Fixes PHP warning about not available array keys.
> [BUGFIX] Fix PHP warnings in ApiEid

- Configuration/SiteConfiguration/Overrides/sites.php
Fix #3563 by using the new checkboxToggle configuration.
Go to the Site Module and edit any config.
Fixes: #3563
> [BUGFIX]: Migrate checkboxToggle

- Classes/ContentObject/Relation.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeUrlDecoder.php
- Classes/Domain/Search/ResultSet/Sorting/SortingHelper.php
- Classes/Domain/Search/Score/ScoreCalculationService.php
- Classes/IndexQueue/AbstractIndexer.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/PageIndexerRequest.php
Since PHP 7.1 there is no need to use
list() calls anymore. Replace list() with [...]
Relates: #3376
> [TASK] Replace list() calls

- Classes/ContentObject/Relation.php
- Classes/Domain/Search/ResultSet/Facets/OptionBased/QueryGroup/QueryGroupFacetParser.php
- Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeUrlDecoder.php
- Classes/Domain/Search/ResultSet/Sorting/SortingHelper.php
- Classes/Domain/Search/Score/ScoreCalculationService.php
- Classes/IndexQueue/AbstractIndexer.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/PageIndexerRequest.php
- Configuration/TCA/Overrides/sys_template.php
- Configuration/TCA/Overrides/tt_content.php
- ext_localconf.php
Streamline die() calls in
* ext_localconf.php
* sys_template.php
* tt_content.php
Relates: #3376
> [TASK] Streamline die calls

- Classes/IndexQueue/Queue.php
> [BUGFIX:BP:11.5] Avoid getSolrConfiguration() on null

- Classes/IndexQueue/FrontendHelper/PageIndexer.php
Fix usage of null coalescing operator
See detailed information in related issue
Fixes: #3607
> Fix usage of null coalescing operator

- Tests/Integration/Controller/Fixtures/customTemplates/ViewHelpers/Widget/ResultPaginate/Index.html
Replace removed s:translate VH with fluids f:translate
> Use f:translate instead of s:translate in Index.html

- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Build/Test/cibuild.sh
- composer.json
This change adds more information to the phpunit
xml files so the calls to phpunit can be simplified.
The PR just needs to have CI green.
> [TASK] Simplify phpunit invocations

- Classes/ViewHelpers/Backend/Security/IfHasAccessToModuleViewHelper.php
- Resources/Private/Templates/Backend/Search/InfoModule/Index.html
Enable requeue button in solr module `Index Queue`.
> Enable button to requeue document

- Classes/Controller/AbstractBaseController.php
- Classes/Domain/Index/IndexService.php
- Classes/Domain/Index/PageIndexer/PageUriBuilder.php
- Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php
- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/Domain/Index/Queue/UpdateHandler/DataUpdateHandler.php
- Classes/Domain/Search/Query/QueryBuilder.php
- Classes/EventListener/PageIndexer/FrontendGroupsModifier.php
- Classes/IndexQueue/FrontendHelper/PageIndexer.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Classes/IndexQueue/Indexer.php
- Classes/IndexQueue/Initializer/AbstractInitializer.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/IndexQueue/PageIndexer.php
- Classes/IndexQueue/PageIndexerRequest.php
- Classes/IndexQueue/PageIndexerRequestHandler.php
- Classes/Middleware/PageIndexerInitialization.php
- Classes/Search.php
- Classes/System/Logging/DebugWriter.php
- Classes/System/Logging/SolrLogManager.php
- Classes/System/Solr/Service/AbstractSolrService.php
- Classes/System/Solr/Service/SolrWriteService.php
- Classes/Task/AbstractSolrTask.php
- Classes/Task/EventQueueWorkerTask.php
- Classes/Typo3PageContentExtractor.php
- Tests/Integration/IndexQueue/RecordMonitorTest.php
- Tests/Unit/Domain/Index/Queue/GarbageRemover/AbstractStrategyTest.php
- Tests/Unit/System/Logging/DebugWriterTest.php
- Tests/Unit/Task/EventQueueWorkerTaskTest.php
Ideally, we reduce any hard dependencies on SolrLogManager and add this one as a replacement via DI for the regular SolrLogManager.
Fixes: #3679
> [TASK] Use PSR3-LoggerTrait for SolrLogManager

- Tests/Unit/ViewHelpers/Backend/IsStringViewHelperTest.php
> [TASK] Fix unit tests for 2023.06.07

- Classes/Task/IndexQueueWorkerTaskAdditionalFieldProvider.php
- Configuration/Services.yaml
- ext_localconf.php
> [TASK:T12] DI for IndexQueueWorkerTaskAdditionalFieldProvider::$siteRepository

- Classes/System/Solr/Service/AbstractSolrService.php
> [BUGFIX] Correct return type of AbstractSolrService->getClient()

- .github/workflows/ci.yml
- Build/Test/bootstrap.sh
- Build/Test/cibuild.sh
- Build/Test/phpstan.neon
- Classes/Domain/Search/ResultSet/Result/Parser/GroupedResultParser.php
- Classes/Search/GroupingComponent.php
- Documentation/Development/Indexing.rst
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- composer.json
This PR contains all adaptions required for EXT:solr* addons by working on TYPO3 12 compatibility.
> [TASK:T12] EXT:solr* addons adaptions

- Classes/Event/IndexQueue/AfterIndexQueueItemHasBeenMarkedForReindexingEvent.php
- Classes/GarbageCollectorPostProcessor.php
- Classes/IndexQueue/Queue.php
- Classes/System/Solr/SolrConnection.php
- Classes/System/Util/SiteUtility.php
- Tests/Integration/Controller/SearchControllerTest.php
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/Domain/Search/StatisticsRepository/StatisticsRepositoryTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Integration/System/Configuration/TypoScriptConfigurationTest.php
- Tests/Integration/TestGarbageCollectorPostProcessor.php
- Tests/Unit/Domain/Index/IndexServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Unit/Domain/Site/SiteRepositoryTest.php
- Tests/Unit/System/Configuration/ExtensionConfigurationTest.php
This PR contains necessary changes, which are required by EXT:solr* addons.
> [TASK] Sync with EXT:solr addons

- Classes/Task/EventQueueWorkerTaskAdditionalFieldProvider.php
s. #3767
s. #3767
Fixes: #3767
> [BUGFIX] prevent Exception when create Event Queue Worker Task

- ext_tables.sql
Adds 2 further index queue indices to reduce run-time.
Resolves: #3772
> [FEATURE] Add index queue indices

- ext_tables.sql
Adds 2 further index queue indices to reduce run-time.
Ports: #3790 
Resolves: #3772
>  [FEATURE:BP:11.5] Add index queue indices

- Classes/Event/Indexing/BeforeDocumentsAreIndexedEvent.php
To be in sync with old implementations it is helpful to e.g. remove the documents completly or just modify it how I like it
> [BUGFIX] Allow setting documents

- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
> [TASK:BP:11.5] Remove duplicate withHeader()

- Classes/FrontendEnvironment/Tsfe.php
> [BUGFIX] Fix missing frontend.typoscript request attribute

- Classes/FrontendEnvironment/Tsfe.php
Fixes: #3751
Ports: #3761 by @tillhoerner
> [BUGFIX:BP:11.5] Fix missing frontend.typoscript request attribute while indexing

- Classes/FieldProcessor/Service.php
Fix a possible notice
Fixes: #3683
> [BUGFIX] Fix possible notice

- Classes/Domain/Index/Queue/UpdateHandler/GarbageHandler.php
- Classes/IndexQueue/FrontendHelper/UserGroupDetector.php
- Configuration/TypoScript/Examples/IndexQueueNews/setup.typoscript
- Documentation/FAQ/Index.rst
- Tests/Integration/Report/SolrVersionStatusTest.php
Update FAQ and TypoScript example for news
Just documentation
Fixes: #3615
---
Maintaners comments:
Port into:
> [DOC] Generate URLs to restricted pages: update documentation and example for news

- Classes/ContentObject/Relation.php
Prevent indexing error on missing 'foreignLabelField' of SOLR_RELATION
Fixes: #3734
Ports: #3740
>  [BUGFIX] Prevent indexing error on missing 'foreignLabelField'

- Classes/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParser.php
- Tests/Unit/Domain/Search/ResultSet/Facets/OptionBased/Options/OptionsFacetParserTest.php
> [BUGFIX:BP:11.5] Handle float values in options facet parser

- Docker/SolrServer/Dockerfile
> [BUGFIX] Remove superfluous char in Dockerfile

- composer.json
See: https://getcomposer.org/doc/06-config.md#preferred-install
>  [TASK] Use composers "preferred-install" config instead of reinstall

- Classes/System/Solr/Service/SolrWriteService.php
Fixes: https://github.com/TYPO3-Solr/ext-tika/issues/217
> [BUGFIX] TikaStatus can't handle all response types of SolrWriteService->extractByQuery()

- Classes/Domain/Search/SearchRequest.php
Fixes: #3874
Ports: #3876
Replaces: #3875
> [BUGFIX:11.5] check if all sorting parts are present before access

- Classes/Domain/Search/SearchRequest.php
> [BUGFIX] check if all sorting parts are present before access

- Classes/Controller/SearchController.php
- Classes/Event/Search/BeforeSearchResultIsShownEvent.php
I am currently migrating an older project and miss this feature. It allows developers to provide additional variables to the view.
Relates: #3705
> [FEATURE] Improve BeforeSearchResultIsShownEvent

- Documentation/Configuration/Reference/TxSolrIndex.rst
Update the wrong section on that it's still impossible to extend the file processors
> [DOC] Add infos about adding own field processors

- Documentation/Configuration/Reference/TxSolrIndex.rst
Update the wrong section on that it's still impossible to extend the field processors
Ports: #3939
> [DOC:BP:11.5] Add infos about adding own field processors

- Documentation/FAQ/Index.rst
Add section to FAQ documentation covering issues with quitting container when using Colima
Fixes: #3949
> Describe issues with Colima as Docker provider

- Documentation/Configuration/Reference/TxSolrSearch.rst
Improves the docs
Render the docs, go to https://docs.typo3.org/p/apache-solr-for-typo3/solr/main/en-us/Configuration/Reference/TxSolrSearch.html#faceting-urlparameterstyle
---
> [DOCS] Make values of faceting.urlParameterStyle more clear

- Classes/Report/SolrStatus.php
- Classes/System/Solr/Service/SolrAdminService.php
- Resources/Private/Templates/Backend/Reports/SolrStatus.html
Adds a check for enabled content streams to the TYPO3 reports module, checking SOLR_ENABLE_REMOTE_STREAMING.
> [TASK] Add content stream check

- Classes/Domain/Search/ResultSet/Facets/AbstractFacet.php
- Classes/Domain/Search/ResultSet/Facets/RangeBased/DateRange/DateRangeFacetQueryBuilder.php
- Classes/Domain/Search/ResultSet/Facets/RangeBased/NumericRange/NumericRangeFacetQueryBuilder.php
- Classes/IndexQueue/AbstractIndexer.php
- Classes/Routing/RoutingService.php
This pr contains the changes recognized by EXT:solr integration into SDS and should be reviewed carefully.
> [Internal] Collection of fixes recognized by SDS task

- Classes/Report/SiteHandlingStatus.php
- Tests/Integration/Domain/Search/ResultSet/SearchResultSetServiceTest.php
- Tests/Integration/FrontendEnvironment/TsfeTest.php
- Tests/Integration/IndexQueue/IndexerTest.php
- Tests/Integration/IntegrationTest.php
- Tests/Unit/Domain/Search/FrequentSearches/FrequentSearchesServiceTest.php
- Tests/Unit/Domain/Search/LastSearches/LastSearchesServiceTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/RenderingInstructions/FormatDateTest.php
- Tests/Unit/Domain/Search/ResultSet/ResultSetReconstitutionProcessorTest.php
- Tests/Unit/Domain/Search/Uri/SearchUriBuilderTest.php
- Tests/Unit/Search/RelevanceComponentTest.php
- Tests/Unit/System/DateTime/FormatServiceTest.php
- Tests/Unit/System/Solr/SolrConnectionTest.php
- Tests/Unit/System/Url/UrlHelperTest.php
- Tests/Unit/System/UserFunctions/FlexFormUserFunctionsTest.php
- Tests/Unit/ViewHelpers/Document/HighlightingResultViewHelperTest.php
> [FIX] Actions errors 2024.04.05

- ext_tables.sql
> [BUGFIX] column `changed` out of range

- .github/workflows/ci.yml
- Tests/Integration/System/Solr/Service/SolrAdminServiceTest.php
- Tests/Unit/Access/RootlineTest.php
- Tests/Unit/Domain/Search/ResultSet/Facets/RangeBased/NumericRange/NumericRangeUrlDecoderTest.php
- Tests/Unit/HtmlContentExtractorTest.php
- Tests/Unit/System/Solr/SolrConnectionTest.php
> [TASK] Remove deprecations for CI-Build

- Resources/Private/Language/fr.locallang.xlf
Fixed two typos I introduced in PR #3984 related to #3983.
In #3996 which is the port to main not yet merged, it should be fixed too.
> [FIX] Typos in last FR translation PR

- Resources/Private/Language/fr.locallang.xlf
- Resources/Private/Language/fr.locallang_be.xlf
- Resources/Private/Language/fr.locallang_mod.xlf
- Resources/Private/Language/fr.locallang_mod_coreoptimize.xlf
- Resources/Private/Language/fr.locallang_mod_indexadmin.xlf
- Resources/Private/Language/fr.locallang_mod_indexqueue.xlf
- Resources/Private/Language/fr.locallang_mod_info.xlf
- Resources/Private/Language/fr.locallang_reports.xlf
- Resources/Private/Language/fr.locallang_tca.xlf
Fixes: #3983
Ports: #3984 
@megamisan please review this port
> [TASK:P:main] Full fixed french translation

- Documentation/Releases/solr-release-12-0.rst
- Documentation/Settings.cfg
- ext_emconf.php
This is a maintenance release for TYPO3 12.4 LTS, containing:
* [BUGFIX] PHPStan 1.11+ by @dkd-kaehm
* [BUGFIX] Allow fe_group modification when indexing subpage of restricted page by @deschilter
* [TASK:P:main] Full fixed french translation by @megamisan 
* [TASK] Update all GitHub-Actions on main branch by @dkd-kaehm
* [TASK] Remove deprecations for CI-Build by @dkd-kaehm
* [BUGFIX] Debug output if response body is read once stream by @Kanti
* [BUGFIX] Use tx-solr-suggest-focus for autofocus on form-submit by @felixranesberge
* [FEATURE] Support stdWrap to resolve relation label field by @DanielSiepmann
* [BUGFIX] Remove superfluous quotation marks in Partials/Result/FacetsActive.html by @julianhofmann
* [TASK] Remove switchableControllerActions from TypoScript by @derhansen
* …
> [RELEASE] 12.0.3

- README.md
> [TASK] Set badges in README.md properly

- Classes/Domain/Index/Queue/IndexQueueIndexingPropertyRepository.php
- Classes/Domain/Index/Queue/QueueItemRepository.php
- Classes/Domain/Index/Queue/Statistic/QueueStatisticsRepository.php
- Classes/Domain/Index/Queue/UpdateHandler/GarbageHandler.php
- Classes/Domain/Search/Statistics/StatisticsRepository.php
- Classes/IndexQueue/Initializer/Page.php
- Classes/System/Records/Pages/PagesRepository.php
First part of migrations to Doctrine v4
Fixes: #4038
> [TASK] Simple blocker:: come through `typo3 extension:setup` command

- Classes/Controller/Backend/Search/AbstractModuleController.php
- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
- Classes/Controller/Backend/Search/IndexAdministrationModuleController.php
- Classes/Controller/Backend/Search/IndexQueueModuleController.php
- Classes/Controller/Backend/Search/InfoModuleController.php
> [TASK] Use new template module API

- Classes/Controller/SearchController.php
Add record data of current content object in all actions of Search controller
Fixes: #4018
> [FEATURE] Add contentObjectData to searchController

- Classes/ViewHelpers/SearchFormViewHelper.php
Add empty array as fallback for mergeRecursiveWithOverrule()
Fixes: #4010
> [BUGFIX] Add empty array as fallback if null

- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
- Resources/Private/Layouts/Backend/WithPageTree.html
* Remove dynamic tabs integration
* Use new Fluid Layout for a nicer look
Fixes: #4058
> [TASK] Beautify backend modules for v13

- Tests/Integration/IndexQueue/PageIndexerTest.php
Add tests to explicitly test the filtering done by the Solr Access plugin.
Relates: https://github.com/TYPO3-Solr/solr-typo3-plugin/issues/33
> [TASK] Add access plugin tests

- Classes/Controller/Backend/Search/CoreOptimizationModuleController.php
- Classes/Utility/ManagedResourcesUtility.php
Fixes the upload of synonym and stop word lists.
Resolves: #4011
> [BUGFIX] Fix synonym and stop word upload

- Documentation/Releases/solr-release-12-0.rst
- Documentation/Settings.cfg
- ext_emconf.php
This is a maintenance release for TYPO3 12.4 LTS, containing:
* [TASK] Use request object to retrieve query params instead of _GET
* [TASK] Use Attributes for PHPUnit tests
* [TASK] Update PHP-Stan to at least 1.11.*
* [TASK] Apply and repair rector refactorings
* [TASK] Migrate requireJS to ES6. Solr BE Modal JS
* [TASK] Apache Solr 9.6 compatibility
* [TASK] Use new template module API
* [FEATURE] Add contentObjectData to searchController
* [BUGFIX] Add empty array as fallback if null
* [BUGFIX] Add empty array defaults in SearchFormViewHelper
* [TASK] Integrate content of Module layout into WithPageTree
* [TASK] Repair statistics chart because of CSP in Solr Info module
* [FEATURE:BP:12] Be able to disable tracking of last searches
* [TASK] Add access plugin tests
* [TASK] Update …
> [RELEASE] 12.0.4

- Classes/Controller/Backend/Search/IndexQueueModuleController.php
- composer.json
Fixes index queue clearance in multi site
environment.
Fixes: https://github.com/TYPO3-Solr/ext-solr/issues/4095
> [BUGFIX] Fix index queue clearance

- Tests/Integration/Extbase/PersistenceEventListenerTest.php
This change fixes the issues within  `ApacheSolrForTypo3\Solr\Tests\Integration\Extbase\PersistenceEventListenerTest` by  adding context-requered stubs.
Relates: #3995
> [FIX] Integration\Extbase\PersistenceEventListenerTest errors

- Build/Test/IntegrationTests.xml
- Build/Test/UnitTests.xml
- Tests/Integration/IndexQueue/PageIndexerTest.php
- Tests/Unit/ContentObject/SetUpContentObject.php
- Tests/Unit/Domain/Search/Suggest/SuggestServiceTest.php
- Tests/Unit/IndexQueue/PageIndexerTest.php
- Tests/Unit/System/Cache/TwoLevelCacheTest.php
- Tests/Unit/System/Solr/Service/SolrReadServiceTest.php
- composer.json
Follow-Up for:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/86184 https://github.com/TYPO3/testing-framework/commit/60f586e8923e48be2e7a2dcd9634e9eac51eab6d Required for "typo3/testing-framework" and TYPO3 dev-main @2024.09.23
> [FIX] Tests for TYPO3 dev-main @2024.09.23

- Resources/Private/Templates/Backend/Search/IndexQueueModule/Index.html
> [BUGFIX] Failed to resolve module specifier '@apache-solr-for-typo3/solr//FormModal.js'

- Documentation/Releases/solr-release-12-0.rst
Picked from: https://github.com/TYPO3-Solr/ext-solr/commit/7e800fb764377eedfba6b03dc0dcbf397c706a9c
Ports: #4133
> [DOCs] for release 12.0.5

- Classes/ContentObject/Relation.php
> [BUGFIX:P:12.0] Respect foreignLabel in related items from mm table

- Classes/ContentObject/Relation.php
> [BUGFIX] Respect foreignLabel in related items from mm table

- Classes/Domain/Index/Queue/RecordMonitor/Helper/ConfigurationAwareRecordService.php
Fixes: #4168, #4176
Ports: #4169
> [BUGFIX:P:main] Add StartTimeRestriction to ConfigurationAwareRecordService

- Documentation/Configuration/Reference/ExtensionSettings.rst
> [DOCS] Actually mention the values of monitoringType

- Classes/Event/Indexing/AfterPageDocumentIsCreatedForIndexingEvent.php
- Classes/Event/Indexing/BeforeDocumentIsProcessedForIndexingEvent.php
- Classes/Event/Indexing/BeforeDocumentsAreIndexedEvent.php
get SiteLanguage from request instead of site
> [BUGFIX] site has no attribte language

- Classes/Task/ReIndexTaskAdditionalFieldProvider.php
> [BUGFIX:P:12.0] Update hardcoded legacy css resource filepath

- .github/ISSUE_TEMPLATE/bug_report.md
- Documentation/Releases/solr-release-13-0.rst
- Documentation/guides.xml
- ext_emconf.php
This is a maintenance release for TYPO3 13.4 LTS.
List of all changes:
* [BUGFIX] 404 on auto-suggest with enabled TYPO3 enforceValidation setting by Wolfgang Wagner | wow! solution
* [TASK] 13.0.x-dev Update solarium/solarium requirement by dependabot[bot]
* [BUGFIX] provide some expression matcher variables by Achim Fritz
* [TASK] Remove solrmlt by Markus Friedrich
* [TASK] Update version matrix by Markus Friedrich
* [TASK] Allow Apache Solr 9.8.1 by Markus Friedrich
* [DOCS] Add section on how to optimize page index runtimes) by Philipp Kitzberger
* [DOCS] Fix typo in ConfigureExtension.rst by Jon Echeveste González
* [BUGFIX] PhpUnit IsStringViewHelperTest for typo3fluid/fluid v4.1.+ by Rafael Kähm
* [BUGFIX] Update hardcoded legacy css resource filepath by Charlotte
* [TASK] fix …
> [RELEASE] 13.0.2

- Classes/ContentObject/Relation.php
> [BUGFIX:BP:12] Avoid PHP warning if related record was not found

- .github/ISSUE_TEMPLATE/bug_report.md
- Docker/SolrServer/Dockerfile
- Documentation/Appendix/VersionMatrix.rst
- Documentation/Releases/solr-release-12-0.rst
- composer.json
- ext_emconf.php
This is a maintenance release for TYPO3 12.4.
* [BUGFIX] 404 on auto-suggest with enabled TYPO3 enforceValidation
setting by Wolfgang Wagner | wow! solution
* [TASK] 12.0.x-dev Update solarium/solarium requirement by
dependabot[bot]
* [BUGFIX] Update hardcoded legacy css resource filepath by Charlotte
* [FEATURE] Add arm64 and ppc64le platforms to docker-images by Rafael
Kähm
* [BUGFIX] Fix mount point garbage collection by Markus Friedrich
* [TASK] Drop workaround for cObj IMAGE by Markus Friedrich
* [TASK] Allow Apache Solr 9.8.1 by Markus Friedrich
* [BUGFIX] Avoid PHP warning if related record was not found by Albrecht Köhnlein
---
* Ask or help or …
> [RELEASE] 12.0.7
